### ISSUE TITLE
New Recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [EnigmaticaModpacks/Enigmatica6#1300]
Disclaimer: NOT final
![billede](https://user-images.githubusercontent.com/21295394/130494386-f1f3532e-4cbd-4034-836b-a5801dae684b.png)
- Image updated 23-08-2021

# Misc
- [x] Furnace
~~Planks~~
- [x] Sticks
- [x] Time in a Bottle
- [x] Gears (hammer + 6 ingots -> 1 gear?)
- [x] Plates (hammer + 2 ingots -> 1 plate?)
- [x] Rods (hammer + plate -> 1 rod?)
- [x] Piston?
- [x] Blast Furnace
- [x] Smoker
- [x] Ender Chest / Tank / Bag
- [x] Observer

# Tech
### Create
- [x] Andesite Alloy
- [x] Crushing Wheel
- [x] Windmill Bearing
- [x] Millstone
- [x] Flywheel

### Thermal
- [x] Redstone Flux Coil
- [x] Machine Frame
- [x] Energy Cell Frame
- [x] Fluid Cell Frame
- [ ] Saw Blade
- [x] Redstone Servo
- [ ] Drill Head
- [x] All Integral Components
- [ ] Aqueous Accumulator?
- [x] Redstone Flux Cell Frame
- [x] Pyrolyzer

### XNet
- Gated by Rockwool + Signalum
- [x] Controller
- [x] Router
- [x] Wireless Router
- [x] Redstone Proxy
- [x] Redstone Proxy (Update)
- [x] Connector Upgrade Kit
- [x] Network Cables
- [x] Connectors
- [x] Advanced Connectors
- [x] Antenna
- [x] Antenna Dish
- [x] Antenna Base

### Immersive Engineering 
- [x] Coke Brick
- [x] Blast Brick
~~Treated Wood?~~
- [x] Engineer's Workbench
- [x] Alloy Brick
- [ ] Redstone Engineering Block *(IE Tier 2)*
- [ ] Heavy Engineering Block *(IE Tier 2)*
- [ ] Light Engineering Block *(IE Tier 2)*
- [ ] Generator Block *(IE Tier 2)*
- [ ] Radiator Block *(IE Tier 2)*
- [x] External Heater
- [ ] Vacuum Tube?
- [ ] Circuit Board
- [x] Conveyor Belt
- [ ] Garden Cloche
- [x] Iron Mechanical Component
- [x] Steel Mechanical Component

### Integrated Dynamics
Gated by: Cured Rubber + Smoldering Lapis Lazuli Compound
- [x] Crystalized Menril Chunk
- [x] Menril Resin
- [x] Squeezer (+Mechanical)
- [x] Drying Basin (+Mechanical)
- [x] Variable Card
- [x] Energy Battery
- [x] Generator
- [x] Portable Logic Programmer
- [x] Variable Store
- [x] Logic Cable
- [x] Omni-Directional Connector

### Powah
Gated by Coal Coke + TBD
- [x] Energized Steel
- [x] Basic Capacitor
- [x] Basic Capacitor (Tiny)

### Pretty Pipes
Gated by Create Shafts
- [x] Pipes
- [x] Item Terminal
- [x] Crafting Terminal
- [x] Pipe Pressurizer

### RFTools
- [x] Builder
- [x] Machine Infuser
- [x] Machine Frame
- [x] Machine Base
- [x] Shape Card: Quarry
- [x] Shape Card: Fortune Quarry
- [ ] Shield Template
- [ ] Modular Storage
- [ ] Tier 1-4 Storage Modules
- [ ] Coal Generator
- [x] Blazing Generator
- [x] Blazing Agitator
- [x] Blazing Infuser
- [x] Matter Transmitter
- [x] Matter Receiver
- [x] Dialing Device
- [x] Charged Porter
- [x] Advanced Charged Porter

TODO: Add RFToolsDimensions stuff

### Modular Routers
- [x] Blank Module
- [x] Blank Upgrade
- [x] Augment Core
- [x] Item Router

### Industrial Foregoing
- [x] Pity Machine Frame
- [ ] Simple Machine Frame
- [ ] Advanced Machine Frame
- [ ] Supreme Machine Frame

### PneumaticCraft
- [x] Compressed Iron

### Mekanism
- [x] Infused Alloy
- [x] Reinforced Alloy
- [x] Atomic Alloy
- [x] Control Circuits

### Refined Storage
- [x] Controller
- [x] Cables
- [x] Crafter (All tiers)
- [x] Grid
- [x] Disk Drive (Occultism crafting materials)
- [x] Drives (Occultism crafting materials)
- [x] External Storage
- [x] Importer
- [x] Exporter

*****

**Comment by Angular-Angel** [comment]
Four byg:pollen into byg:pollen block would be good, though byg will probably be adding this eventually.

**Comment by Merlo17** [comment]
Not really the right place for this since this is for planned expert recipes but it seemed like a good idea so I did it anyways :P https://github.com/NillerMedDild/Enigmatica6/pull/1309

**Comment by Angular-Angel** [comment]
Hey, nice!
