### ISSUE TITLE
Lava Crystal (blood magic) in Heat Generator (mekanism) seems to crash the server

### ISSUE THREAD

**Issue by sublimeparadox** [EnigmaticaModpacks/Enigmatica6#1328]
**Modpack version**
0.3.13

**Describe the bug**
After placing a lava crystal (from blood magic) in a heat generator (mekanism), server crashes whenever someone enters that chunk. I've reverted the server to a version prior to putting the lava crystal in the heat generator, but wanted to report it!

**Logs**
Edit: Moved your crash to this gist: https://gist.github.com/NillerMedDild/d3578ea6917a89eaf658996d845c175b

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
