### ISSUE TITLE
Emendatus Enigmatica Dimensional Crystals not accepted by RFTools Infuser

### ISSUE THREAD

**Issue by zombiethoughts** [EnigmaticaModpacks/Enigmatica6#1456]
**Modpack version**

Enigmatica 6
36.0.40 

**Describe the bug**
I am not able to place dimensional shards into the infuser from rftools to infuse machines.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by Merlo17** [comment]
afaik the EE shards still don't work unfortunately, but you should be able to convert them into RFTools ones

**Comment by r-mc2** [comment]
Yep, Niller added the 1:1 conversion back in #776 
Linked issue on RFTools tracker still hasn't heard back from the author.

**Comment by zombiethoughts** [comment]
Ah, thank you. I didn't realize you could convert through the crafting table.
I'll leave this here for anyone else seeking the same issue.
