### ISSUE TITLE
New worlds ignore difficulty setting when made

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#1462]
**Modpack version**
0.4.1

**Describe the bug**
1) make a new world, set difficulty peaceful

Result: Difficulty is set normal instead

**Comment by TemperedFool** [comment]
Noticed this myself when I made a creative super flat world; assumed I made a mistake.

**Comment by NillerMedDild** [comment]
I've removed the setting from default options, hopefully that helps.

**Comment by NillerMedDild** [comment]
Nope, still an issue. Reported here: https://github.com/blay09/DefaultOptions/issues/50

**Comment by NielsPilgaard** [comment]
I can't reproduce @HaxtonSale1, the difficulity is what I set it to during creation.
