### ISSUE TITLE
Ultimate Fluid Tank consumed in recipe for Asphalt Concrete

### ISSUE THREAD

**Issue by jallen6769** [EnigmaticaModpacks/Enigmatica6#1994]
When using the ultimate fluid tank from mekanism in bucket mode in the crafting recipe for treated wood, it works as intended where the recipe doesn't consume the tank. However, when using it in the recipe for Asphalt Concrete, it gets consumed.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Relayed here: https://github.com/TwistedGate/ImmersivePetroleum/issues/15
