### ISSUE TITLE
Endless Quiver Enchant does not apply to Archer's Paradox arrows

### ISSUE THREAD

**Issue by AngelsSaber** [EnigmaticaModpacks/Enigmatica6#2123]
**Modpack version**
1.16.5
**Describe the bug**
the JEI description of Endless quiver is it makes all arrows infinite, but i'm losing diamond and phantasmal arrows

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/Shadows-of-Fire/Apotheosis/issues/373
