### ISSUE TITLE
[0.4.14] Tetra Warforged tools don't have access to all weapons enchantements

### ISSUE THREAD

**Issue by Larandar** [EnigmaticaModpacks/Enigmatica6#2329]
**Modpack version:** 0.4.14

**Describe the bug**
Warforged tools don't have access to all weapons enchantments when we expect them to be available.

**Screencast**
Trying to put Ender Disruption and Knowledge of ages on a scythe: 

https://user-images.githubusercontent.com/906021/120303583-436a7080-c2cf-11eb-9e74-bd5a866a72e2.mp4

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
