### ISSUE TITLE
Blood Magic's "Mark category as read" crashes client to desktop

### ISSUE THREAD

**Issue by PipeWizard** [EnigmaticaModpacks/Enigmatica6#2332]
**Modpack version**
0.4.14

**Describe the bug**
Open the Blood Magic guide book and on the bottom right there is a button to "Mark category as read" which will cause an immediate crash to desktop.  Seems to work for all? of the sections.

**Logs**
https://paste.ee/p/wPRum

**Screenshots**
![image](https://user-images.githubusercontent.com/22507874/120416078-932a5580-c32a-11eb-9e22-5d34f3bc0f31.png)

Additional note:
This issue was reported on Blood Magic's github though someone made a note that it is likely Patchouli needing to update.
https://github.com/WayofTime/BloodMagic/issues/1815#issue-901411165

**Comment by NillerMedDild** [comment]
Thanks for the report. Please update to 0.4.14 and see if the issue persists :)

**Comment by PipeWizard** [comment]
Hah whoops I accidentally put 0.4.11 instead of 0.4.14.  Issue is present on 0.4.14. My bad. Too many versions on MultiMC that I need to clean up.

**Comment by NillerMedDild** [comment]
Found it reported here as well: https://github.com/Vazkii/Patchouli/issues/398
