### ISSUE TITLE
Tinkers Construct Questline

### ISSUE THREAD

**Issue by Katon152021** [EnigmaticaModpacks/Enigmatica6#2463]
Hello I would like to recommend we add a Tinker's Construct Questline into the Quest book. 

I hope this suggestion receives some traction from other players who would also be interested in seeing some sort of questline attached to Tinkers Construct since I know it's a really famous mod and I think its deserving of some quest love. 

If I had to picture it in my head I would think something along the lines of tiers or certain tools have to be made to complete a quest.

Look forward to what you guys decide :)

**Comment by MVethana** [comment]
In Progress 😃
