### ISSUE TITLE
Apotheosis Spawner stats not visible when placed.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#2556]
**Modpack version**
0.5.0

**Describe the bug**
Any Apotheosis spawner (showing as Apotheosis in inventory, and showing its stats in inventory) reverts to a "Minecraft" spawner when placed down, and won't show its stats anymore. It will apparently still *use* its stats (mine stay redstone controlled for instance), but you can't see any of its stats when placed down, not even when sneaking.

I installed Jade to check, and it displays "Sneak for Info", but doesn't display anything when sneaking.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by Splutty** [comment]
E6, Apotheosis-1.16.4-4.6.1, Jade-1.16.4-2.7.1:
https://media.discordapp.net/attachments/726178356143456287/858951455654412298/unknown.png?width=413&height=616

Kitchensink, Apotheosis-1.16.4-4.5.2, Jade-1.16.4-2.7.1:
https://media.discordapp.net/attachments/726178356143456287/858951985184112650/unknown.png?width=361&height=616

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
No idea what's going on there, I'm guessing it's something Jade does?

**Comment by Splutty** [comment]
No. It is not something Jade does. It doesn't matter if I use TOP or Jade, in E6 the tooltip isn't visible, in a kitchensink pack it is.

So.. Something is off. Somewhere.

**Comment by Splutty** [comment]
[SPG.zip](https://github.com/NillerMedDild/Enigmatica6/files/6758380/SPG.zip)

This is the modlist/manifest of the kitchensink pack I put together for a bunch of my players. I can't really see anything that would cause this particular behaviour to be different from the ones in the E6 pack in regards to tooltips.

I've also gone through the most likely configs, and there really aren't any options to cause this as far as I can find.

So I'm stumped.. Hopefully someone knows why this is happening, or what mod I added to the kitchensink pack that adds this info.

It's very useful to be able to see the stats on a spawner when it's actually placed, so that's why I made this issue.

**Comment by TemperedFool** [comment]
Is this an issue with line 57 of https://github.com/NillerMedDild/Enigmatica6/blob/master/config/theoneprobe-client.toml ? Has anyone tried changing that to a number instead of "Normal"?

**Comment by Splutty** [comment]
Since it happens with both TOP and Jade, I doubt a TOP config is the issue :( Just checked the config in the kitchensink pack, it's also set to "NORMAL".

#Show mob spawner setting (0 = not, 1 = always, 2 = sneak)
showMobSpawnerSetting = "NORMAL"

**Comment by Darkere** [comment]
Did you guys check the log/debug log in case there is something in there?

Otherwise... It's binary search time?

**Comment by Splutty** [comment]
It's not a TOP issue, though. That's why I did the pictures with Jade installed on both clients instead, to try to rule out that it's a TOP issue. (Although I suppose TOP could somehow mess up Jade, possibly...)

**Comment by Splutty** [comment]
And Darkere, it doesn't show anything anywhere, not client side, not server side, so it's not causing a java error or anything in debug, either..

**Comment by NillerMedDild** [comment]
Turns out Apotheosis has Jade support specifically, so it's not really a bug.
