### ISSUE TITLE
Tetra does not recognize Emendatus Enigmatica's brass ingots

### ISSUE THREAD

**Issue by Zennle** [EnigmaticaModpacks/Enigmatica6#2645]
Trying to use Emendatus Enigmatica brass ingots in Tetra tool parts gives a "The provided material cannot be used for this schematic" message. I also noticed the Holosphere shows Create brass ingots when you check brass parts' stats.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported the issue here: https://github.com/Syrikal/Tetranomicon/issues/7

**Comment by pmytilin1984** [comment]
Problem Persists

**Comment by NielsPilgaard** [comment]
On the develop branch? This change is unreleased.

**Comment by MuteTiefling** [comment]
Did just check in Dev, actually. Does not seem to have fixed it. :(

**Comment by pmytilin1984** [comment]
metals.js already contains an entry about brass, maybe there is something there

**Comment by NielsPilgaard** [comment]
Good catch, ready for testing again :P
