### ISSUE TITLE
Forged Container causes crash to launcher

### ISSUE THREAD

**Issue by BooshWookery** [EnigmaticaModpacks/Enigmatica6#2649]
**Modpack version**
0.5.4
**Describe the bug**
Using a tier 4 hammer from Tetra and right clicking on a Forged Container to open it causes a crash to the launcher to occur. 
**Logs**
https://pastebin.pl/view/cdc90883
**Screenshots**
![image](https://user-images.githubusercontent.com/87048827/124685008-0842fa80-de96-11eb-970e-99b108d93dcd.png)

**Comment by NillerMedDild** [comment]
Did it happen in a ruin in a quark cave?

**Comment by BooshWookery** [comment]
It was in a Rogue Like Dungeon, when I found another ruin, I found that the crate actually generated with only half of it, and caused a crash when trying to open it.
