### ISSUE TITLE
RFTools Machine Infuser does not accept Screen Controller

### ISSUE THREAD

**Issue by Roukurai** [EnigmaticaModpacks/Enigmatica6#2726]
**Modpack version**
0.5.6
**Describe the bug**
Unable to infuse the RFTools Screen controller in the Machine infuser.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
try shift + click into the infuser, nor drag n drop.

**Comment by NielsPilgaard** [comment]
https://github.com/McJtyMods/RFToolsBase/issues/51
