### ISSUE TITLE
BYG Compatibility for Environmental's Sawmill

### ISSUE THREAD

**Issue by Larandar** [EnigmaticaModpacks/Enigmatica6#2847]
**Description**
In expert (and normal?) mode environmental's sawmill can transform various wood to plank, stick and decorative blocks, it would be nice (essentially during the early game) for recycling slabs, doors, stairs, chests, etc..., you have in stock to sticks for crafting

It could also be made so sticks can be transformed to sawdust for earlier access to cardboard (useful for moving from hobbit hole to started base)

**Comment by Erysch** [comment]
plus adding the cutting recipes for the OTBYG woods would be nice as well (if they are not implemented yet)

**Comment by NillerMedDild** [comment]
We already have this through the modded Sawmills, I think that's good enough :)

**Comment by NillerMedDild** [comment]
Expanding the Sawmill to also work for other mods would be good though

**Comment by NillerMedDild** [comment]
We won't implement this after all because of time constraints :(
