### ISSUE TITLE
Environmental Mud Ball recipe can't use Mekanism fluid tanks

### ISSUE THREAD

**Issue by Golfavel** [EnigmaticaModpacks/Enigmatica6#2882]
**Modpack version**
0.5.6

**Describe the bug**
Mekanism fluid tanks are typically(?) able to be substituted for buckets of a fluid to ease crafting. This is not the case with crafting Mud Balls from Environmental.

**Screenshots**
![treatedplanks](https://user-images.githubusercontent.com/32048635/127940834-059a1404-e343-4dfd-97cc-e8173aaba895.png)
![mudballs](https://user-images.githubusercontent.com/32048635/127940983-192807b6-5fc2-4eab-9777-4009bfb53788.png)
(changing the amount of water in the tank does not work)

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it here: https://github.com/team-abnormals/environmental/issues/232

**Comment by pupnewfster** [comment]
Was randomly looking at things and just fyi there is nothing on Mek's end to let fluid tanks be substituted for buckets so unless environmental allows(?) other fluid containers than buckets I don't think this is a bug.

**Comment by MuteTiefling** [comment]
I think I've actually fixed this now in dev by using PNC's fluid recipe handler to encode the recipe.

**Comment by NillerMedDild** [comment]
Sadly not fixed for Mekanism tanks, looks like it works with PNC ones though.

**Comment by pupnewfster** [comment]
IE's fluid supporting crafting recipe type likely would work (with all our tanks even assuming the configs got updated when updating to 10.1, if not then just elite+ due to output limits)
