### ISSUE TITLE
Screen Shimmy on Player Approach

### ISSUE THREAD

**Issue by MFWalter** [EnigmaticaModpacks/Enigmatica6#2925]
**Modpack version**
0.5.8

**Describe the bug**
When a player teleports to you or approaches from off screen the screen will do a weird shimmy effect. This did not happen in 0.5.6

**Logs**
N/A

**Screenshots**
https://clips.twitch.tv/PoorTrustworthyDogSaltBae-KW28_ktPLY6Tir_Y

**Comment by NillerMedDild** [comment]
Thanks for the video, helps a great deal in understanding the issue. That is super weird 😄 
Could you please update to 0.5.9 just to verify that it's still happening?

**Comment by MFWalter** [comment]
I'll pass the request to the guy actually running the server. Today we have 2 people streaming from the server so probably won't happen until night time {USA Central Time} after both streams are over.

**Comment by MFWalter** [comment]
We are still getting the "Screen Shimmy" on 0.5.9
