### ISSUE TITLE
Infinity Items with RFTools Storage Scanner!

### ISSUE THREAD

**Issue by KacproPL132** [EnigmaticaModpacks/Enigmatica6#2926]
**Modpack version**
0.5.6

**Describe the bug**
When Placing Storage Scanner from RFTools near Personal Chest from Mekanism (in range of it) and placing some items in it (from example 9 diamonds), you can craft with those items without losing them (so you can have infinity diamonds for example).

**Screenshots**
Here is a video! (PS: Sorry for horrible quality... I'm not in home and was sending it with internet from my phone :v)
https://youtu.be/eIgNlMe77Us

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it here: https://github.com/McJtyMods/RFToolsStorage/issues/53

**Comment by KacproPL132** [comment]
After some testing at newer version of  the pack (1.1.2) It seems that it got fixed... somehow... so I think I can close this :D
