### ISSUE TITLE
JEI + Refined Storage should ideally have a "default" item per valid tag

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#2975]
**Modpack version**

0.5.9

**Describe the bug**

when you use the + in JEI to create a pattern for rs, you often get the weirdest of items with technically correct tags.

while it would (probably?) work fine in non-exact mode, i still get nightmares of having those patterns in my system,
hence i have a few requesters setup to keep the bellow items in stock, so if i need to make a pattern with one of the weirdified items i can pick a fresh one from rs to override the suggested pattern with before putting it in a crafter.

**Screenshots**

obsidian & chests:
![Screen Shot 2021-08-13 at 20 09 03](https://user-images.githubusercontent.com/3179271/129401426-3836e0c3-4c26-4474-b307-8c8ae6acc7ee.png)

sticks:
![Screen Shot 2021-08-13 at 20 10 08](https://user-images.githubusercontent.com/3179271/129401546-63323955-fee3-4b1c-ba7d-3a89aefcfe27.png)

gears:
![Screen Shot 2021-08-13 at 20 10 51](https://user-images.githubusercontent.com/3179271/129401620-40821fe6-4184-4c35-bc1b-7c78202a6892.png)

and worst of all, connecting glass:
![Screen Shot 2021-08-13 at 20 11 36](https://user-images.githubusercontent.com/3179271/129401696-d27d33d8-8fd6-4a75-a062-5c6353afb5aa.png)

(keep in mind that none of those "suggested" items are even in the rs network at all, let alone ever made on this map)

**Comment by NillerMedDild** [comment]
Did you have anything else with the tags in question in your system at the time?

**Comment by Quezler** [comment]
i suppose, but it doesn't feel like that ever was the issue:

![Screen Shot 2021-08-13 at 20 40 56](https://user-images.githubusercontent.com/3179271/129404570-55c7c350-f3b9-4e1a-900d-f494fa955bd4.png)
![Screen Shot 2021-08-13 at 20 41 03](https://user-images.githubusercontent.com/3179271/129404572-7307bc9c-3b4b-4c47-bc46-b52540dd978f.png)
![Screen Shot 2021-08-13 at 20 41 09](https://user-images.githubusercontent.com/3179271/129404574-c121e768-0071-4687-8ce8-fcf573948ac8.png)
![Screen Shot 2021-08-13 at 20 41 14](https://user-images.githubusercontent.com/3179271/129404577-0e3f3331-e7d0-4f7c-80be-c0c947fdb7a0.png)
![Screen Shot 2021-08-13 at 20 41 36](https://user-images.githubusercontent.com/3179271/129404591-8bf9a035-019d-4e50-a6f3-f055021afdb4.png)

but even if i remove (lets say) all the sticks, i still get a borked suggestion when trying to craft a gold pickace pattern:

![Screen Shot 2021-08-13 at 20 42 35](https://user-images.githubusercontent.com/3179271/129404721-c074ed89-bb6e-4fd6-900e-32d179f711f3.png)

**Comment by Darkere** [comment]
I have a PR open for RS with this feature. Don't think it is possible to fix this easily on pack level.

**Comment by Quezler** [comment]
could you paste the link to it?

**Comment by NillerMedDild** [comment]
Oh I thought that PR was merged ages ago :P

**Comment by Wishbone1977** [comment]
This wouldn't be so annoying if it wasn't for the fact that the weird substitutions actually often break the recipes. It seems like the tag used to match the substitutions when making patterns is not always the same as the tag used to match ingredients during crafting. Either that, or the crafters always consider a pattern an exact match even if it was made without that. This usually happens with recipes containing planks. If I don't change the weird wood type it chooses for the pattern to regular oak planks, the RF system won't use the oak planks in the system to craft with (and there are no other kinds of plank in the system).

**Comment by Darkere** [comment]
This is a rather unfortunate sideeffect of how the the wood types translate into different items depending on which wood type you select. 

Picking one wood type vs. another or even selecting multiple wood types are all separate recipes, while patterns can only encode a single one. Removing the oak recipe and using the generic recipe for that could potentially help, but I think JEI breaks that idea....

The PR should improve that since it will pick the most common wood type you have to make the recipe. Now we are just waiting for a release ....

**Comment by theboo** [comment]
This is fixed now, yeah? Should use whatever you have most of in the tag?
