### ISSUE TITLE
JEI lacking crafting catagories in Multiplayer

### ISSUE THREAD

**Issue by Pacific-Legend** [EnigmaticaModpacks/Enigmatica6#3075]
### Modpack Version

0.5.11

### Describe your issue

I play on a single-player world, occasionally opening up LAN to co-op with my friend. 
For simplicity, I will use "Primary" and "Secondary" in reference to me and my friend, respectively, in this report.

After both clients updating from 0.4.14 to 0.5.11, the Secondary client can no longer see most JEI recipes when logged into the LAN world hosted by Primary -- the Primary client can see all recipes as usual. We've also tested this numerous times on newly created worlds, the same bug occurs.

Secondary is still able to see all JEI recipes within a single player world or a LAN world hosted by himself.

Strangely, when Primary joins a LAN world hosted by Secondary, he is able to see all JEI recipes as usual.

The JEI recipe categories that are disabled for Secondary are, but not limited to:
Crafting Table Recipes, Furnace Recipes, Various Autocrafter Recipes, Magic Recipes, Mob Drops, Bees, and Immersive Engineering Machines. 
The above list is inexhaustive, and likely contains even more not yet tested for. The only crafting recipe that is still visible for Secondary is, strangely, Villager Trading.

There are no differences between the two clients **with the exception** that Primary deleted the Config, Configdefault, and Kubejs folders before updating and installed Optifine. However, both tried a complete reinstallation of their respective clients, which changed nothing.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Optifine was added to the primary client, but not the secondary's.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by DoomSquirter** [comment]
just an aside to this.  Over the last many days, there have been a bunch of ppl complaining about this and I was surprised nobody had created an issue for it (that I could see).  namely, the tinkers tables/anvil, etc were the big ones that ppl kept on talking about.

**Comment by Darkere** [comment]
Open to Lan worlds were not Update Compatible before 5.9 or so and would become unjoinable. Would not be suprised if this isssue is related to that. 

Anyone tried this with a fresh world?

**Comment by Pacific-Legend** [comment]
I've specified in the report that "We've also tested this numerous times on newly created worlds, the same bug occurs." I doubt it's an issue of the specific world, but rather the client.


> Open to Lan worlds were not Update Compatible before 5.9 or so. Before that open to lan worlds would not be joinable after an update. Would not be suprised if this isssue is related to that.
> 
> Anyone tried this with a fresh world?

**Comment by Darkere** [comment]
Ah my bad.

**Comment by NillerMedDild** [comment]
The latest log from both of you after secondary has joined the LAN World would be helpful :)

**Comment by Pacific-Legend** [comment]
> The latest log from both of you after secondary has joined the LAN World would be helpful :)

I've uploaded Secondary's log: https://gist.github.com/Pacific-Legend/dd7b0dbb1c295da2d5b0e423a086458b

**Comment by Pacific-Legend** [comment]
Here's Primary's Log: https://gist.github.com/Pacific-Legend/19167c72c423773abfb5551c92fc8d9d

**Comment by NillerMedDild** [comment]
Seems like you've added and removed the mod Calemi's Utilities at some point, that might be an issue.

The JEI registration for UTeamCore and JustEnoughBeacon seems to be failing for the player joining your world, which  I'm guessing is causing the main issue here. Could both of you please try updating to the latest JEI and see if the issue persists? 

The last version added a change that fixed a heap of other issues, hopefully this one too.

**Comment by Pacific-Legend** [comment]
That's strange: I've never heard of Calemi's Utilities, let alone add or remove it at any point. 

I'll update to JEI 7.7.1.121 and re-try on both clients.

**Comment by Pacific-Legend** [comment]
Both clients have updated to JEI's newest version, the bug persists.
