### ISSUE TITLE
Gold and Netherite crafters losing patterns

### ISSUE THREAD

**Issue by Brandon-1012** [EnigmaticaModpacks/Enigmatica6#3076]
### Modpack Version

5.11

### Describe your issue

Gold crafters randomly lose all contained patterns or the whole crafter disappears. It happens on server and on on singleplayer

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Could you have changed the forge config to remove erroring tile entities?

**Comment by Brandon-1012** [comment]
I didn't change any config, I seen on discord someone else has same issue

**Comment by Edivad99** [comment]
I released an update, it should have fixed the problem once and for all🤞🤞🤞
