### ISSUE TITLE
Dank/Industrial Forgoeing dupe glitch

### ISSUE THREAD

**Issue by zanderwild** [EnigmaticaModpacks/Enigmatica6#3195]
### Modpack Version

5.9

### Describe your issue

If you take a dank in bag mode and put multiple empty mob imprisonment tools inside it they will stack in 1 slot. If you then change the dank to construct mode and have the mob imprisonment tools selected, and right click on 1 mob, you will fill all of the empty mob imprisonment tools in the dank with that 1 mob. I did this my mistake in the 5.9 version of the pack and havent tried it in 5.11 but it should be easy to reproduce

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks for the report. Relayed here: https://github.com/Tfarcenim/Dank-Storage/issues/135

**Comment by MuteTiefling** [comment]
Send the only sensible fix to this is to add it to the black list for items that can be used from the dank.
