### ISSUE TITLE
Resourceful Bees Breeder seems to reset its "breeder upgrade" on reload

### ISSUE THREAD

**Issue by ThePB** [EnigmaticaModpacks/Enigmatica6#3227]
### Modpack Version

0.5.11

### Describe your issue

Upon loading in the game, it is impossible to use the second breeding line offered by the breeder upgrade on a formed apiary (t1 in tests if it matters): the bees and materials are simply "pushed out" in the inventory (after a bit of time) or in world (if the GUI is closed) until the breeder upgrade is removed and reinserted. At that point, everything is peachy - until reload.

Didn't try to see if the order of the upgrades (one time and one breeder, in this order) matters, and didn't think to check if the time upgrade actually works on reload.

(Notice: dunno why my MC behaves "weirdly" when trying to re-log on the same world after exiting it, so each time i have to re-run the whole instance).

(Also, tried to look it it was already reported, didn't see anything. Hope i did miss it.)

### Crash Report

-

### Latest Log

-

### Have you modified the modpack?

Yes

### User Modifications

Nothing that should impact: config for waystones/Journeymap compat, adding sword enchants to spears in tetra...

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
Do you have a latest.log from right after this has happened?

**Comment by ThePB** [comment]
Will make one after i'm done with dinner (had a bit to do and had to post the other issue, too). I can simply recreate it by logging in, after all :D

**Comment by ThePB** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7150226/latest.log)

Attempts starting from 21.55, when the world loaded. At 21.57 i removed the upgrade, reinserted it and all was well. Let me know if there's anything else i can help with.

**Comment by TemperedFool** [comment]
Issue is solved on the RBees side; they probably won't push a release unless they can batch it with some other stuff, however.

**Comment by ThePB** [comment]
Not a huge issue for me anyway, so not a problem! Thank you!

**Comment by ThatGravyBoat** [comment]
It may get pushed out as we have another small thing that I fixed up, which @TemperedFool you will probs need to update recipes for.

**Comment by TemperedFool** [comment]
That sounds ominous @ThatGravyBoat, but I'm happy to see updates whenever they come!
