### ISSUE TITLE
Fillet Knives duplicating in Occultism storage

### ISSUE THREAD

**Issue by Kuroomega** [EnigmaticaModpacks/Enigmatica6#3293]
### Modpack Version

0.5.11

### Describe your issue.

Shift-clicking the result of a fillet knife and a fish in an occultism storage results in the knife being duplicated.
![image](https://user-images.githubusercontent.com/22209482/134221727-f4260587-0970-4c5d-9b94-ea56b804f928.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by MuteTiefling** [comment]
Confirmed fixed in dev. probably fixed in main release already ^_^
