### ISSUE TITLE
Teleporting in the Nether

### ISSUE THREAD

**Issue by Ticskter** [EnigmaticaModpacks/Enigmatica6#3296]
### Modpack Version

Pack Version 0.5.9

### Describe your issue.

if i teleport in the nether using the Journey Map teleporting feature it does not teleport me to the location. i entered the nether, placed a way point and then explored. i went to teleport back to the portal and it teleported me 5000 blocks away from the portal and in to a lava ocean. when i died there was a death marker placed as a teleport option, and when i attempted to teleport to it, it put me some where random and i was suffocating in a wall.

Journey Maps teleporting feature works fine in the over world, and i am not sure about teleporting in the End as i have not gotten that far yet.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Would you be able to update and test again? You're a few versions behind.

Also, out of curiosity, what are the coordinates of the waypoint and where it is teleporting you?

**Comment by Ticskter** [comment]
OK i updated to 0.5.11 entered portal and moved away must far enough to see the way point in world, teleported and it teleported me 450m away

Portal is at                    X: 64     Z: 1     Y:74
Teleport location is      X:520    Z: 0     Y: 55


Side note question.... does anyoneelses pack take like 10 minutes to load, and then like another 5 minutes to actually load the world?

**Comment by scotty9090** [comment]
Can confirm these issues with JourneyMap teleportation - same issue for me.  

@Ticskter My pack load time seems reasonable, or about what I'd expect for a pack of this size.  Loading the world though - yeah, incredibly slow.  Not sure if this is a 1.16 thing or an E6 thing.

**Comment by MuteTiefling** [comment]
https://github.com/TeamJM/journeymap/issues/319

Already reported it seems.

**Comment by jinks** [comment]
> Can confirm these issues with JourneyMap teleportation - same issue for me.
> 
> @Ticskter My pack load time seems reasonable, or about what I'd expect for a pack of this size. Loading the world though - yeah, incredibly slow. Not sure if this is a 1.16 thing or an E6 thing.

I have experienced the same thing in other packs, so it seems to be a 1.16 thing. On the flip side, changing dimensions is now way faster than in the past.
