### ISSUE TITLE
Dragon auto respawns

### ISSUE THREAD

**Issue by Rafael-RD** [EnigmaticaModpacks/Enigmatica6#3307]
### Modpack Version

0.5.11

### Describe your issue.

If you use Industrial Foregoing mob crusher to kill the ender dragon it dies, drops the loot and respawns after 1 minute

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
