### ISSUE TITLE
make resourceful bees spawn more commonly

### ISSUE THREAD

**Issue by Mass1milian0** [EnigmaticaModpacks/Enigmatica6#3363]
### Describe your suggestion

Ive noticed that resourceful bees do not spawn commonly and that the variety of the bees that do spawn is very limited (you will find coal bees and rgbee everywhere but it will take hours to find a creeper bee)

My suggestion is to balance out the spawn of bees in such a way to induce more variety

### Why would you like this added/changed?

Mainly to make it easier for the player to get into bees, everytime i want to make a specific bee im usually always missing 1 or 2, so i have to go look for them, which usually takes from hours to days depending on the bee (i still haven't been able to find oreo bees, ive been 2 days straight without sleeping trying to find one), it would also facilitate new player into getting into resourceful bees mod, which by itself is confusing to many

**Comment by NillerMedDild** [comment]
Thanks for the suggestion.

@TemperedFool what do you think, can we bump up the weight a bit? Not for the Oreo bee since it's supposed to be super rare, but the others?

**Comment by TemperedFool** [comment]
> @TemperedFool what do you think, can we bump up the weight a bit? Not for the Oreo bee since it's supposed to be super rare, but the others?

Yeah, the beeper specifically has come up frequently as being hard to find. I'll take a look. I don't want to go too crazy bumping up spawn rates though, since that'll just crowd out other passives...

**Comment by TemperedFool** [comment]
Apparently I failed to mark this as fixed earlier - this was fixed in #3703 and released in 0.5.20...
