### ISSUE TITLE
Unable to craft Alfsteel AIOT using the Quintuple Alfsteel recpie 

### ISSUE THREAD

**Issue by Wolfog288** [EnigmaticaModpacks/Enigmatica6#3365]
### Modpack Version

1.16.5 0.5.14

### Describe your issue.

After gathering all the resources to make the Alfsteel AOIT i go to the smithing table with my D tier Terrasteel AOIT and Quintuple Alfsteel ingot, place both in the smithing table as shown in jei, and which jei autofills when having in inventory, for it to come up with the red cross over the final line indicating a non existent recipe.

https://i.imgur.com/rD267mxh.jpg   In Table

https://i.imgur.com/XWHCjwih.jpg in Jei

### Latest Log

https://paste.atlauncher.com/view/12f1837e-b408-4a2d-87b3-963c31b558ba

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm not sure what's going on here to be honest, I've been unable to fix the recipe so far ^^'

**Comment by Wolfog288** [comment]
Ah ,for the meantime ive sacrificed the items and spawned in the aoit, but if you manage to find a fix for this ide love to hear what the issue was upon resolving :)

**Comment by otvoiski** [comment]
same problem!

**Comment by NillerMedDild** [comment]
Yes, we know :P
