### ISSUE TITLE
Thermal Series Fractioning Still does not accept Latex from Refined Storage Crafter.

### ISSUE THREAD

**Issue by zcrowell** [EnigmaticaModpacks/Enigmatica6#3475]
### Modpack Version

0.5.14

### Describe your issue.

While trying to automate Dry Rubber using the Fractioning Still recipe, I found that it won't accept Latex from the Crafter.

I was able to work around the issue by placing the Crafter onto a Mekanism Basic Fluid Tank, then setting the Fractioning Still to auto-accept input.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
Yeah there seems to be something weird about the fractioning still. I'll investigate when I get the time.
