### ISSUE TITLE
Integrated Dynamics Squeezer does not accept items when there's a Dank in your inventory

### ISSUE THREAD

**Issue by staviq** [EnigmaticaModpacks/Enigmatica6#3478]
### Modpack Version

0.5.16

### Describe your issue.

Integrated Dynamics Squeezer does not accept items when playing on a server.

Squeezer should accept menril logs or wood as a way to produce menril resin, it does not.

I build it exactly like always, on top of drying basin, with a pressure plate next to it. I can jump on it and it does animate, but does not accept menril logs or any items i tried.

**Does work in single player**, does not on a server.

Tested with and without optifine.

I see no errors on the server console.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by afolk2** [comment]
I just started a new server myself and don't have a problem with this at all.

I think this is how you have it built from what you are saying. I squished the log some so that you could see it was working.

![2021-10-17_16 55 05](https://user-images.githubusercontent.com/24921099/137647885-171f17ae-d266-420f-b87d-ed88637db97e.png)

**Comment by staviq** [comment]
Yes, exact same setup.

I have tested it a couple of times, single player and on my server, it works in singleplayer but not on the server.

When i try to insert an item into either the squeezer or even the drying basin, just nothing happens when on the server, but works as intended in single player.

I tried to craft all the items, grow the menril from sappling, tried cheating the items in from jei, neither works on the server.

**Comment by nitrofenix** [comment]
Do you have a dank null anywhere in your inventory? I had a similar issue that a [quick Google search](https://www.reddit.com/r/allthemods/comments/lg6r6q/squeezer_from_integrated_dynamics_is_broken/gmwyduu/) solved by suggesting to put the dank temporarily in your backpack.

**Comment by staviq** [comment]
> Do you have a dank null anywhere in your inventory? I had a similar issue that a [quick Google search](https://www.reddit.com/r/allthemods/comments/lg6r6q/squeezer_from_integrated_dynamics_is_broken/gmwyduu/) solved by suggesting to put the dank temporarily in your backpack.

Yes i do, always in my last tool slot, and in the singleplayer i didn't because i just created a fresh world for testing.

I'll try this tomorrow, and let you know.

**Comment by staviq** [comment]
@nitrofenix 

Yup, that was it. Dank is screwing this up.
And you actually need to have it out of inventory for squeezer to work, not just out of the toolbar.

Ok, so this confirms the source of the problem, and gives a workaround, but the problem still exists, so i leave it up to You whether close this bug or not.

Maybe possibly add a comment in the squeezer quest description ? Just in case anybody else has this problem ?
