### ISSUE TITLE
Living armor equip causes ctd and world corrupt

### ISSUE THREAD

**Issue by ThwartAbyss54** [EnigmaticaModpacks/Enigmatica6#3494]
### Modpack Version

Enigmatica 6 0.5.16

### Describe your issue.

Equipping the last piece of Living Armor from Blood Magic caused an immediate ctd and seems to have corrupted the world because it will not load back up.

### Crash Report

https://pastebin.com/WeT6i8iW

### Latest Log

Its to big, if you need it i can send it via discord i believe

### Have you modified the modpack?

Yes

### User Modifications

Removed overloaded armor and toughness bar. Added Classic Bars

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. I found it on the BM tracker here: https://github.com/WayofTime/BloodMagic/issues/1853
Hopefully they'll get it fixed :)

**Comment by ThwartAbyss54** [comment]
Not gonna lie, looked and skipped right over it on bms issues page. Thanks!
