### ISSUE TITLE
Inconsistent issue with PCR Programmers refusing to switch difficulty

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3498]
### Modpack Version

Enigmatica 6 0.5.16

### Describe your issue.

For reasons known, the PCR Programmer refused to switch difficulties to either Medium or advanced. While visually the 'advanced' tickbox got ticked, the advanced puzzle pieces did not become available. I did try going back and forth on the list of PCR puzzle pieces, but the amount of pieces available did not update.
After exiting the PCR Programmer GUI, the difficulty was Easy again as if nothing had changed. Somebody else in the Enigmatica discord also claimed to have had this issue.

It fixed itself after setting it to advanced, hovering over one of the puzzle pieces, pressing 'I' to open its manual entry, then returning to the PCR Programmer from the manual and setting the difficulty to advanced (and suddenly, the missing pieces had returned and started to behave as usual. According to the other player experiencing this issue, it may also fix itself after restarting the game.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks, I've relayed the issue

**Comment by MuteTiefling** [comment]
This has been fixed.
