### ISSUE TITLE
Resourceful Bees Beehive de-tier when broken with Silktouch

### ISSUE THREAD

**Issue by Ridanisaurus** [EnigmaticaModpacks/Enigmatica6#3517]
### Modpack Version

0.5.16

### Describe your issue.

When breaking a Tiered Resourceful Bees Beehive (tiered with an item upgrade) with Silktouch (tested with Vanilla Silktouch, and both a Silktouch Pickaxe from Tetra, and Ars Nouveau spell using the Extract Glyph) returns the original Beehive, disregarding the tier upgrade applied to it.

It's a mod issue as far as I can tell, and reported it to RBees with https://github.com/Resourceful-Bees/ResourcefulBees/issues/294

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Both

**Comment by theboo** [comment]
Is this still an issue in newer RBees? Guessing this can be closed

**Comment by MuteTiefling** [comment]
Seems fixed on their end yeah.
