### ISSUE TITLE
Morphing Tool Quest.

### ISSUE THREAD

**Issue by HeavyDeception** [EnigmaticaModpacks/Enigmatica6#3628]
### Describe your suggestion

A quest for the Morphing tool.

### Why would you like this added/changed?

I didn't even think about it until I was opening my bag and thinking man why is there no tool for everything.

Also, does anyone know if we can turn it into a sonic screwdriver when we add the Tardis mod?

**Comment by theboo** [comment]
Morph-o-tool quest is a great idea... Tbh I thought we had one lol... 

As for the Sonic screwdriver, it may be possible? But the TARDIS mod being added to the pack no nowhere near being a certainty at this time

**Comment by HeavyDeception** [comment]
@theboo I suggested adding support for it to the dev of the New tardis mod because it would be so cool if their Sonic screwdriver could use it or something when it's added with the mod.

**Comment by MuteTiefling** [comment]
Better late than never :D
