### ISSUE TITLE
Immersive Engineering Ores don't drop chunks [They don't generate either]

### ISSUE THREAD

**Issue by hofmannk69** [EnigmaticaModpacks/Enigmatica6#3651]
### Modpack Version

0.5.20

### Describe your issue.

Immersive Engineering Ores drop as the ore and not the chunk when mined.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### User Modifications

Nothing added or removed from the pack.  No optifine.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by hofmannk69** [comment]
Deleted the instance and recreated a new one and cant reproduce this.  Sorry for the bother.

**Comment by NillerMedDild** [comment]
No bother, this does happen once in a while, for some reason the IE server config is seen as invalid and is reset to default. We'll override the IE ore loot table so they drop chunks :)
