### ISSUE TITLE
Shift the Dragon Head from the Centre of the Portal upon Dragon Death

### ISSUE THREAD

**Issue by RobuxShooters** [EnigmaticaModpacks/Enigmatica6#3710]
### Describe your suggestion

Shift the dragon head that appears at the base of the centre column of the portal when the Ender Dragon dies to the side of the portal or perhaps somewhere further out from the portal.

### Why would you like this added/changed?

When the Ender Dragon dies, a dragon head spawns at the centre column of the portal that brings players back to the Overworld. Due to the way it generates after the portal blocks have formed, breaking the dragon head usually causes the head to fall into the portal and be brought to the original spawn point in the Overworld, which may be difficult to get back to due to how much players explore in this pack.

Even if the dragon head does not fall into the portal, players may have a difficult time getting the head without a magnet or a tool that teleports broken blocks into the player's inventory. Having a magnet sometimes does not help either, as the magnet may pull the head into the portal blocks when it is trying to pull the item towards the player.

Spawning the head on the edge of the portal or further out from it should hopefully stop the head from dropping into the portal accidentally. This also avoids a hole in the portal in which the dragon head spawns.

Edit: This is where the head spawns when the dragon dies (yes, in the hole where a portal block should be at):
![2021-11-13_01 57 33](https://user-images.githubusercontent.com/16001607/141513113-8df39818-2b1b-4831-995b-bf7a6c60da32.png)

With the head re-added for clarity,
![2021-11-13_01 59 34](https://user-images.githubusercontent.com/16001607/141513271-327f729a-560c-411f-a9cb-529fac678317.png)

**Comment by Darkere** [comment]
... Can you not just place some blocks beneath the head?

**Comment by RobuxShooters** [comment]
Unfortunately, the head is surrounded on all sides (except the top) by blocks that cannot be broken normally (bedrock and the portal blocks themselves), so no.

**Comment by theboo** [comment]
So apparently the portal frame can generate at different y-levels? The head is supposed to place on the top most block of the portal frame one space below where the egg spawns...

When I tested this script, I loaded 10 new worlds and the portal frame was in the exact same spot in all of them... Apparently, yours generated a few blocks higher

**Comment by Darkere** [comment]
I can add this to more dragon eggs pretty easily. I don't think its that easy to do make work in KubeJs.

**Comment by theboo** [comment]
that would be great haha. Otherwise i think my only options, with the current script anyway, would be to either spawn it floating in the air high enough that the y-level variation doesnt matter, or make it an actual drop from the dragon, but that's nowhere near as fun...

**Comment by BooBeerb** [comment]
making it an actual drop from the dragon is not simple because the dragon doesn't really die in a traditional way, and has no loot tables from what i recall

**Comment by NillerMedDild** [comment]
> I can add this to more dragon eggs pretty easily. I don't think its that easy to do make work in KubeJs.

yes please 😄
