### ISSUE TITLE
RFTools Utility, Cannot get property EnumProperty crash

### ISSUE THREAD

**Issue by clienthax** [EnigmaticaModpacks/Enigmatica6#3724]
### Modpack Version

0.5.20

### Describe your issue.

Server crashed during ticking

### Crash Report

https://gist.github.com/clienthax/62210bef61e985a15bac8c1897962554

### Latest Log

https://gist.github.com/clienthax/f774411cfbc3e670b9953aec55fd96ea

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Relayed, thank you :)
