### ISSUE TITLE
Make Gold Bars meltable

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#3746]
### Describe your suggestion

Make it possible to melt Gold Bars into 3 Gold Nuggets, similar to what you can do with Iron Bars.

### Why would you like this added/changed?

It makes it possible to recycle Gold Bars either found in the world or crafted.

**Comment by MuteTiefling** [comment]
Should be good. Added dustrial decor bars too, allowing them to melt to 3 nuggets like vanilla bars.
