### ISSUE TITLE
Game hard-crashes when attempting to use the tool menu for "Chisel & Bits" measuring tape item

### ISSUE THREAD

**Issue by Foxtrot2Nov** [EnigmaticaModpacks/Enigmatica6#3754]
### Modpack Version

0.5.20

### Describe your issue.

Game hard-crashes when attempting to use "Open Tool Menu" for Chisel & bits "Tape Measure" item. I tried rebinding the keys and it still crashes. Not sure what else to try troubleshooting-wise. 

[crash-2021-11-20_22.41.54-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/7575717/crash-2021-11-20_22.41.54-client.txt)
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7575718/latest.log)
 

### Crash Report

https://github.com/NillerMedDild/Enigmatica6/files/7575717/crash-2021-11-20_22.41.54-client.txt

### Latest Log

https://github.com/NillerMedDild/Enigmatica6/files/7575718/latest.log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found reported here: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/780

**Comment by tyr0wl** [comment]
This has been fixed with 1.0.63. Tested it in my world and the menu works now.
