### ISSUE TITLE
Non-vanilla/simple farming/farmer's delight crop seeds can't be made into IE Plant Oil

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica6#3773]
### Modpack Version

0.5.20

### Describe your issue.

The Immersive Engineering can't make Plant Oil out of seeds that aren't vanilla/Simple Farming/IE/Farmer's Delight. Similar machines like the IF Bioreactor or PNC Vegetable Oil don't seem to have this issue.

The missing seeds are the following:
* Undergarden's Gloomgourd
* Occultism's Demon's Dream
* Supplementaries's Flax (can you even get those?)
* BetterEnd's 11 seeds (they all work for Bioreactor or Vegetable Oil)
* Sushi Go Crafting's 5 seeds (not sure the harvested Sesame one should count, but the unharvested ones definitely)
* Atum's Flax and Emmer

Also Environmental adds Cattail Seeds, I don't know how/if you can obtain them, but unlike the other listed here they don't work in the IF Bioreactor or for PNC Vegetable Oil, so dunno.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)

**Comment by Lykrast** [comment]
While I still remember it, the IE Fermenter might also be missing some crops, though I didn't take the time to note what is missing. I can open another issue and see if I can get a list next time I get some time.

**Comment by MuteTiefling** [comment]
Sorry for the delay, completely forgot about this one
