### ISSUE TITLE
[Mod Suggestion] Observable

### ISSUE THREAD

**Issue by RobuxShooters** [EnigmaticaModpacks/Enigmatica6#3775]
### URL

https://www.curseforge.com/minecraft/mc-mods/observable

### Why would you like the mod added?

So far in this modpack, we have Crash Utilities and Spark to diagnose any performance and lag issues occurring in our worlds. However, Spark is relatively difficult to read without some experience and less experienced or less technical players may have a hard time assessing their issues using Spark. Crash Utilities can list out which tile entities are ticking and the number of entities in the world, but doesn't really give information on which tile entities use up the most tick time.

Hence, I think that this mod could be more accessible towards inexperienced and less technical players to diagnose and identify lag-inducing entities / tile entities. It is similar to Lag Goggles for 1.12 and can tell you the tick times of specific tile entities compared to Spark which tells you the total tick times of a particular type of tile entity without telling you its location in the world. (This makes it harder to tell exactly *which* specific blocks are lagging the world when all of them are jumbled together into one profiling report.)

**Comment by NillerMedDild** [comment]
Seems like a solid addition, I'll test it 👌
