### ISSUE TITLE
[Mod Suggestion] Mekanism: Addons

### ISSUE THREAD

**Issue by RobuxShooters** [EnigmaticaModpacks/Enigmatica6#3776]
### URL

https://www.curseforge.com/minecraft/mc-mods/mekanism-addons

### Why would you like the mod added?

There are quite a few enchantments in this pack, but because Mekanism doesn't allow enchantments on the MekaSuit, it makes it somewhat less useful in terms of utility. For example, you have Aqua Affinity and Air Affinity to restore mining speed while underwater or while flying in the air, but because the MekaSuit doesn't take enchantments normally, you lose out on these nice enchantments while wearing the suit, and you mine much slower underwater and in the air.

Hence, this mod adds a few new Units that can be installed in the MekaSuit to act as 'enchantments' for the MekaSuit for these cases where a player would lose out on the utility due to the MekaSuit not being able to be enchanted.

Notable features include:
- Cancelling the mining speed penalty when in the air
- Cancelling the mining speed penalty when underwater
- Allowing 3x3 mining for the Meka-Tool
- A Meat Feeder alternative by filling Saturation too for the Nutritional Injection Unit instead of just Hunger
- The Meka-Tool can act as a Wireless Grid for RS.

**Note:** There seems to be an issue with it not launching with RS right now on the mod's GitHub. Would be wise to wait until that issue is fixed before adding this if this is considered.

**Comment by NillerMedDild** [comment]
Solid addition, if/when https://github.com/MorningSage/Mekanism_Addons/issues/7 is fixed 😄 
https://github.com/MorningSage/Mekanism_Addons/issues/5 might also be blocking, we'll see.

**Comment by Darkere** [comment]
I believe the first one is already fixed? The curseforge description at least talks about it. 

I just commented there because it was literally impossible to find out which mod was causing the crashes, as they called their mixin "rs".

**Comment by RobuxShooters** [comment]
> I believe the first one is already fixed? The curseforge description at least talks about it.
> 
> I just commented there because it was literally impossible to find out which mod was causing the crashes, as they called their mixin "rs".

Ah if that's the case, then it should be okay. I just assumed it wasn't fixed yet because the issue was still open.

**Comment by RobuxShooters** [comment]
I tried out this addon mod by adding it to my own instance and it looks quite solid. I do think there needs to be some adjustments though.

The MekaSuit can hold 128,000 mB of Sodium with all 4 Ignition Retardation Units installed, but it uses up 1234 mB/t of Sodium when removing fire damage (at the same time, the Superheated Sodium is cooled back to Sodium, so it's not exactly using 1234 mB/t of Sodium). This results in around 20/21 seconds of being in lava or fire without taking damage or having that 'on fire' visual indicator obscuring the player's view. I reckon that this number should be increased somewhat by increasing how much Sodium can be stored in the MekaSuit or by reducing how much Sodium is used per tick when in lava or fire. Considering how late-game(ish) the MekaSuit is, 20/21 seconds of fire damage immunity is somewhat underwhelming. I would suggest increasing it so that the Unit can allow the player to last around 3-5 minutes in lava or fire without taking damage. Additionally, the rate at which Superheated Sodium is cooled back to Sodium can be increased to balance out how much Sodium the MekaSuit can hold (if buffed).

In addition to that, you might need to change some of the recipes up as one of the Units uses a Turtle Shell and some Scutes in its crafting recipe, which may be difficult to come across (but at least there's a chance to get turtles from the Astral Shrines now).

The Luck Upgrade crafting recipe could also be modified as it currently requires 2 Antimatter Pellets, 2 Polonium Pellets, and 1 Plutonium Pellet just for 1 upgrade.

**Comment by YashTFEM** [comment]
We already have other methods for infinite fire resistance, like the ring of odin. I don't see why we need this.

**Comment by YashTFEM** [comment]
Also, there's no need for the last two changes, because the mekasuit is ment to have a sense of difficulty in crafting and upgrading it

**Comment by RobuxShooters** [comment]
> We already have other methods for infinite fire resistance, like the ring of odin. I don't see why we need this.

This addon mod doesn't just add this single Unit to the MekaSuit - I was referring to how underwhelming it feels as compared to 128,000 mB of hydrogen contained for the Jetpack Unit, the Ignition Retardation Unit 'burns' through Sodium extremely quickly compared to the Jetpack Unit.

Also, the 'Fire Resistance' serves as an alternative with the same functionality as a Security Upgrade in a Pneumatic Chesplate. Given that the Pneumatic set can be enchanted and kitted with various upgrades and the MekaSuit lacks utility in that regard, I'm just hoping that by having this addon mod in the pack, the MekaSuit can get more utility for anyone who wants to use the MekaSuit as their main armour set (instead of feeling cheated out on nice utility upgrades just because they decided not to pursue a certain mod).

> Also, there's no need for the last two changes, because the mekasuit is ment to have a sense of difficulty in crafting and upgrading it

Of course it should have a sense of difficulty in crafting and upgrading it, but having to travel thousands of blocks just to find turtles causes the world size to become extremely large, although that is somewhat mitigated with the addition of a breeding pair of turtles that can be found in Astral shrines occasionally, but it still depends on some luck in finding the structures and getting a loot table roll for the turtles.

The Luck Upgrade has no relation to the MekaSuit whatsoever, it is meant to be an upgrade to certain processing machines to double their output occasionally (i.e. Energized Smelter and Enrichment Chamber, from what I see so far). I felt that gating such a Unit behind Antimatter makes it a somewhat redundant upgrade as you would rather consider other processing options as opposed to spending a ludicrous amount of materials just for one upgrade. Sure, it probably works on other items and not just ores, but given the small chance of doubling the outputs, its effective multiplier is probably much much less than 2x.

**Comment by YashTFEM** [comment]
Again, many other infinite options for fire resistance. You don't need to have a mekasuit ignition retardation. Also when you look at the luck upgrade from a long time perspective, it gives you a lot more stuff for a very cheap price. Assume you put a luck upgrade on everything in an ore processing unit. The chance of doubling the ore and items increases by a lot. And if you want turtles, there are many ways of spawning them using other mods in this pack. It's isn't forcing you to travel thousands of blocks. You could always use natures aura to get turtles.

**Comment by YashTFEM** [comment]
And ofc, if you're worried about the ignition retardation module there may be a tiny chance that the devs reduce the sodium consumption rate so as to have an actual use for it.

**Comment by MuteTiefling** [comment]
I agree with robux. If we do add it, recipes and rates will need to be tweaked to make them worthwhile.

**Comment by YashTFEM** [comment]
And I completely disagree with you. Many methods for achieving the things robux wants. We don't have to go around adding a mod when it adds something we already have

**Comment by YashTFEM** [comment]
I believe this is the reason behind some mods not being added to E6 which you highlighted before

**Comment by RobuxShooters** [comment]
The thing is, the mods you suggested are large-scale mods that add loads of content into the pack, which severely increases load time. This addon mod adds like, what, 8 items to the game? And for the most part, it is QOL for any players using the MekaSuit instead of the Pneumatic Set without having to cheese the system by using Pedestals and such just to get basic underwater and mid-air mining penalty negation, among other useful utilities.

**Comment by Ridanisaurus** [comment]
> I believe this is the reason behind some mods not being added to E6 which you highlighted before

You can't really compare the 2 in this case. Some of the mods that didn't make the cut, and flagged as duplicated content were mostly stand alone mods (i.e. the addition of AE2 when there is RS, or Pam's Harvest when there is Simple Farming), while this is an addon to a mod that we already have, and it just adds couple items that alone won't replace the functionality of the other content you tagged as duplicate, like the Odin Ring from Botania for example. 
It brings the customization level of the Mekasuit to the other available option of end-game tech-based armor that is the PNC Armor.

**Comment by MorningSage** [comment]
For what it’s worth, I admit that I’m not great at recipes, etc.  They can all be tweaked from a mod perspective so that pack devs don’t have to put in a bunch of work just to integrate it so it feels like it fits.  I’m definitely open to suggestions.

There are a few updates I need to make so that it plays better with other mods and versions of Java.  I’ll make these changes as soon as I’m back from my vacation through the rest of the year.  In the meantime, if there are changes that anyone feels are required or would be nice, open an issue on my GitHub and I’ll address in January when I have access to a computer.

I’ve had quite a few good ones come in, so thank you all for contributing!

**Comment by NillerMedDild** [comment]
I'll close this for now, we can re-open if the mod is fixed and updated :)
