### ISSUE TITLE
Custom bees show entity ID when selected with Honey Dipper

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#3784]
### Modpack Version

0.5.20

### Describe your issue.

Custom bees created by the modpack show the entity ID when selected with Honey Dipper, unlike the base bees made with the mod.

![bild](https://user-images.githubusercontent.com/12349921/143564886-c25c3b55-2b90-4191-a0e4-9f3fa0c4f4e0.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
That's pretty weird - that key is set here: https://github.com/NillerMedDild/Enigmatica6/blob/master/config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json#L300

I'll report this over on the RBees tracker.

**Comment by TemperedFool** [comment]
They know what's going on, should get fixed at some point.

**Comment by Vaerys-Dawn** [comment]
seems to be fixed in latest dev build, requesting close

**Comment by Vaerys-Dawn** [comment]
deleted comment as i realised i needed to test multiplayer too

**Comment by Vaerys-Dawn** [comment]
![image](https://user-images.githubusercontent.com/5305116/144563807-b76c64b0-83ad-423a-8858-08795b178d85.png)
confimed fixed on dev
