### ISSUE TITLE
Marketplace crash when no trade is selected

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica6#3803]
### Modpack Version

0.5.20

### Describe your issue.

When placing Emeralds in the Marketplace's trade UI without a trade selected, the game crashes. I managed to do it twice in a row on the public server.

Selecting a trade before putting the Emeralds works as intended.

Pastebin has a size limit so I cut the log to when JEI is done (there's a LOT of recipes error apparently) and the world is loaded.

Despite Immersive Backpacks being mentionned in the stack trace, taking it off did not change the crash.

### Crash Report

https://pastebin.com/XBiB6pL7

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by g0urra** [comment]
Works as intended on my side playing on server, I'd recommend you to check the support channel on the Enigmatica Discord.

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/ModdingForBlockheads/FarmingForBlockheads/issues/127
