### ISSUE TITLE
Storage Drawers upgrade recipe issues

### ISSUE THREAD

**Issue by HappyHepo** [EnigmaticaModpacks/Enigmatica6#3808]
### Modpack Version

0.5.21

### Describe your issue.

Storage drawers Storage Upgrades and Void Upgrades only accept Scented Sticks from KubeJS, but there is no recipe to obtain them

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Oh, no this one's fixed in dev already https://github.com/NillerMedDild/Enigmatica6/commit/6da657811cd2049fabccdb094b6dcaddf3d782ef
