### ISSUE TITLE
Bad lightning no cookie

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica6#3811]
### URL

https://www.curseforge.com/minecraft/mc-mods/bad-lightning-no-cookie

### Why would you like the mod added?

Localized lightning sound so you won't hear everyone and their mother doing lightning crafts, but will still be able to hear apotheosis bosses spawning around you!
(Bad wither no cookie's shutoff is global no lightning sound at all)
Buuz doesn't have enough mods in the pack anyway...

Won't be approved on cf until tomorrow I guess

**Comment by Buuz135** [comment]
![Approved](https://c.tenor.com/82Rr2PPBCtIAAAAd/cat-jam-cat.gif)
