### ISSUE TITLE
Petal Apothecary not accepting cobblestone slab variants

### ISSUE THREAD

**Issue by jcsanady** [EnigmaticaModpacks/Enigmatica6#3822]
### Modpack Version

0.5.21

### Describe your issue.

When attempting to craft the petal apothecary from Botania, it doesn't accept variants of 'cobblestone slab' such as 'gabbro cobblestone slab'

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
