### ISSUE TITLE
Refined Storage Wireless Transmitters only function on the top side of cables

### ISSUE THREAD

**Issue by incomingnerd** [EnigmaticaModpacks/Enigmatica6#3832]
### Modpack Version

0.5.21

### Describe your issue.

Placing Refined Storage Wireless Transmitters on any side of a wire _except_ the top causes them to not function.

![2021-12-02_17 57 21](https://user-images.githubusercontent.com/43726486/144477407-929108a2-ce35-4260-bea3-afaed19d9428.png)

This functioned correctly in 0.5.20. Upon upgrading to 0.5.21 my wireless crafting grid stopped working, whereupon I discovered this bug.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by incomingnerd** [comment]
As an extra added weirdness: The transmitter seems to work absolutely fine if placed on the side or bottom of a controller, but placing it on the side or bottom of any other RS block behaves the same as the cable.

**Comment by Darkere** [comment]
Fixed in dev.

**Comment by NillerMedDild** [comment]
https://github.com/refinedmods/refinedstorage/issues/3145

**Comment by Darkere** [comment]
oh LOL wrong git.

**Comment by NillerMedDild** [comment]
I suspected as much 😄
