### ISSUE TITLE
[Expert] Modified recipes for Sophisticated Backpacks reset the backpack's contents after an upgrade

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3840]
### Modpack Version

Enigmatica 6 0.5.21+ (commit 0dfcb4604ca8327f09d8ff45cda001caae9b6f31 dev branch, expert pack mode)

### Describe your issue.

Recipes for Sophisticated Backpacks in Expert mode do not keep the backpack's NBT data, resetting it instead.
Expected behavior is that the backpacks won't lose their contents after an upgrade.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by P3pp3rF1y** [comment]
I am no expert on kube.js recipe overrides, but for tier upgrade recipes to properly copy contents and set the new size of backpack they need to be of type `"type": "sophisticatedbackpacks:backpack_upgrade"`. That's a custom recipe that makes sure this happens. 

And I don't see this type used here https://github.com/NillerMedDild/Enigmatica6/blob/master/kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/sophisticatedbackpacks/backpack_upgrade.js

**Comment by NillerMedDild** [comment]
Hopefully fixed in-dev, seems like a typo, thanks for the help P3pp3rF1y :D

**Comment by MuteTiefling** [comment]
Oh. Nice catch. I was staring at that and never even noticed...

**Comment by P3pp3rF1y** [comment]
Looks like I learnt a bit about how these scripts work and where to look. I assumed the type should be up there in each of the recipe blocks, but as I can see it's just a matter of saying it's a custom recipe at the bottom.

**Comment by NillerMedDild** [comment]
Both would work, setting it at the bottom just saves a few lines :)

**Comment by Rodg88** [comment]
Looks like this happens with danks too, just upgraded from t2 to t3 dank and the upgraded one was empty

**Comment by MuteTiefling** [comment]
same issue with danks. testing a fix right now

**Comment by MuteTiefling** [comment]
Danks fixed
