### ISSUE TITLE
Rusty Iron not updated with the other ingots and nuggets.

### ISSUE THREAD

**Issue by HeavyDeception** [EnigmaticaModpacks/Enigmatica6#3844]
### Describe your suggestion

Would it be possible to update the texture to the same level as the other nugs?

### Why would you like this added/changed?

It would look nicer and you find them in a lot of chests.

**Comment by NillerMedDild** [comment]
@Ridanisaurus thoughts? 😄

**Comment by Ridanisaurus** [comment]
Sure thing. I will provide a texture to update them to match the current EE Style.

**Comment by HeavyDeception** [comment]
I don't know why this excites me so much lol.
