### ISSUE TITLE
Enigmatica 6 0.5.21 (server/multiplayer) Industrial Foregoing Dissolution Chamber power usage / UI desync

### ISSUE THREAD

**Issue by mjevans** [EnigmaticaModpacks/Enigmatica6#3852]
### Modpack Version

0.5.21

### Describe your issue.

Since updating the client and server to 0.5.21 the Dissolution Chamber UI appears to be desynced from the machine state, with a constantly refilling power buffer, and a fluid tank that shows 2x the capacity (16 buckets rather than 8).

This issue ONLY shows up on a multiplayer server, single player creative testing does not manifest the problem.

All crafting operations are also insanely more power expensive.

Enigmatica6-21/mods/industrial-foregoing-1.16.5-3.2.14.7-16.jar
Enigmatica6-20/mods/industrial-foregoing-1.16.5-3.2.14.6-14.jar

I tried to replicate the situation in my mob grinder in singleplayer creative with a Dissolution Chamber, creative Essence tank, power cable, creative energy cube, a trash can to handle the XP bottles.

efc4844ec375f8f77d75272da8b1fa94 *../Enigmatica6-0.5.21.zip

config/industrialforegoing/machine-core.toml

        [MachineCoreConfig.DissolutionChamberConfig]
                #Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
                maxProgress = 100
                #Amount of Power Consumed per Tick - Default: [60FE]
                powerPerTick = 60
                #Max Stored Power [FE] - Default: [10000 FE]
                maxStoredPower = 10000
                #Max Amount of Stored Fluid [Input] - Default: [8000mB]
                maxInputTankSize = 8000
                #Max Amount of Stored Fluid [Output] - Default: [8000mB]
                maxOutputTankSize = 16000

I have not modified the configuration files since extraction, and Enigmatica 6 Server 0.5.21 (Fix 2 - Electric Boogaloo) is only 5KB and appears to just be wrapper scripts.

I do not use Discord, so I have not been able to check if there's E.G. an expert / hard mode that got enabled by default in the latest update; though this seems more likely to be an Industrial Foregoing bug.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
> I do not use Discord, so I have not been able to check if there's E.G. an expert / hard mode that got enabled by default in the latest update; though this seems more likely to be an Industrial Foregoing bug.

We added a config override for expert mode, it should not be active by default though, we'll investigate 👍

**Comment by Darkere** [comment]
The issue is that version 0.5.21 ships with the IF expert configs. If configswapper fails to apply normal mode for whatever reason they will stay there..

**Comment by NillerMedDild** [comment]
I .. had not realized that you meant in the actual config folder until just now.

**Comment by mjevans** [comment]
What can I do to set this to the correct (normal???) mode on my server?

**Comment by NillerMedDild** [comment]
Go to the folder `config\configswapper\normal\config` and copy the `industrialforegoing` - Paste it into the `config` folder

**Comment by mjevans** [comment]
I have confirmed the following resolves the issue I reported, though I was hoping for more generic documentation of some automated way to apply the entire normal / expert configs on a typical Linux server command line.

# stop the server

# remove old config folders and files
rm -r config/industrialforegoing config/Mekanism config/powah/ config/mininggadgets-common.toml

# copy normal config
cp -a --target=config/ config/configswapper/normal/config/industrialforegoing config/configswapper/normal/config/Mekanism config/configswapper/normal/config/powah config/configswapper/normal/config/mininggadgets-common.toml

# start the server

**Comment by Skar78** [comment]
> I have confirmed the following resolves the issue I reported, though I was hoping for more generic documentation of some automated way to apply the entire normal / expert configs on a typical Linux server command line.
> 
> # stop the server
> # remove old config folders and files
> rm -r config/industrialforegoing config/Mekanism config/powah/ config/mininggadgets-common.toml
> 
> # copy normal config
> cp -a --target=config/ config/configswapper/normal/config/industrialforegoing config/configswapper/normal/config/Mekanism config/configswapper/normal/config/powah config/configswapper/normal/config/mininggadgets-common.toml
> 
> # start the server

Please note that configswapper/normal/config/powah does NOT contain a general_common.toml so it will set a defualt one upon start and that will enable urnaninite production and disable some other things

**Comment by NillerMedDild** [comment]
> Please note that configswapper/normal/config/powah does NOT contain a general_common.toml so it will set a defualt one upon start and that will enable urnaninite production and disable some other things

It doesn't have to, the normal config folder contains that file :)

**Comment by Skar78** [comment]
> > Please note that configswapper/normal/config/powah does NOT contain a general_common.toml so it will set a defualt one upon start and that will enable urnaninite production and disable some other things
> 
> It doesn't have to, the normal config folder contains that file :)

Not if you rm the folder as stated in mjevans step by step guide :)
