### ISSUE TITLE
Botony Pots Colorized with Hopper Transformation

### ISSUE THREAD

**Issue by Vonrek** [EnigmaticaModpacks/Enigmatica6#3865]
### Modpack Version

0.5.21

### Describe your issue.

The recipe to undie the Hopper Bottony Pot is a bucket of water and the pot.
The recipe says it returns a generic Hopper Botony Pot, but returns a generic Botony Pot without Hopper

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
