### ISSUE TITLE
Replace Better End with Better End Reforked

### ISSUE THREAD

**Issue by ShakterNano** [EnigmaticaModpacks/Enigmatica6#3878]
### URL

https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

### Why would you like the mod added?

It's a more updated version of Better End with more content, and may also fix some issues with the original Better End mod.

**Comment by NillerMedDild** [comment]
Do you know what we would gain by updating? :)

**Comment by ShakterNano** [comment]
More content like biomes and hopefully less bugs and better stability.

**Comment by NillerMedDild** [comment]
To be honest it looks just as unmaintained as the original, I prefer sticking with what we have :)

**Comment by Abalieno** [comment]
I've verified that BetterEnd Reforked works with Rubidium 0.2.3

Rubidium is the most recent port of the Sodium style of performance mods, so it might be nice to have it. I don't have time to text extensively, but Magnesium was crashing soon after logging into a world, and BetterEnd Reforked was the reason of the crash.

https://www.curseforge.com/minecraft/mc-mods/rubidium

Someone who's well into the progression could try to run a test and see if it plays nice with the other mod.

Also the rest of the suit could be interesting to try:

https://www.curseforge.com/minecraft/mc-mods/radium-reforged (Lithium/Roadrunner)
https://www.curseforge.com/minecraft/mc-mods/radon (Phosphor/Sulfuric/Starlight)

**Comment by NillerMedDild** [comment]
We're not going to add those mods, I generally don't trust the ports of Sodium/Lithium

**Comment by Abalieno** [comment]
Weird, they are now used in Better Minecraft and Crucial 2 by Vazkii.

If it's about the time required to test if they are really compatible, I understand.
