### ISSUE TITLE
Tinkers construct questline issue

### ISSUE THREAD

**Issue by Xemicha** [EnigmaticaModpacks/Enigmatica6#3883]
### Modpack Version

0.5.21

### Describe your issue.

When trying to complete the tinker's construct questline you are instructed to craft a tinkers anvil. No matter how many different types of tinkers anvils I make none of them fulfill the quest. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm guessing the quest is looking for one very specific anvil, we'll get that fixed 😀

**Comment by MuteTiefling** [comment]
Couldn't replicate in dev.

**Comment by DarkAngel22579** [comment]
Seems to only accept the scorched variant and not the seared one

**Comment by Xemicha** [comment]
Awesome thanks guys
