### ISSUE TITLE
Industrial Foregoing Stasis Chamber using infinite Energy

### ISSUE THREAD

**Issue by Laciacrus** [EnigmaticaModpacks/Enigmatica6#3890]
### Modpack Version

0.5.21

### Describe your issue.

The Instruial Foregoing Stasis Chamber using infinite Energy when any Cable or other Means to insert Energy is connected if you dont limit it. 
We are using it to produce Ether Gas with the Wither if that helps.
![image_2021-12-12_172432](https://user-images.githubusercontent.com/20803484/145720552-a1a9a356-e964-41ab-aba6-a6bac6e26022.png)
![image_2021-12-12_172719](https://user-images.githubusercontent.com/20803484/145720648-5e68a138-e696-41de-8979-9cd982b2efb7.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by 616dustin** [comment]
Having the same issue, worked fine in 0.5.20 issue arose after updating to 0.5.21

Also effected the mob crusher until i broke it and placed again.

Mob Duplicator has same issue but did not fix after being replaced.
 seems that the max energy capacity is ignored and it will fill indefinitely. 
 
Relevant config settings appear to be the same on both pack versions
		
also hosting on a Server.

**Comment by YashTFEM** [comment]
Are you using flux networks? If yes, then set a limit on the flux point

**Comment by YashTFEM** [comment]
Temporary solution

**Comment by 616dustin** [comment]
Appears to be same as issue as #3852. replacing the expert mode configs with normal mode resolved the issue.
