### ISSUE TITLE
Pretty Pipes fails to accurately calculate how many of an item it can craft when a recipe outputs multiple of an item

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3892]
### Modpack Version

 Enigmatica 6 0.5.21+ (commit  047b59fd3c609346212aae3093e213474efbc78b dev branch, expert mode)

### Describe your issue.

Pretty Pipes appears to fail to properly calculate how many of an item it can craft when a recipe outputs multiple of an item.
This results in Pretty Pipes believing it can craft more items than it actually can (often leaving stuck crafts on the terminal or junk leftovers in the crafting module inventory)

Small pretty pipes system to replicate this issue:
![image](https://user-images.githubusercontent.com/48930896/145733286-c1bf479b-a806-45d3-b6f9-f0e08268a09d.png)

When the crafting card is set to (for the sake of an example) 1 andesite -> 1 cobble, and there's 20 andesite in the system.
![image](https://user-images.githubusercontent.com/48930896/145733341-cfc4b1c9-c2b9-4461-ae7f-812c4b5955f1.png)
Ask for the highest amount of cobble you can. It knows to only ask for 20 cobblestone, as expected. 

When the crafting card is set to 1 andesite -> 2 cobble (still with 20 andesite in the system)
![image](https://user-images.githubusercontent.com/48930896/145733372-33a84d09-6cca-461a-a819-35e0d7e723dc.png)
Ask for the highest amount of cobble you can.
![image](https://user-images.githubusercontent.com/48930896/145733449-472474cb-6a5b-471a-9fdd-951a3e5e7a62.png)
The pretty pipes system **promises to send back 80 cobblestone, rather than the expected 40** (since there's 20 andesite in the system and every andesite can be turned into two cobble, according to the crafting card)

Another example would be setting the recipe to 1 andesite -> 5 cobble, with 20 andesite in the system. It promises 384 (max amount) rather than the expected 100.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Iris-xii** [comment]
As I have found time to investigate it myself and wasn't particularly hard to replicate and track down, I have relayed it to the Pretty Pipes github.
