### ISSUE TITLE
Industrial Foregoing ore laser base generates certus quartz chunks

### ISSUE THREAD

**Issue by tdphillips** [EnigmaticaModpacks/Enigmatica6#3893]
### Modpack Version

0.5.21

### Describe your issue.

Using a gray lens and targeting Y 5, the drill generates certus quartz chunks.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Oops! Thanks for the report, nice catch :D

**Comment by Skar78** [comment]
Same goes for IF Laser Drill.
