### ISSUE TITLE
Diamonds & Emeralds can be duped by using a multi servo press with rod mold and then smelting the resulting rods in a Tinkers' smeltry.

### ISSUE THREAD

**Issue by LaNeige725** [EnigmaticaModpacks/Enigmatica6#3896]
### Modpack Version

0.5.21

### Describe your issue.

If a multi servo press from Thermal Series/metal press from Immersive Engineering is used to make diamond/ emerald rods with the rod mold, and the resulting 2 rods get put in a smeltry, it will result in 2 gems, instead of the input of 1, therefore 1 diamond/ emerald becomes 2.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get the amount it smelts into reduced :)
