### ISSUE TITLE
Add tag for shields

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#3904]
### Describe your suggestion

Please add tags for shields. All other tools and armor have tags, but shields can only be filtered on per-item basis

### Why would you like this added/changed?

I was making sorting system for my mobfarm, and noticed that shields are missing shared tag, unlike all other tools/weapons/armor

**Comment by MuteTiefling** [comment]
Good call. Will work on that tonight.
