### ISSUE TITLE
Item duplication using Sophisticated Backpacks Stonecutter upgrade

### ISSUE THREAD

**Issue by incomingnerd** [EnigmaticaModpacks/Enigmatica6#3914]
### Modpack Version

0.5.21

### Describe your issue.

Any block that can be processed in a stonecutter can be duplicated using a Sophisticated Backpack.

You will need:
1. A Sophisticated Backpack (any tier, this example uses the basic one)
2. A Stonecutter upgrade
3. Any item with a stonecutter recipe (this example uses one stack of Diamond Chunks)

This bug seems like a GUI/inventory desync, so the steps to reproduce are specific. Important steps required to trigger the bug appear in **bold**.

To reproduce:
1. Open the backpack and insert the upgrade
2. Expand the stonecutter upgrade tab
3. Insert the stack of diamond chunks into the stonecutter
4. Select any Diamond Ore block as the target (I used the Atum 2 Limestone variant, first in the list)
5. **Shift-click the result out of the stonecutter upgrade**
6. **Collapse the stonecutter upgrade tab**
7. **Escape out of the backpack UI**
8. Save and quit back to the Minecraft main menu
9. Re-open the world
10. Open the backpack
11. Expand the stonecutter tab and retrieve your duped items!

Tested in a fresh creative world. I have only tested this in single player. I don't know if the bug is confined to SP or if there's a way to trigger it in multiplayer too. Additionally the bug doesn't seem to be time sensitive. As long as steps 5-7 are performed in order the backpack will reward you with free items on the next reload of the world. I have found myself with confusing bonus limestone on several occasions as a result.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, very well made 👍 
Would you mind testing if this also happens in survival mode?

**Comment by incomingnerd** [comment]
It does. I found the bug in my survival play then tested it in creative to check it wasn't some weird quirk caused by anything else I had on my character.

**Comment by NillerMedDild** [comment]
Alright thanks 👍 
@P3pp3rF1y are you aware of this dupe bug? :)

**Comment by P3pp3rF1y** [comment]
No I wasn't aware of this, the upgrade contents don't appear to save on this shift click so I will fix for the next release

**Comment by NillerMedDild** [comment]
Thank you ❤️

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release of SBP on curseforge
