### ISSUE TITLE
[Expert] Crash when viewing Refined Obsidian in Blast Chiller recipe in JEI

### ISSUE THREAD

**Issue by Jyrath** [EnigmaticaModpacks/Enigmatica6#3916]
### Modpack Version

develop 495d4af

### Describe your issue.

When looking up the recipes for Mekanism's Refined Obsidian, the game crashes when clicking on the Thermal Blast Chiller tab in JEI.

### Crash Report

https://gist.github.com/Jyrath/13a09f201f522996366357a1605f156f

### Have you modified the modpack?

Yes

### User Modifications

Because the latest manifest downloads cofh_core-1.16.5-1.4.0.6.jar, I've updated the thermal mods to 1.4.1
thermal_innovation-1.16.5-1.4.1.3.jar
thermal_foundation-1.16.5-1.4.1.7.jar
thermal_expansion-1.16.5-1.4.1.3.jar
thermal_locomotion-1.16.5-1.4.1.2.jar

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by gruff8** [comment]
A small note to this, despite it aready being mentioned.
Thermal needs to be updated in the dev branch as it currently crashes on load.
Solution is to either downgrade cofh_core to version betwen 1.3 and 1.4 or upgrade thermal mods as mentioned has been done above.
Let me know if I should make a separate bug report.

**Comment by NillerMedDild** [comment]
I'll do that ASAP ty :) no need for a separate bug report

**Comment by NillerMedDild** [comment]
Fixed and pushed to develop branch 😀
