### ISSUE TITLE
[Expert] Machine Frame Parts are missing artwork

### ISSUE THREAD

**Issue by waleed2244** [EnigmaticaModpacks/Enigmatica6#3917]
### Modpack Version

v0.5.21 expert

### Describe your issue.

Bug
![Base Profile Screenshot 2021 12 16 - 22 03 58 28](https://user-images.githubusercontent.com/95529273/146477959-b2fbbffa-18ca-42a7-ab70-424b8aaa372d.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
Not so much a bug as it is Expert being unfinished. Need to get that dealt with...
