### ISSUE TITLE
Armor stands don't get placed

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3919]
### Modpack Version

E6E 17/dec

### Describe your issue.

I try to place an armor stand, the item count goes down, but nothing gets placed. checking an inventory fixes the desync of the item count (i get the item back). I tried placing in my base and out of any claimed chunks, both failed. There are a few errors in the log mentioning curiousarmorstands (errors at the end of file)

### Latest Log

https://gist.github.com/Rodg88/12c6e47a25510e668b357a83b03e8d7d

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by HopeNotDespair** [comment]
I'm pretty sure that's called lag. Happens a lot when my game is lagging. And no, lag does not mean that yoour screen stutters. There's block lag which is what you're facing

**Comment by HopeNotDespair** [comment]
Allocate more ram, and the problem is solved

**Comment by Darkere** [comment]
Log shows that its erroring on the server when initializing the armorstand curio slots. Curios got some major changes recently so not that suprising the armorstand mod having problems.

**Comment by Darkere** [comment]
@ochotonida

**Comment by ochotonida** [comment]
I've uploaded an update for Curious Armor Stands that fixes the issue. (I see it's already on the dev branch)
