### ISSUE TITLE
[Expert] Recipe ingredients aren't consumed when crafting Sentient Harm glyph through occultism.

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3921]
### Modpack Version

Enigmatica 6 0.5.21+ (commit  6e12680b1b3283ed57a4839b8588bfcbce42f620 dev branch, expert mode)

### Describe your issue.

Recipe ingredients aren't consumed when crafting Sentient Harm glyph through occultism.
![unknown](https://user-images.githubusercontent.com/48930896/146564164-6d45ccbd-f5c3-4cea-9f77-bdc03075fef3.png)

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
occultism-1.16.5-1.23.5 has released and seems to be fixed. Didn't make it into the last round of mod updates though. 

@NillerMedDild Boo mentioned something about the version number scheme changing and messing up some update scripts for other packs. Might be worth a look though when you get a chance.

**Comment by NillerMedDild** [comment]
Ah yes, I see I missed a bunch. I'll get that fixed.
