### ISSUE TITLE
Decrease Atum Patrol Spawn Rate

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3929]
### Describe your suggestion

It would be nice if atum:nomad atum:sergeant atum:barbarian and atum:brigand were added to the mega torch blocking list in config/torchmaster.toml

I'd also suggest considering lowering their spawn rates in general to 1500 or 2000, instead of 1000, in the atum config

### Why would you like this added/changed?

Trying to set up a base in Atum is a pain (needed in expert), you can't stop the patrols with ether mega torches or dread lamps. Even trying to explore on foot is also a grind, they constantly spawn around you. It might also make animals more common?

**Comment by Rodg88** [comment]
Though testing it, I'm not even sure the modified config stops them...

**Comment by NillerMedDild** [comment]
I agree, I'll decrease the spawnrate :) They don't spawn like normal mobs, Mega Torch and such don't help unfortunately. Perhaps we can request compat between Torchmaster and Atum to remedy this.

**Comment by NillerMedDild** [comment]
Yeah it doesn't work. The decreased spawn rate helps a ton though.

**Comment by NillerMedDild** [comment]
https://github.com/Xalcon/TorchMaster/issues/173
https://github.com/TeamMetallurgy/Atum2/issues/377

**Comment by NillerMedDild** [comment]
I've suggested that Torchmaster and/or Atum add Mega Torch support against patrols, closing this as part of 0.5.23 :)
