### ISSUE TITLE
[Expert] Quest Dependency Change - Gates - Refined Storage

### ISSUE THREAD

**Issue by gruff8** [EnigmaticaModpacks/Enigmatica6#3935]
### Describe your suggestion

Either remove dependency for Occultism, change the dependency to Eidolon, or build in a real in-game dependency.
Currently it is possible to craft a refined storage controller with no need for occultism.
Pewter from Eidolon is needed in the machine casing.
Unless I am missing something...

This is also the case for Blood Magic in the same chapter.

### Why would you like this added/changed?

Allows you to progress with quest along side in-game progression.

**Comment by NillerMedDild** [comment]
We'll look into it ty 👍

**Comment by MuteTiefling** [comment]
Occultism is required for RS disks, just not the primary automation portions.

**Comment by Darkere** [comment]
You need occultism the first time for the dimensional matrix... That might be a bit late.

**Comment by telemenar** [comment]
The gates quests in general are... Less linear than they were in e2e, as the mods are more deeply intertwined. I'm this is pretty well represented in the Tech Tier quest lines or in the Magic Tier Quest lines but means that the gates are less straight forward.

**Comment by gruff8** [comment]
I guess that since there are a lot of developments going on with the quest line we should close this and I can maybe come with more constructive suggestions for the short term. Is there a place where the current plans and ideas are logged? Just thought it might be good for me to read something like that before coming with my own suggestions (I have a few...).

**Comment by NillerMedDild** [comment]
> I guess that since there are a lot of developments going on with the quest line we should close this and I can maybe come with more constructive suggestions for the short term. Is there a place where the current plans and ideas are logged? Just thought it might be good for me to read something like that before coming with my own suggestions (I have a few...).

Not.. really 😄
