### ISSUE TITLE
Shrink bottles voided when picking up a mob while you have a full inv

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3940]
### Modpack Version

Dev expert 21/dec

### Describe your issue.

While having a full inventory, picking up a shrunken mob in a bottle (from a stack of bottles, so it doesn't make space in the inv) will just void the item of the bottled mob. Nothing I could see in the log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it 🙂
