### ISSUE TITLE
'unpacking' recipe for valhelsia bone block

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3946]
### Describe your suggestion

A way to unpack the valhelsia bone block would be good, to bring it in line with most other storage blocks. ATM you can get bones from it, but needs placing and breaking to get the full bones out.
![image](https://user-images.githubusercontent.com/2611674/147354316-1bfe944e-e608-43b7-8b13-09fc90fde776.png)
maybe replacing it's default bone pile recipe, and making sure compacting drawers make bones instead of piles too.
![image](https://user-images.githubusercontent.com/2611674/147354457-04ec7ba0-1880-417f-9db0-662cf1ab3a00.png)
![image](https://user-images.githubusercontent.com/2611674/147354547-e05947e3-5440-4831-96d7-36daca566e2f.png)

### Why would you like this added/changed?

a proper bone storage block would be nice, it's currently so close to being a useful one in-line with other storage blocks

**Comment by NillerMedDild** [comment]
Good idea👍
