### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by Damalas75** [EnigmaticaModpacks/Enigmatica6#3950]
### Describe your suggestion

Chisel and Iron knife recipe conflict suggestion Polymorph mod

### Why would you like this added/changed?

It solves the issue of recipe conflicts by adding a slide bar to select which item to craft making both recipes accessible

**Comment by MuteTiefling** [comment]
We already have polymorph ;D it's just a little broken in the current release.

Still, this should be a simple conflict to resolve.

**Comment by Ridanisaurus** [comment]
Duplicate of #3948
