### ISSUE TITLE
NA Canopy Diminisher not recognising modded 'big' trees

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3952]
### Modpack Version

Dev expert 26/dec

### Describe your issue.

In this pack there are a few types of large oak trees added by other mods (possibly terraforged and/or BYG), which the Canopy Diminisher doesn't recognize as big.
Some examples:
![image](https://user-images.githubusercontent.com/2611674/147404750-c32eca97-21d5-46b2-912e-c55a72b151c2.png)
![image](https://user-images.githubusercontent.com/2611674/147404769-8e868bea-c30d-4001-910b-523659084d9c.png)

And a farm with the Canopy Diminisher in the middle:
![image](https://user-images.githubusercontent.com/2611674/147404800-1898e6b4-8ef7-43bf-a754-a1e73ecb8859.png)

Not sure how the ratios of small/large trees changing would affect aura generation, but the modded trees seem fairly common, which might mean a big boost in aura gen if the diminisher starts catching them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I lazily relayed 👍

**Comment by NillerMedDild** [comment]
Ellpeck was not willing to work on fixing this sadly, as it would require adding compat for every mod that adds large oak trees in some form.
