### ISSUE TITLE
Crash on load E6 0.5.21

### ISSUE THREAD

**Issue by Swagnerb** [EnigmaticaModpacks/Enigmatica6#3954]
### Modpack Version

v0.5.21

### Describe your issue.

Crashing on launch. Sometimes I can get through to the Main Menu, and then crash again when launching a single player world

### Crash Report

https://paste.ee/p/5bUsV

### Latest Log

https://gist.github.com/Swagnerb/153839f1a62ad35263289d2c187e8f77

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.

Looks like java is crashing because of an access violation, please provide the java crash log located in your instance in the path `minecraft/hs_err_pid30380.log`

**Comment by Swagnerb** [comment]
Went with a fresh install again. Will post both logs when i try again later tonight

**Comment by Swagnerb** [comment]
[hs_err_pid9692.log](https://github.com/NillerMedDild/Enigmatica6/files/7778167/hs_err_pid9692.log)

**Comment by Swagnerb** [comment]
[hs_err_pid14904.log](https://github.com/NillerMedDild/Enigmatica6/files/7778216/hs_err_pid14904.log)

I was able to replicate it and grab the error. Still looks like that exception I was seeing earlier. Not sure what's going on.

Sometime it wont even let me load a world save - other times it lets me play for a few minutes...

tysm for the help!

**Comment by NillerMedDild** [comment]
What kind of drive is your A drive?

**Comment by Darkere** [comment]
Most likely caused by something being incompatible with java 17. 1.16.5 mods are build with java 8.

**Comment by NillerMedDild** [comment]
The first crash is with Java 8, albeit it's running from Program files 86

**Comment by Swagnerb** [comment]
A drive is a 2TB NVMe drive.

**Comment by NillerMedDild** [comment]
Is it an external drive? If possible switching to the C drive might fix this.

**Comment by Swagnerb** [comment]
It's not, it's a M.2 NVMe

I suppose I might have enough space to run my modded instances in my C drive.. I can give that a shot.

**Comment by NillerMedDild** [comment]
Got any news on this issue? :)
