### ISSUE TITLE
Avocado leaves not consumed by Botania munchdew

### ISSUE THREAD

**Issue by AndyGHG** [EnigmaticaModpacks/Enigmatica6#3956]
### Modpack Version

0.5.21

### Describe your issue.

Avocado leaves from Sushi Go Crafting are not consumed by the Botania munchdew.  Checking tags in JEI, it appears that the avocado leaves are missing numerous tags that exist on other leave blocks.  Don't know for sure if this is the cause, but one of the things I noticed that differentiate avocado leaves from other leaf blocks.

### Have you modified the modpack?

No

### User Modifications

None

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This was supposed to be fixed in 0.5.21 actually, could you please supply a screenshot of the tags you see on the leaves? :)

**Comment by AndyGHG** [comment]
Sure thing!  Here are the tags on the avocado leaves:
![avocado_leaves](https://user-images.githubusercontent.com/91009871/147664682-6924dcd4-e2d6-49b2-966d-94ef731bbb4a.png)

Here are the tags on oak (for example).  Most other leaf blocks have these:
![oak_leaves](https://user-images.githubusercontent.com/91009871/147664722-8c141d57-cf74-4d4a-8e08-03df902db09f.png)

**Comment by AndyGHG** [comment]
Did a little more testing on this... the same problem occurs regardless of whether or not they are placed via a block placer or dropped on the ground from player inventory.  Not sure if this is helpful, but I do appreciate your efforts!

**Comment by NillerMedDild** [comment]
Ahh I forgot to give it the leaves block tag 😅 we'll get that fixed, thanks for your help!
