### ISSUE TITLE
Nether wart block in compacting drawer resolves to 9 nether wart (duplication)

### ISSUE THREAD

**Issue by cosmosgenius** [EnigmaticaModpacks/Enigmatica6#3959]
### Modpack Version

0.5.21

### Describe your issue.

Nether Wart Blocks in compacting drawer gives 9 Nether Wart instead of 4 causing duplication of Nether Wart
![2021-12-29_12 10 56](https://user-images.githubusercontent.com/1056039/147634547-173fb28d-72d0-4573-a726-e92284a3fa8b.png)

I don't think nether wart block should be supported in compacting drawer since Nether Wart Sack is there for that.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Rodg88** [comment]
If you want a work around in-game, put a quark nether wart sack in the top of the compacting drawer, then you'll get the correct 1-9 ratio both ways.
