### ISSUE TITLE
Missing localisation string for blood school in Ars Nouveau

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#3961]
### Modpack Version

0.5.21

### Describe your issue.

Missing localisation string for blood school
![unknown](https://user-images.githubusercontent.com/15922601/147714678-e9aa14c2-0eb7-4841-b900-34b2179e18c6.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
