### ISSUE TITLE
Ladder Unification

### ISSUE THREAD

**Issue by DJSkyRoad** [EnigmaticaModpacks/Enigmatica6#3962]
### Describe your suggestion

Currently the recipes for ladders are unified, so crafting the spruce ladders from quark outputs oak ladders. It would be nice to have matching woodstyles.

### Why would you like this added/changed?

Diffrent Wood Styles are nice

**Comment by Rodg88** [comment]
It seems like polymorph isn't working for them for some reason. for now you can use the "saw" block from Environmental to get them
