### ISSUE TITLE
[Expert] Energy Cell basic consumes item

### ISSUE THREAD

**Issue by ntn6371** [EnigmaticaModpacks/Enigmatica6#3963]
### Modpack Version

5.21

### Describe your issue.

Modpack Version
0.5.21

Describe your issue.
I was playing in expert and was trying to charge a copy gadget I just made and it charged for about 2 seconds then it consumed it. I tried other energy items and it just disappears.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by ntn6371** [comment]
Looks like thermal energetic infuser also consumes.

**Comment by MuteTiefling** [comment]
You're playing a month old version of the development pack.

Please attempt to recreate this in the latest dev branch. There are instructions for testing on our Github landing page.

**Comment by ntn6371** [comment]
Fired up the dev branch locally and this is no longer happening. 

Also kudos the quest line looks much better then in the current release.
