### ISSUE TITLE
Macaw's Bridges integration mods

### ISSUE THREAD

**Issue by djmattyg007** [EnigmaticaModpacks/Enigmatica6#3967]
### URL

https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-atmospheric

### Why would you like the mod added?

It allows creation of bridges with more types of wood already in the pack. There are mods for Atmospheric, Environmental and BYG:

https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-atmospheric
https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-environmental
https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go

**Comment by NillerMedDild** [comment]
I'd love more wood options when it comes to Macaw's mods, but adding all these extra compat mods will result in a massive amount of extra blocks, especially if all the Macaw building mods have them.

I don't think the performance "penalty" of adding this many blocks is worth it in this case, so your suggestion is sadly not accepted :(
