### ISSUE TITLE
Add Connected Glass variants to stonecutter list

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3968]
### Describe your suggestion

connectedglass:borderless/clear/scratched (plus panes and coloured) glass variants should probably be added to the stone cutter, since chipped glass is stonecuttable, and it's just a simple crafting recipe to swap between the types anyway.

It might also be worth putting tinker's clear glass in the stonecutter script. However it's not just a plain crafting recipe to get it, needing the smeltery, so not sure if you'd want to let people bypass that requirement. It is just cosmetic afaik so might not be an issue

### Why would you like this added/changed?

Only Chipped glass gets the stonecutter treatment currently

**Comment by NillerMedDild** [comment]
Good idea 👍 I don't think Clear Glass should be stonecuttable though, don't wanna let people bypass the smelter as you mentioned :)

**Comment by MuteTiefling** [comment]
Have this in progress. Of course...not all glass is properly tagged, so it's making this complicated.
