### ISSUE TITLE
Bigger Reactors

### ISSUE THREAD

**Issue by SoftGuardian** [EnigmaticaModpacks/Enigmatica6#3969]
### URL

https://www.curseforge.com/minecraft/mc-mods/biggerreactors

### Why would you like the mod added?

Generating power in this pack is a little hard as Powah is so complicated and way more expensive on resources so bigger reactors could be the power generation mod for this pack

**Comment by MuteTiefling** [comment]
#1955

**Comment by mcilhargey** [comment]
Actually discussed in #1956

**Comment by MuteTiefling** [comment]
that's what I get for responding in mobile :D
