### ISSUE TITLE
Astral Scorcery XP bar glow covering Powah info overlay

### ISSUE THREAD

**Issue by Rodg88** [EnigmaticaModpacks/Enigmatica6#3970]
### Modpack Version

Dev branch 1/1/22

### Describe your issue.

The Astral starlight glow on the XP bar covers up the display of Powah's info readouts when looking at certain blocks like the Energizing Orb or Rod
Before:
![image](https://user-images.githubusercontent.com/2611674/147879190-3870b6b2-5e0e-40c4-b1af-2ac33ec3bf40.png)
When holding an AS rod or mantle:
![image](https://user-images.githubusercontent.com/2611674/147879221-54261ae1-5e48-4fbf-81ae-a51aeacbf5a9.png)
The numerical readout is covered up.

Same with the rod:
![image](https://user-images.githubusercontent.com/2611674/147879227-6a59c0b8-2453-4168-8b86-dbd4998e7387.png)
![image](https://user-images.githubusercontent.com/2611674/147879234-cf9b09d8-3a82-46d7-9456-5f3c2a076729.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.
How annoying would you say this bug is for you? :)

**Comment by Rodg88** [comment]
I posted it on behalf of ijan_goetbeard on discord who found it, so can't speak for them, but maybe 3/10? lol
Motoko suggested posting it here to track, despite low chance of it getting fixed

**Comment by ijangoetbeard** [comment]
Hey thanks for the post on my behalf! This issue does not impact my gameplay, as I thought the smaller amount of information was normal. Discovered when pressing F2 for screenshot, suddenly more information than "normal" (for me) appeared for a short period of time, even while wearing the Mantle of Stars. 

I would say for me, bug annoyance level 2/10. Even though I grew accustomed to less information, I'm sure the full readout can be super useful to those who like to see all variables. I figured it was more of a "Huh. That's odd" situation, for myself. Thanks for considering it!

**Comment by NillerMedDild** [comment]
To be honest I think this bug isn't worth fixing, I have a feeling it would require a ton of work from one mod, or a fair deal of coordination between both mods to fix this. I'm gonna close this as unresolved, thanks for the report anyway :)
