### ISSUE TITLE
Alex's Mobs Mimicream + TCon Armor allows for item duplication

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3972]
### Modpack Version

Enigmatica 6 0.5.21+ (commit  5a9c80693c289a6e40e42f13b3d85893d8306f3d dev branch, expert mode)

### Describe your issue.

Mimicream allows for items with durability to be duplicated at the cost of their durability. Using a Tinker's Construct armor with the pockets modifier (which gives a piece of armor a small inventory) allows to duplicate just about any item using mimicream.

To replicate, just fill the inventory of a Pockets modifier TCon armor with the items you'd like to duplicate, then put the armor and 8 pieces of mimicream on the crafting table. The armor will be duplicated along with all its contents.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
I'm afraid it's got to go. It's ok as a rare means of duping items, but this becomes a dupe loop really quick (just ensure you're always duping enough mimicream each dupe to repeat again.
