### ISSUE TITLE
Add deepslate to cobbleworks cobblestone gen.

### ISSUE THREAD

**Issue by salviija** [EnigmaticaModpacks/Enigmatica6#3978]
### Describe your suggestion

I would like the newly added deepslate to be generatable via the cobblestone and/or stone generation for the stone and cobblestone variants respectively.

### Why would you like this added/changed?

I think it would be useful for generating and automating deepslate for larger and more extensive builds where building a quarry or mining it en masse wouldn't do the trick.

**Comment by NillerMedDild** [comment]
Huh, I thought this was a thing already tbh. 😳

**Comment by MuteTiefling** [comment]
Er, yeah it actually is showing in dev. I wonder what happened there.
