### ISSUE TITLE
my game keeps crashing

### ISSUE THREAD

**Issue by oreoozz** [EnigmaticaModpacks/Enigmatica6#3982]
### Modpack Version

0.5.20

### Describe your issue.

my game keeps crashing whenever i load it on curseforge.I asked some people from the curseforge community and they said its not my pc and theres a bug in the modpack. Hope u can fix it, thanks

### Crash Report

https://gist.github.com/oreoozz/2ddd4c154523961e213937856baf5d67

### Latest Log

https://gist.github.com/oreoozz/67194a980d0272aacfe8f858959924d5

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Darkere** [comment]
Please go to `powah/energy/generators/furnator.toml` and remove the invalid text at the bottom.

**Comment by oreoozz** [comment]
Hey,I'm new to mods and I couldn't find the file could u help me
