### ISSUE TITLE
Some molten materials from KubeJS can't be used to make ingots with tinker's ingot cast

### ISSUE THREAD

**Issue by shyloneguy** [EnigmaticaModpacks/Enigmatica6#3983]
### Modpack Version

0.5.21

### Describe your issue.

i tried to use the scorched lantern with molten terrasteel and the scorched lantern with the  molten elementium that you can get as a reward from tinker quests to make ingots, but when i poured the molten materials inside the tinker's smeltery i got the molten matrials from the KubeJS and I saw that in the JEI there is no recipe for the tinker ingot cast
![kubejs terrasteel](https://user-images.githubusercontent.com/97125047/148280144-7fee598a-c212-4431-833e-abf3539292ff.png)
![jei missing recipe](https://user-images.githubusercontent.com/97125047/148280153-c2f7382d-fecc-4ec9-bf8f-7d1f4e6f1967.png)
![kubejs elementium](https://user-images.githubusercontent.com/97125047/148280322-5e12424d-15b6-4a3a-abe7-d40ec338e54a.png)
![jei elementium missing recipe](https://user-images.githubusercontent.com/97125047/148280473-a456a0b1-dd50-41da-bef0-06d87aa5be18.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm 95% sure that this is fixed in dev 😄
