### ISSUE TITLE
Server crash with Immersive engineering multiblock structures

### ISSUE THREAD

**Issue by tmukh** [EnigmaticaModpacks/Enigmatica6#3987]
### Modpack Version

Enigmatica6_0.5.21

### Describe your issue.

Building a multiblock structure in singleplayer throws the error "Gamestage missing: heavy_machinery"
And doing this on a server results in a complete crash.

### Crash Report

https://gist.github.com/tmukh/962f4bde876c32ed2048e83846540548

### Latest Log

https://gist.github.com/tmukh/9660a78f6115bb1e8ab0a95908f559d1

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report. 

Got any idea whether this is still an issue @MuteTiefling ?

**Comment by MuteTiefling** [comment]
I've never actually tested this on a server, will have to test in dev.

It was working fine for me last night in single player though.

**Comment by tmukh** [comment]
In singleplayer only the Pumphack gives a gamestage error atm (others build
just fine), requiring a gamestage called "heavy_machinery" , and the
gamestages themselves did not unlock except starting_items, even though
quests were complete.
An update to the server thought, it seems like all multiblock structures
crash it now, not just the pumpjack

Am Do., 6. Jan. 2022 um 12:42 Uhr schrieb MuteTiefling <
***@***.***>:

**Comment by MuteTiefling** [comment]
@tmukh are you playtesting Expert on the 0.5.21 release? If so, you should be pulling from Github development branch. Your instance is a month's worth of development behind.

**Comment by tmukh** [comment]
> @tmukh are you playtesting Expert on the 0.5.21 release? If so, you should be pulling from Github development branch. Your instance is a month's worth of development behind.

This did it, the server doesnt crash anymore, and our quests caught up!
Thank you ❤️
