### ISSUE TITLE
Server doesn't start anymore

### ISSUE THREAD

**Issue by alexander-neumeier** [EnigmaticaModpacks/Enigmatica6#3994]
### Modpack Version

0.5.21

### Describe your issue.

Yesterday were config files messed up, because jei said, that I am playing expert mode, but i wasn't, I was playing normal mode. I couldn't craft many compressors from pneumaticcraft, because jei said, they were disabled. Then I modified a config file. After that it worked perfectly, but then I realized, that i'm having the hard recipes. Today I deleted the config files and reuploaded the Originel. but my server doesn't start anymore.

Sorry for my bad English, I come from Austria

### Crash Report

https://gist.github.com/alexander-neumeier/b257917023fe255d428c0331325dbdd3

### Latest Log

https://gist.github.com/alexander-neumeier/cfeb2aad8f464b56bfe791cd3020f677

### Have you modified the modpack?

Yes

### User Modifications

Mods added: Applied Energistics, Mystical Agrigultura and Agraditions, 
Mods updated: Mekanism and all mekanism addons that are in the pack
Forge updated to: 36.2.21(because Mekanism requires the latest forge version)

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Go to config/polymorph-integration.toml and turn off the RS integration.
