### ISSUE TITLE
[Occultism] - Summon Blacksmith Familiar quest bug

### ISSUE THREAD

**Issue by jynxdarkspell** [EnigmaticaModpacks/Enigmatica6#3997]
### Modpack Version

Enigmatica 6 - 0.5.21

### Describe your issue.

Quest does not complete when familiar is summoned.

Steps to reproduce:
Perform ritual to summon blacksmith familiar (I used stone for the stone requirement of the ritual),

Expected behavior:
Summon blacksmith familiar.  Receive notification that quest is complete.  Collect reward.

Behavior observed:
Summon blacksmith familiar.  No quest notification.  No rewards.

### Have you modified the modpack?

No

### User Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by fajcyk** [comment]
I was looking at this recently so I will share what I found out.
Advancement that is required by quest is occultism:occultism/familiar/blacksmith_upgrade which is
![obraz](https://user-images.githubusercontent.com/48088075/148595344-c0ab25f3-bb8c-4d60-8bcf-9196aae5671a.png)
When you let blacksmith upgrade a familiar and you get this advancement, quest gets completed like expected.
I don't see an advancement (hidden or visible) that would be granted when summoning blacksmith familiar, so solution for now would be updating quest description.

**Comment by MuteTiefling** [comment]
Relayed. Best fix will be to get an advancement for this guy just like all the others.

https://github.com/klikli-dev/occultism/issues/628

**Comment by HopeNotDespair** [comment]
Can't you just put the ingredients of summoning blacksmith familiar as the quest requirements?

**Comment by theboo** [comment]
If it isn't fixed in occultism soon, we can just datapack in the advancement we need... Using items from the recipe wouldn't work cuz expert and normal use the same quests for mod chapters
