### ISSUE TITLE
Enigmatica 6 Expert 8x Kiln brick dependency issue

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4002]
### Modpack Version

Dev

### Describe your issue.

The 8x Kiln brick quest has both smoldering Lapis Lazuli and Engineers Blueprints as dependencies for the quest when you need the Kiln to make the blueprints. I would also suggest adding the 8x Kiln brick quest as a dependency to the Engineers blueprint quest rather than just the Thermopneumatic Processing Plant.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Ah, dependency was backwards there, thanks :D
