### ISSUE TITLE
Tinkers Archery Mod

### ISSUE THREAD

**Issue by YashTFEM** [EnigmaticaModpacks/Enigmatica6#4008]
### URL

https://www.curseforge.com/minecraft/mc-mods/tinkers-archery

### Why would you like the mod added?

This mod adds the good old tinkers bow and arrow from 1.12. With some very exciting modifications!

**Comment by telemenar** [comment]
Given that bows are still in the roadmap for TC3 I wonder how much the add-on is warranted.

**Comment by YashTFEM** [comment]
Yes, but according the thhe dev, they won't be added in 1.16 and will go straight to 1.18

**Comment by NillerMedDild** [comment]
Sorry but no, we'll have to live without bows for the time being. Tinkers Archery looks too unstable, and I'd rather not discourage players who want to try out Tinkers bows from using 1.18
