### ISSUE TITLE
Ore generation defaulted to false

### ISSUE THREAD

**Issue by nickrobi** [EnigmaticaModpacks/Enigmatica6#4011]
### Modpack Version

0.5.21

### Describe your issue.

The default ore generation in the world is absolutely horrible. Overworld ore only spawns in basic stone. Nether and End have absolutely no ore generation whatsoever. 

Not sure if this intended, but there's not even any nether quartz in the nether? I eventually found out to go into emendatusenigmatica-common.toml and manually change every single ore spawn value to TRUE, and all the stratum configs to TRUE. This fix worked for my server world generation but apparently these defaults are the same for the singleplayer version of the mod. Please fix default ore generation for future updates.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
What world type did you use? This sounds like you've not chosen Terraforged. Other world types aren't really supported.

**Comment by nickrobi** [comment]
![image](https://user-images.githubusercontent.com/48817428/148623951-6e6bf8df-eecb-4de9-8164-acf247081e11.png)

It seems like default world type is Terraforged, unless this line is somehow improper.

All these values in the emendatusenigmatica config file were defaulted to false, as well as the "Ore gen in The Nether" lines.

![image](https://user-images.githubusercontent.com/48817428/148624032-640db157-a310-48fa-a95e-c640bf43ec55.png)

**Comment by nickrobi** [comment]
for more context, the .toml file I opened on my server had vastly different values from this file you guys have up 

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/config/emendatusenigmatica-common.toml#L85

**Comment by TemperedFool** [comment]
Looking at the config in the repo:

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/bdcca524fc9bc57d695d466ea6a2451f6dacc98e/config/emendatusenigmatica-common.toml#L1921

Seems like something is broken with your install - I'd recommend reloading your instance from scratch. I'd also come to the Discord for support of this type - we try to use the issue tracker for bugs and things requiring code changes.
