### ISSUE TITLE
Matrix3d crash on Pumpjack in version 0.5.22

### ISSUE THREAD

**Issue by tmukh** [EnigmaticaModpacks/Enigmatica6#4013]
### Modpack Version

0.5.22

### Describe your issue.

Right clicking with an Engineer's hammer on a mutliblock structure causes the server to crash

### Crash Report

https://gist.github.com/tmukh/e44ea0eb5ffc49bafeacf8f657c096c2

### Latest Log

https://gist.github.com/tmukh/a3edd946e801135d3020764a8ac82282

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Looks like your Java is out of date. Can you update it and see if you're still able to reproduce this?

**Comment by tmukh** [comment]
I have the latest Java 8 version on my pc, do you mean the server?

Am Sa., 8. Jan. 2022 um 21:26 Uhr schrieb MuteTiefling <
***@***.***>:

**Comment by tmukh** [comment]
Update: I tried running it locally with Java 8u311

Crash-report: https://gist.github.com/tmukh/a6f894b29211fe6b89fcaa9a3e692486

**Comment by NillerMedDild** [comment]
Looks like a KubeJS issue to me, trying to access a class that doesn't exist - Perhaps it's in the 1.18 codebase?

**Comment by tmukh** [comment]
> Looks like a KubeJS issue to me, trying to access a class that doesn't exist - Perhaps it's in the 1.18 codebase?

That's odd,  what do you mean exactly?
Any idea what could be causing it? It's on a fresh clone from the the repo, and I don't see any issues reported on it.
About KubeJS, I get 1 fatal error and 74 warnings when launching the server as well, if that helps.

**Comment by Darkere** [comment]
Kinda a kubejs issue. Our code is accessing the IE code to determine when multiblocks are formed. 

It is crashing because a clientside only method is being looked at. 

The problem is I can't reproduce this in dev and haven't seen it before either. Will try again with 5.22 I guess.

**Comment by tmukh** [comment]
> Kinda a kubejs issue. Our code is accessing the IE code to determine when multiblocks are formed.
> 
> It is crashing because a clientside only method is being looked at.
> 
> The problem is I can't reproduce this in dev and haven't seen it before either. Will try again with 5.22 I guess.

Weird, the reason we migrated over to 5.22 was because it was happening in 5.21 in the first place.

**Comment by tmukh** [comment]
Update  just becaue I saw the 0.5.23 update which mentioned a fix in the changelogs:

Steps taken:

Fresh install on MultiMC with Forge version  36.2.22 (not latest since the InstanceSyn.bat from the server downloads 36.2.22)
Fresh install of the server 

Load into new world, take a projector, pick the pumpjack, and Shift + Right click  to creative build it.

Result:

Crash with following crash logs:

https://gist.github.com/tmukh/56e4b4e1b6d65410608c67d466e139db

Notes:

Works in singleplayer after obtaining the schematics for the machinery.
Works if the server is set to normal mode.

I hope this helps you.

**Comment by Darkere** [comment]
Can you post this file from your server? 
kubejs/startup_scripts/multiblock_gamestages.js

**Comment by tmukh** [comment]
Of course.

https://gist.github.com/tmukh/885b6327cabbd04b52d3357e17499488

**Comment by Rixhephtos** [comment]
Hello, we had a somewhat similar issue on our server- creating the pumpjack is fine, but if it is unloaded after creation, and then reloaded, the server will crash.

The server will crash whenever someone loads the chunk the pumpjack is located in. Happened around 3 times now.

https://gist.github.com/Rixhephtos/48195fc224585f3d48e08f1d7e09957e

**Comment by NillerMedDild** [comment]
Thanks for the added info Rixhephtos - That seems like this issue: https://github.com/TwistedGate/ImmersivePetroleum/issues/68
Which modpack version are you on?

**Comment by NillerMedDild** [comment]
I was able to reproduce the crash on our dev server by spamming the hammer on random blocks of a non-assembled Pumpjack.

**Comment by Rixhephtos** [comment]
Hello, sorry for the delay, we're on v0.5.21. That does seem to be exactly the issue we're having.

**Comment by NillerMedDild** [comment]
Updating to 0.5.23 ought to fix that then :)
We're working on fixing the reported issue still.

**Comment by tmukh** [comment]
Update 0.5.23 fixed this in normal mode for me, I don't know if it's a specific issue having to do with our files, since I don't see this reported often, but expert mode -> building pumpjacks or excavators causes these (in the curseforge release 0.5.23 version, at least)

**Comment by Darkere** [comment]
The code doesn't run in Normal mode. 

Max has wrapped the event in kjs immersive, so we just need to update that and move our code over.

**Comment by Rixhephtos** [comment]
> Updating to 0.5.23 ought to fix that then :) We're working on fixing the reported issue still.

Thank you, sorry for butting in on an unrelated issue! :)
