### ISSUE TITLE
Ars Arsenal

### ISSUE THREAD

**Issue by baileyholl** [EnigmaticaModpacks/Enigmatica6#4016]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-arsenal

### Why would you like the mod added?

Adds a new selection of Ars Nouveau armors and tools for specialized casting and elemental discounts

**Comment by NillerMedDild** [comment]
I am not fond of the tool item textures, and the armor is a bit plain, other than that looks good 👍
