### ISSUE TITLE
Cannot unpack Assembly Packages in Expert mode

### ISSUE THREAD

**Issue by 1mphuls3** [EnigmaticaModpacks/Enigmatica6#4022]
### Modpack Version

0.5.22

### Describe your issue.

I can only unpack assembly packages in normal mode, and I can only craft them in expert mode. So I cannot get into mekansim because I cant get basic control circuits in expert mode.

### Have you modified the modpack?

Yes

### User Modifications

Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Pneumaticcraft recipes usually take 2 reloads to change. Sounds like you're changin back and forth from normal to expert... so you'd load expert, this forces a reload but the pnc recipes won't be quite there yet (they'll still be normal recipes). A second reload would finish loading them. But your second reload comes in the form of a swap back and now you're inverted.

Restart your game and keep it in whatever game mode you're playing in. There's no reason to be flipping back and forth constantly.
