### ISSUE TITLE
RFTools Monitor Crash

### ISSUE THREAD

**Issue by ijangoetbeard** [EnigmaticaModpacks/Enigmatica6#4028]
### Modpack Version

Enigmatica6-0.5.21

### Describe your issue.

Client and server crash when attempting to use the auto-sort  (default button mouse3) when in the RFTools Monitor GUI. Replicated issue after server rollback. 

server latest:
https://gist.github.com/ijangoetbeard/7e7825a690bc3e2098fc2e09c2a4e41b
server crash:
https://gist.github.com/ijangoetbeard/baf6c021467422e82aee725841e66810

client latest:
https://gist.github.com/ijangoetbeard/4be588c381f514528486866a480d2e3f
client crash:
https://gist.github.com/ijangoetbeard/fac6249fa1734bc6b5c1b8fe0962097f

Have not tested in single player.

### Crash Report

https://gist.github.com/ijangoetbeard/baf6c021467422e82aee725841e66810

### Latest Log

https://gist.github.com/ijangoetbeard/7e7825a690bc3e2098fc2e09c2a4e41b

### Have you modified the modpack?

No

### User Modifications

None

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
