### ISSUE TITLE
Prismarine Brick and masonry:prismarine are inconsistently smeltable into prismarine

### ISSUE THREAD

**Issue by FieldArmada** [EnigmaticaModpacks/Enigmatica6#4031]
### Describe your suggestion

Prismarine brick doesn't smelt into prismarine, but you can stonecutter it into literally any other form and it does.

### Why would you like this added/changed?

Consistency

**Comment by NillerMedDild** [comment]
Actually it seems like Prismarine and Prismarine Bricks are not considered equal, Chisel Prismarine Bricks do not smelt either.
