### ISSUE TITLE
[0.5.22] Immersive Engineering Copper Ore

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica6#4033]
### Modpack Version

0.5.22

### Describe your issue.

Immersive Engineering's copper ore is generating and giving copper ore blocks instead of Copper Chunks.

Fresh install set to Expert mode.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed by MuteTiefling in dev :D
