### ISSUE TITLE
Atum sarcophagus replaced with lootr chest, pharaoh doesn't spawn

### ISSUE THREAD

**Issue by FieldArmada** [EnigmaticaModpacks/Enigmatica6#4036]
### Modpack Version

develop@ [4ec524e8bf0eebefa53b6da0441c6f44cd31b057](https://github.com/EnigmaticaModpacks/Enigmatica6/commit/4ec524e8bf0eebefa53b6da0441c6f44cd31b057)

### Describe your issue.

Atum sarcophagus replaced with lootr chest, pharaoh doesn't spawn

![Capture2](https://user-images.githubusercontent.com/75914799/148884372-3cf71709-f255-43c7-a9bf-18ffdef14723.PNG)
![unknown](https://user-images.githubusercontent.com/75914799/148884383-4ba8b025-2c10-49fb-84d8-77416a9255a6.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
reported here:
https://github.com/noobanidus/Lootr/issues/74

temporarily fixed by blacklisting the loot table in lootr config in pr #4037

**Comment by theboo** [comment]
closing as the version of lootr that causes this issue is not in e6 0.5.22, issue was caught in dev
