### ISSUE TITLE
java.awt.HeadlessException on MineOS

### ISSUE THREAD

**Issue by Pavocracy** [EnigmaticaModpacks/Enigmatica6#4039]
### Modpack Version

0.5.21

### Describe your issue.

I am trying to install this modpack on my MineOS server. It currently has other modpacks running well.

The way i do this is use the webui to install a "vanilla" server, and then `scp` the modpack zip to the server directory and follow normal installation instructions for the modpack.

In this case, once i had the Enigmatica6Server-0.5.21-log4j-fix.zip on the server, i used `unzip Enigmatica6Server-0.5.21-log4j-fix.zip` and then run `sh start-server.sh`. It downloaded all of the mods correctly, but it got stuck with the forge jar. So i manually got it with `wget https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-installer.jar`, but the start-server.sh script still did not work. It has the below error:
![image](https://user-images.githubusercontent.com/9214102/148946004-54bba45b-4b73-44f9-a857-33d9516423d6.png)

So instead i tried to also run the forge jar with `java -jar forge-1.16.5-36.2.20-installer.jar` but i get the awt error as below:
![image](https://user-images.githubusercontent.com/9214102/148946706-a5a873f8-94ce-413a-ad2c-d0baa174bc85.png)

I have tried commenting out `assistive_technologies=org.GNOME.Accessibility.AtkWrapper` line in /etc/java-8-openjdk/accessibility.properties as per stackoverflow threads but this does not work.

Is there a way to install this modpack on a headless OS? or is a display output needed to run this jar?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I... have no idea ^^'

**Comment by Pavocracy** [comment]
I can run this fine on my windows machine, and it does indeed pop up the GUI that makes me select if im installing a client or a server. 

Is there a way to pass a command line argument to the forge installer to select the server option and bypass the gui popping up?

Surely i am not the only one that has tried to install this server on an OS that does not have a display output?

**Comment by NillerMedDild** [comment]
Well there's the `-nogui` toggle, but that doesn't stop the command prompt from opening.

**Comment by Darkere** [comment]
for the installer I believe its -install .

We've got a few linux users in discord who are active there. Not anyone on here I'm afraid.

**Comment by Pavocracy** [comment]
> for the installer I believe its -installServer .
> 
> We've got a few linux users in discord who are active there. Not anyone on here I'm afraid.

This fixed my issue! Thank you!
