### ISSUE TITLE
Shapeless recipe for Source Berry Roll can't be crafted via Create mixer

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#4040]
### Modpack Version

269a02559f907eb207390aa92b414f5e915d90aa (expert)

### Describe your issue.

Unlike other shapeless recipes, recipe for Source Berry Roll can't be crafted via Create shapeless mixing

### Have you modified the modpack?

Yes

### User Modifications

Added https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
