### ISSUE TITLE
Create Chunkloading

### ISSUE THREAD

**Issue by Witted** [EnigmaticaModpacks/Enigmatica6#4041]
### URL

https://www.curseforge.com/minecraft/mc-mods/create-chunkloading

### Why would you like the mod added?

Create allows you to build all sorts of machines, a popular one is a train however currently there is no way to load that amount of chunks for a railway leading to issues when the minecarts travel into unloaded chunks

This mod adds a single block that will load the chunk around the train (or whatever machine its on) so you are able to have working railways or machines that travel (miners etc)

Think it would be a really nice addition and would make the railway I spent 2 days building actually usable lol

**Comment by juh9870** [comment]
Adding this mod would basically allow launching "mining drones" into an infinity mining jorney, creating another way of generating infinite resources, may be laggy if too many is loaded at once tho

**Comment by Witted** [comment]
Potentially but I guess its about using common sense like with any pack.

Redstone can be abused to make it laggy as well if thats the case 😄

**Comment by NillerMedDild** [comment]
Iirc this functionality was not added to Create itself because it caused too many issues. I think it's too risky to add unfortunately.
