### ISSUE TITLE
start-automated-server.bat doesn't support IPv6

### ISSUE THREAD

**Issue by algorythm** [EnigmaticaModpacks/Enigmatica6#4043]
### Modpack Version

d3638970

### Describe your issue.

Starting the server won't work on Windows if you have a public IPv6 address.

The script makes a `ping` to `minecraftforge.net` and tries to look for `TTL` in the response. Apparently, if the server returns an IPv6 address, the `TTL` is not included:

![image](https://user-images.githubusercontent.com/5315872/149198619-efcff989-8a0f-4d65-b7da-4c9012b380d6.png)

As I personally have a public IPv6 address, the server responds with IPv6 as well, causing the script to think, that I don't have internet.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report and fix, very nice of you :D 
I've decided to remove the check entirely, it's pretty redundant anyway.

**Comment by algorythm** [comment]
Cool. I reckon this will be relevant for your other mod packs as well. Also, if you ever plan to update the script with latest from https://github.com/AllTheMods/Server-Scripts/, you'll have the issue again, as the problems stems from that. I've submitted a PR there as well https://github.com/AllTheMods/Server-Scripts/pull/89.

**Comment by NillerMedDild** [comment]
I've refactored the script for 1.18 a while back, so that's already fixed 👍 But thanks!
