### ISSUE TITLE
Trade with Market crash

### ISSUE THREAD

**Issue by RyoNam** [EnigmaticaModpacks/Enigmatica6#4053]
### Modpack Version

Lastest

### Describe your issue.

The game Crash when i make a trade with Market trader ( Farming for Block head )

### Crash Report

https://gist.github.com/RyoNam/0776ce3ab21c3a31bd374e259986ac39

### Latest Log

https://gist.github.com/RyoNam/d7719de0a10d6dd8c97ec63f94e30091

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
Which version is "latest"?

**Comment by HopeNotDespair** [comment]
v0.5.23 I believe

**Comment by Darkere** [comment]
The question is not what is the latest pack version, the question is what version OP is actually on. I believe this bug is quite old.
