### ISSUE TITLE
Universal Grid

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4059]
### URL

https://www.curseforge.com/minecraft/mc-mods/universal-grid

### Why would you like the mod added?

This mod unifies the Refined storage addon wireless grids into a single unit which will eliminate the need to carry multiple grids.

**Comment by MuteTiefling** [comment]
Seems to have some major issues that prompted a full rewrite of the mod. That doesn't appear to be ready yet.

**Comment by starforcraft** [comment]
Sorry for all the major issues with this mod. The rewrite is already out and everything should be fine now
