### ISSUE TITLE
Culinary Construct

### ISSUE THREAD

**Issue by HopeNotDespair** [EnigmaticaModpacks/Enigmatica6#4062]
### URL

https://www.curseforge.com/minecraft/mc-mods/culinary-construct#:~:text=Culinary%20Construct%20is%20a%20mod,items%20you%20have%20lying%20around.&text=This%20mod%20adds%20one%20new,Sandwich%20and%20Bowl%20of%20Food!

### Why would you like the mod added?

This mod allows you to make custom sandwiches and bowl foods/stews out of the food you have. It allows for great customizability and is useful for making perfect easy food. The foods made, are affected by repetition of same ingredient, and are rewarded when using different ingredients. Currently the use for it as I see it, is early game easy food source since it can't be automated. It also takes on the buffs of the food it is made using, so people using rotten flesh, have a chance of getting food poisoning when eating the food. Right now, the foods we have are mainly from farmer's delight which has mostly meat foods which are a bit hard to automate, and regular  Minecraft food which doesn't offer much option. I'd really appreciate it if you could consider this mod.

**Comment by NillerMedDild** [comment]
I'll think about it, good sales pitch 😄

**Comment by HopeNotDespair** [comment]
Um, not to be pushy, but did you forget about this?

**Comment by NillerMedDild** [comment]
This will be reviewed in the next feature release, the one today was mostly bug fixes :)

**Comment by HopeNotDespair** [comment]
Thank you
