### ISSUE TITLE
Server Crashing After Daily Restart

### ISSUE THREAD

**Issue by redwrench** [EnigmaticaModpacks/Enigmatica6#4063]
### Modpack Version

0.5.22

### Describe your issue.

Server started crashing after daily reset. This has happened the past two nights. Restored from a backup the first time, but I don't want to keep rolling back. For some reason everything is fine until the scheduled reset, during which the server gets stuck in a crash loop.

### Crash Report

https://gist.github.com/redwrench/d188360f5a52dacedb83746c77aa7ea1

### Latest Log

https://gist.github.com/redwrench/b0ec6bc376289dd15f1cdfb9b4711636

### Have you modified the modpack?

Yes

### User Modifications

Added some mods:

- MrCrayfish's Gun and Vehicle Mods
- Cyclic
- Exchangers
- Extreme Reactors
- GunpowderLib
- Mystical Agriculture & Agradditions
- Obfuscate
- Pam's Harvestcraft 2 Core, Extended, Crops, and Trees
- Zero Core

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Updating to 5.23 should help with that particular issue.
