### ISSUE TITLE
Mystical Agriculture (+aggradations & additions)

### ISSUE THREAD

**Issue by mkrasnow** [EnigmaticaModpacks/Enigmatica6#4064]
### URL

https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

### Why would you like the mod added?

Mystical agriculture seems like it should thematically fit right in with what you are building here!  It also  adds a dynamic to the play style which potentially has interesting interactions with other automation mods.  

These two add-ins are great with it:
https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions
https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations

(FWIW, I added these 3 to my local installation and the game played fine (world gen, mob drops, recipes, etc.).  The only surprising bug was that botany pots wouldn't accept mystical soil (so there is some setting somewhere limiting that compatibility, I'm still tracking it down)

**Comment by TemperedFool** [comment]
Previously rejected in #76, #159, and #845.
