### ISSUE TITLE
Expert mode Basic Memory Chip

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4069]
### Modpack Version

Dev

### Describe your issue.

I am trying to create a Dissolution Chamber which requires the Elite Mechanical Pipe. This requires the Advanced Mechanical Pipe which requires the Infuser. To build this I am trying to make some Basic Memory Chips. I have previously used a memory stick to get the memory essence and put it though a Thermopneumatic Processing Plant to make the chips. This recipe seems to have disappeared and the only recipe that is showing is using the Dissolution Chamber which would mean that I need the Dissolution chamber in order to build the Dissolution chamber. 

Memory essence seems to only turn into essence in a Thermopneumatic Plant. Not sure if this is intended or not. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
this is being addressed in #4061

the idea of using the PNC memory stick was abandoned a while ago. The new method uses the custom items you're seeing. It wasn't intended that the dissolution chamber become uncraftable, however. That was just a bug introduced by attempting to patch another bug.
