### ISSUE TITLE
Journey map and FTB chunks configs arent getting saved

### ISSUE THREAD

**Issue by HopeNotDespair** [EnigmaticaModpacks/Enigmatica6#4071]
### Modpack Version

0.5.23(Beta) 

### Describe your issue.

Whenever I change FTB chunks and Journeymap, in game client configs, they keep getting reset. I tried turning off death waypoints on journey map and turned them on on FTB chunks but they respectively turned back on and turned back off when I saved the world, left and rejoined later

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment]
There is an update to JM (beta9) that fixes the issue on that side, not sure about FTB Chunks

**Comment by HopeNotDespair** [comment]
How do I fix the ftb chunks then? Is there a new version?

**Comment by frank89722** [comment]
Set `disableFTBFunction` to false in config/jmi-client.toml

**Comment by HopeNotDespair** [comment]
What will that do?

**Comment by frank89722** [comment]
That's a mod called JouneyMap Integration, and that's the function that force disables the conflicting features between Journeymap and FTBChunks on FTBChunk's side.

**Comment by HopeNotDespair** [comment]
Anyway worked. Thx. Would be helpful if it was on by default though

**Comment by NillerMedDild** [comment]
By default we want Journeymap death markers not FTB Chunks, since that's not the default map.

**Comment by CassWindred** [comment]
I know its been like 2 years but I'm having this issue now and I think @NielsPilgaard missed the issue here - Journeymap death markers being default is fine, the problem is that when those settings are changed those changed settings are reset to default every load, which is very frustrating if you prefer the FTB Chunks death markers.
