### ISSUE TITLE
Reduce Sooty bee spawn rates

### ISSUE THREAD

**Issue by HopeNotDespair** [EnigmaticaModpacks/Enigmatica6#4073]
### Describe your suggestion

There are far too many sooty bees spawning in the world which is causing the other bees to spawn much less frequently. 

### Why would you like this added/changed?

If you reduce the rates, then there's a better chance of the other bees spawning. I have scoured every biome (not every but you get the gist) that a particular bee can be found in for a few hrs, and sooty bees seemed to be very common, while the other bees were much rarer. I am not talking about bees like the oreo bee. I am talking about bees like the woody bee. This is for overworld bees only. The nether bees are completely fine. Thank you

**Comment by TemperedFool** [comment]
@HopeNotDespair that should give them the same spawn weight as normal passives (cows/sheep/chickens) etc.
