### ISSUE TITLE
Wasabee breeding tab causing client to crash

### ISSUE THREAD

**Issue by PandaSkunkPunk** [EnigmaticaModpacks/Enigmatica6#4076]
### Modpack Version

0.5.23

### Describe your issue.

Trying to access the Breeding tab for the Wasabee in the Beepedia causes a crash in both singleplayer and multiplayer. Seems exclusively linked to the Beepedia as looking at the bee info in JEI is fine. Maybe linked to the lack of a food item for the Kitten bee?

### Crash Report

https://gist.github.com/PandaSkunkPunk/6b3ebecf7ff05acee58c589ac040431d

### Latest Log

https://gist.github.com/PandaSkunkPunk/8ddc996776468c6a781fd00e9967d40a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
>.<

In JEI, it shows no feed item for breeding? If so I'm assuming I must have a typo in there - it's specified here:

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/d3638970fa581f6e6dfe5e483465bd6860085995/config/resourcefulbees/bees/special/Wasabee.json#L61

Can you post a screenshot of JEI? It should be `sushigocrafting:wakame_gunkan`.

**Comment by PandaSkunkPunk** [comment]
The Wasabee itself does have the feed item, that seems fine. The thing I find weird is the Kitten Bee's lack of an item. It's the only thing that stands out from the other bees.
![2022-01-17_19 37 59](https://user-images.githubusercontent.com/97923378/149851579-a31951fb-7058-4e8f-ac6b-5f1c229d57a5.png)

**Comment by TemperedFool** [comment]
Well, shoot, that's probably do it. Let me look into that.

**Comment by PandaSkunkPunk** [comment]
Gonna hope that's the issue anyway! It's not a make or break problem in my case, but I figured it definitely needed reporting.

**Comment by TemperedFool** [comment]
It is much appreciated, believe me!

**Comment by TemperedFool** [comment]
All fixed indev.
