### ISSUE TITLE
Bees disappearing in a apiary level 4

### ISSUE THREAD

**Issue by Sinestesiado** [EnigmaticaModpacks/Enigmatica6#4089]
### Modpack Version

0.5.21

### Describe your issue.

I was using bees for ore generation and in random moments some of my bees disappear, then I reintentent assuming that was a problem made by a mob but sudenly 7 of my 9 bees disappear; so I assume that its some tipe of bug but I dont what could it be.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Please update to 0.5.24 and see if the issue persists :)

**Comment by Sinestesiado** [comment]
Okay, I will see if the problem continue or not
