### ISSUE TITLE
Undergarden Only Spawning Overworld Mobs

### ISSUE THREAD

**Issue by shibeobi12** [EnigmaticaModpacks/Enigmatica6#4095]
### Modpack Version

0.5.23

### Describe your issue.

Hello! I've noticed since updating my server to 0.5.23 from 0.5.20, only mobs from the underworld seem to spawn in the Undergarden dimension. Upon testing in single player the world generates the underworld without error, mobs and all... the weirdest part to me, the skybox is completely broken, but only server side, single player also has a working skybox. Could something have corrupted my servers undergarden? I'm not opposed to a reset, but avoiding it if I can.

Thanks guys, appreciate any help on this odd bug. I checked in the Discord and didn't see anything like it so far.

### Have you modified the modpack?

Yes

### User Modifications

Client side for my device has optifine/borderless/RAD (Audio reload mod) -
But the issue persists for all my players with unmodified clients.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by shibeobi12** [comment]
Correction - I have found one singular slug.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by shibeobi12** [comment]
Hey, finally had some time on my end to test - resetting the undergarden dimension fixed, and the regenerated spots are very different. Something weird with the seed maybe? Either way, it seemed to fix it for my server. Skies fixed too for all my clients.

Weird bug, I can close this if you'd like or keep it open for tracking if anyone else has it, let me know!

**Comment by NillerMedDild** [comment]
Nice  glad it's fixed! I'd prefer that you close the issue :)

**Comment by shibeobi12** [comment]
Noted! Thanks again!
