### ISSUE TITLE
Unnerf Integrated Dynamics as per #1881, increases the cost of the fluid/energy interface to a level on par with that of an Xnet connector instead

### ISSUE THREAD

**Issue by changhe3** [EnigmaticaModpacks/Enigmatica6#4096]
### Describe your suggestion

The nerf to integrated dynamics transfer rate as per #1881, though not unjustified, is way too harsh. The lack of a "tier" system in ID makes it worse, as you cannot pay more/better materials to improve the transfer rate as in Powah or Mekanism. A better way to nerf it is to simply make fluid/energy interfaces cost more.

### Why would you like this added/changed?

This is a kitchen sink pack not an expert pack. The previous nerf castrated integrated tunnel completely and simply forces you to use Mekanism/Powah cable for late game, which is totally uncalled for.

**Comment by Darkere** [comment]
You say this is not an expert pack, but... your suggestion clearly goes in the direction of making it an expert pack??

**Comment by TemperedFool** [comment]
Tunnels, with this nerf, are still an extremely powerful tool that costs trees and chorus fruit. Normal mode is, as you say, a kitchen sink pack so we've avoided messing with most of the recipes in the pack for those sorts of purposes. What in the normal pack, other cheesing fusion, has need of higher transfer rates?

**Comment by MuteTiefling** [comment]
Even Powah cables don't keep up with Mek's at the high end. Not everything can be kept perfectly useful all of the time. Some things will become obsolete as you progress; it's simply unavoidable.

For the material cost, ID cables are very generous. If you hit a point where they're insufficient, then you have options.
