### ISSUE TITLE
shields are not visible on left hand

### ISSUE THREAD

**Issue by condeale** [EnigmaticaModpacks/Enigmatica6#4098]
### Modpack Version

0.5.24

### Describe your issue.

Shields, including from mods, are not visible on the left hand.
I attach a photo:
![image](https://user-images.githubusercontent.com/98193731/150613228-8893a415-b5be-48a8-a864-4de64e6204a6.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment]
Check your keybinds for 'toggle hide offhand item', and try pressing that

**Comment by condeale** [comment]
I saw it and it still persists

**Comment by HopeNotDespair** [comment]
I fail to see the downside.

**Comment by iMahco** [comment]
Apparently this change was added since 0.5.22
To fix this open **config/clienttweaks-client.toml**
Look for **hideShieldUnlessHoldingWeapon** and change it from true to false.
On a separate note **autoClimbLadder** was also changed to false, you can change that as you see fit as well.

**Comment by NillerMedDild** [comment]
Those options are currently set to `false` and `true` in our defaultconfig:

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/defaultconfigs/clienttweaks-client.toml#L17
https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/defaultconfigs/clienttweaks-client.toml#L7

**Comment by condeale** [comment]
hello, yes it worked, thank you very much
