### ISSUE TITLE
[Expert] Sooty Marble Variants cannot be crafted into other variants

### ISSUE THREAD

**Issue by Shadows-of-Fire** [EnigmaticaModpacks/Enigmatica6#4101]
### Modpack Version

0.5.24 (CF Release Build)

### Describe your issue.

Sooty Marble `astralsorcery:black_marble_raw` has a stonecutter recipe to all variants ->
* `astralsorcery:black_marble_arch`
* `astralsorcery:black_marble_bricks`
* `astralsorcery:black_marble_chiseled`
* `astralsorcery:black_marble_engraved`
* `astralsorcery:black_marble_pillar`
* `astralsorcery:black_marble_runed`
* `astralsorcery:black_marble_stairs`
* `astralsorcery:black_marble_slab` * 2

Of these, all except stairs and slabs are 1:1 equivalent with Sooty Marble, but cannot be re-crafted into other variants (expected is all variants should go back into the stonecutter).
Slabs are also missing a recipe to turn them back into sooty marble bricks.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Rodg88** [comment]
My fix, which is just adding the sooty marble to the stonecutter script, means you can swap between any full block, but only the "smooth" will make stairs and slabs still. And currently in the pack there aren't standard recipes for turning slabs into blocks, and adding them might start to conflict with some chiseled block recipes, so not sure what to do there. Maybe just a new script with a curated list of 'returnable' slabs?

**Comment by NillerMedDild** [comment]
Good fix 👌 

> Maybe just a new script with a curated list of 'returnable' slabs?

Sounds good to me 👍
