### ISSUE TITLE
Can't brew "Potion of Mana Regeneration II" get "Calming Potion" instead

### ISSUE THREAD

**Issue by Moonwolf287** [EnigmaticaModpacks/Enigmatica6#4102]
### Modpack Version

0.5.23

### Describe your issue.

When using the recipe for creating a "Potion of Mana Regeneration II", you will get a "Calming Potion" instead.
The recipe (according to JEI) is "Potion of Mana Regeneration (3:00)" + Glowstone = "Potion of Mana Regeneration II" 
![grafik](https://user-images.githubusercontent.com/1161223/150627866-77ce3b71-f1ea-4627-9ad4-26e5eef006e7.png)

I also tried using the 8:00 min version of the Potion as base and also got  "Calming Potion".

### Have you modified the modpack?

Yes

### User Modifications

Added more Curio Slots.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment]
I still get this in 0.5.25 dev:
![image](https://user-images.githubusercontent.com/2611674/150746289-d4aaca15-0d18-401f-b83e-ad62c3faf096.png)
![image](https://user-images.githubusercontent.com/2611674/150746348-9f4f800f-00de-4f19-a76a-ce73d7157cb8.png)

**Comment by theboo** [comment]
Same issue making a spell damage 2 potion, spell damage 1 crafts fine but when you go to add the glowstone it makes the 10 minute calming potion

**Comment by NillerMedDild** [comment]
I'm not sure who could be at fault here to be honest, I've looked at the Calming Potion registration code and it seems fine to me, might be something on Ars side.

**Comment by MuteTiefling** [comment]
No clue what is breaking these either, but we have so many things messing with potions...

Backing this out to use just the regular Spell Damage potion instead

**Comment by demethan** [comment]
Recipes that are messing up in the brew stand work fine in the Industrial Forgoing Potion brewer.  From what we can tell, the glowstone applies twice in the brew stand.
