### ISSUE TITLE
Duplicate Dense Construction Block -> Construction Paste crushing recipe

### ISSUE THREAD

**Issue by FieldArmada** [EnigmaticaModpacks/Enigmatica6#4103]
### Modpack Version

develop @ a1bb13646f03a74a76b1d08a6e44b2a645b9928a

### Describe your issue.

one of these is `create:crushing/dense_construction_block`, other is `enigmatica:base/create/crushing/construction_paste` and they probably don't both need to stay

![duplicate-paste](https://user-images.githubusercontent.com/75914799/150628724-7e1b545d-f471-4f3b-aac5-7f9eacfe7ff6.PNG)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
ah, fancy they've added default compatibility. We'll get that cleared up. thanks :D
