### ISSUE TITLE
Player being logged in on server restart completely breaks the server. Note only seen happen on a server.

### ISSUE THREAD

**Issue by glitchy-5** [EnigmaticaModpacks/Enigmatica6#4109]
### Modpack Version

0.5.21

### Describe your issue.

Player logged in on server restart causes a stack over flow sending the server into a crash loop. (log for that included)
We where only able to get the server out of the loop was to restore from backup or do a fresh world file.
If there are questions ask and I will try to answer them.

### Crash Report

The crash report was not retrievable.

### Latest Log

https://gist.github.com/glitchy-5/38a6e3361b27f245336e64246693d299

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
go to config/polymorph-integrations.toml and disable RS integration.
