### ISSUE TITLE
Fried Potato Slices recipe issue

### ISSUE THREAD

**Issue by Moonwolf287** [EnigmaticaModpacks/Enigmatica6#4115]
### Modpack Version

0.5.23

### Describe your issue.

You can't create "Fried Potato Slices" because they have the same recipe as "Fried Potato Cubes"
![grafik](https://user-images.githubusercontent.com/1161223/150683333-3a66f334-e01f-45bd-846c-2d670a137316.png)
![grafik](https://user-images.githubusercontent.com/1161223/150683341-41bea0b8-7692-4f4c-8bb5-79654b9dcc8a.png)

"Fried Potato Cubes" should take "Potato Cubes" as input.

### Have you modified the modpack?

Yes

### User Modifications

Added more Curio slots.
Added Curious Jetpacks Mod.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. I've got that fixed on our end and PRd a fix to the mod.
