### ISSUE TITLE
All items can be duped using the Pretty Pipes "Crafting Terminal"

### ISSUE THREAD

**Issue by AWrongUsername** [EnigmaticaModpacks/Enigmatica6#4122]
### Modpack Version

0.5.25

### Describe your issue.

Hello!

To dupe stuff you need two players. First, put a crafting recipe in the "Crafting Terminal".
When all the items are in the crafting grid, and both players are in the terminal at this time, both players can take the item, thus duplicating the item.
Only one set of items will actually be used when duping.
As far is we've seen this works with all ingame crafting recipes.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Oh boy. Thanks for the report.

**Comment by NillerMedDild** [comment]
Found it reported here: https://github.com/Ellpeck/PrettyPipes/issues/112
Not fixed though, only in the 1.18 version.

**Comment by AWrongUsername** [comment]
Original mod author seems to have provided a patch with the dupe fixed. Haven't tried it myself yet.

**Comment by NillerMedDild** [comment]
Would you mind testing when you have time? :)

**Comment by AWrongUsername** [comment]
Certainly, give me a few minutes to replicate this again and I will get back to you!

**Comment by AWrongUsername** [comment]
The build provided by the mod author still has this bug. I have reported back to the original mod maker.

**Comment by AWrongUsername** [comment]
Latest build (PrettyPipes-1.9.5.5) has resolved the issue!

**Comment by MuteTiefling** [comment]
wooo!

**Comment by NillerMedDild** [comment]
Thanks a lot for testing! 🎉
