### ISSUE TITLE
RS System Dupe glitch

### ISSUE THREAD

**Issue by EfsaneThePizza** [EnigmaticaModpacks/Enigmatica6#4128]
### Modpack Version

0.5.16

### Describe your issue.

I can dupe items very easily using the RS system as I've demonstrated in the video below. Basically, I can create 6 blocks of diamonds for the cost of 2 diamonds and then continue this loop by converting those free diamonds blocks I got into diamonds and using 2 of those to get 6 new blocks. It doesn't have to 6 blocks for 2 diamonds, nor only diamonds. It can even be any number of blocks for 1 material (If you're lucky enough to get 9x+8 amount of ghost materials). This can also be done with any recipe that can be reversed. What I mean by reversed is, basically how you can spend 9 materials on a block and then turn that block back into 9 materials. It works on any type of "reversable" recipes, even chunks into clumps into chunks. Altho it can still be done on recipes that are not "reversable", it will not be an infinite dupe, it'll just make them cheaper. I suggest you watch the video to understand a bit better!

Video link since it's bigger then 10MB: https://youtu.be/xd876Q53CIc

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
You're a few versions out of date. The part I'm not understanding is where the ghost diamonds are from? I can't get anything like that to occur in my test world to even begin to attempt to reproduce this. 

Would you be able to update to 0.5.25 and try to reproduce this? Also if you could let us know where your diamonds are being stored, that might help. I feel like there's something goofy with the actual storage device there.
