### ISSUE TITLE
Mod suggestion: Fairy lights

### ISSUE THREAD

**Issue by SammyWhamy** [EnigmaticaModpacks/Enigmatica6#4133]
### URL

https://www.curseforge.com/minecraft/mc-mods/fairy-lights

### Why would you like the mod added?

It's a pretty small and simple mod, and adds some really cute and pretty lighting options!

I'm not sure how the block variations work and if this would be considered adding a lot of blocks (And thus a performance hit), but I'd love to see this in the pack!

**Comment by NillerMedDild** [comment]
Sorry but no, I think we have enough lighting options :)
