### ISSUE TITLE
Tinkers Con Capacitor Modifier

### ISSUE THREAD

**Issue by NeosGhost** [EnigmaticaModpacks/Enigmatica6#4138]
### Modpack Version

Expert 0.5.24

### Describe your issue.

Having an issue with the capacitor modifiers, tool does not seem to use RF just durability.

![wZKQLAM - Imgur](https://user-images.githubusercontent.com/16095247/151281953-9c732853-17ab-466b-b633-57bd8687f7cb.jpg)
![151281638-20448d7f-61c9-4e1e-ae5b-53bc0da5e8c8](https://user-images.githubusercontent.com/16095247/151281990-e7d8134c-6021-4943-aeba-5f87f3121b53.jpeg)

Reported to Materialis as well.

Thanks

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, linking to the other one you made for good measure: https://github.com/RCXcrafter/Materialis/issues/17

**Comment by RCXcrafter** [comment]
That's correct, the capacitor upgrade only adds energy capacity. Currently only the draconic evolution materials have traits that use power. I want to add other things that use power eventually but I'm not yet sure what those things will be. I'll probably disable the recipes for the capacitor upgrade in the next version if draconic is not installed.

**Comment by MuteTiefling** [comment]
Redstone Arsenal is now available for 1.16. That might be another good use case for you.

**Comment by RCXcrafter** [comment]
I didn't realize that was ported already, I'll probably include some compatibility for that then.

**Comment by MuteTiefling** [comment]
It's only been out for 3 days or so :D easy to miss

**Comment by RCXcrafter** [comment]
Materialis 2.5.0 has been released, redstone arsenal compatibility was added and the capacitor modifier is only enabled if draconic evolution and/or redstone arsenal is installed.
