### ISSUE TITLE
Pollution of the Realms

### ISSUE THREAD

**Issue by kuba44** [EnigmaticaModpacks/Enigmatica6#4139]
### URL

https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms

### Why would you like the mod added?

Pollution of the Realms is a great mod that adds pollution and its managment into the game. Every industrial thing produces pollution, carbon and sulfur, that have negative effects on players, so they have to mangage it. At first the player will play normally, but producing too much pollution will lead to: blindness, weakness and even death. But of course the players can manage the pollution, filter it out, so they won't suffer from its negative effects. The mod also has a lot of compatibility with other mods and allows a lot of configuration to change stuff, it even allows to make new pollutants for even more varied gameplay.
Edit: I forgot to add that for the best experience, it should be used with Advanced Chimneys.

**Comment by NillerMedDild** [comment]
I think this is the sort of mod that a modpack needs to be based entirely on for it to work well. I don't want to put in that amount of work tbh, though I like the mod concept.
