### ISSUE TITLE
Expert quests are [again] visible on normal version from CurseForge!

### ISSUE THREAD

**Issue by KacproPL132** [EnigmaticaModpacks/Enigmatica6#4140]
### Modpack Version

0.5.25

### Describe your issue.

Expert quests that are under developement are again visible ^^" This time 3  of the sections w/o any description or rewards:
Tech - Nuclear Physics
Magic - Adept
Magic - Master
![obraz](https://user-images.githubusercontent.com/60540476/151329255-295a46ba-b5b7-442a-bc7b-4f57d45d51aa.png)

Any of those quests have any information in them, only what you need to complete them.
![obraz](https://user-images.githubusercontent.com/60540476/151329364-bc8d0355-cdb6-4d4f-b5db-9c1bcf7501da.png)
![obraz](https://user-images.githubusercontent.com/60540476/151329398-ccbbc165-2984-4d17-82d8-1a6c93bbc64a.png)
(Oke ignore above one... I found actually few that have description ^^" Some of them have / some of them no.)
![obraz](https://user-images.githubusercontent.com/60540476/151329483-dd1aed98-92e3-4761-8651-b7d78d0c6713.png)
![obraz](https://user-images.githubusercontent.com/60540476/151329503-12768a55-4075-45ba-8956-04a9309a897a.png)
![obraz](https://user-images.githubusercontent.com/60540476/151329516-967bbd66-9569-444b-a842-bfabe3e6dee1.png)

Anyways I think this should be hidden am I right ^^"?
_PS: Didn't see if this happened on Singleplayer, but I think it should as well._

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Oh no 😅

**Comment by MuteTiefling** [comment]
My bad, I see what I did wrong here :D
