### ISSUE TITLE
Redstone Arsenal

### ISSUE THREAD

**Issue by HopeNotDespair** [EnigmaticaModpacks/Enigmatica6#4143]
### URL

https://www.curseforge.com/minecraft/mc-mods/redstone-arsenal

### Why would you like the mod added?

Redstone arsenal is a mod which adds tools and weapons using the incredible power of redstone flux. It is now ported to 1.16.5. It's takes the best sides of tech and adds it to minecraft. It's an absolutely must have and amazing mod which fits in with the pack extremely well. I request you to consider adding this mod in the next feature release.

**Comment by HopeNotDespair** [comment]
Changed the link. Sorry for accidentally putting the wrong link

**Comment by NillerMedDild** [comment]
We'll consider it 👍

**Comment by NillerMedDild** [comment]
Love the mod, but we have no need for it. We'll keep our eyes on it though, see if/how it updates over time.
