### ISSUE TITLE
[Mod Suggestion] Interactive Corporea 

### ISSUE THREAD

**Issue by jlfree12** [EnigmaticaModpacks/Enigmatica6#4144]
### URL

https://www.curseforge.com/minecraft/mc-mods/interactive-corporea

### Why would you like the mod added?

I’ve been told (not sure how true this is, haven’t played expert yet) that Corporea is a good option for a storage system pre-RS in e6e, and this may make Corporea more appealing as an option compared to something like pretty pipes or occultism, as the chat request system is really weird.

**Comment by HopeNotDespair** [comment]
The visuals aren't really all that good based on the pics in the link

**Comment by NillerMedDild** [comment]
I think that looks pretty good tbh, but I'm not sure if adding it would mess with @MuteTiefling's intentions for its usage - what do our think?

**Comment by MuteTiefling** [comment]
Yeah, I think it looks pretty sweet, and might help people to use it early game expert as I was hoping. I'd say let's give it a try.

**Comment by NillerMedDild** [comment]
Nice 👌
