### ISSUE TITLE
Dramatic Speedup of Recipe Access Time With the Mod: FastSuite

### ISSUE THREAD

**Issue by KleinByte** [EnigmaticaModpacks/Enigmatica6#4145]
### URL

https://www.curseforge.com/minecraft/mc-mods/fastsuite

### Why would you like the mod added?

I've been experimenting with some performance mods.

FastSuite looks to be a pretty solid choice.

- The improvements are pretty substantial as seen on their page.
- Works worth all other mods such as Fastworkbench-FastFurnace,KubeJS,etc...
- Doesnt impact loading times.

Obvious more testing would be nice to verify it actually doesn't break anything.

**Comment by NillerMedDild** [comment]
We've had it before and it does break things sadly. Random recipes didn't work 🙃
