### ISSUE TITLE
Moving Occultism Storage crashes and gives java error

### ISSUE THREAD

**Issue by NunbearTWITCH** [EnigmaticaModpacks/Enigmatica6#4146]
### Modpack Version

Enigmatica 6

### Describe your issue.

When I broke my Occultism Storage to move its position whenever I try to click it to put it down again it gives the a message saying payload may not be larger that 32767.  the storage has not used more than 3000 types of 9000

### Latest Log

https://gist.github.com/NunbearTWITCH/842080b80b49b03b94c705812acb04c3

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. There's no indication of a crash or disconnect in your log, could you please provider a new one?
