### ISSUE TITLE
Caves & Cliffs Backport

### ISSUE THREAD

**Issue by Thiana** [EnigmaticaModpacks/Enigmatica6#4151]
### URL

https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport

### Why would you like the mod added?

Since 1.18 has been out for a few months now and it doesn't look like E6 will hit 1.0 for a while yet, could you please consider adding a backport mod? Quark introduces a few things like deepslate and glowsquid but there are a lot of other 1.18 blocks/features that would be nice to have once E6 is released.

Caves & Cliffs Backport seems to introduce most/all the 1.18 features/blocks/npcs and all the worldgen can be disabled if you want to make them available by other means. It's also kept actively updated (last update being in January).

Thanks!

**Comment by jlfree12** [comment]
I doubt this will get added because of the performance impact but it would be super cool.

**Comment by NillerMedDild** [comment]
Looks like a solid mod 👌 I disabled all worldgen features, since this is only for the blocks.

**Comment by Rodg88** [comment]
How much overlap is there with quark? do we need to check and disable double-ups?

**Comment by NillerMedDild** [comment]
> How much overlap is there with quark? do we need to check and disable double-ups?

A ton :P

**Comment by jlfree12** [comment]
If worldgen is disabled does that mean no lush caves, geodes etc. spawning naturally?

**Comment by NillerMedDild** [comment]
No lush caves, but geodes would spawn.

**Comment by NillerMedDild** [comment]
Myeah sorry, this would be too much work for too little, we won't add it :(
