### ISSUE TITLE
Mod Suggestion: Legendary Tooltips.

### ISSUE THREAD

**Issue by AcceptCookiesPls** [EnigmaticaModpacks/Enigmatica6#4153]
### URL

https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips

### Why would you like the mod added?

It replaces the boring vanilla tooltips with ones that look a little bit better and change depending of an item's rarity. Plus it has resource pack compatibility, so you can create custom tooltips if you don't like the default ones. Also, works with every tooltip that exists. It's a pretty simple yet nice mod to have in my opinion.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. I'm a bit on the fence on this one, I'll think about it :)

**Comment by NillerMedDild** [comment]
I have come to the conclusion that I don't wanna add this mod, sorry :)
