### ISSUE TITLE
Oreo Bees Vanish

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4158]
### Modpack Version

5.0.25

### Describe your issue.

A community hosting an E6 server "Devious" updated the pack to 5.0.25 today, but during the update my oreo bees on the server vanished, they no longer existed. I'm wondering if there was some sort of change that caused this to happen?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
@TemperedFool caused by turning off dev bees perhaps?

**Comment by FooterMan14** [comment]
Also a quick note: the server updated from 5.0.21 to 5.0.25

**Comment by TemperedFool** [comment]
Man I hope not; shouldn't be since the ID didn't change in the added JSONs.

**Comment by FooterMan14** [comment]
Any update on my issue here?

**Comment by TemperedFool** [comment]
I haven't been able to reproduce this. We do get occasional reports of bees disappearing, which generally traces back to something like low aura killing them, or them despawning because they can't find a nest or flower.
