### ISSUE TITLE
Teleportation Enchant for Tetra

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4159]
### Describe your suggestion

Tetra tools cannot use the Teleportation enchantment from Travel Anchors, is there any way to make it possible to use it on Tetra tools?

### Why would you like this added/changed?

Would be nice to be teleporting around your base with one tool.

**Comment by NillerMedDild** [comment]
Good idea, would you mind suggesting that on the Tetra issue tracker? That's how new enchants are usually added :)
https://github.com/mickelus/tetra/issues

**Comment by FooterMan14** [comment]
Yes I can do that

**Comment by NillerMedDild** [comment]
Thank you kindly :)
