### ISSUE TITLE
Building Gadgets Readme Mislabelled Binding

### ISSUE THREAD

**Issue by spooked** [EnigmaticaModpacks/Enigmatica6#4164]
### Modpack Version

Wasn't sure where to find this sorry (installed in the past month)

### Describe your issue.

The readme for building gadget templates says the wrong keybind, should be building gadgets not mining gadgets

_"At this point, the template is loaded and may be used to paste the structure in your world. The Gadget may still be in "Copy" mode and will need to be switched to "Paste" mode in order to work. With the Gadget in hand, press and hold the Mining Gadgets "Settings Menu" keybind** to open the gui. "_

instances\Enigmatica 6 - E6 - 1.16.52\minecraft\building_gadgets_patterns\README.TXT

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed ty!
