### ISSUE TITLE
Can't craft a cabinet

### ISSUE THREAD

**Issue by kati0na** [EnigmaticaModpacks/Enigmatica6#4166]
### Modpack Version

E6 - 1.16.5

### Describe your issue.

Cabinet (from MrCrayfish's furniture mod) crafting recipe crafts 4 chests instead
Here i'm trying to craft a cabinet, opening the recipe in JEI:
![frus1](https://user-images.githubusercontent.com/98770669/151851452-8b9e502b-98a2-4fd2-b557-6f3342a7d64a.png)
And after i press '+', this happens:
![frus2](https://user-images.githubusercontent.com/98770669/151851453-4a888e06-1714-4423-8c32-f62d04c2e61b.png)
Did not try other wood
Did not try this in multiplayer
I suggest this happens because the recipe is overlapping with 4 chest recipe, since it basically is a ring of logs
pls fix ty

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by HopeNotDespair** [comment]
Shouldn't polymorph be fixing this problem?

**Comment by HopeNotDespair** [comment]
Shouldn't Polymorph be fixing this problem?

**Comment by NillerMedDild** [comment]
This should be resolved on version 0.5.25, the latest release version.
Please update and let us know if that fixes it for you :)

**Comment by kati0na** [comment]
![ty](https://user-images.githubusercontent.com/98770669/151968867-4591b059-4cf0-4eb1-aa49-dd57afa38956.png)
Thank you, after the update everything is fine
