### ISSUE TITLE
Conflict between Manual Centrifgure and Tinkers' Construct chest armor

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#4167]
### Modpack Version

0.5.24

### Describe your issue.

Trying to use a Manual Centrifuge (shift-right click) from Resourceful Bees while wearing a Tinkers' Construct chest armor (Traveler's Vest, Plate Chestplate) does nothing. Unequipping the chest armor lets you interact with the Manual Centrifuge again.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KnightMiner** [comment]
You probably just need to update the pack to the TiC build released today. It fixed chestplate interaction bug 2 which affects interactions while wearing a chestplate that run on sneak-right click (a pretty edge case vanilla interaction hook.

**Comment by NillerMedDild** [comment]
Oh nice, thanks! 😊
