### ISSUE TITLE
Resourceful Bees Centrifuge PCBee Honeycomb output

### ISSUE THREAD

**Issue by gruff8** [EnigmaticaModpacks/Enigmatica6#4168]
### Modpack Version

0.5.23 - expert mode

### Describe your issue.

I don't know if this is a bug or an anoying feature.
The recipe for centrifuge of PCBee Honeycomb has the fluid as the primary output and an item as the honey/fluid output.
It would be nice to swap these as curruntly this bee cannot be automated in the cetrifuge multiblock but has to be done separately in a centrifuge with glass bottles in it.

![image](https://user-images.githubusercontent.com/8487636/151863414-97684aa7-e935-4a64-bf8b-53acf8524b22.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
This is, unfortunately, intentional. Also not exclusive to Expert. Etching Acid doesn't have a bottle, which bottle outputs require. Since I could output it as a fluid, which is allowed for the primary and secondary outputs, I got around this limitation by setting it up that way.

**Comment by gruff8** [comment]
ok, fair enough.
