### ISSUE TITLE
Quartz Ore processing with Create Crushing wheels doesn't make sense?

### ISSUE THREAD

**Issue by KacproPL132** [EnigmaticaModpacks/Enigmatica6#4174]
### Describe your suggestion

_I don't think this can be under bugs, so here ya go suggestion time!_

Well... in Create with Crushing wheels there are two recipes from Quartz ore. First of them gives 2x of quartz with 50% of 6x, and second one gaves 2x of quartz and aditionally 50% for 4 sulfur dust. However, first recipe works _only_ for Vanilla quartz, while second for everything else like chunks and other type of Quartz ore.
First recipe:
![obraz](https://user-images.githubusercontent.com/60540476/152176000-9b33ba8e-6236-4616-bcf1-e71216ca2da4.png)

Second recipe: (Quartz Chunk or Nether Quartz Ore)
![obraz](https://user-images.githubusercontent.com/60540476/152176093-343d680b-ac47-461d-a926-3059584168a9.png)
![obraz](https://user-images.githubusercontent.com/60540476/152177330-65c8aa78-4188-46e9-ae22-467adead7c71.png)

Actuall suggestion: Just delete one of them:
Delete first recipe and add vanilla ore to the second one
**_or_**
Delete second one with sulfur and add forge:ores/quartz to the first one :D 

### Why would you like this added/changed?

Does this even make sense to have both of them in the pack?

**Comment by MuteTiefling** [comment]
Ah, cool thanks. I've removed the base Create one. Seems to have gone un-noticed.
