### ISSUE TITLE
Tinkers' Luck not applying to ore drops

### ISSUE THREAD

**Issue by MrSnowShark** [EnigmaticaModpacks/Enigmatica6#4176]
### Modpack Version

0.5.25

### Describe your issue.

Not sure if intended or not but the 'Luck' modifier on Tinkers' tools doesn't apply to ores like iron, copper, tin, etc.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Quite normal. Fortune doesn't work on metal ores.
