### ISSUE TITLE
Rotary condensentrator not producing water vapor @mekanism

### ISSUE THREAD

**Issue by Sekido123** [EnigmaticaModpacks/Enigmatica6#4181]
### Modpack Version

0.5.25

### Describe your issue.

Rotary condensentrator not producing water vapor when set to decondensentrating. i have it hooked up with a sink and mechanical pipes. i was almost done making fissile fuel too lol

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by KacproPL132** [comment]
Well weird... It works for me like a charm on server :D 
Are you sure you have everything connected like it should?

**Comment by NillerMedDild** [comment]
Screenshots of the setup would be helpful :)

**Comment by Sekido123** [comment]
![272548860_3158791851025096_416266220994830737_n](https://user-images.githubusercontent.com/97376914/152495402-90a94fe6-fd83-4095-9d97-e285fec9b23e.jpg)

Hopefully you can see this.

**Comment by Sekido123** [comment]
so i drained the water via the guage dropper and refilled it with the same pipe and it started to work! i have no clue why, but it works lol!
