### ISSUE TITLE
Bizzarre crash

### ISSUE THREAD

**Issue by User-12691296** [EnigmaticaModpacks/Enigmatica6#4182]
### Modpack Version

2586

### Describe your issue.

I placed a creative energy cube, wanting to charge two infinity backpacks with my infinity charger, and the game crashed. I only attached the crashing part of my latest.log, since the last autosave.

My inventory consisted of an iron backpack in the cosmetic chestplate slot, two IF infinity backpacks, an IF infinity charger, and a mekanism creative energy cell (which I tried to place, and it crashed. It crashed before the cell placed, if that's relevant), a diamond sword (enchantments sharpness 10, looting 255), and some mob drops from killing basic hostiles and passive overworld mobs with that sword.

### Crash Report

https://gist.github.com/User-12691296/5bd96f519b5752970bdcc93563c8baab

### Latest Log

https://gist.github.com/User-12691296/5bd96f519b5752970bdcc93563c8baab

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. There's not really anything we can do here I'm afraid, the crash log is completely generic :/
