### ISSUE TITLE
Normal mode - IE press - broken gear recipe

### ISSUE THREAD

**Issue by SteaSteaStea** [EnigmaticaModpacks/Enigmatica6#4185]
### Modpack Version

0.5.25

### Describe your issue.

In normal mode the IE press requires the gearworking die (which is uncraftable and hidden from jei).
In expert it seems to be alright so maybe you guys messed something up with the base recipes while working on expert.

![2022-02-03_01 39 56](https://user-images.githubusercontent.com/76264934/152427970-f19e044b-783e-4615-8c61-1b56b3a8f8fe.png)

Another thing here is something that may be intended but I would expect the press to require the mold for plates just like all the other items (rods,gears, wires, etc.) Is this the correct recipe?

![2022-02-03_01 40 49](https://user-images.githubusercontent.com/76264934/152427975-db8baad0-d3b1-4009-a347-50d12bcccb1b.png)

Btw you may notice extra recipes from other mods in the jei as the screenshots are from a modified instance but I did check it with a completely untouched E6 instance as well and the same issue was there.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. I swear I've fixed this twice now ><
