### ISSUE TITLE
PneumaticCraft tank upgrade recipe does not consume tanks with fluids

### ISSUE THREAD

**Issue by tyr0wl** [EnigmaticaModpacks/Enigmatica6#4188]
### Modpack Version

0.5.25

### Describe your issue.

Playing on expert (commit 1a33a42d6f1ebbde188e3b909e4f0e608362432e)

When upgrade 2 PneumaticCraft tanks with fluids inside to a medium tank, the tanks do not get consumed in the craft

![image](https://user-images.githubusercontent.com/6159764/152462612-5016ac7f-d098-4b4c-8d6a-67e31ad34bde.png)

Result:

![image](https://user-images.githubusercontent.com/6159764/152462716-50f0b9ec-225b-4fcb-9a7e-5d7fb1d15aa3.png)

Notice how it only used 1b of the fluid inside. Only tanks without a fluid get consumed. Does not work for medium tanks to large tank. Did not test with Huge tank.

### Have you modified the modpack?

Yes

### User Modifications

Added following mods:

DynamicSurroundings-1.16.5-4.0.5.0
GameMenuModOption-1.16.4-1.8

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by desht** [comment]
Has the Medium Tank recipe been changed in E6?  Because the default recipe won't allow crafting with tanks that aren't empty (specifically, the tank itemstacks must have no NBT):

![image](https://user-images.githubusercontent.com/736831/152520466-66cbb300-5a9e-4cec-bdf5-fd5e7a3627e0.png)

The default recipe (note use `forge:nbt` for the tanks):
```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "PSP",
    "ITI",
    "PSP"
  ],
  "key": {
    "P": {
      "tag": "pneumaticcraft:plastic_sheets"
    },
    "S": {
      "type": "forge:nbt",
      "item": "pneumaticcraft:small_tank",
      "count": 1
    },
    "I": {
      "tag": "forge:ingots/gold"
    },
    "T": {
      "item": "pneumaticcraft:pressure_tube"
    }
  },
  "result": {
    "item": "pneumaticcraft:medium_tank"
  }
}
```

**Comment by MuteTiefling** [comment]
Yep. It has been changed to accept either gold or copper. I'll take a look at what I did wrong in a bit :D

**Comment by MuteTiefling** [comment]
Odd, I'd have thought the replaceInput script that's doing this would have been safe. Looking into options here and checking with Latcord, but so far my tests have all failed.

Might have to simply revert this one, or possibly do it with a straight datapack recipe instead of scripts.
