### ISSUE TITLE
Starlight x Create

### ISSUE THREAD

**Issue by Quantombb** [EnigmaticaModpacks/Enigmatica6#4189]
### URL

https://www.curseforge.com/minecraft/mc-mods/starlight-x-create

### Why would you like the mod added?

Optimizes the light engine much more than vanilla, and finally compatible with Create.

**Comment by NillerMedDild** [comment]
Ooh interesting! I hope this works in E6 😅

**Comment by Quantombb** [comment]
Yep haha, e6 has a LOT of mods

**Comment by SteaSteaStea** [comment]
I've been using this with E6 instead of phosphor for 2 weeks so far and it seems to be working fine.

**Comment by novaexe** [comment]
works with 0 issues for me as well 👍

**Comment by NillerMedDild** [comment]
Adding Starlight prevents you from opening the iChisel GUI :/

**Comment by NillerMedDild** [comment]
I think adding this is too risky, sorry.
