### ISSUE TITLE
Broken Cooking Recipe for Fried Potato Cubes

### ISSUE THREAD

**Issue by KacproPL132** [EnigmaticaModpacks/Enigmatica6#4190]
### Modpack Version

0.5.25

### Describe your issue.

_Well this is quite easy one again :D_
Recipe for Fried Potato Cubes is broken ^^" It uses Potato Slices not Potato Cubes, making Fried Potato slices unobtainable.
![obraz](https://user-images.githubusercontent.com/60540476/152605016-3a6ec7e1-da61-4ee2-88a9-ebab5c4813e4.png)
(Yes... I've checked it and it gives back only Fried Potato Cubes. Potato Cubes you can't even put onto a campfire)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4115
