### ISSUE TITLE
Forbidden and Arcanus

### ISSUE THREAD

**Issue by User-12691296** [EnigmaticaModpacks/Enigmatica6#4192]
### URL

https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus

### Why would you like the mod added?

A couple of reasons. 

First, it has awesome visuals and blocks, especially for dark, imposing structures. In 1.16, epic textures are becoming more important to modded now, and this mod easily applies to that theme. Its style also fits in well with the ingot library mod.

Second, it adds some powerful, but not overpowered, mid-game armor and tools. This armor is strong, comes after you beat the ender dragon, and gives you a nice amount of protection, that really helps when fighting end cities, and moving on to the next stage of the game

Third, it encourages exploration, and completing parts of vanilla that are often ignored. This includes the ocean monument, getting the dragon head, and finding and exploring to new biomes. You need the end cities to create the mid game armor, and the ocean monuments to make it stronger, and the enchanted forest biome of vanilla to start the mini-progression this quest has to offer. You also need to explore to find a cool flower that allows you to automate the generation of arcane gold.

Finally, it would work well in the expert mode of this pack. The mod itself, especially the 1.16 version, has a lot of features without a use yet. But it still has a recipe for nearly everything it adds. And what it adds would fit well in a progression line. This is due to the powerful tools it provides, and the necessity of exploration. It also adds some cool features such as soul extraction from soul sand (which could be used to gate the mob duper, powered spawner, and some apotheosis modifiers), an unbreakable tool enchantment (which is crafted from a rare ore, once again gateable, but which will provide massive QoL in the endgame of this pack).

**Comment by MuteTiefling** [comment]
Duplicated by #506 and #63
