### ISSUE TITLE
Little Logistics

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica6#4194]
### URL

https://www.curseforge.com/minecraft/mc-mods/little-logistics

### Why would you like the mod added?

Because it's just about the most adorable thing I've seen in Minecraft in a minute haha.

Basically a tiny automated boat system for transporting items/fluids, also does fishing too. They have a little spotlight page/wiki here, all the coming soon stuff has been added in the last couple days. I've been playtesting it in e6 for a few days now and haven't ran in to any major issues, any minor issues have been fixed almost immediately by the dev team there.

https://littlelogistics.murad.dev/
Gif from playtesting:
https://gyazo.com/6718c311369ee587e0da0744c2dcecae

**Comment by NillerMedDild** [comment]
That does look awesome :P but I feel like we have a ton of ways to do similar things? Albeit not as cute.

**Comment by theboo** [comment]
True, we do have multiple item/fluid transfer options available... And I definitely don't see anyone using this as their main item/fluid transport, it's not exactly the fastest thing. I see it as more of an aesthetic mod, or something to use where speed isn't exactly a priority. Fairly light weight(only 8 or 9 items total) and would be really fun with our huge rivers(next update has a seat barge so you can ride it)

**Comment by jlfree12** [comment]
This is so adorable it reminds me of railcraft

**Comment by theboo** [comment]
Bit by bit! https://youtu.be/4hI99VUqczw

**Comment by juh9870** [comment]
I can see this having some use in earlygame e6e

**Comment by jlfree12** [comment]
Any update on this? Its so adorable.
