### ISSUE TITLE
Issue starting server

### ISSUE THREAD

**Issue by greene5300** [EnigmaticaModpacks/Enigmatica6#4198]
### Modpack Version

0.5.25

### Describe your issue.

Not entirely ruled out on user error yet, however the server seems to get hung up for 1hr+ on server startup "[ Server thread/INFO] [co.re.re.ResourcefulBees/]: Validating Mutations..." Upon attempting to connect on the client side I get a message Connection closed -mismatched channel list.  Server prompt from this can be found in debug.log.

### Latest Log

https://gist.github.com/greene5300/612c24b0fbe2fdce4e742c1e04f52ce0

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Mismatched mod channel list, means what it sounds like. You have different mod versions on client and server.

Validating mutations is just the last message after starting. If you scroll up you can see the "Done!" message. It is ready and waiting for someone to join.
