### ISSUE TITLE
Invalid Fried Potato Cubes recipe

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#4200]
### Modpack Version

0.5.24

### Describe your issue.

Due to invalid recipe for Fried Potato Cubes, it's impossible to cook Fried Potato Slices.
This has also been [reported](https://github.com/Immersive-Geology-Team/Immersive-Cooking/issues/4) on the Immersive Cooking issue tracker, but the supposed version to fix this is not released yet. Supposedly there's a [fix for it](https://github.com/Immersive-Geology-Team/Immersive-Cooking/issues/4#issuecomment-955815837).

![bild](https://user-images.githubusercontent.com/12349921/152686740-06d70097-674b-4c0e-9b42-24196fe6708f.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate #4115
