### ISSUE TITLE
Invalid Player Transmitter quest requirement

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#4202]
### Modpack Version

0.5.24

### Describe your issue.

The quest for Player Transmitter says "OR Filter" instead of "Player Transmitter (Any Tier)".

![bild](https://user-images.githubusercontent.com/12349921/152692024-9b6f258e-51bb-4b9d-93a8-cf065b174a34.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks! Got that all fixed up now.
