### ISSUE TITLE
Max thermo generator IO can't keep up to its output

### ISSUE THREAD

**Issue by User-12691296** [EnigmaticaModpacks/Enigmatica6#4204]
### Describe your suggestion

The problem is pretty simple. With max generation on a thermo generator, it produces more power than it can output. The generator below is making 91K fe/t, and it can only output 12K.

![image](https://user-images.githubusercontent.com/94016358/152697927-c6d3b77a-f9e9-4e05-8396-a9214005f29b.png)

This is due to your addition of ether gas as a super high tier coolant, which buffs the thermo gens too much for them to handle (the extreme power gen isn't the problem, it's a cool feature and reward of ether gas, a farm that's hard to make). 

I'm suggesting that the IO on the thermo gens be improved to this:

-  Basic: 12K fe/t (not anywhere close enough to match the power gen, at 64K fe/t, so it encourages moving up to the higher tiers, creating a natural fix to this issue: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/1737)
-  Hardened: 20K fe/t (^, same thing)
-  Blazing: 30K fe/t
-  Nitotic: 50K fe/t
-  Spirited: 80K fe/t
-  Nitro: 120K fe/t

### Why would you like this added/changed?

The powah thermo gens are weak, and in vanilla it's unrewarding to go for nitro. The IO on these is not a _limit_, the mekanism power cables set to "extract" with the configurator, on all four sides, give you 8x the default IO, allowing you to get the full power out of these machines. This means that this change is more for compactness, and QoL, than it is for balancing.

The reason this would be great is because it encourages the drive to Nitro. Nitro and starter produce relatively similar power outputs, despite the fact that Nitro is much more end game, and requires nether stars. The minor difference between these tiers makes for an underwhelming, non-rewarding, relatively useless usage of nether stars. This change would make nitro viable for a reason different than the simple "more power", which I think is a creative take on this problem.

This is also somewhat balanced still. In order to get these efficiencies, you need to get a constant source of ether gas, and a lot of Nitro crystals. These both require the mid-game, practically farming the wither and the 91K fe/t is still not too much, yet not too little, to be balanced. Also consider that it is not just one block producing the power here, it requires a block below it and a source of ether gas. All this combined makes for a minimum of 3 blocks just for the generator, and a bunch more for the actual setup of getting the nitro tiers. This all means 5+ blocks per generator, if you have a lot of generators, and that becomes 18K fe/t/block at maximum, which is still decently balanced.

**Comment by MuteTiefling** [comment]
Yeah seems like a good change.
