### ISSUE TITLE
Disable Automatic Recipe Unlock from Quark

### ISSUE THREAD

**Issue by Esteria** [EnigmaticaModpacks/Enigmatica6#4206]
### Modpack Version

0.5.25

### Describe your issue.

It makes lag like when you in water, or get cobble first time

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Setting it to false doesn't fix anything sadly, the lag comes from something else :/
