### ISSUE TITLE
[Expert] Make pink slime ball meltable in smeltery/magma crucible

### ISSUE THREAD

**Issue by Blewin** [EnigmaticaModpacks/Enigmatica6#4213]
### Describe your suggestion

Make pink slime ball meltable in smeltery/magma crucible to pink slime

### Why would you like this added/changed?

Pink slime ball is one of the outputs of industrious bee, and it looks rare, but has no special uses.

**Comment by MuteTiefling** [comment]
Been thinking about this for a bit and I'm not sure I want the slime ball to be turned back to liquid slime.

**Comment by Blewin** [comment]
In that case maybe consider giving industrious bee different output?  :)

(Awesome work on the pack, gave me countless hours of fun! with friends!)
