### ISSUE TITLE
Certain things need manual chunk-loading inside Compact Machine dimension

### ISSUE THREAD

**Issue by changhe3** [EnigmaticaModpacks/Enigmatica6#4214]
### Modpack Version

6.0.5.22

### Describe your issue.

Pure daisy won't convert blocks, and Industrial Foregoing won't build/kill Withers without manual chunk-loading.

### Have you modified the modpack?

Yes

### User Modifications

Added Mob Grinding Utils
Added Chlorine and removed Roadrunner

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.
Please update to 0.5.25 and remove Chlorine and let us know if the issue persists :)
