### ISSUE TITLE
Bacon sandwich and BLT crafting recipe conflict

### ISSUE THREAD

**Issue by Ricket** [EnigmaticaModpacks/Enigmatica6#4218]
### Modpack Version

0.5.25

### Describe your issue.

Bacon sandwich and BLT share the same (shapeless) recipe, so you can only craft a bacon sandwich, can't craft a BLT.

![image](https://user-images.githubusercontent.com/196978/153733147-e90d98ac-ae17-4e94-90b3-fa3ce495b797.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Rodg88** [comment]
There should be a polymorph option to select the output, maybe is disabled on that particular crafting table? 
![image](https://user-images.githubusercontent.com/2611674/153733347-7b09669c-b469-4da7-9646-bb5d867ae402.png)

**Comment by Ricket** [comment]
I checked both Oak Crafting Table (Minecraft) and Acacia Crafting Table (More Crafting Tables Mod) -- which exact crafting table are you seeing that button?

**Comment by Ricket** [comment]
Err, I see the 2x2 so I guess you're just in your inventory -- my inventory doesn't give me the option...

![image](https://user-images.githubusercontent.com/196978/153733377-6b8d09e9-6793-4671-b438-0ea6973c68ef.png)
