### ISSUE TITLE
[Expert] - Some way to get Nebu other than exploration

### ISSUE THREAD

**Issue by gruff8** [EnigmaticaModpacks/Enigmatica6#4221]
### Describe your suggestion

Since god shards are used in many recipes I would suggest having a way to get a steady supply of Nebu ore.
One idea would make a convoluted recipe in a sequence crafting using strange sand and nebu drop?

Nebu drop means that it needs to be found at least once naturally.
Strange sand can be automated using bees, but requiring a lot would means that it is not an auto infinite.
Maybe it can be a one strange sand and one pice of clay on a nebu drop, 32 times in sequenced crafting? Having two different items in sequenced crafting makes it more difficult to set up.

### Why would you like this added/changed?

I feel that I have spent too much time in atum trying to find Nebu, and the spawn rates are way too low.
You could also just make a more consistent spawn rate so people need to go mining there but currently you can spend 10 min mining and not find a single ore chunk...

**Comment by gruff8** [comment]
I didn't realise scanners were in the pack, thanks. 
I will see if that changes the quality if life. 
Maybe this needs to be hinted at in some quest...

I saw an issue mentioning the excavator but I can't see anything in JEI.

**Comment by RobuxShooters** [comment]
> I didn't realise scanners were in the pack, thanks. I will see if that changes the quality of life. Maybe this needs to be hinted at in some quest...
> 
> I saw an issue mentioning the excavator but I can't see anything in JEI.

Yeah you won't find anything about the excavator in JEI, but you can find it in the IE manual. I forgot the exact term to search for but I think it's something along the lines of 'Mineral Nodes' or 'Mineral Deposits'.

**Comment by TemperedFool** [comment]
You can also order useful packs of stuff via Armadron, including a mineral survey from Atum that will include a lot of Nebu ore. It makes a nice intermediate stop between hand mining and Excavator.

**Comment by MuteTiefling** [comment]
Current ways to get Nebu:
1. Mining (includes Create based quarries early on, or the Builder later) 
2. IE Excavator (called out in the manual)
3. Pneumaticcraft Drone Surveys through Amadron (called out in quests)

Ways to stretch your Nebu:
1. Use Dusty Mummbee Honeycomb in place of 2 Nebu and one Godshard (discoverable in JEI)

I might consider lowering the Nebu cost for summoning pharaohs too, if you wanted to automate that ritual. And a little more pointing towards options could be in order. But overall I think you've got the means of production well in hand.

**Comment by TemperedFool** [comment]
@gruff8 I would highly recommend Create crushing wheels & ore washing; it's not THE BEST scaling in the pack but will produce a lot of metal from your ores.

**Comment by gruff8** [comment]
Yeah, I have a pulveriser and furnace setup for x2 ore processing, rather than the x2.15 (I think) from create more because of lazyness than anything else. The scanner though has solved my issue in this case. Now to investigate the excavator stuff in IF.

**Comment by TemperedFool** [comment]
Fwiw @gruff8 once you add in ore washing Create is better than 3x. Worth looking into imo.

**Comment by gruff8** [comment]
Didn't see it was 2x60% on the crushing. Probably worth setting up. 👍

**Comment by MuteTiefling** [comment]
Pharaoh's nebu cost is now reduced, making it another reduced cost rout to godshards. And a few quests have been updated to gently prod the player into checking out Amadron as it's not as discoverable through JEI.
