### ISSUE TITLE
Quark Runes

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4222]
### Describe your suggestion

Currently you need various quark runs for things like the lenses. This means that you either get lucky with blank runes have each corundum colour growing or take forever with starlight. I would suggest Having some way to split the rainbow rune into its components so that runes can be renewably farmed from the rgbee.

### Why would you like this added/changed?

Would make expert crafting a little easier and give more incentive for the bees.

**Comment by MuteTiefling** [comment]
I'll take a look at some options here. Understand that bees are already a very powerful source of raw materials, however, and I don't want them to be a one stop shop. I'd rather that players have a reason to explore other mechanics.

**Comment by MuteTiefling** [comment]
I've created a way to recycle these. It's a multi step process, but it should help make the Rainbow runes a touch more useful. Do note that many of the existing recipes accept _any_ rune, so they were already useful for those.
