### ISSUE TITLE
[Expert] Possibly changing Create belt recipe

### ISSUE THREAD

**Issue by SaturdayHS** [EnigmaticaModpacks/Enigmatica6#4225]
### Describe your suggestion

This idea is inspired from the belt recipe from Create Above and Beyond where they used Cured Rubber from Thermal instead of the default recipe using Kelp. Maybe have the same amount of Kelp but put it through a Redstone Furnace or a furnace that requires power? Or a Create Press recipe with a heated Basin? 
I also don't want to have belts be gated behind Thermal or other mods that have plastic. 
What are your thoughts on this?

### Why would you like this added/changed?

I'd like this to be changed because when I think of a conveyor belt, I think of it being made of plastic not of kelp.

Snippet from Wikipedia:
The belt consists of one or more layers of material. It is common for belts to have three layers: a top cover, a carcass and a bottom cover. The purpose of the carcass is to provide linear strength and shape. The carcass is often a woven or metal fabric having a warp & weft. The warp refers to longitudinal cords whose characteristics of resistance and elasticity define the running properties of the belt. The weft represents the whole set of transversal cables allowing to the belt specific resistance against cuts, tears and impacts and at the same time high flexibility. The most common carcass materials are steel, nylon, polyester, cotton, and Aramid (class of heat-resistant and strong synthetic fibers, with Twaron or Kevlar as brand names). The covers are usually various rubber or plastic compounds specified by use of the belt.

**Comment by MuteTiefling** [comment]
With create being an entry level mod here, there's not much room for other materials. Certainly not rubber.

**Comment by SaturdayHS** [comment]
Appreciate the response.

Would it make sense to change the recipe to look like this for 2 belts? It wouldn't be too difficult to get string and iron since using rubber or plastic won't make much sense for the early game.

XXX
YZY
XXX

X - Kelp
Y - String or Hemp
Z - Iron
