### ISSUE TITLE
Create Gears

### ISSUE THREAD

**Issue by SirArlen** [EnigmaticaModpacks/Enigmatica6#4229]
### Describe your suggestion

https://www.curseforge.com/minecraft/mc-mods/create-gears
https://www.curseforge.com/minecraft/mc-mods/create-deco

### Why would you like this added/changed?

Both mod are small additions to Create, with Create Deco adding more brick types for steampunk builds and synergize well with IE and Dustrial Decor while Create Gears addd QoL changes to Create for more compact contraptions

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by FrederikRasmussen** [comment]
I very much like the look of Create Gears, they include features I use all the time in my current Create builds, but just prettier. As a fellow player, I'd be happy to see it added.

**Comment by NillerMedDild** [comment]
Create Gear yes, Create Deco no - We can't really "afford" adding that many blocks that look very similar.

**Comment by Quezler** [comment]
if it breaks it'll stay broken 👀 
<img width="585" alt="Screen Shot 2022-03-07 at 15 06 24" src="https://user-images.githubusercontent.com/3179271/157049478-36925b30-4df0-4839-b2b6-cc915a6b313b.png">
