### ISSUE TITLE
crash when forming Immersive Engineering multiblocks

### ISSUE THREAD

**Issue by Toonlink264** [EnigmaticaModpacks/Enigmatica6#4232]
### Modpack Version

Dev branch

### Describe your issue.

i tried to make the IE kiln and the game crashed

### Crash Report

https://paste.ee/p/48izy

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
likely unrelated. just try again

**Comment by Toonlink264** [comment]
it was formed when i loaded back in, but it's the second time it's crashed on me when forming
