### ISSUE TITLE
Chicken Chunks

### ISSUE THREAD

**Issue by CameronWDMorgan** [EnigmaticaModpacks/Enigmatica6#4237]
### URL

https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8

### Why would you like the mod added?

(checked the issues and doesn't seem to have been requested)
I am wanting this mod to be added cause currently the way of keeping chunks loaded with the FTB Chunks claiming thing doesn't work in some instances, for example: I have a enderman farm using a spawner and a spawner agitator, for some reason when not in render distance the farm does not function even when the chunks are set to be forced to load within FTB Utilities. Being able to define an area where I would like chunks to be loaded with chicken chunks would be appreciated, as the FTB utils chunk loading is flakey at best.

**Comment by NillerMedDild** [comment]
If FTB chunks chunkloading is broken then we need to fix that, I won't add another chunkloader mod, chunkload management on servers is hard enough as it is :P

**Comment by NillerMedDild** [comment]
@MaxNeedsSnacks have you guys had any reports of chunkloading breaking on 1.16.5 recently? 😅

**Comment by CameronWDMorgan** [comment]
I only made a suggestion rather than a bug report cause I have no clue why it isnt working as intended (or what i think to be as intended)

**Comment by MaxNeedsSnacks** [comment]
> @MaxNeedsSnacks have you guys had any reports of chunkloading breaking on 1.16.5 recently? sweat_smile

I remember Lat saying his force chunk loading wasn't working properly on *some* version, but I'm not sure whether that applied to the 1.16 versions as well or just 1.18

**Comment by NillerMedDild** [comment]
Oh boy, sounds like we need to investigate further 😳
