### ISSUE TITLE
Immersive Engineering Wire Cutter Crafting Glitch

### ISSUE THREAD

**Issue by Oofthe3rd** [EnigmaticaModpacks/Enigmatica6#4238]
### Modpack Version

0.5.14

### Describe your issue.

When the Engineer's Wire Cutters from Immersive Engineering are lower than max durability, I can't craft any wires with them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
This bug was fixed a good while ago, please update :)
