### ISSUE TITLE
MM Advance Assembly Table

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4239]
### Modpack Version

Dev

### Describe your issue.

Trying to construct the advanced assembly table and can't get it to work by default. The recipe calls for immersive engineering blocks of steel to construct it but it seems like I can't find a way to get them with the Emandatus enigmatica version in instead. Jumping to creative to give myself the correct blocks forms the machine so it is otherwise correct.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
You should be able to get them through the stonecutter from any type of steel block :)

**Comment by Kevin-Marsh** [comment]
That works, thanks for the heads up. Now I am just playing around with it to try to figure out how it works.
