### ISSUE TITLE
[Expert] Lightning Arrows need more availability

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4242]
### Describe your suggestion

The lightning arrow should be available through doing more then just surrounding a lightning charge with arrows or from fletchers in my opinion for expert. Could there be a lightning interaction or an alchemical array for getting lightning arrows too? 

### Why would you like this added/changed?

Because terraforged unless you get VERY LUCKY, does not spawn you anywhere near a hot biome, and we'll end up with many more arrows beforehand. Exploration required, but for the convenience of home.

**Comment by TemperedFool** [comment]
If the concern is for early game, there are tons of them available via exploration - I've never crafted one and am well into the mid game, closing on late. You can also use charged snowballs and lightning charges for crafting 😉

**Comment by MuteTiefling** [comment]
Charged snowballs are the intended "I don't feel like exploring" recipe. You can get everything you need for them near home no matter where you settle.

Lightning arrows are your ticket to automation, and therefore require a bit more effort to set up. Either go or and find blizz, or wait til you can summon them with the altar of birthing.

Of course, you could also automate with snowballs if you're intent on it. Just requires teching up to routers to automate throwing them as opposed to a simple dispenser for the arrows.
