### ISSUE TITLE
Typo in quest book

### ISSUE THREAD

**Issue by aurumvorax** [EnigmaticaModpacks/Enigmatica6#4246]
### Modpack Version

dev branch, commit  bde5f89ad236dc65b1db7384501d6750b9f443df

### Describe your issue.

In the new "Automation" chapter, there is a typo in the "2x Redstone Module" quest description - "differnt"

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks!
