### ISSUE TITLE
Cannot place anything into Integrated Dynamics squeezer in normal mode

### ISSUE THREAD

**Issue by Null-14** [EnigmaticaModpacks/Enigmatica6#4249]
### Modpack Version

0.5.25

### Describe your issue.

I cannot put anything into the integrated dynamics squeezer in the standard Enigmatica 6 modpack. This includes menril logs.

### Have you modified the modpack?

Yes

### User Modifications

Dynamic Surroundings is the sole addition.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Do you happen have a Dank in your hotbar?

**Comment by Null-14** [comment]
Yes, but the Dank was configured to void, and did not contain any logs of any kind, only cobble and other stones.

**Comment by NillerMedDild** [comment]
Remove it from your hotbar and all should be well 👌 known issue, has been reported :)

**Comment by Null-14** [comment]
Ah, thank you.
