### ISSUE TITLE
[Expert] Mastery Token Textures are broken

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4251]
### Modpack Version

0.5.25, second most recent development branch update

### Describe your issue.

Testing expert mode, and the mastery token images are broken for when I look them up in JEI. If they are placeable, I do not know if they are broken that way too. I don't see the images in the kubejs model/texture folder. 

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

Yes

### User Modifications

metalbarrels-3.3a.jar
hexblades-1.16.5-0.0.9.3.jar
Babel-1.0.5.jar
bagofyurting-1.16.4-1.2.0.1.jar
interactive_corporea-1.2.jar
forbidden_arcanus-16.2.2.jar
EvilCraft-1.16.5-1.1.12.jar
eidolonrecipes-1.16.5-1.0.jar
configswapper-2.5.jar
turtlemancy-1.16.5-1.6.3.jar
tomeofblood-1.16.5-1.2.3.jar
smarterfarmers-1.16.5-1.2.1.jar
nolakes-0.1-1.16.4.jar.disabled
MythicBotany-1.16.5-1.4.19.jar
NaturesAura-34.3.jar
geckolib-forge-1.16.5-3.0.65.jar
MushroomQuest_1.16.5_v3.2.jar
ars_nouveau-1.16.5-1.24.16.jar
jei-professions-1.0.0-1.16.4.jar
DeLogger-3.0.4-build.20+mc1.16.5.jar
Druidcraft-1.16.5-0.4.54.jar
Modest+Roses+1.2.3+-+Forge+1.16.5.jar
autumnity-1.16.5-2.1.2.jar
betteranimals-1.16.4-5.5.0.jar
cherishedworlds-forge-1.16.5-5.1.1.0.jar
seasonals-1.16.5-2.0.0.jar
neapolitan-1.16.5-2.1.0.jar
Lollipop-1.16.5-3.2.9.jar
LostTrinkets-1.16.5-0.1.27.jar
serverconfigupdater-1.3.jar
TravelersTitles-1.16.4-1.5.jar
abyg-1.2-forge.jar
Paxi-Forge-1.16.4-1.0.jar
Buddycards-1.16.5-2.5.2.jar
BetterDungeons-1.16.4-1.2.1.jar
creeperconfetti-3.7.jar
ExplorersCompass-1.16.5-1.1.2-forge.jar
Notes-1.16.5-1.2.3.jar
NekosEnchantedBooks-1.16-1.4.0.jar
playerex-1.1.8-1.16.5.jar
relicex-1.0.0-1.16.4.jar
NaturesStarlight-1.1.22.jar
EnigmaticLegacy-2.11.11.jar
ArcaneFundamentals-alpha-9.jar
SpawnerFix-1.16.2-1.0.0.2.jar
no-nitwits-1.16.4-1.0.0.jar
weirdinggadget-1.16.(2-4)-2.2.7.jar
betteranimalsplus-1.16.5-11.0.0-forge.jar.disabled
whisperwoods-1.16.5-2.0.2.jar.disabled
endrem_forge-5.0.1-R-1.16.5.jar
mana-and-artifice-1.5.1.6.jar
ExtraBotany-r1.2-68.jar
BetterStrongholds-1.16.4-1.2.1.jar
upstream-1.0.jar
MmmMmmMmmMmm-1.16.5-1.3.1.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
blue_skies-1.16.5-1.1.3.jar
campfiretorches-1.16.3-1.0.3.jar
farmersdelightintegrations-1.16.5-1.2.jar
farmerstea-1.16.5-1.3.jar
simplytea-1.16.5-2.4.0.jar
tea_kettle-1.16.5-0.4.0.0.jar
beenfo-1.16.4-forge35.0.7-1.2.jar
wandering_trapper-1.16.5-0.1.2.jar
PackingTape-1.16.5-0.10.1.jar

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
Not broken... Expert is still in development, the textures for these have not been made yet...

Also, good gravy your added mods is longer than our already crazy long modlist oO
