### ISSUE TITLE
Make Seaweed exchangable for Kelp

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4258]
### Describe your suggestion

I’ve noticed there is a loss on nori sheets when crafting them for the mod, but I’m sure that’s more of a ‘file this with sushi go crafting’s github then the modpack. 
Secondly, the amount of seaweed is excessively spawning. Any chance to turn it down? 
Please and thank you. 

### Why would you like this added/changed?

Too much seaweed, and losing about 30-40% of my nori sheets doesn’t make me willing to make ‘non gas station sushi’ as the discordians put it.

**Comment by NillerMedDild** [comment]
I'll look into making Seaweed and it's byproducts be usable in Kelp recipes though
