### ISSUE TITLE
Pink wither milking

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4259]
### Modpack Version

Dev

### Describe your issue.

It appears that milking a pink wither doesn't work at y heights above 100. Regular ether gas production sets the max height at 256 so that you can produce it anywhere within the correct biome. Is it possible to increase the fluid laser pink slime recipe to 256 as well?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed in-dev, thanks for the report :)
