### ISSUE TITLE
A Buzzing Source of Nautilus [expert]

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4262]
### Describe your suggestion

Water bees can create kelp and such with their water combs. Why not nautilus shells when crafted with another type of comb? 

### Why would you like this added/changed?

Warm oceans are not a consistently easy biome to find, culling nautilus mobs isn't a lot of fun initially, fishing is slow, hunting for embedded ammonite is annoying and Zephyr's finding stupid reasons to complain at 3am. 
And if bees make the life easier, how about a way to get them through bees. 
Please and thank you for the time of thought.

**Comment by NillerMedDild** [comment]
I think this is a pretty good idea, earlier incentive to get bees going would be good, I think.
Thoughts @MuteTiefling @TemperedFool ?

**Comment by TemperedFool** [comment]
I didn't personally have THAT much trouble in my run, but I get that it can be frustrating.

@MuteTiefling maybe some sort of craft involving combs and some other ingredients, if at all? Make it annoying enough that grabbing a nautilus for your drygmy is preferable once you can?

**Comment by MuteTiefling** [comment]
I really don't want to turn bees into the default answer for everything.

I already had a note to look at deals to see if the van be made more reliable for getting the shells. Otherwise they could turn up other places. Like guardian drops, or those pvj shells on the ground.

**Comment by NillerMedDild** [comment]
Fair enough, your other ideas sound good 👍

**Comment by Hjaldar** [comment]
Drowned also having a small chance of spawning holding a nautilus shell and there are plenty of drowned spawners in the oceans.
