### ISSUE TITLE
Change '$storage/bags' in storage quest to '$storage/bag' and potentially add more items to the tag

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#4264]
### Describe your suggestion

The storage quest (in the 'storage' chapter) says
 'Note: Most blocks that are useful as a storage block have been Tagged for search in JEI. Search for the following categories:
[...]
$storage/bags
[...]'
Searching for $storage/bags however yields no results. $storage/bag does, matching the forge:storage/bag tag which some items have, so I'm assuming that might have been the intended tag to search for.

Additionally I'd like to suggest considering adding the tag to some of these items: 
- The thermal satchel (thermal:satchel) 
- Substantial satchel (occultism:satchel)
- Create toolboxes (potentially?)
- Tetra's toolbelt (tetra:modular_toolbelt)
- RFTools tablets
- Mekanism's personal chest

Some of these might not fit (create toolboxes aren't quite 'bags', neither are tablets), I just went with some stuff I find fits a similar 'portable storage' niche that somebody searching for portable storage solutions might be interested in knowing about. 

### Why would you like this added/changed?

It's one of those little lovely quality of life features. The quest probably meant to say '$storage/bag', and I feel like more items could benefit from having this tag, so that people consider options they might otherwise not be aware of.

**Comment by MuteTiefling** [comment]
Thanks! All fixed up in dev now.
