### ISSUE TITLE
[expert] The Ars Nouveau quests for the enchanting apparatus and the crystallizer should be switched around for progression, since the crystallizer is made on the apparatus. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4265]
### Describe your suggestion

What it says on the title. The Ars Nouveau quests for the enchanting apparatus and the crystallizer should be switched around for progression, since the crystallizer is made on the apparatus in expert mode, and slightly gates the quests to open up the ars nouveau chapter of the questbook. 

### Why would you like this added/changed?

fixes progression.

**Comment by MuteTiefling** [comment]
Should be better now. :D
