### ISSUE TITLE
No drops after update

### ISSUE THREAD

**Issue by gruff8** [EnigmaticaModpacks/Enigmatica6#4270]
### Modpack Version

commit 6079c68eab62144440bce8c9ed507ca387dfdc33

### Describe your issue.

Since updating I have no drops.
Neither manually breaking blocks, mob drops, or auto cobblegen (create).

I hesitate making this bug report as I feel it is potentially on my end, but all I did was git pull the latest dev branch.

Also, I posted a commit ID instead of a version number in the bug report, is there a good way to get the version number instead?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
There is a known bug with a trinket or something that revives you, which will cause items to no longer drop after activating.

**Comment by novaexe** [comment]
na moto broke stuff, it's fixed now repull the update

**Comment by Darkere** [comment]
The commit he linked is 30 days old.

**Comment by novaexe** [comment]
ah helps to read the fine print, sry the timing with what just happened was soo perfect lol

**Comment by gruff8** [comment]
> There is a known bug with a trinket or something that revives you, which will cause items to no longer drop after activating.

I have experienced this one, but it tends to only happen once the token getes triggered.
I keep it active but am just aware of it and prefer the reset after trigger than a corspe run...

> The commit he linked is 30 days old.

sorry, for some reason I pasted the master branch katest commit rather than the dev branch, so yes wrong commit was linked... my bad.

**Comment by gruff8** [comment]
> na moto broke stuff, it's fixed now. repull the update

Just repulled.
old commit: 76b599aeba87ee65502ccb33dcdad44b39e0a976 
new commit: 4e8660d128e18f6a28a10a1f639c7d5c6e3b53b5 

now I get drops. Thanks for the quick fix.
