### ISSUE TITLE
[Expert] Eidolon's Hexblades

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4271]
### URL

https://www.curseforge.com/minecraft/mc-mods/eidolons-hexblades

### Why would you like the mod added?

A combat oriented addon for Eidolon, that has some neat weaponry, some mod compatibility and an urn that fills all open placed entities with water. 

Expert would need to fix some of their recipes because it does use the crucible some.

**Comment by NillerMedDild** [comment]
I don't want to add an addon to a mod that isn't receiving updates :)
