### ISSUE TITLE
[expert] Quality of life: Otherstone support for stonecutter

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4274]
### Describe your suggestion

In early game, the arcane stone for occultism otherstone is very expensive, and slabs especially. Would it be possible to add support for making otherstone slabs for the stonecutter? 

### Why would you like this added/changed?

Quality of life, and I had 8 otherstone when I made my first six blood magic slates.

**Comment by MuteTiefling** [comment]
This would conflict with the sawing recipe of `Otherstone > Blank Plates` since stonecutting recipes are automatically registered on the Create saw. 

Will have to think about how I'd want this to work.

**Comment by MuteTiefling** [comment]
Alright, re-worked things a bit to make this happen.
