### ISSUE TITLE
Progression Impossible

### ISSUE THREAD

**Issue by aurumvorax** [EnigmaticaModpacks/Enigmatica6#4281]
### Modpack Version

Dev - 01c4b0e1e1f2a1794b25e9c2f0089b484c877720

### Describe your issue.

Wicked Weave is required to make the alchemy table.  Wicked Weave requires a Shadow gem, which can only be made on the alchemy table.  There used to be a Shadow Gem recipe that used the crucible, I suspect it just got missed when moving crucible recipes to the cooking pot.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks, I'll get that fixed up

**Comment by MuteTiefling** [comment]
fixed in dev, please update.
