### ISSUE TITLE
Sophisticated Backs and Equipment Compare Incompatibility 

### ISSUE THREAD

**Issue by DaddySpin** [EnigmaticaModpacks/Enigmatica6#4282]
### Modpack Version

0.5.25

### Describe your issue.

I would recommend adding Sophisticated Backpacks to the blacklist for Equipment Compare.

Without Blacklisting:
![2022-02-23_01 02 41](https://user-images.githubusercontent.com/34575655/155274244-73457cf6-84b0-4007-baba-93dcd18327b4.png)

With Blacklisting:
![2022-02-23_00 52 39](https://user-images.githubusercontent.com/34575655/155273650-4c6e181f-a139-4f3f-bb32-eac0e70d8811.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
#4105
