### ISSUE TITLE
Add Game Menu Mod Options

### ISSUE THREAD

**Issue by Pysis868** [EnigmaticaModpacks/Enigmatica6#4287]
### Modpack Version

0.5.25

### Describe your issue.

Used it with other modpacks.  Like is present on the main menu.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by tuca1234567890** [comment]
That's not a bug, Forge 1.16.5 doesn't show the Mod Options button in-game. There's a mod for it though: https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption

**Comment by NillerMedDild** [comment]
Time to add another mod 😄

**Comment by Pysis868** [comment]
@tuca1234567890 It's a bug from consistency by expectation.
