### ISSUE TITLE
Add a quest-step for attunement (Astral Sorcery Questline)

### ISSUE THREAD

**Issue by bunton002** [EnigmaticaModpacks/Enigmatica6#4291]
### Describe your suggestion

I'd like there to be a quest, or a quest step that tells you to be attuned somewhere in the Astral Sorcery questline, as it is required to get any of the constellations beyond the 5 Bright Constellations.

### Why would you like this added/changed?

The only in-game paragraph is hidden in the Attunement Altar entry of the Astral Sorcery Book, at the very end.
As such people like me, who followed the questbook to progress in Astral Sorcery, but weren't completionists, would never know about this beeing a requirement for learning the dimmer Constellations.
That's why I'd like it a lot if that was added to the quests.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion!
