### ISSUE TITLE
[expert] Nature Aura - Ender Crate recipe seem alittle bit too easy 

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4297]
### URL

https://www.curseforge.com/minecraft/modpacks/enigmatica6

### Why would you like the mod added?

![image](https://user-images.githubusercontent.com/74948675/155884374-40891dde-f3ac-495c-8f5d-4e2930b27ef2.png)
sorry,for my english.
In expert mode , all wireless item trasportation seem likely to use  Botania Corperea spark as core in recipe but this Ender Crate is not .
So it seem not silmilar with other type of wireless item trasportation like ender chest 
and by recipe is just obsidian ,eye of ender , and air in Undergarden

**Comment by MuteTiefling** [comment]
Leaving it cheap was an intentional choice since it has a cost for transportation.

I could see making the recipe a little more thematic, but I'd still want it early

**Comment by TemperedFool** [comment]
Corporea sparks are pretty early - does seem like a thematic change. I'd also rather make those than Eye of Enders early...

**Comment by AlphaP2712** [comment]
Oh ,Understandable, Thank you for attention.
