### ISSUE TITLE
[Mod Suggestion] Beyond Earth

### ISSUE THREAD

**Issue by CheetahCyberBoi** [EnigmaticaModpacks/Enigmatica6#4298]
### URL

https://www.curseforge.com/minecraft/mc-mods/beyond-earth

### Why would you like the mod added?

It is a great space mod and has a easy to follow and integrateable progression system. It ties well with other mods.

**Comment by MuteTiefling** [comment]
this looks like a complete ripoff of galacticraft, and I'm pretty sure their license doesn't allow it

**Comment by NillerMedDild** [comment]
Galacticraft's license seems to allow it as far as I can see, it's a bit rough on the eyes though so I might be wrong 😅 
That being said, I don't want to add Beyond Earth, it's not worth integrating at this time imo.

**Comment by CheetahCyberBoi** [comment]
OK I'll close it then.
