### ISSUE TITLE
Entities Disappearing 

### ISSUE THREAD

**Issue by DanJ-B** [EnigmaticaModpacks/Enigmatica6#4301]
### Modpack Version

0.5.26

### Describe your issue.

entities do not drop and disappear when dropped either by players or mobs after the server has been running for a while

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
does your server happen to have keepinventory=true gamerule set?

**Comment by NillerMedDild** [comment]
Fixed in-dev :)
