### ISSUE TITLE
Blocks do not drop after player death.

### ISSUE THREAD

**Issue by OlivierHogue** [EnigmaticaModpacks/Enigmatica6#4304]
### Modpack Version

0.5.26

### Describe your issue.

After I die, the blocks are no longer being dropped. It affects the quests rewards and the mining gadget.
I use keepInventory = true, however even without it, as soon as I die, the problem returns. Each time I have to either : 
- Change the keepInventory value, die another time and then the drop are working again.
or
- Completely close the instance, then start it again.

I do not know why it is doing so, however it is since this version (0.5.26).
It seems like it is linked to the player death.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
reported to enigmatic graves tracker here: https://github.com/Quarris/EnigmaticGraves/issues/34

**Comment by OlivierHogue** [comment]
I can confirm that after removing Enigmatic Graves, it solves the issue completely.
