### ISSUE TITLE
[expert] Remove / Change  NBT Tag "minecraft:planks" in Polished wood plank

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4306]
### Describe your suggestion

Remove / Change  NBT Tag "minecraft:planks" in Polished wood plank form eidolon in expert

### Why would you like this added/changed?

![image](https://user-images.githubusercontent.com/74948675/156015679-7c8ec6f0-d2d2-4d48-8bbd-fcdb79f6e0c8.png)
Polished wood plank form eidolon is expensive than normal plank .
it use in some of expert recipe such as Dreamwood , Brass caseing etc.
But because of tag "minecraft:planks" all of automatic crafting that request any planks use it like normal plank . so it waste of resource (that some time you don't notice)
I'm not sure that have any filter in refined stroage that can use like "any plank but not this",that I can use.

**Comment by NillerMedDild** [comment]
Makes good sense, sure thing :)
