### ISSUE TITLE
Deep Resonance

### ISSUE THREAD

**Issue by castilio20** [EnigmaticaModpacks/Enigmatica6#4307]
### URL

https://www.curseforge.com/minecraft/mc-mods/deep-resonance

### Why would you like the mod added?

interesting mod with radiaton and a little more complex  power gen for ealry and late game

**Comment by NillerMedDild** [comment]
It's too late in E6s life cycle to add a mod like this, plus I'm kinda afraid it'll remain bug riddled on 1.16.5 :P

**Comment by castilio20** [comment]
then what about enigmatica 8? this mod is out for 1.18

**Comment by NillerMedDild** [comment]
Sure why not :P
