### ISSUE TITLE
Journeymap integrations block ftb chunks minimap and chunk claims map shows first

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4308]
### Describe your suggestion

Suggestion to disable the chunk claims map of ftb chunks map showing first and the disabling of the ftb chunks minimap, as that shows bees much better, and I was extremely confused on why. 

### Why would you like this added/changed?

Give the people back their choice of minimap?

**Comment by NillerMedDild** [comment]
Sure thing, the switcheroo has been disabled by default 😄 
However it will not update unless the player removes `config/jmi-client.toml` or is on a fresh instance :)
