### ISSUE TITLE
(Linux) Add server files zip in releases tab of github

### ISSUE THREAD

**Issue by JoaGamo** [EnigmaticaModpacks/Enigmatica6#4311]
### Describe your suggestion

As an option to curseforge, add the server files in the releases page too. It would help cut off 4-6~ minutes by simply using wget githublink instead of following complicated steps for downloading from curseforge in a linux terminal.
The steps I've been following for downloads were: download another browser that I dont use on my main PC, firefox, go into the curseforge e6 server files, start download, cancel, get link, then paste that link into my server's terminal, then configuring.

### Why would you like this added/changed?

By adding the server files directly into github as a zip/tar, the command wget (and variations) on linux environments will get the files faster and will not depend on another computer/vm to get the correct working link.

**Comment by theboo** [comment]
We do have these server automation scripts and instructions for use! .sh scripts are included
 https://github.com/EnigmaticaModpacks/Enigmatica6#server-automation

**Comment by JoaGamo** [comment]
Oh my I thought the zip files were only for client and the wiki wasnt updated (I didnt knew where to search for an "automation folder")
Thanks!
