### ISSUE TITLE
The one probe mod crashing game

### ISSUE THREAD

**Issue by DrGrim200** [EnigmaticaModpacks/Enigmatica6#4324]
### Modpack Version

1.16.5

### Describe your issue.

Whenever I try to open the config file in the main menu for The one probe mod it crashes the game, I even tried a different version of the mod for 1.16.5 but it did the same thing.. Is there a way to fix this right now or no??

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Please supply the crash report :)

**Comment by DrGrim200** [comment]
I never got a crash report is the thing..it just kinda, crashed after it
froze for a few seconds..I apologize for that..I can try to tweak it a bit
later myself to see if I can fix it and if I can I will let you know :)
