### ISSUE TITLE
E6E Wixie charm

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4326]
### Modpack Version

Dev

### Describe your issue.

I can't seem to make the Wixie charm using the new recipe. I am using the 4 arcane gold nuggets, electrum coin, brewing stand, twisted sapling and wixie shards but it states that there is no recipe found.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Why did you close the issue? :)

**Comment by MuteTiefling** [comment]
Looks like they resolved this on discord with buuz.

They had an extra pedestal close to the enchanting apparatus, so it wasn't seeing the recipe correctly.
