### ISSUE TITLE
No map on minimap

### ISSUE THREAD

**Issue by xILikepuddingx** [EnigmaticaModpacks/Enigmatica6#4327]
### Modpack Version

0.5.26

### Describe your issue.

Hello,

I have already described this problem on Discord but no one could really help me.

it's about the fact that the journeymap minimap 1 and 2 shows nothing of the map (animals, monsters, etc are displayed normally).
https://i.imgur.com/rZpCddz.png
The fullscreen map itself is displayed but does not load properly and if the map is deleted via the button, no new one is generated.
https://i.imgur.com/8nIuFkM.png
If you delete the world on the server and then create a new one, the old map is displayed.

the problem seems to be only on server. in singeplayer the map works fine.

everything is default. I have not changed anything

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report.

Is it possible that you accidentally put the map in cave mode?
