### ISSUE TITLE
Amadron Mineral Survey

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4331]
### Describe your suggestion

At the moment the Amadron surveys return a renamed chest. This is good for keeping it sorted out but problematic if you wanted to craft a bunch of surveys through RS to be able to semi automate the surveys. Would it be possible to add a recipe where you place these chests in the crafting grid and receive a blank chest in return?

### Why would you like this added/changed?

Make it easier to use Amadron surveys

**Comment by MuteTiefling** [comment]
The problem with any recipe to clear the name would be that you'd also void any items stored in it. 

I'll give it a think and see what will work best here.

**Comment by Darkere** [comment]
I'm not sure why you would want a blank chest? I think it makes more sense to automate with the name chest?

**Comment by MuteTiefling** [comment]
I think Darkere's right on this. Just set your recipe to re-use the named chest. Shouldn't be much of an issue.
