### ISSUE TITLE
Add Storage Parts to Advanced assembly table.

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4333]
### Describe your suggestion

At the moment only the base crafting components are available for the advanced assembly table. I am suggesting that you add the storage parts in too since it is an extremely long craft at the higher levels for RS.

### Why would you like this added/changed?

Save time making large disks.

**Comment by MuteTiefling** [comment]
well, it's a ton of extra items in JEI, but it wasn't too bad to do.
