### ISSUE TITLE
Add Induction smelter recipes to arc furnace E6E

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4337]
### Describe your suggestion

I am suggesting to add the remaining recipes from the induction smelter into the arc furnace. At the moment most of the recipes are directly swappable between the smelter and the arc furnace. There are some that are still limited such as the glass (Hardened, signalum, lumien, and enderium) and the metals (Signalum, lumien, enderium) added by thermal. 

### Why would you like this added/changed?

This change would mean that the arc furnace would be a complete drop in replacement for the smelter which will allow faster bulk creation of these alloys in the late game for crafting some of the larger recipes.

**Comment by NillerMedDild** [comment]
I'm kinda torn here, because I want the Arc Furnace to be the very best, but I also want people to feel their early infrastructure is useful in the mid-lategame.

**Comment by NillerMedDild** [comment]
I don't want this, sorry 😄
