### ISSUE TITLE
Show item icons the enchanment can be applied to in the tooltip of enchanted books

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4345]
### URL

https://www.curseforge.com/minecraft/mc-mods/better-enchanted-books

### Why would you like the mod added?

when you have large quantities of books or are looking through jei it would make it easier to see what it can be used on:
![feature_showcase_tooltip_icons](https://user-images.githubusercontent.com/3179271/156899979-b8f9266c-7abf-4750-bf88-0266e8c4c21c.png)
(the row above `minecraft:enchanted_book`)

**Comment by NillerMedDild** [comment]
Hmm.. Can the enchant sorting be disabled? I can imagine it does not play nice with disenchanting.
