### ISSUE TITLE
Explorer's Compass, the nature's compass' web across the realms to find the structures blind to your eyes. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4346]
### URL

https://www.curseforge.com/minecraft/mc-mods/explorers-compass

### Why would you like the mod added?

Some structures prove difficult to find across this land of terraforged expanse. This mod solves that. Sister mod to Nature's Compass, which is already in. Works for all modded structures, according to the tin.

**Comment by NillerMedDild** [comment]
I think this ruins the exploration aspect of adventuring tbh, no thanks :)
