### ISSUE TITLE
Filling out the Abnormals mod choices (and my pantry)

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4347]
### URL

https://www.curseforge.com/minecraft/mc-mods/autumnity https://www.curseforge.com/minecraft/mc-mods/berry-good https://www.curseforge.com/minecraft/mc-mods/seasonals https://www.curseforge.com/minecraft/mc-mods/neapolitan https://www.curseforge.com/minecraft/mc-mods/farmers-delight-compats https://www.curseforge.com/minecraft/mc-mods/simply-tea https://www.curseforge.com/minecraft/mc-mods/farmers-tea 

### Why would you like the mod added?

I'm aware that autumnity was on the yeet list for 0.5.0+, but a majority of the mods from the Abnormals team are still here. Would it match again?
Autumnity; lovely autumn themed mod with lovely foods to boot
Neapolitan: MILKSHAKES. Needs to turn down the generation of banana trees, they are literally everywhere. Thank you terraforged and your great amount of tropics. 
Seasonals: Take the above two, and give them compatibility. Pumpkin milkshakes!
berry good: sweet berry pips. No more accidentally planting berries while eating them. 
Farmers delight compats: Compatibility with the abnormals mods and a handful of others! 
Simply tea and farmer's tea: tea in minecraft. Who needs coffee. Pfft. (I am writing this at 4am, so... TEA!!!!) please.

**Comment by MuteTiefling** [comment]
Wouldn't mind the tea one, but Autumnity and Seasonals were just a lot of bloat (and I vaguely remember world gen issues tied to them). Neapolitin is similarly mostly bloat.

**Comment by NillerMedDild** [comment]
No to them all, sorry.
