### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by AhmedEhabAmer** [EnigmaticaModpacks/Enigmatica6#4348]
### URL

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

**Comment by Quezler** [comment]
duplicate, please close & search the other closed issues for the reasons it was rejected for this pack :)

**Comment by AhmedEhabAmer** [comment]
very sad :( applied energetics the best mod for auto craft, please if you can fix the issue add it ASAP :)

**Comment by TemperedFool** [comment]
> very sad :( applied energetics the best mod for auto craft, please if you can fix the issue add it ASAP :) 

As Quezler mentioned @AhmedEhabAmer, we determined it really isn't "the best" mod for item management/autocrafting, as repeatedly outlined in other issues. RS is generally as good, and better in many ways.

Note this is all a determination for E6 and 1.16 - AE2 is currently in E8.

We will not be revisiting this decision - E6 is basically feature complete, and E6e (built around the same pack) makes extensive changes to integrate RS into progression that we have no intention to duplicate with AE2.

See #761 and #845 for lengthy discussion examples.
