### ISSUE TITLE
With the inclusion of when dungeons arise, the terraforged config preset of enigmatica needs to be updated for structures. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4349]
### Describe your suggestion

Basically what it says on the tin; the new dungeons arise isn't included on the terraforged config. 

### Why would you like this added/changed?

Certain structures should be limited in size.

**Comment by theboo** [comment]
I will regenerate our terraforged preset to include all the dungeons arise stuff as well as whatever other structures may be missing. But, structure size is not configurable in the terraforged preset and would have to be done in the dungeons arise config itself(the jigsaw iteration settings)... which structures are you thinking need to be limited?

**Comment by ZephyrWindSpirit** [comment]
The tall aboveground towers ones; like the bandit towers, thornborn towers... those. Also the wishing well should be disabled. It does nothing.

**Comment by NillerMedDild** [comment]
> The tall aboveground towers ones; like the bandit towers, thornborn towers... those.

We've already decreased their size to 50% of the original :)
