### ISSUE TITLE
`level-type` terraforged confusion

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4351]
### Describe your suggestion

Update [the wiki article](https://github.com/EnigmaticaModpacks/Enigmatica6/wiki/Installing-A-Server) on server installation to show [terraforged:terraforged](https://github.com/EnigmaticaModpacks/Enigmatica6/blob/32c1b84b2fe6ac5b5b6f417e9772a4668676451a/config/forge-common.toml) as the world type instead of just terraforged.

(the new wiki doesn't have that information yet and the old wiki can still be accessed directly, and both i cannot(?) pr to) 🤔 

### Why would you like this added/changed?

https://discord.com/channels/195234321836146688/726178356143456287/949687617669185566

**Comment by NillerMedDild** [comment]
Fixed thanks!

**Comment by NillerMedDild** [comment]
Fixed in new wiki too btw, and synced it to GitHub: https://wiki.enigmatica.net/main/help-desk/guides/server-installation
