### ISSUE TITLE
Sandy bee jar looks the same as the Mumbee

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4352]
### Describe your suggestion

make the item look more like it could belong to this bee:
![Screen Shot 2022-03-06 at 20 54 55](https://user-images.githubusercontent.com/3179271/156939816-11087190-7ed5-4ecf-aacf-691bdc5bd39c.png)

### Why would you like this added/changed?

since currently it shares the same texture as the sandy bee:
![Screen Shot 2022-03-06 at 20 54 36](https://user-images.githubusercontent.com/3179271/156939831-854be93e-5853-4ddf-aaa1-cd7377742ac5.png)
(left one is sandy, the stacked 4 are mumbees)

**Comment by TemperedFool** [comment]
The bee jar textures are procedurally generated based on the bee; since Mumber & Sandy share similar color schemes they end up looking similar in the jar. I'm not sure what we can do about this; a few of the bees (see rocky and clay for another example) look pretty similar in jars.

**Comment by User-12691296** [comment]
That's gonna _bee_ a tough one to fix, for sure
