### ISSUE TITLE
iChisel not working

### ISSUE THREAD

**Issue by FallenRosemary** [EnigmaticaModpacks/Enigmatica6#4353]
### Modpack Version

0.5.26

### Describe your issue.

The chisel gui doesn't open when right clicking with the iChisel, all the other functionalities do seem to still work though

### Latest Log

https://paste.ee/p/8MprC

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
I don't think starlight is part of the pack yet?

**Comment by NillerMedDild** [comment]
It is in-dev: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4189
