### ISSUE TITLE
Immersive Engineering Copper Ore has generated in world

### ISSUE THREAD

**Issue by Kamisoi** [EnigmaticaModpacks/Enigmatica6#4355]
### Modpack Version

0.5.26

### Describe your issue.

Running Enigmatica 6 on Expert, version of modpack 0.5.26. World was pregenned with ChunkPregenerator on slow mode; seems like from time to time there's pure copper ore from Immersive Engineering for some reason. Upon mining it drops itself, not the chunks.
![image](https://user-images.githubusercontent.com/26931504/157110493-b278337f-b0f5-409e-b430-73c552262c11.png)

### Have you modified the modpack?

Yes

### User Modifications

Changes to FTB Chunks, Essentials and Ranks.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Please describe in what order you pregrenned and changed to expert?

Also please check on world/serverconfig/immersiveengineering-server.toml. All vein sizes under ores should be at 0.

**Comment by Golfavel** [comment]
I can confirm this also happening in the normal release 0.5.25, no pre-generation. ``[ores.copper]`` in "immersiveengineering-server.toml" has ``vein_size = 0``, just as the rest of the ores there.

**Comment by Kamisoi** [comment]
> Please describe in what order you pregrenned and changed to expert?
> 
> Also please check on world/serverconfig/immersiveengineering-server.toml. All vein sizes under ores should be at 0.

Sorry, did not notice your response yesterday.
Order was: setup server, change mode, change FTB configs, pregen dimensions (multiple in span of 2 days).
All veins sizes under ores are at 0.

**Comment by NillerMedDild** [comment]
Fingers crossed it's fixed this time around 😅

**Comment by Darkere** [comment]
Alright. Please also check that you have the immersiveengineering-server.toml in the defaultconfigs folder

**Comment by Kamisoi** [comment]
immersiveengineering-server.toml is present in defaultconfigs (I haven't updated yet to 0.5.27), settings same as told before - all vein sizes for ores are 0.
