### ISSUE TITLE
time in a bottle on arcane ashes gives multiple outputs

### ISSUE THREAD

**Issue by benzenebanana** [EnigmaticaModpacks/Enigmatica6#4357]
### Modpack Version

0.5.26

### Describe your issue.

When you use time in a bottle on arcane ashes as they are crafting it gives multiple items instead of one, seemingly as a function of how much it's sped up. When i was crafting a heart of the sea and sped it up a few clicks, it gave me three, and when i repeated it to see if its a bug or intended, to i think 64x, it gave me 21.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Duplicate: #4130
