### ISSUE TITLE
[Expert] Upgrade Aquatic Coral can't be used for Create Tree fertilizer

### ISSUE THREAD

**Issue by bevilp** [EnigmaticaModpacks/Enigmatica6#4358]
### Modpack Version

latest

### Describe your issue.

Upgrade Aquatic Coral can't be used for Create's Tree Fertilizer recipe, only vanilla coral works.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks!
