### ISSUE TITLE
E6 is showing E6E main menu

### ISSUE THREAD

**Issue by WitherTM** [EnigmaticaModpacks/Enigmatica6#4367]
### Modpack Version

0.5.27

### Describe your issue.

![image_2022-03-08_213215](https://user-images.githubusercontent.com/101216712/157319993-1f185127-9fb8-41c4-8824-fd7c98b07198.png)
The screen is showing the Enigmatica 6 Expert menu in the newest version of Enigmatica 6 Normal.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Is your pack set to expert mode?

**Comment by WitherTM** [comment]
Uh this was on a fresh version of Enigmatica 6, so no.

**Comment by MuteTiefling** [comment]
Odd, I couldn't replicate it earlier today... Guess we'll need to investigate more.

So all you did was download a fresh instance of the pack and start it up?

**Comment by WitherTM** [comment]
yes, yes I did

**Comment by WitherTM** [comment]
I did it again just now and the same thing happened. I was updating it from an existing profile but used the update in new profile option.

**Comment by theboo** [comment]
Open the new profile folder and open the mode.json file there, what mode does it say you are in?

**Comment by WitherTM** [comment]
expert

**Comment by NillerMedDild** [comment]
Shit, we managed to reproduce it, we'll try to figure out what's up 😄 thanks!

**Comment by WitherTM** [comment]
np happy to help
