### ISSUE TITLE
E6 0.5.26 Item Drops

### ISSUE THREAD

**Issue by minimutson** [EnigmaticaModpacks/Enigmatica6#4368]
### Modpack Version

E6 0.5.26

### Describe your issue.

Many other players and I are having issues with items not dropping. This occurs after an unspecified amount of playtime. Upon investigation, one user on R/FeedTheBeast has stated that "I know there's one bug tied to the broken totem trinket. once it triggers, items globally stop dropping until the world restarts, or you die." Though this statement cannot be confirmed. I have sent my friend's game log (since he is the LAN server host) along with this post. This issue also occurred in both single player and multiplayer scenarios.

Thanks,
-minimutson
_(Not affiliated with FTB or mod/modpack creation in any way.)_

R/FeedTheBeast Post Link:
https://www.reddit.com/r/feedthebeast/comments/t9q967/enigmatica_6_blocks_do_not_drop_anything_after_a/

R/Enigmatica Post Link:
https://www.reddit.com/r/Enigmatica/comments/t9q7tm/enigmatica_6_blocks_not_dropping_when_broken/

### Latest Log

https://gist.github.com/minimutson/0e2d90a61b9e47793f4f6a6d950534b7

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by minimutson** [comment]
Upon further independent investigation, we have potentially traced the issue back to Botania. This cannot be confirmed until further testing is completed. I will keep updating as we play.

Thanks,
-minimutson
_(Not affiliated with FTB or mod/modpack creation in any way.)_

**Comment by Quezler** [comment]
is keepinventory on?

**Comment by minimutson** [comment]
> is keepinventory on?

Yes. keepInventory is enabled. Though we did not have this issue following a player death, hence why I find the affiliation with graves mod quite strange/unusual. 

Thanks,
-minimutson
_(Not affiliated with FTB or mod/modpack creation in any way.)_

**Comment by NillerMedDild** [comment]
Please update to 0.5.27 and see if the issue persists :)

**Comment by minimutson** [comment]
Hey, I am currently running a 30 minute test on V0.5.27 to see if I can replicate the issue. Though it does come up as the Expert version of the modpack, I will still proceed with the test. 

Thanks,
minimutson
_(Not affiliated with FTB or mod/modpack creation in any way.)_

**Comment by minimutson** [comment]
After 30 minutes of play testing, the issue has not presented itself. If I may ask, what did you do to fix the modpack?

Thanks,
minimutson
_(Not affiliated with FTB or mod/modpack creation in any way.)_
