### ISSUE TITLE
Cable Tiers

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4369]
### URL

https://www.curseforge.com/minecraft/mc-mods/cable-tiers

### Why would you like the mod added?

Cable tiers provides higher level items for refined storage. It has faster importers /exporters with more slots and higher level requesters.

**Comment by MuteTiefling** [comment]
Extra Storage already has importers/exporters with more slots though.

**Comment by Kevin-Marsh** [comment]
Extra storage does have more slots but far less than the capacity that cable tiers offers. Cable tiers are also faster when fully upgraded than what Extra Storage provides can offer and also provide requesters that have more slots.

**Comment by NillerMedDild** [comment]
I don't think we need this tbh.
