### ISSUE TITLE
E6E crash bug

### ISSUE THREAD

**Issue by User-12691296** [EnigmaticaModpacks/Enigmatica6#4376]
### Modpack Version

Latest develop fetch as of 2:30 AM UTC

### Describe your issue.

I've crashed 7 times today, all because of the same issue. It all happens on the very first server/singleplayer tick, this has never been a problem for me before. 

I've tried changing Java versions, as the error: symbol "}" not expected, is usually coinciding with outdated java syntax. Nothing has seemed to work.

### Crash Report

https://pastebin.com/GiqMXSVc

### Latest Log

https://pastebin.com/dJ0bn22D

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Seems like your packmenu.cfg is corrupt in some way, could you please paste it's contents here?

**Comment by Darkere** [comment]
nah. He has an outdated version of configswapper

**Comment by NillerMedDild** [comment]
Oh 😅 easy fix!
