### ISSUE TITLE
In E6E, the brutish zombee wont stay calm

### ISSUE THREAD

**Issue by TheDragonicSlayer** [EnigmaticaModpacks/Enigmatica6#4385]
### Modpack Version

1.0.0

### Describe your issue.

When i smoked a brutish zombee, it stayed calm for less than a second, before it became angry again

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment]
Brutish zombies need splash calming potions or a "beecon" to be calmed. If you want to capture one, a soul gem doesn't require them being calmed

**Comment by TheDragonicSlayer** [comment]
They used to calm down in 0.5.25 of E6 normal

**Comment by TemperedFool** [comment]
Some stuff about angry bees changed in RBees around then. This is one of them, the other being that you can't jar bees while they're angry.
