### ISSUE TITLE
Mixin: UncaughtException: NoClassDefFoundError

### ISSUE THREAD

**Issue by derdotte** [EnigmaticaModpacks/Enigmatica6#4386]
### Modpack Version

1.0.0

### Describe your issue.

Freshly installed the modpack from curseForge. Started it and crashed with the log from below. It seems to be a NoClassDefFound thrown by the IDataProvider Interface and caused by something in mixin.

### Latest Log

https://gist.github.com/derdotte/9dc98e74fed5c1daf22a5ab7ab4f5ca2

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by derdotte** [comment]
Just ran it with latest java version 1.8.0_321 by manually changing the used java.exe in the profile of the modpack aswell. Same error. Here is the gist: https://gist.github.com/derdotte/d277ef9e93c106c15d130c747ed887df

**Comment by derdotte** [comment]
According to discord user this issue might be related to https://github.com/SpongePowered/Sponge/issues/3514 
Which would then hopefully be just a mod update to fix.

**Comment by Darkere** [comment]
The linked issue is unrelated. This looks like a broken vanilla install.

**Comment by derdotte** [comment]
Darkere was right, this was a broken vanilla install on the curseforge launcher.
Navigating to \Twitch\Minecraft\Install and deleting the containing stuff fixed this crash.
Therefore fixed and closed.
