### ISSUE TITLE
Shears are destroyed when making twigs from leaf

### ISSUE THREAD

**Issue by Cyprex** [EnigmaticaModpacks/Enigmatica6#4387]
### Modpack Version

1.0.0 Expert

### Describe your issue.

The recipe for leaf+shears->4 twigs consumes the shears
As in a full durability vanilla shears tool completely disappears. My guess is it's supposed to use up durability instead.

### Have you modified the modpack?

Yes

### User Modifications

Removed Discord RPC, modified DietMod

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by z64555** [comment]
I get the same behavior in E6E on multiplayer, pack is unmodified.

**Comment by NillerMedDild** [comment]
@MuteTiefling seems like the recipe for both PVJ Twigs and Pinecones should use a function to reduce the durability of the input shears instead of consuming them, do you remember the syntax for that kinda thing? ^^'

**Comment by MuteTiefling** [comment]
I don't :( thought it was automatic

**Comment by NillerMedDild** [comment]
Shit :P

**Comment by MuteTiefling** [comment]
I'll just look at making some different craft for these
