### ISSUE TITLE
Crash when mining stone. (Expert)

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4388]
### Modpack Version

1.0.0

### Describe your issue.

I randomly crashed when mining stone yesterday, and I didn't play again, but then this morning I decided to go back to play it and I was sent back around 5 minutes of work and was missing a chest I had crafted. I made my pickaxe again and tried to mine stone, and it crashed again. No crash log was made for some reason, but I have the latest log for you peeps.

### Latest Log

https://gist.github.com/FooterMan14/24a7c29aedf4fb98aed6ba3a09ff8e95

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by FooterMan14** [comment]
...

**Comment by NillerMedDild** [comment]
Did you manage to get help on our Discord? :)

**Comment by FooterMan14** [comment]
I asked and talked with Darkere but I haven't gotten a full answer to this yet

**Comment by NillerMedDild** [comment]
Alright then - I see he asked how much RAM you have allocated, could you please share that? :)

**Comment by FooterMan14** [comment]
![image](https://user-images.githubusercontent.com/71946346/158064023-d71bb1ed-d1fd-4962-ae52-58d06586e6dd.png)

**Comment by FooterMan14** [comment]
We can take this conversation elsewhere if needed, feels weird to comment on a closed issue

**Comment by Darkere** [comment]
That was unfortunately already my last guess at what the problem could be... 

You could try letting it sit for a while and see if it comes back. But even if it does,  that doesn't seem like it would be the greatest solution. 

Depending on how far you are in your world, you may want to try if the same thing happens in a new one. 

To actually investigate the issue, you would need to profile with something like visualvm (Guide: https://gist.github.com/Darkere/3a58d8adfb64738a289c9636544656bc ).

**Comment by FooterMan14** [comment]
gotcha, I'll see what I can do, thanks for the help
