### ISSUE TITLE
Bleeding RAM?

### ISSUE THREAD

**Issue by Oppenheimert** [EnigmaticaModpacks/Enigmatica6#4389]
### Modpack Version

1.0.0

### Describe your issue.

Playing on a host by uploading the server files myself (no pre-set in the host modpack options, launched on my PC before uploading to a host). Server had 8 GB, upgraded to 16GB. Seems to be swallowing as much RAM as possible (previously capped at 6.5GB, now caps at 13,5GB-ish.  Tried editing the ramdisk option to true (in server-setup-config) and seemed to help for some time, after that it just went up again with its "can't keep up" thing. Rolled it back to the time where it ate less RAM - caps at 10.5GB out of 16. Tried to mess with configs, didn't help. Really want to play this modpack, hoping for answers. 

Only extra to the modpack is the Ice & Fire mod, ran a test after removing it - issue persists.

### Latest Log

https://gist.github.com/Oppenheimert/2455aeac7e4bcf794dd9d1f72fa583d2

### Have you modified the modpack?

Yes

### User Modifications

Added Ice & Fire mod. 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Oppenheimert** [comment]
![image](https://user-images.githubusercontent.com/101472846/158029226-ac3b4f1a-2ca0-4431-82f5-89a71fb8e81e.png)
This shows up right before it lags completely out.

**Comment by NillerMedDild** [comment]
Thanks for the report - I recommend that you switch host tbf :P this doesn't seem normal.
