### ISSUE TITLE
Item not visible while in a mechanical crafter slot

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4391]
### Modpack Version

0.5.26

### Describe your issue.

You cannot see the screen required for the assembly controller while it is in a mechanical crafter:

![2022-03-12_19 43 04](https://user-images.githubusercontent.com/3179271/158030767-98942830-a509-4739-9daf-360225644114.png)

(not in the block at least, the one probe does show it)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This might be culling being a bit too aggressive. I'm noticing something similar with a weapon in a deployer too. Only visible from very specific angles

**Comment by Quezler** [comment]
This item in the mechanical crafter didn't seem to be visible from any angle at all 🤔

**Comment by NillerMedDild** [comment]
Doesn't seem to be Entity Culling related after all, blacklisting `create:mechanical_crafter` doesn't change anything.

**Comment by Surnyy** [comment]
This change has made the Assembly Controller uncraftable, as the Computer requires an Assembly Controller to be crafted in the first place.

**Comment by Quezler** [comment]
> This change has made the Assembly Controller uncraftable, as the Computer requires an Assembly Controller to be crafted in the first place.

They were obtainable from the amadron market, opening the tablet on a handful of different days would get you one ^

**Comment by MuteTiefling** [comment]
yeah, that's not a super obvious path, and wasn't the intent with the fix. I think you had suggested the monitor as a replacement in the first place and I snagged the computer instead.
