### ISSUE TITLE
Auto-crafting jetpack doesn't work

### ISSUE THREAD

**Issue by ElSivad** [EnigmaticaModpacks/Enigmatica6#4394]
### Modpack Version

0.5.27

### Describe your issue.

When I tried to do the auto crafts for the jetpacks from IRON JETPACKS. Crafts do not detect POWAH reators.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Why'd you close the issue? :)
