### ISSUE TITLE
Connected server

### ISSUE THREAD

**Issue by mogcid** [EnigmaticaModpacks/Enigmatica6#4395]
### Modpack Version

1.0.0

### Describe your issue.

hello I have a problem to connect to the server can you help me message:

[Server] Server thread/INFO MogCid joined the game
13.03 07:34:05 [Server] Server thread/INFO [KubeJS Server/]: server_scripts:enigmatica/kubejs/packmode.js:4: setting mode for player: MogCid
13.03 07:34:05 [Server] Server thread/INFO [KubeJS Server/]: server_scripts:enigmatica/kubejs/packmode.js:7: set mode to expert for player: MogCid
13.03 07:34:05 [Server] Server thread/INFO [se.mi.te.da.DataManager/]: Sending data to client: MogCid
13.03 07:34:05 [Disconnect] User MogCid has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
13.03 07:34:05 [Server] Server thread/INFO MogCid left the game
13.03 07:34:05 [Server] Netty Epoll Server IO #23/ERROR Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@2e82ff9e (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!
13.03 07:34:05 [Server] Netty Epoll Server IO #23/ERROR Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@2e82ff9e (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client

### Latest Log

https://gist.github.com/mogcid/c0319e805a432e1b4ca7546b69ebc9a7

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by mogcid** [comment]
I already asked for help on your discord but no one answered me I am with the support of my server but even them are struggling lol

**Comment by MuteTiefling** [comment]
There are a lot of people asking for help since expert just released.

Just be patient and ask again politely on discord.

**Comment by mogcid** [comment]
how come I was not polite a hello is enough right?

**Comment by MuteTiefling** [comment]
I'm not saying you weren't. I'm just asking you to keep it that way :D
