### ISSUE TITLE
[Expert]Arcane gold / Gold Inlay Quest can easy bypass by Looting Apotheosis Tower

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4396]
### Modpack Version

1.0.0

### Describe your issue.

Arcane gold can found as loot in Apotheosis Tower that can use to craft gold inlay without need Enchanting Apparatus with conduit recipe, If this is it what  it should work , sorry ^^

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Intended ;D
