### ISSUE TITLE
[Mod Suggestion] Improved Mobs

### ISSUE THREAD

**Issue by Quantombb** [EnigmaticaModpacks/Enigmatica6#4397]
### URL

https://www.curseforge.com/minecraft/mc-mods/improved-mobs

### Why would you like the mod added?

Because when people get OP Armor from some modded drop, and zombies and skeletons are no longer a threat anymore. 
This mod aims to fix that, by introducing some new features and difficulty mechanics. Also can be configured to not be completely overwhelming.

**Comment by TheDragonicSlayer** [comment]
Now, now. This is a expert/kitchen sink pack, not a apocalypse pack

**Comment by NillerMedDild** [comment]
Looks like a cool mod, but it doesn't really fit tbh.
