### ISSUE TITLE
Game stuck in loading textures (Expert)

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4399]
### Modpack Version

1.0.0

### Describe your issue.

Had this issue on multiple packs before, still not sure why it happens.

![image](https://user-images.githubusercontent.com/71946346/158066608-3b555632-d0f0-4c31-9b64-7050b26ffd55.png)
The game likes to get stuck loading certain textures on Modded at times, and it usually requires a complete re-install of the pack, I have tried Curseforge's repair system, but that did not fix it.
The game gets stuck loading: minecraft:textures/atlas/particles.png with the Memory Heap first number counting slowly upwards.
![image](https://user-images.githubusercontent.com/71946346/158066743-b5bf1d54-84d6-4652-ab30-f8f6e7b9e742.png)
Not even using the full amount of RAM allowcated (8GB) with a system of 32GB.
Every other part of the system is fine if that matters (GPU, CPU etc)

Edit: This now happens on a new instance of E6E, which leads me to believe this is Curse's fault:
![2022-03-13](https://user-images.githubusercontent.com/71946346/158067135-6d1ef9f7-2084-4c13-ae5b-3db9caee1b33.png)

Another Edit: Tried again using GDLauncher, had same issue.

### Crash Report

No crash report, just stuck loading something

### Latest Log

https://gist.github.com/FooterMan14/b9f78cf361dc1f3cd9842c3ef979a485

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report - Does it ever get unstuck? How long have you tried?

**Comment by FooterMan14** [comment]
> Thanks for the report - Does it ever get unstuck? How long have you tried?

I checked the Windows Event Viewer and apparently the RAM was having a bad day, so I restarted my PC and it fixed the issue. Very weird issue.
