### ISSUE TITLE
Enigmatica 6 expert crashes after joining a server with magnesium in the modpack 

### ISSUE THREAD

**Issue by cheetahbooked** [EnigmaticaModpacks/Enigmatica6#4400]
### Modpack Version

1.0.0

### Describe your issue.

when i try to join a server it crashes and the only thing i added was magnesium 

### Crash Report

https://gist.github.com/cheetahbooked/9af7c5a054d390f6bd1f72c7ab20d205

### Have you modified the modpack?

Yes

### User Modifications

i added magnesium 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Remove magnesium, magnesium extras, and dynamic lights reforged and see if you still crash

**Comment by cheetahbooked** [comment]
> Remove magnesium, magnesium extras, and dynamic lights reforged and see if you still crash

i did im just saying that it crashes because of that
