### ISSUE TITLE
Resourceful Bees starry bee and dev bee starry_lexxie

### ISSUE THREAD

**Issue by Humphr3y420** [EnigmaticaModpacks/Enigmatica6#4401]
### Modpack Version

0.5.26

### Describe your issue.

not finding the starry be anywhere in the small end islands. when searching through the configs I found this. it shows that the starry_lexxie spawns in the small end islands not the normal starry bee
![notepad_L369QMBBpP](https://user-images.githubusercontent.com/86567819/158069487-c73354ee-653b-44fc-af29-9e4ab737aa90.png)
![notepad_eF34Kq4JQQ](https://user-images.githubusercontent.com/86567819/158069488-c8501825-1c5f-4fc0-bea8-a43707141f22.png)
.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TheDragonicSlayer** [comment]
Um... The starry.json is the file for the starmetal bee. The starry_lexxie.json is for the starry bee which gives you that honey you need which you can mutate into nether stars.

**Comment by TheDragonicSlayer** [comment]
FYI, the starmetal bee AKA starry.json bee is obtained hy throwing a iron bee in liquid starlight I think

**Comment by TemperedFool** [comment]
It's actually crafted on the iridescent altar, but otherwise you're correct.

The Starry Bee (from the starry_lexxie file) is a very rare Dev bee, and is hard to find. The Constellation Bee (from the starry file) is the Astral bee, and is crafted, not found.
