### ISSUE TITLE
Create Dungeons (Expert)

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4404]
### Describe your suggestion

Create dungeons made of things like Andesite and Brass casings seems like it shouldn't belong in an expert pack, you instantly get several stacks of these casings which will help the player for quite some time. Would recommend disabling them and other ones that also break the expert aspect if they exist.

### Why would you like this added/changed?

Easy casings with no need to craft breaks the expert aspect

**Comment by TemperedFool** [comment]
This is intended, and was in place prior to Expert development. All it really does is save the lucky recipient time and materials; the casings aren't gated except by that andesite and brass.
