### ISSUE TITLE
JEI is not showing all the recipes at SMP

### ISSUE THREAD

**Issue by IsmaelIRM** [EnigmaticaModpacks/Enigmatica6#4407]
### Modpack Version

1.0.0

### Describe your issue.

I can't see every craft of any items or block at my friend's world (it is an LAN-hosted world). He can see all of the recipes as the owner. And in the tinkers book is blank at the recipes spot.
If I enters a world in singleplayer, I can see the the craftings, so those are not missings.
I can see a few (like the fuel time of the things and some others of creatio), so that shows me that it is not a problem of the keybinds or the entire JEI.
I can craft the items even if the recipe is not showing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report.

I'm afraid LAN often has weird issues like this, I highly recommend that you use a server instead.

That being said, I'd ofc like to fix this - Could you please provide both you and your friend's latest log?
