### ISSUE TITLE
I found where the apotheosis towers config is, can it be added for terraforged structure list?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4408]
### Describe your suggestion

I did a little poking around in my configs on my instance and found the deadly module of apotheosis is where the wizard towers, the "tome towers" as called, have their spawning 1/x ratio. Is it possible to add that into the terraforged structures config? 
Because I wasn't finding any in my world with the shipped choice, I dropped my config to 180 instead of 280, and suddenly I'm finding them again. XD

### Why would you like this added/changed?

Easier to find where the structure configs are while attempting to tweak to the liking, but mainly pointing out where the config is for if others can't find the towers like I was.

**Comment by theboo** [comment]
That list is automatically generated, those towers just don't show up. Apotheosis must be registering that tower weird cuz it doesn't show up on /locate either
