### ISSUE TITLE
Crash when moving server in server list up

### ISSUE THREAD

**Issue by Chronophylos** [EnigmaticaModpacks/Enigmatica6#4412]
### Modpack Version

E6E v1.0.0

### Describe your issue.

Game crashes when moving a server in the list up when its the first server in the list.
Above the server entry is the server hoster advert.

Steps to reproduce:
1. Go to Multiplayer
2. Add a server
3. Move it up util its the first real server and second entry in the list
4. Move it up again

### Crash Report

https://paste.ee/p/hKDlv

### Latest Log

https://paste.ee/p/s5EUI

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report! I relayed it here: https://github.com/BisectLabs/BisectHostingServerIntegrationMenu/issues/1

**Comment by Darkere** [comment]
Any chance you tested this with just that mod? The crashlog looks like it's caused by cherished worlds.

**Comment by NillerMedDild** [comment]
Seems to be fixed already, we just gotta update \o/
