### ISSUE TITLE
Make Pretty Pipes Blank Module craftable using other types of stone slabs

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#4413]
### Describe your suggestion

Make the Blank Module craftable using: 

- (Vanilla) Stone Slab (default)
- Andesite / Diorite / Granite slabs (Vanilla overworld stones)
- Limestone / Weathered Limestone / Dolomite / Gabbro / Scoria / Dark Scoria slabs (Create stones)
- Marble / Limestone / Jasper / Slate / Voidstone / Myalite slabs (Quark stones)

### Why would you like this added/changed?

Currently it is only craftable using the vanilla stone slab, which is rare with all those stone types spawning in the world.

**Comment by TheDragonicSlayer** [comment]
This is a problem for many recipes like grindstone too

**Comment by TemperedFool** [comment]
Fwiw, none of the stone types, vanilla included, are rare; a vanilla stone or cobble generator is super simple to setup, and you can use them to target other stone types or randomly generate different types. There's even a ponder for it if you hold W while mousing over stones or cobblestones!

**Comment by MuteTiefling** [comment]
The trouble is... none of the other slabs are tagged in such a way as to do this easily. I'll give it a think how to approach this without too much work though.

**Comment by NillerMedDild** [comment]
I think we should just tag the other slabs, replace the input and call it a day :D
