### ISSUE TITLE
Venison with Bamboo Shoots missing Protein food group

### ISSUE THREAD

**Issue by Jomeaga** [EnigmaticaModpacks/Enigmatica6#4417]
### Modpack Version

E6E 1.0.0

### Describe your issue.

The food "Venison with Bamboo Shoots" from Abnormals Delight is missing the protein food group. It should have it because there's a piece of meat used to craft it.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it 👍
