### ISSUE TITLE
Cherry Planks from the Environmental mod are unable to be used to craft a Cherry Chest

### ISSUE THREAD

**Issue by hotdog2314** [EnigmaticaModpacks/Enigmatica6#4419]
### Modpack Version

Enigmatica 6 Expert - 1.0.0

### Describe your issue.

Cherry Planks from the _Environmental_ mod are unable to be used to craft a Cherry Chest. You can still craft the Cherry Chest using 8 Cherry Planks from _Project: Vibrant Journeys_ or 8 Cherry Blossom Planks from _Oh the Biomes You'll Go_, and using 8 Cherry Logs from any of the three aforementioned mods (which crafts four).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by HaxtonSale1** [comment]
Cherry Sign has similar issue; it is craftable with 2 other types of cherry planks but not Environmental cherry planks

**Comment by MuteTiefling** [comment]
Bit of a typo on my part there. All fixed up :D
