### ISSUE TITLE
Extra item outputs getting stuck in RF Tools Crafter

### ISSUE THREAD

**Issue by jynxdarkspell** [EnigmaticaModpacks/Enigmatica6#4420]
### Modpack Version

0.5.25

### Describe your issue.

Extra item outputs from RF Tools Crafter Tier 3 are getting stuck in Crafter

For example:
Crafting honey blocks from 4 bottles of honey produces 1 honey block and 4 glass bottles.
Using RS exporter to move honey from bottles to crafter, using RS importer to retrieve honey blocks and empty bottles from crafter

Expected behavior, this system should work without issue.

Instead, empty bottle are stuck in the crafter, even if output slots are available in the crafter or if there is space available in the RS system.

An example of this has been caught on MindedGryphon6's most recent Twitch Stream. (3/15/2022 Hiya everyone! Lets play Froggonia, time to do things? Idk what im doing ngl)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
cleared it up on stream, the crafter was not configured correctly with some recipes set to extC which keeps the left over items in the input.

**Comment by jynxdarkspell** [comment]
Thank you for figuring that out!  I have never messed with those settings on the crafter before and didn't notice it was changed!
