### ISSUE TITLE
 Passthrough Signs mod not compatiable with Quark edit sign.

### ISSUE THREAD

**Issue by WonderDog** [EnigmaticaModpacks/Enigmatica6#4421]
### Describe your suggestion

Passthrough Signs mod not working as Quark Right Click takes priority even if edit sign is disabled in the quark config

### Why would you like this added/changed?

Remove  Passthrough Signs mod

**Comment by NillerMedDild** [comment]
Found this bug report: https://github.com/GirafiStudios/PassthroughSigns/issues/5
I'll enable shift to to ignore the sign, hopefully that fixes it.

**Comment by NillerMedDild** [comment]
Shift-click to ignore the sign now :)

**Comment by WonderDog** [comment]
Great news

Thank You

**Comment by theboo** [comment]
We like to close issues after they make it in to a release :)
