### ISSUE TITLE
Create deployer recipe to make Immersive Engineering wires

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4422]
### Describe your suggestion

We all know (or will shortly) know that Immersive Engineering wires are a literal pain to craft early game. Can a recipe be made to use a deployer or sequenced crafting with the wire cutters to make wires _slightly_ cheaper? Otherwise its waiting for making the metal press behind medium machine making and that's just pain. 
Please consider, thank you for your time. 

### Why would you like this added/changed?

Quality of life, sanity of mind.

**Comment by ZephyrWindSpirit** [comment]
Not wanting this closed by autobot

**Comment by theboo** [comment]
Shouldn't, autobot only shows up when we add awaiting information label

**Comment by TemperedFool** [comment]
Autobots, roll out!

Jokes aside, I have some ideas for this. I'll see if I can steal a little time tomorrow and try some stuff out.

**Comment by MuteTiefling** [comment]
Once you get to steel, you get a huge cost reduction. Not sure we need it cheaper before then.
