### ISSUE TITLE
Game crashes on load due to trying to read a macOS .DS_Store file 

### ISSUE THREAD

**Issue by cocona20xx** [EnigmaticaModpacks/Enigmatica6#4427]
### Modpack Version

1.0.0 (Expert Mode Download)

### Describe your issue.

Seemingly due to an Astral Sorcery Mixin or Access Transformer, E6(E) crashes on macOS during a late stage of loading due to the client trying to load a .DS_Store as an actual file.

Issue is "fixed" (in that the game loads) by recursively removing all .DS_Store files from the instance's related directories.

### Crash Report

https://paste.ee/p/dCPoa

### Latest Log

https://paste.ee/p/xN9vo

### Have you modified the modpack?

Yes

### User Modifications

Removed Discord Rich Presence due to it not being compatible with macOS (you should also probably note this somewhere, maybe in another issue?)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
_Fellow Max User here_

These .DS_Store files get written when you open a directory in the Finder. I also run into this occasionally - not much to do about it except what you did.

**Comment by NillerMedDild** [comment]
I'm afraid we don't actually ship any `.DS_Store` files, so we can't do much here.
