### ISSUE TITLE
[Expert] Documentation - PNC compressed iron not generated with explosion crafting

### ISSUE THREAD

**Issue by jkirkpatrick** [EnigmaticaModpacks/Enigmatica6#4431]
### Modpack Version

E6E 1.0.0

### Describe your issue.

Expect approx 80% to be converted - Actual is 0% conversion (and 100% destroyed) 

When attempting to craft compressed iron using explosion crafting, all the iron ingots are destroyed and no compressed iron is dropped / created. Followed instructions according to PNC manual. 

1. Place block of vanilla TNT
2. Place button on TNT (also tried lever)
3. Drop stack of iron ingots next to TNT (tried above, below, and beside) 
4. Press button / flip lever and run

I have lost several stacks of iron, and there is no explosion crafting visible in JEI - so I don't know if there is a recipe bug. Attempted crafting on stone/limestone, wood, dirt, and finally bedrock.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MaxNeedsSnacks** [comment]
The default method of crafting Compressed Iron has been disabled, as there's a custom recipe for expert. You might want to check that one instead :p (Hint: Superheated Iron is your go-to)

**Comment by jkirkpatrick** [comment]
@MaxNeedsSnacks Thank you.

Perhaps better classified as a documentation issue?
![Screenshot from 2022-03-17 19-40-55](https://user-images.githubusercontent.com/1149447/158911680-97dd32a0-04be-442a-84f5-5fa1dbeca88c.png)

**Comment by MuteTiefling** [comment]
We intentionally avoided putting recipes in the quests because they're used for both Normal and Expert. JEI shows the recipes clearly.

**Comment by jkirkpatrick** [comment]
@MuteTiefling Your comment added to the quests says to check the PNC guide regularly; there must be a better way to clarify it. After viewing the quest, the player _can_ check JEI, but the comment says to view the guide.
