### ISSUE TITLE
Gold duplication using powered rails + smeltery

### ISSUE THREAD

**Issue by Hamderber** [EnigmaticaModpacks/Enigmatica6#4433]
### Modpack Version

1.0.0

### Describe your issue.

Creating Powered Rails using the Transport mod's method (using 6 gold rods) creates 24 Powered Rails, but Tinkers' Construct still lets you melt each Powered Rail into a Gold Ingot. This results in a very simple loop that can quadruple gold quantity per iteration for the simple cost of one redstone, stick, and a bit of lava for a smeltery.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by TemperedFool** [comment]
I removed the smelting recipes for regular and powered rails (pending PR acceptance); that addresses this loop on both.
