### ISSUE TITLE
Arboreal Extractor not extracting resin from Menril trees

### ISSUE THREAD

**Issue by ArtkoXT** [EnigmaticaModpacks/Enigmatica6#4436]
### Modpack Version

1.0.0

### Describe your issue.

When placing an Arboreal Extractor near a Menril Tree it does nothing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
You need to break one of the blocks at the base so the extractor is right up against the main trunk.

**Comment by ArtkoXT** [comment]
![image](https://user-images.githubusercontent.com/101877782/159041661-2ebf5ca9-c68d-48bb-8f07-e3b723914d91.png)
that doesn't work either, extractor is facing the trunk

**Comment by ArtkoXT** [comment]
Fixed, it appears if the main trunk is an enriched log it doesn't work.
