### ISSUE TITLE
Quest for: Create - Mechanical Piston

### ISSUE THREAD

**Issue by milcondoin** [EnigmaticaModpacks/Enigmatica6#4438]
### Describe your suggestion

Quest completion not only by "Mechanical Piston", but alternatively also by "Sticky Mechanical Piston".

### Why would you like this added/changed?

I crafted the sticky version in one go, putting the normal version not in my inventory once, but directly from the crafting output back into the input. Thus the quest didn't realize, that the piston was already crafted. The sticky one doesn't count and also has no recipe to scrape the slime off again.

**Comment by MuteTiefling** [comment]
Fixed in #4463
