### ISSUE TITLE
[Expert] Novice armor from Ars requires weirdly huge amount of silk

### ISSUE THREAD

**Issue by Yowesephth** [EnigmaticaModpacks/Enigmatica6#4439]
### Describe your suggestion

Reduce the amount of silk fibres required to craft novice armor from ars noveau 

### Why would you like this added/changed?

Putting the recipe for a full set of novice armor into the crafting calculator shows you need 288 silk fibers, mostly due to the novice armor requiring 4 silky cloth per part, and each silky cloth requiring 16 silk fibers.

But, if you compare this to the higher tiers, they only need 32 silk fibres total.

Silk fibres don't seem like they justify ramping up production for such an early game set of armor
They also seem like they don't get used that much overall.
I would assume this is more of an accidental oversight than an intentional balance decision.

**Comment by ZephyrWindSpirit** [comment]
I have found novice armor as loot in tome towers, but silk isn't hard to get. But I do wonder why

**Comment by MuteTiefling** [comment]
The recipe was set this way largely because silk is easy to get :D. Armor is meant to be something you find, or spend a decent amount of time on crafting (see all metal armors).
