### ISSUE TITLE
Nebu Drops

### ISSUE THREAD

**Issue by Thiana** [EnigmaticaModpacks/Enigmatica6#4442]
### Modpack Version

dev/head (expert)

### Describe your issue.

There is a very odd recipe chain that takes a nebu ore through (mana pool, lightning crafting, natural altar, fluid crafting, blood altar) all to create a single nebu drop. Just smelting the nebu ore will give an ingot which crafts to 9 drops. Something is odd here ;)

### Have you modified the modpack?

Yes

### User Modifications

darkohud, incontrol, villagernames, villagerdeathmessages

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MaxNeedsSnacks** [comment]
Recheck the lightning and fluid recipes: Each of them have 20 rolls to them, meaning you can actually get up to 400 nuggets from a single craft ^^ (though the average yield is lower than that, see the individual recipes for the chances)

**Comment by TemperedFool** [comment]
This process will yield 9-10x overall, just requires a significant infrastructure investment.
