### ISSUE TITLE
Deepslate (Quark) can not be used in a mineral survey (Immersive Engineering)

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#4448]
### Modpack Version

1.0.0

### Describe your issue.

As described in title

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I think that's working as intended to be honest, the amount of blocks mineral prospecting works on is limited.
