### ISSUE TITLE
[Client]Crash when arriving in Atum dim

### ISSUE THREAD

**Issue by Saecal** [EnigmaticaModpacks/Enigmatica6#4449]
### Modpack Version

Enigmatica6Expert 1.0.0

### Describe your issue.

Every time I arrive in Atum dim,game crash,even another try in creative mode or another saves

### Crash Report

https://gist.github.com/Saecal/993d4c1d2efedb60f8a7c0a26c90ae44

### Latest Log

https://gist.github.com/Saecal/55786bb4af62e0301285f75d14affe7e

### Have you modified the modpack?

Yes

### User Modifications

1.i18nupdatemod-1.16.5-2.0.2-hotfix-4:for translation
2.JustEnoughCharacters-1.16.4-4.3.2:for convenient search in jei

I have tried to play without these two mods,unfortunately game crash again in the same situation

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Is the crash report with or without the mods you added? :)

**Comment by Saecal** [comment]
Thanks for your reply！The report uploaded in github is with the mods added.Here is the report without the mods.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EnigmaticaModpacks/Enigmatica6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EnigmaticaModpacks/Enigmatica6] [Client]Crash when arriving in Atum dim (Issue #4449)





 
Thanks for the report. Is the crash report with or without the mods you added? :)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NillerMedDild** [comment]
Err where? ^^'

**Comment by Saecal** [comment]
I'm sorry my reply with file was sent directly by mail so the file was not sent(ノへ~、)，here is the report without mods
https://gist.github.com/Saecal/5c7e95193eb8134c00da2510f3782c13

**Comment by NillerMedDild** [comment]
Ah thanks! Could you please remove the mod Starlight and see if the issue persists?

**Comment by Saecal** [comment]
The issue persists after removing the mod so I tried another laucher multimc instead of hmcl.This time I entered the dim and game didn't crash even if keeping the mod Starlight:-) Thanks a lot for your reply and hope the modpack grow better！
