### ISSUE TITLE
World Not Loading

### ISSUE THREAD

**Issue by CommonConDog** [EnigmaticaModpacks/Enigmatica6#4452]
### Modpack Version

1.0.0

### Describe your issue.

Enter the world and chunks will not load or appear even after waiting for 1hr. Inventory can be opened with JEI and look through recipes. The map can be opened and looked through as well as waypoints. Tried leaving the game however, it freezes on saving the game and can't exit without using alt+f4. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Please try removing the mod `starlight` and see if that resolves the issue.

**Comment by GorrionCojonero** [comment]
Thank you for responding quickly. I have done what you told me and now my game loads perfectly. Thank you very much, once again you save my game. :) :1st_place_medal:
