### ISSUE TITLE
(Expert) Reactor crafting not taking NBT data into account

### ISSUE THREAD

**Issue by Luxaedel** [EnigmaticaModpacks/Enigmatica6#4453]
### Modpack Version

1.0.0

### Describe your issue.

When crafting a Powah reactor in expert mode it only works with 100% 'fresh' machines (energy cell, thermal generator, furnator). If you craft a furnator (hardened) using a USED furnator (basic) the crafting recipe will fail and spit everything back out.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks! Should be all fixed up now :D
