### ISSUE TITLE
IE refinery form with invalid message after unlock medium Schematic

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4454]
### Modpack Version

1.0.0

### Describe your issue.

![image](https://user-images.githubusercontent.com/74948675/159174944-cdc59015-6746-467c-a1a5-0a3e3cd5aac0.png)
![image](https://user-images.githubusercontent.com/74948675/159174955-1252009a-13b2-40f6-96f3-c5cb4692b5c4.png)
![image](https://user-images.githubusercontent.com/74948675/159174977-f141d296-8508-4498-b320-7d5bcc381ea1.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
Unfortunately, due to the way how the event works we use for this message, there is no way around this. Hitting the block calls the event for all multiblocks that can be formed using this block. 

The only alternative we could have is changing the structures.

**Comment by NillerMedDild** [comment]
Perhaps we should change the error message?

**Comment by Darkere** [comment]
Feel free :D
