### ISSUE TITLE
World not load

### ISSUE THREAD

**Issue by GorrionCojonero** [EnigmaticaModpacks/Enigmatica6#4456]
### Modpack Version

0.5.27 and 1.0

### Describe your issue.

When starting my world, it stays on the tips page with the box at 100% and does not go beyond that even after several hours. I have updated java in case it was the problem, but nothing changes. Version 0.5.26 works perfectly and loads the world, but when updating it doesn't work anymore. And I don't get any error reports or anything, it just waits to load the world, but it doesn't.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Removing the mod Starlight ought to fix this #4452
