### ISSUE TITLE
[E6E]Astral altar's recipe, relay can't show item form tag

### ISSUE THREAD

**Issue by KuroPeach** [EnigmaticaModpacks/Enigmatica6#4465]
### Modpack Version

e6e 1.0

### Describe your issue.

Astral altar's recipe, relay can't show item form tag
![image](https://user-images.githubusercontent.com/19620848/159273922-bd720b9e-2c85-445e-9cdf-8a5eb5be56a0.png)
My friend and I used the ID's NBT reader to read the coordinates to complete the synthesis, my english is not good 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
You're sure you haven't added anything to the game? I can't reproduce this at all. All 3 of those items show up just fine.
![2022-03-22_13 51 39](https://user-images.githubusercontent.com/9543430/159544519-cc66405b-1a0a-43a0-a1cd-f6db7657bf71.png)
![2022-03-22_13 51 49](https://user-images.githubusercontent.com/9543430/159544522-f708c086-c24a-44c0-b542-7b540a1a26dd.png)

**Comment by KuroPeach** [comment]
This problem occurs on the server. I tested the Gaia launcher and it can be displayed normally in the single player, but the server does not work, because I did not find a more intense star energy in the single player world to test the solar neutron collector.
![image](https://user-images.githubusercontent.com/19620848/159618037-5a633e1a-3cc3-417c-9bf6-da7f89928339.png)

**Comment by KuroPeach** [comment]
Status in Multiplayer
![)53A8_{)Y} @8N( P0CUKBD](https://user-images.githubusercontent.com/19620848/159619171-7f1945dc-6492-4523-80ef-43c504488229.jpg)
![6MB5)I4@~ %5BVO6E4{M} E](https://user-images.githubusercontent.com/19620848/159619193-1e20a324-7a6b-48c5-a09a-593a9f9f5c2b.jpg)
![M7$PP7 DH~NH8 $5}WY4Q~J](https://user-images.githubusercontent.com/19620848/159619221-34df5679-63e9-4df0-a6eb-872930820876.jpg)

**Comment by KuroPeach** [comment]
But the strange thing is that the star map recipe with tags can be displayed normally
![image](https://user-images.githubusercontent.com/19620848/159623948-345aef9b-1f6d-4b31-9989-514155c05171.png)

**Comment by MuteTiefling** [comment]
Guess not much choice here but to convert these so they no longer use tags on the external items...
