### ISSUE TITLE
Smooth Boot giving server connection issues. 

### ISSUE THREAD

**Issue by dog38145** [EnigmaticaModpacks/Enigmatica6#4467]
### Modpack Version

1.0.0

### Describe your issue.

Server started disconnecting every player with the timed out exception after about a week of smooth sailing. Removing Smooth Boot from the mod list has allowed the server to run fine again. 

The latest.log doesn't show smooth boot stuff but the debug.log does. I was concerned by the amount of times it initialized "Worker Main" so I tried deleting it. Might have been a coincidence I guess, but it worked.

### Latest Log

https://gist.github.com/dog38145/f86c822cf32be47192daa115c5bb89f3

### Have you modified the modpack?

Yes

### User Modifications

Added two mods:
https://www.curseforge.com/minecraft/mc-mods/dcintegration
https://www.curseforge.com/minecraft/mc-mods/auto-restart

Removed Smooth Boot afterwards to fix the issue.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by dog38145** [comment]
https://gist.github.com/dog38145/404abc0fa6d41e507d8565cbbad485b2

**Comment by NillerMedDild** [comment]
Thanks for the report, could you please try to repeat this issue without the mods you added? :)

**Comment by dog38145** [comment]
Alright, will try uploading the mod back and removing those two when the server is less active again later today. Give me roughly half a day I think lol

**Comment by dog38145** [comment]
Hm. Can't replicate instantly but then again the issue only arose after a few days of the server running. I'm going to leave Smooth Boot and those two mods in until it gives those errors again, then I'll get rid of the two. This might take a little while unfortunately as I'm not sure what triggered the issue :|

Should I leave this open for now?

**Comment by NillerMedDild** [comment]
Yes please 😀

**Comment by dog38145** [comment]
Alrighty it's happening again. I have removed those two extra mods and it appears that the server isn't letting me in. 

Latest: https://gist.github.com/dog38145/40aa0630f4cda797a6e74c5611d1b7fe
Debug: https://gist.github.com/dog38145/cf81c4b51f944ed64872aec8c9b67630

Deleting Smooth Boot fixed the issue once again

**Comment by NillerMedDild** [comment]
Awesome, thanks! Smooth Boot will be removed in the next update :)
