### ISSUE TITLE
TerraForged structure generation is deadlocking server

### ISSUE THREAD

**Issue by TheWalrusman** [EnigmaticaModpacks/Enigmatica6#4468]
### Modpack Version

1.0.0 Expert

### Describe your issue.

When generating new terrain and a TerraForged structure attempts to spawn it has a chance to deadlock the server.

### Crash Report

https://gist.github.com/TheWalrusman/86ca4bc1428605aa434e5c8e2f0d366f

### Latest Log

https://gist.github.com/TheWalrusman/dc9536c05605e2864f16dcca36dd58c0

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report!
Do you happen to know which structure is causing the issue? 
Could you provide a VisualVM snapshot of the deadlock?

**Comment by NillerMedDild** [comment]
Possibly covered in #4479

**Comment by TheWalrusman** [comment]
@NillerMedDild 
I have seen that #4479 log in my server and that has never locked the server.
This actually may be a non-issue as it seems that my server PC was getting close to max RAM usage at the time of the issue. I have since upgraded the RAM amount and have never seen the issue again.
