### ISSUE TITLE
Alex's Mobs Seagull - Add Everlasting Beef/Eternal Steak to Seagull Stealing Blocklist

### ISSUE THREAD

**Issue by Zeranny** [EnigmaticaModpacks/Enigmatica6#4470]
### Describe your suggestion

Seagulls are able to steal the Everlasting Beef & Eternal Steak artifacts. They should be added to the blacklist.

### Why would you like this added/changed?

It doesn't seem great to have what seem to be relatively rare artifact items lost to a mob interaction. Especially if it goes unnoticed and the item cannot be recovered from the seagull.

**Comment by MuteTiefling** [comment]
now that's efficiency :D

**Comment by NillerMedDild** [comment]
IKR :D
