### ISSUE TITLE
Expert - possible repeated boss fight required to progress through adept magic chapter

### ISSUE THREAD

**Issue by zifnab06** [EnigmaticaModpacks/Enigmatica6#4477]
### Modpack Version

1.0.0

### Describe your issue.

It's possible to need to defeat Swampjaw twice to progress through the Magic - Adept chapter. 

Steps to reproduce: 
- Complete "Blank Rune", "Fossil Bait", and build a tier 2 blood altar. Do not complete "Sacrificial Knife"
- Summon/Defeat Swampjaw
- Craft Caged Heart, turn it into an Apprentice Blood Orb in your tier 2 blood altar. 
- Realize you never completed the sacrificial knife, make one. 
- "Blood Alter - Tier 2" will not complete until you make a second Caged Heart, requiring a second Swampjaw fight. 

Reversing the dependency between "Sacrificial Knife" and "Blood Altar - Tier 2" would fix this (this dependency seems a bit strange anyways, you need a tier 2 blood altar to craft the knife, but the knife is a pre-req for a quest named tier 2 blood altar). 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
@MuteTiefling is this intended? :)

**Comment by MuteTiefling** [comment]
Will double check but I thought I already changed this dependencies in dev

**Comment by MuteTiefling** [comment]
Yeah, dev already has the fix: 
![image](https://user-images.githubusercontent.com/9543430/159767057-d6cb553d-7ccf-423b-9fc9-e478badb4c6d.png)
