### ISSUE TITLE
I-Chisel does not function (Expert)

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#4478]
### Modpack Version

1.0.0

### Describe your issue.

I was playing with a few peeps on a server earlier today and I made an I-Chisel for more durability and the better GUI, but for some odd reason I could not use it, I couldn't change blocks in the world or right click it to open the GUI. I gave it to others to see if they had the same problem, which they did. I don't think this is intended because I can't think of anything that would have it removed. (Note: it was not disabled by server admins)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Remove starlight x create mod, the mod wasn't supposed to make it in to the pack, but did accidentally... Unsure if it needs to be removed from both client and server for you to connect to the server with it removed

**Comment by FooterMan14** [comment]
I see, thanks for your help :D
