### ISSUE TITLE
Server - Locking when structures generate above build height

### ISSUE THREAD

**Issue by YoItSoul** [EnigmaticaModpacks/Enigmatica6#4479]
### Modpack Version

Enigmatica6-1.0.0.zip

### Describe your issue.

When players are exploring, it appears that the server soft crashes (never stops responding) when structures such as the air ship are generated above the world height. Players cannot move and console in unresponsive to commands other than killing the java PID.

This is simply speculation but some of my players have connected when/where the issues occur.

The only error I could catch from the logs appear as: 

```[Server thread/WARN] [minecraft/Chunk]: Tried to load a block entity for block Block{minecraft:air} but failed at location BlockPos{x=-8424, y=261, z=-2747}```

(*no crash report, since it never stopped entirely, just locked up*)

### Latest Log

https://gist.github.com/YoItSoul/ad41863bf827c3b2acd954b25677f317

### Have you modified the modpack?

Yes

### User Modifications

The only modification we have to the modpack is a "welcome" quest and Discord integration.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report - I found it reported on their tracker here: https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/issues/38

**Comment by theboo** [comment]
Any chance you could grab a screenshot of the structure at that location?

**Comment by YoItSoul** [comment]
> Any chance you could grab a screenshot of the structure at that location?

Literally can't. Server locks up when loading the chunk.

**Comment by YoItSoul** [comment]
Requires myself to edit the playerdata position in order to unlock the server.

**Comment by theboo** [comment]
Damn, alright... Well I'm going to disable these structures for the next update, was hoping to see what this one was specifically... After disabling you'll prolly just need to delete those chunks and should be good I would think

**Comment by YoItSoul** [comment]
@theboo So it appears that the issue is primarily coming from the airships as they tend to be the only structure that can spawn x high above an already high world gen.

**Comment by YoItSoul** [comment]
Multiple sources have confirmed that the "cursed chunks" as my community calls them, contain air ships. - Specifically the ones that may have phantom mounted enemies?

**Comment by theboo** [comment]
yup yup, ty... i spoke with the dev of dungeons arise and was told which structures to disable... this wont help those chunks tho, after next update when those structures are disabled, u will have to delete those chunks to purify the curse xD
