### ISSUE TITLE
Questline tech computer sience Liquide Compressor Recipe

### ISSUE THREAD

**Issue by ferrium42** [EnigmaticaModpacks/Enigmatica6#4481]
### Modpack Version

Enigmatica expert last release

### Describe your issue.

I stuck - the progression line suggested to make the liquide compressor from pneumatic craft - but it needed a advanced printed circuit board that run down the crafting line to pneumatic craft thermopneumatic processing plant which need compressed air ??? - so i look at all compressor from pneumatic craft and find the thermal compressor so i will try to use those - overlook i something ?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
There are two routes to advanced PCBs.

**Comment by ferrium42** [comment]
ok , yeah after looking a long time in jei i find the problem i was run into - i missed the create recipe for circuit backplane and not know that i can make it in the new immersive table - but i´m not the only one see lashmak video - perhaps a litte more explanation will help

**Comment by MuteTiefling** [comment]
What would have helped you, do you think?
