### ISSUE TITLE
Issue crafting Ironjetpacks Hardened Jetpack due to NBT issue with water bucket

### ISSUE THREAD

**Issue by Jyrath** [EnigmaticaModpacks/Enigmatica6#4484]
### Modpack Version

1.0.0 expert

### Describe your issue.

#MLG-YOLO infinity buckets looted from Loot Chests have only 2 NBT tags, and don't seem to work for the Hardened Jetpack recipe
`Item.of('minecraft:water_bucket', "{display:{Name:'{\"text\":\"#MLG-YOLO\"}'}}").enchant('minecraft:infinity', 1)`
![image](https://user-images.githubusercontent.com/54685113/159765560-bb7a72c2-a1df-4295-957d-b9058b22fddf.png)

#MLG-YOLO infinity buckets manually crafted by the player have 3 NBT tags, and work correctly:
`Item.of('minecraft:water_bucket', "{RepairCost:0,display:{Name:'{\"text\":\"#MLG-YOLO\"}'}}").enchant('minecraft:infinity', 1)`
![image](https://user-images.githubusercontent.com/54685113/159765626-525205bd-b2b4-4e8c-81ce-05a6862d3bac.png)

The RepairCost NBT tag is added when the user renames the bucket in the anvil.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.

The recipe only looks for the specified name and the infinity enchant, so I'm surprised only one of those is accepted.

**Comment by NillerMedDild** [comment]
I was able to craft the jetpack using this bucket: `Item.of('minecraft:water_bucket', "{display:{Name:'{\"text\":\"#MLG-YOLO\"}'}}").enchant('minecraft:infinity', 1)`
Are you certain the looted bucket had that info?

**Comment by Jyrath** [comment]
https://user-images.githubusercontent.com/54685113/160305823-71ebc3e1-c7fc-47d4-b587-b87a105cc12b.mp4

![image](https://user-images.githubusercontent.com/54685113/160304728-9da88ec6-ee40-463d-9548-677ea3701e49.png)
I can 100% confirm that the non-working bucket is:
`Item.of('minecraft:water_bucket', "{display:{Name:'{\"text\":\"#MLG-YOLO\"}'}}").enchant('minecraft:infinity', 1)`

using the command:
`/give @p minecraft:water_bucket{display:{Name:'{"text":"#MLG-YOLO"}'},Enchantments:[{id:"minecraft:infinity",lvl:1}]} 1`
or
`/give @p minecraft:water_bucket{RepairCost:0,display:{Name:'{"text":"#MLG-YOLO"}'},Enchantments:[{id:"minecraft:infinity",lvl:1}]} 1`
both give a non-working bucket.
Changing the name of a non-working bucket to anything, then back to "#MLG-YOLO" then allows the bucket to work for the recipe.

![image](https://user-images.githubusercontent.com/54685113/160304781-432453e7-dc49-46e0-bef9-5ec6b5926dfc.png)
The working, self-crafted bucket is:
`Item.of('minecraft:water_bucket', "{RepairCost:0,display:{Name:'{\"text\":\"#MLG-YOLO\"}'}}").enchant('minecraft:infinity', 1)`

All of the ingredients in the recipe are unchanged, except for the #MLG-YOLO infinity water bucket.

NBT explorer:

![image](https://user-images.githubusercontent.com/54685113/160305034-490b62b1-e6dc-4fa2-90a0-2aab2d89b0e7.png)


maybe my buckets are cursed

**Comment by MuteTiefling** [comment]
I'm convinced the loot table is borked here, but I don't understand how or why. I've tried forcing this to specifically require the one from the loot table, and it won't work. And all other attempts to make it work with anything, just result in it only working with hand crafted ones, or loot table ones that get modified on an anvil...

**Comment by MuteTiefling** [comment]
yep! NBT was cursed. The fix won't help your old buckets, but you know already you can fix those by renaming them. New buckets work as expected.
