### ISSUE TITLE
PNC:R Refinery crash when > 2 outputs are present in a setup producing only 2 products

### ISSUE THREAD

**Issue by SammyWhamy** [EnigmaticaModpacks/Enigmatica6#4485]
### Modpack Version

Expert 1.0.0

### Describe your issue.

The game crashes when you put a 3rd refinery output ontop of a setup that only produces 2 products. More info in the comment below

### Crash Report

https://gist.github.com/SammyWhamy/c8a2b9961dc03e7a2c3ef06aea0749d6

### Latest Log

https://gist.github.com/SammyWhamy/53b2f65df97edac87aef68d845b939d7

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SammyWhamy** [comment]
I found a setup which reproduces this issue. Notably, the game ran fine until I placed a third processing output on top of the other 2, before the placement even rendered, my game crashed.

Crash logs from this setup:
https://gist.github.com/SammyWhamy/634cfbe33299b7f764a394a82926b202

Setup:
![image](https://user-images.githubusercontent.com/45788465/159801898-b40e79e1-cf46-458a-8ff3-89b430fb1690.png)
![image](https://user-images.githubusercontent.com/45788465/159801943-9e5a57ca-6f94-4a76-8423-e5cfc6204dac.png)

It seems to happen consistently when there is:
1. Brine or water in the refinery controller (These give 2 outputs)
2. Enough heat to make the refinery output other products

As soon as you place a third refinery output on top, a crash happens. With the temp-fix below turned on, I can still see the crash take place in the console, however it is suppressed and the refinery continues as normal.

Note:
Setting
`removeErroringTileEntities = true`
In `minecraft\saves\world\serverconfig\forge-server.toml`
Allows the machine to work fine. It doesn't seem to remove any blocks and the machine runs properly.

**Comment by NillerMedDild** [comment]
Thanks for the report! Would you mind relaying this to https://github.com/TeamPneumatic/pnc-repressurized/issues ? :x

**Comment by Darkere** [comment]
Probably a good idea to test updating PNC first. I believe we are already a few versions behind.

**Comment by desht** [comment]
Happened to spot this one, although a PNC issue hasn't been raised yet.  Updating won't fix the problem, but the good news is it's a trivial fix and I'm just about to do a new 1.16.5 release anyway so I'll get this fixed too.

(It is indeed a case of custom recipes not being handled as they should, and the issue title describes the problem accurately; this bug wouldn't occur with the default refinery recipes)

**Comment by desht** [comment]
Just to note that 2.15.5 (available now) fixes this.

**Comment by NillerMedDild** [comment]
Noo, I updated too soon 😅

**Comment by desht** [comment]
Blame Curseforge, I uploaded that release last Friday and they sat on it for a day and a half :smile:
