### ISSUE TITLE
PCBee , IronBee Not detecting

### ISSUE THREAD

**Issue by Xashz** [EnigmaticaModpacks/Enigmatica6#4488]
### Modpack Version

E6E - 1.0.0

### Describe your issue.

Hi , Im trying to make pcbee and the chamber is accepting the lub bucket and the helmet but not the iron bee jar , i check the nbt its 45 , i placed it down , made new in breeder (apairy) and still either 45 , 47 or 49 nbt and i see the jei it says nbt 3 , i tried diff methods of transfering items still takes the other 2 but not the bee

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
Can we get some screenshots? I've had this work fine for me before, and I'm pretty sure others have too.

**Comment by Xashz** [comment]
its just a chest with 3 items and it pulls 2 but not the bee in
can u plz specify what screenshot u need?

**Comment by Rodg88** [comment]
Only time I've seen this before is when the config files for the bee are edited to be invalid. Maybe the iron bee config got corrupted or edited?

**Comment by TemperedFool** [comment]
> its just a chest with 3 items and it pulls 2 but not the bee in
> 
> can u plz specify what screenshot u need?

Anything that would help indicate what is wrong. Pictures of your setup, the bee in question, anything else that might help.

I agree with Rodger, solid chance something in your install is corrupted. Might be worth reinstalling your instance and seeing if that helps.

**Comment by MuteTiefling** [comment]
Since you're playing on a server, try crafting this in Single Player. More likely that the server itself is borked.

**Comment by Tarod7** [comment]
I have this issue too. Maybe a metadata thing? I'm going to breed a new bee and see if it works

**Comment by Tarod7** [comment]
new bee did not work, going to try upgrading server to new version tomorrow.

**Comment by Tarod7** [comment]
Worked on 1.2
