### ISSUE TITLE
Starlight causes server hang on startup

### ISSUE THREAD

**Issue by themaster402** [EnigmaticaModpacks/Enigmatica6#4489]
### Modpack Version

E6E - 1.0.0

### Describe your issue.

A server of mine, after a regular restart, began to hang for the full 10 minutes of max tick time immediately after loading finished and subsequently crash. After troubleshooting and seeing others' similar issues and fixes, it seems the Starlight mod causes this hang.

The attached log is the first instance of the hang happening.

### Crash Report

https://gist.github.com/themaster402/f1d28d5e82572e4e19187089444331db

### Latest Log

https://gist.github.com/themaster402/50402cc48b219e4393f7263bda770482

### Have you modified the modpack?

Yes

### User Modifications

Discord Integration mod
https://www.curseforge.com/minecraft/mc-mods/dcintegration

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Starlight will be removed :)

**Comment by TheDragonicSlayer** [comment]
Oh but it reduced lag so much!

**Comment by MuteTiefling** [comment]
It's also breaking things, which is no bueno.
