### ISSUE TITLE
Sophisticated backpacks without inception upgrade can be placed in shulkers, which can be placed in backpacks, ad infinitum

### ISSUE THREAD

**Issue by Old-Man-D** [EnigmaticaModpacks/Enigmatica6#4490]
### Modpack Version

1.0.0

### Describe your issue.

I have noticed that I can put backpacks in a shulker, then into a backpack, etc.  Seems like a recipe for NBT disaster.  I am not sure if this is intentional or not.  Note, I do not have any inception upgrades on anything.  

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
The good news is sophisticated backpacks don't store the items inside as nbt on the backpack item... It's more similar to how refined storage stores items, like carrying around a super full RS storage disk

**Comment by NillerMedDild** [comment]
Known and intended :)
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/144
