### ISSUE TITLE
Partial cokebrick not craftable after placing

### ISSUE THREAD

**Issue by Arxxer** [EnigmaticaModpacks/Enigmatica6#4493]
### Modpack Version

1.0.0

### Describe your issue.

After placing a partial cokebrick (cokebrick that's in the middle of a sequencial assembly) it won't keep crafting, the deployers completly ignore the block.

This happened on the third itineration of the craft

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This'll be fixed next release. In the meantime, I strongly encourage you to automate this, rather than moving the interim item around by hand.
