### ISSUE TITLE
Terminite Ingot too easy to obtain

### ISSUE THREAD

**Issue by DAmNRelentless** [EnigmaticaModpacks/Enigmatica6#4495]
### Modpack Version

Expert 1.0.0

### Describe your issue.

The Terminite Ingot from BetterEnd Forge usually takes Thallasium Ingots and Ender Dust. However, the recipe with Iron Ingots is still enabled in the Immersive Engineering Alloy Kiln.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Huh, that's odd. @MuteTiefling do you know if there is a reason for this, or is it just a weird bug we made? 😄

**Comment by MuteTiefling** [comment]
Think it's just an oversight.
