### ISSUE TITLE
Allow Composter to extract/insert from all sides

### ISSUE THREAD

**Issue by scotty9090** [EnigmaticaModpacks/Enigmatica6#4496]
### Modpack Version

1.0.0

### Describe your issue.

1. Craft a composter
2. Ensure the result is from the mod Compote
3. Place in world but it becomes a vanilla composter (per TOP), and receive a vanilla composter when breaking.

Am I missing something?

### Have you modified the modpack?

Yes

### User Modifications

Added CarryOn.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
This is normal. It's just how the mod works.

**Comment by scotty9090** [comment]
Okay, but then what is the point of the mod?  I was hoping to be able to hopper into the side - something that the mod's page says it supports, but that doesn't work (unsurprisingly since I end up with a vanilla composter in world.)  

I can open an issue on the Compote page.  I just feel like I'm either completely missing the point of this mod, or something is wrong.

**Comment by NillerMedDild** [comment]
We added it to be able to make non-compostqble items compostable through datapacks :)

I don't see any harm in enabling the last two configs though.
