### ISSUE TITLE
Mod Loading error has occured

### ISSUE THREAD

**Issue by Corruptedtouch** [EnigmaticaModpacks/Enigmatica6#4497]
### Modpack Version

1.0.0

### Describe your issue.

Server crash on boot attempt (first boot).

Unable to run server for even the first time.

### Crash Report

https://gist.github.com/Corruptedtouch/5765b92d7b217a834437b709badfa0a3

### Latest Log

https://gist.github.com/Corruptedtouch/3b184208672fa6dc388264c26e3a2b19

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Corrupt install, please reinstall :)

**Comment by Darkere** [comment]
OpenJ9 does not work with the current pack.

**Comment by Corruptedtouch** [comment]
Thaaaaats probably what it is then. I'll check that next time I get a
chance.

Thanks you
