### ISSUE TITLE
Impossible to extract blood from mushroom and tree

### ISSUE THREAD

**Issue by MrReps** [EnigmaticaModpacks/Enigmatica6#4499]
### Modpack Version

1.0.0

### Describe your issue.

Can't get any blood from arboreal extractor. 
I have tried many different spawning of blood tree or mushroom (in overworld) and i can't make the treee extractor reconize the tree. I think it's due to a 3rd block spawning for mushroom and incomplet tree for tinker.

Also i'm not placing block by and and i don't modify anythink of the tree. I tried for 1h and half with both and noone work. 

Thanks

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I can't get it to work either 🤔 I wonder if there's a trick to it, or if the "tree" just isn't recognized.

**Comment by MuteTiefling** [comment]
I seem to recall this being an actual tree early on in tinkers, then changed to a shroom. Might just have to remove it.

**Comment by NillerMedDild** [comment]
Damn, it was a cool feature ._.

**Comment by TemperedFool** [comment]
Maybe there's another tree we can swap to? Maybe one of the tinkers ones?

**Comment by TheDragonicSlayer** [comment]
There's blood shroom trees

**Comment by TheDragonicSlayer** [comment]
Tinkers has Bloodshroom trees which spawn in the nether on islands that have congealed blood and ichor. Pretty sure they're called bloodshroom trees. It could probably be used

**Comment by MrReps** [comment]
That the problem. Bloodshroom Tree aren't recognize. Maybe it work if the tree is directly from nether, but In my case with a spawn with the sapling it can't work, even if I tried 1000 times.

**Comment by TheDragonicSlayer** [comment]
Maybe it's because its from a Fungus and not a sapling

**Comment by FooterMan14** [comment]
Do other nether related trees work with arboreal extractor/fluid extractor to get fluids out? (Crimson, Warped, etc)

**Comment by MuteTiefling** [comment]
some will, yes. I have an idea here, just need to test it

**Comment by Voidion** [comment]
Found the issue, the Block Class of the Blood Slime Leaves is SlimeWartBlock, so Thermal must be looking specifically for the Leaves class
