### ISSUE TITLE
Clarify Requirements for Industrial Deuterium Plant in Quests

### ISSUE THREAD

**Issue by FuturePot** [EnigmaticaModpacks/Enigmatica6#4503]
### Modpack Version

E6E 1.0.0

### Describe your issue.

For enigmatic tree of life, There are three Brown Mushroom (from mod "Chipped") near the tree roots will drop on the floor when I use building gadgets patterns to build the tree.

For industrial deuterium plant, first thing is the blueprint and building gadgets patterns don't mention that I should put it on the water. I found it when I open the structure file, the 4th layer to 8th layer should contain water. Second thing, blueprint shown that there should be 4 tesla coil in the strcture, but building gadgets just use two. They both work.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
#4406 please update

**Comment by MuteTiefling** [comment]
Hrm, went too fast there. I'll have a look at the deuterium plant. But the tree is already fixed.

**Comment by MuteTiefling** [comment]
Alright. Seems we forgot to even put the quest in for this. That's fixed now and covers the water requirements. 

I could not replicate your issue with multiple Tesla coils, however. Pasting in both with Building Gadgets and the Schematicanon resulted in identical structures.
