### ISSUE TITLE
MAGIC workbench

### ISSUE THREAD

**Issue by FuturePot** [EnigmaticaModpacks/Enigmatica6#4504]
### Modpack Version

E6E 1.0.0

### Describe your issue.

This workbentch should be banned.
![YB_@_VW2P85 M6WST$POAFJ](https://user-images.githubusercontent.com/102435609/160257012-e7f9eb57-6c86-4802-9e9d-e5d86a3f5a25.png)
![(40%I~F`OY0BAE~{AF7MEY7](https://user-images.githubusercontent.com/102435609/160257022-c226a308-0160-4f69-810b-7ee74fcf8b0b.png)
![T){K ZDWFE$PPC~OJCQC`}G](https://user-images.githubusercontent.com/102435609/160257026-c3b4b369-5c7f-4a1c-98e1-b81654a674a8.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Darkere** [comment]
It has been :D in version 1.0.1
