### ISSUE TITLE
/mode expert instructions unclear

### ISSUE THREAD

**Issue by myavkat** [EnigmaticaModpacks/Enigmatica6#4506]
### Modpack Version

Expert 1.1.0

### Describe your issue.

"Expert mode" quest in the enigmatica 6 expert 1.1.0 tells players to run /mode expert command to play in expert mode. When player runs "/mode expert" command it gives an error about reload command not working as in the picture below:
![image](https://user-images.githubusercontent.com/77459135/160281084-2abb3f06-105b-4acb-8a52-c3455740413c.png)
When I shared this with people on discord they said that command is not required in expert pack. So I suggest this quest to be removed from expert pack or to add to the description of the quest to something like "If you are playing in expert pack you dont need to run commands".

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
You can run /mode to see which mode you are in. Although it looks like I screwed up making the command available in sp.

**Comment by NillerMedDild** [comment]
We'll sort out the quest description too, thanks 👍
