### ISSUE TITLE
Enigmatica 6 Expert - Cannot place Soul Enchanter in the nether even after crafting new lesser tartaric gem

### ISSUE THREAD

**Issue by PiratePete1911** [EnigmaticaModpacks/Enigmatica6#4508]
### Modpack Version

1.1.0

### Describe your issue.

Cannot place Soul Enchanter in the nether even after crafting new lesser tartaric gem, I had one before the update but I crafted a fresh gem and it still would not let me place it.

My friend on the server also tried crafting a fresh gem and he cannot place it either.

### Have you modified the modpack?

Yes

### User Modifications

I have edited the config for Waystones to not cost XP.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Please read the tooltip of the soul enchanter carefully

**Comment by MuteTiefling** [comment]
Nah, I think I goofed up the quest on this. Will take a look later. Thanks for the report

**Comment by Darkere** [comment]
tbh it might be a good idea to change the recipe to require something from the hellfire forge. The tooltip/quest is easy to overlook if you know that the thing is pretty good.

**Comment by MuteTiefling** [comment]
the recipe does require a tartaric gem. But it was super cheap before. I wanted to be sure that anyone who had the item from before couldn't place it until they had at least crafted the tartaric gem.
