### ISSUE TITLE
gatling gun from guns w/o roses will not craft in mechanical crafters

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica6#4509]
### Modpack Version

expert 1.0

### Describe your issue.

tried to craft the gatling gun and it starts the craft and all the pieces go into tetris mode but when it gets to the end, all the items spill out on the ground.  did this twice.

https://cdn.discordapp.com/attachments/947932229143760957/957669272140800021/2022-03-27_08.54.53.png

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
At some point the mechanical crafter started caring about nbt. Gonna go through all these recipes and try to fix anything that might have nbt on it.

**Comment by MuteTiefling** [comment]
Ok, so after a whole lot of testing and banging my head against the wall, I realized you were probably making the same mistake as I had been: You have the recipe wrong. 

It is not 3 Encased Chain Drives. It is 2 Encased Chain Drives and 1 Adjustable Chain Gearshift. Can you try it again?
