### ISSUE TITLE
[Expert] Quest Update - Allow Superheated Steel ingot quest under Mechanical Mayhem to accept block variants

### ISSUE THREAD

**Issue by SinKane-MC** [EnigmaticaModpacks/Enigmatica6#4511]
### Describe your suggestion

It would be helpful for the quest  line to accept the block variant of the Superheated  Steel Ingot, Hot Compressed ingot and Compressed ingot quests.

### Why would you like this added/changed?

There is a lot of hoping around in the quest book, I was working on PNC and as you know in Modded more is usually better so I crafted the Block variant, not realizing the questline only accepted the ingot form.

**Comment by MuteTiefling** [comment]
Yep sounds like a good idea.
