### ISSUE TITLE
[EXPERT] Cannot craft Ars Elemental's Elemental Foci

### ISSUE THREAD

**Issue by Hans6677** [EnigmaticaModpacks/Enigmatica6#4522]
### Modpack Version

1.0.0

### Describe your issue.

Attempting to craft the Focus of Water via the Occultism Ritual: Sevira's Permanent Confinement will yield no results and consume all offered items after the sacrifice of the Blizz.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
I'm completely unable to reproduce this right now:

https://streamable.com/27aao6

Will try again in a minute on a server, but it seems to be working fine.

**Comment by MuteTiefling** [comment]
Finally was able to test on a server and I'm still unable to reproduce this. Do you have any other details you can add to this? Is it possible something is just picking up the focus before you get it?

**Comment by Hans6677** [comment]
Seems to work now after we updated to 1.1.0. It kept failing on 1.0.0 though.
