### ISSUE TITLE
Appearing offline?

### ISSUE THREAD

**Issue by Same14** [EnigmaticaModpacks/Enigmatica6#4523]
### Modpack Version

1.0.0

### Describe your issue.

Im trying to go onto a server but appearing offline when on the pack? 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Can you join the server anyway? :)
Which launcher are you using?

**Comment by Same14** [comment]
yeah nvm fixed it D:
