### ISSUE TITLE
Dupe glitch using engineers circuit 

### ISSUE THREAD

**Issue by Floppa-8765** [EnigmaticaModpacks/Enigmatica6#4528]
### Modpack Version

Expert 1.0.0

### Describe your issue.

if you have the items to make a circuit, click the thing to craft it, and shift click the output then it doesnt consume the items.

video is too large to upload to github, https://cdn.discordapp.com/attachments/947932229143760957/958448503737171979/Badlion_Client_2022.03.29_-_15.31.04.03.mp4

### Latest Log

https://gist.github.com/Floppa-8765/c86025eb0ac76b489e14ab00884fc66f

### Have you modified the modpack?

Yes

### User Modifications

added Easy Villagers and JER Integrations

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5109

**Comment by MuteTiefling** [comment]
Duplicate #3866
