### ISSUE TITLE
[Expert] Spirit Magic quest request  patty tartaric gem but have dependency with Blood magic Part two gate, That request common tier gem to craft? That backward progress.

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4529]
### Describe your suggestion

It just seem not right that ,to unlock  Spirit Magic quest  that need just patty tartaric gem but it have dependency with blood magic pt2 that request Demon Crucible that need common teir gem , and with in quest line of Magic Master page also request that demon crucible again. Why not start Blood magic part 2 with Hellfire Forge? or someting around that?

### Why would you like this added/changed?

 start Blood magic part 2 with Hellfire Forge or someting around that.

**Comment by MuteTiefling** [comment]
Thanks for the report. Please update and you'll find this has been fixed. #4457
