### ISSUE TITLE
Enigmatica 6 Expert Blood Magic 3 Demon realm Not generated Demon Stone Tile Slab

### ISSUE THREAD

**Issue by TianMing911** [EnigmaticaModpacks/Enigmatica6#4531]
### Modpack Version

1.1.0

### Describe your issue.

Opened dozens of demon fields, and no room was generated Demon Stone Tile Slab

### Crash Report

No response

### Latest Log

No response

### Have you modified the modpack?

No

### User Modifications

NO

### Did the issue happen in singleplayer or on a server?

Server

**Comment by UraraChiya** [comment]
The Stellar Neutron Activator needs Demon Stone Tile Slab to build. I can't find its recipe in JEI. Then I guess it'll be on the Edge of  Hidden Realm, but I can't find it there.

**Comment by MuteTiefling** [comment]
oops, that was meant to be craftable from demon stone tiles. Will get that fixed up
