### ISSUE TITLE
[Suggestion] Allow smelting EE crushed ores

### ISSUE THREAD

**Issue by Targren** [EnigmaticaModpacks/Enigmatica6#4532]
### Describe your suggestion

I'm not sure if it's intentional or an oversight, but EE crushed ores (e.g. the ones output by the Create millstone/crushing wheels) can't be directly put in a TiC smeltery/foundry without going through a furnace cooking process first.  

### Why would you like this added/changed?

It doesn't seem to add much other than slowing down the processing. It shouldn't change progression, since you've likely got vanilla blast furnaces out the wazoo by the time you have a smeltery and millstone, and by the time you have enough power infrastructure to use RF cooking methods to make it faster, you've probably gotten access to more profitable ore multiplication anyway.

**Comment by NillerMedDild** [comment]
Hmm, I don't see why not 🤔 Do Create Crushed Ores go into the Smeltery/Foundry?

**Comment by Targren** [comment]
> Do Create Crushed Ores go into the Smeltery/Foundry?

They currently do not.

**Comment by NillerMedDild** [comment]
In that case this is a no, the intended way to process them is through splashing anyway iirc :)

**Comment by Targren** [comment]
What's "splashing?"

**Comment by TemperedFool** [comment]
> In that case this is a no, the intended way to process them is through splashing anyway iirc :)

You can also process them via blasting, I think.

> What's "splashing?"

Create fan, blowing through water. Will splash, or wash, stuff that's in front of it. Doing so with one of the create chunks yields 10-15 nuggets.

**Comment by Targren** [comment]
Well that's certainly novel! I'll have to set that up then. Thanks!
