### ISSUE TITLE
Pretty Pipes 1.9.7 crashes when requesting items from terminals.

### ISSUE THREAD

**Issue by GzusO** [EnigmaticaModpacks/Enigmatica6#4534]
### Modpack Version

1.1.1

### Describe your issue.

Already reported to mod: https://github.com/Ellpeck/PrettyPipes/issues/122

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed in 1.1.2, out now :)
