### ISSUE TITLE
E6E - Pneumaticcraft Pressure Chamber Not Accepting Some Items on Dedicated Server

### ISSUE THREAD

**Issue by Ommina** [EnigmaticaModpacks/Enigmatica6#4543]
### Modpack Version

1.0.0

### Describe your issue.

OK, I did peek on Discord, and there was (that I found) one individual reporting the same problem on Tuesday, Mar 29, so I presume I'm not alone.

This issue appears to affect server play only.  The same setup works when attempted single player.

Short version: the pressure chamber will simply not accept some items part of a recipe.  The three items about which I know are:
```

tag: 'forge:wires/electrum'
tag: 'forge:plates/signalum'
tag: 'forge:plates/aluminum'

```
The player on Discord also mentioned Raw Basic Processor, but I have not checked.

Remaining two items of the recipe do insert fine.  And, again, all five work on single player.

/mode on the server reports it is in Expert mode (and frankly I don't know how it would have got this far if it were not.)

kubejs server.txt log seems happy loading _pressure_chamber.js_:

`[01:33:14] [INFO ] Loaded script server_scripts:enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js in 0.003 s`

(There are some "failed to parse recipe" warnings later, but they seem to exclusively refer to crops.)

Let's see -- I am using a different version of Forge on the client than I am on the server (36.2.29 vs 39.2.30).  I can't bring myself to believe that this matters, but if it does, it's probably worth noting somewhere!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Ommina** [comment]
Follow-up:

After starting the client today, JEI no longer shows the expert recipe for the item (`pneumaticcraft:transistor`), but gives the normal recipe instead.  The normal recipe _does_ craft successfully.

/mode still claims "expert", and any number of Pressure Chamber expert recipes are displayed by JEI.  But Transistor and Capacitor, at a minimum, are normal.

Server has not been restarted in the interim.

So, presumably, the server had normal recipes 12h ago, while the client's JEI showed the expert versions, and this is why the Pressure Chamber refused to accept the items.  Sadly, it doesn't really explain why the recipes are wobbling in the first place.

Thank you for looking into it.  I appreciate the original report is not wholly coherent.  I was tired!

**Comment by NillerMedDild** [comment]
Thanks for the additional info. I think you should re-install the server files and see if that fixes it :)
