### ISSUE TITLE
Oversized Stacks with thermal Packer

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4552]
### Modpack Version

1.0.0 Expert (checking newest now)

### Describe your issue.

Using the unpacking plate with the thermal press, if you put prismarine blocks in the press will not stop at 63 items but continue to 72 items in one slot, Im guessing this is a custom recipe and the press sees that it can process one more time when it has 63 items, and does so, rather than checking the quantity of the output stack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by theboo** [comment]
this is an intended feature in thermal machines in 1.16, can go over stack size in the outputs
