### ISSUE TITLE
StarLight

### ISSUE THREAD

**Issue by dodieboy** [EnigmaticaModpacks/Enigmatica6#4554]
### URL

https://github.com/PaperMC/Starlight/releases

### Why would you like the mod added?

I saw that there are many bug cause by starlight x create mod so it was removed, but I saw and tested that the official version of starlight (version 1.0.0-RC2) for forge 1.16.5 and it is working fine for me. Hope that it can be added to the pack which can improve the pack performance. Tested and do not see the problem in past issue report as follow:

- server hang on startup #4489 / world cannot load #4452
- I-Chisel #4478 #4353

**Comment by NillerMedDild** [comment]
The server hang / world not loading issues didn't appear for me either. I'd like to include this mod, but it's too risky :(
