### ISSUE TITLE
Shulkerbox in Backpack causes disconnect

### ISSUE THREAD

**Issue by zkwj** [EnigmaticaModpacks/Enigmatica6#4556]
### Modpack Version

Expert 1.0.0

### Describe your issue.

Clicking on a shulkerbox (with bees and nests causes) d/c:

`lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes`

After adding a number of bees and tier 0-2 hives into my shulker boxes, then placing them in my gold backpack, I get disconnected when trying to click any of the affected shulker boxes (currently two are stuck). Somewhat easy to reproduce.

![shulkerbees](https://user-images.githubusercontent.com/72935752/161382004-7711be8c-4996-43a6-8ec3-56563eeb9e60.png)
.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by zkwj** [comment]
I was able to get my shulker boxes out of the backpack by placing the backpack on the ground and using a hopper into an iron chest.

Moral of the story: don't put shulkers in the backpack

**Comment by MuteTiefling** [comment]
Sneak right click to place your backpack in the world. Then use a pipe to pull the shulker out.

Once it is out, don't put it back unless you clear out the bees. They have a ton of nbt data attached to them and are the source of your issue.
