### ISSUE TITLE
Advanced Machine Frame quest unable to be completed in Expert due to quest dependency

### ISSUE THREAD

**Issue by Jyrath** [EnigmaticaModpacks/Enigmatica6#4557]
### Modpack Version

1.1.2 expert

### Describe your issue.

The Advanced Machine Frame quest in the Industrial Foregoing chapter of the questbook is unable to be completed in Expert mode because the quest is dependent on the Mob Slaughter Factory quest, which is disabled in Expert.

![image](https://user-images.githubusercontent.com/54685113/161399739-83bf860d-2018-4818-8d6d-886a7ae2fc43.png)

Maybe the Mob Slaughter Factory quest can be changed to allow completion with either a Mob Slaughter Factory or Pink Slime Bucket?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Good idea 👍
