### ISSUE TITLE
Add Seared Stone recipe to the Magma Crucible [Expert Mode E6E]

### ISSUE THREAD

**Issue by b0bst3r** [EnigmaticaModpacks/Enigmatica6#4558]
### Modpack Version

1.0.0

### Describe your issue.

In the Equipment - Tinkers Construct chapter of the quest book you are asked to make a "Mighty Smelting" book by pouring seared stone onto a book.  This is before you've created the smeltery.  The melter is disabled in Expert mode and the Magma Crucible cannot melt seared stone.  

Either the quests need juggling around or Seared Stone needs adding to the Magma Crucible.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.
