### ISSUE TITLE
[E6E] - Allow any forge:cobblestone in Crushing Wheel cobblestone -> gravel recipe

### ISSUE THREAD

**Issue by Stians92** [EnigmaticaModpacks/Enigmatica6#4559]
### Describe your suggestion

Currently the Crushing Wheel and Millstone from Create specifically require vanilla cobblestone when making gravel.

![image](https://user-images.githubusercontent.com/16592521/161422324-b220a0fe-e709-48bf-9a99-d86eabaa0072.png)

I suggest allowing any forge:cobblestone to be used in the recipe instead, like has been done already for the Immersive Engineering Crusher, the Mekanism Crusher and the Thermal Series Pulverizer.

![image](https://user-images.githubusercontent.com/16592521/161422382-4f08d379-3ff0-40e5-aa59-3beb6b5a6e48.png)

### Why would you like this added/changed?

I am currently in need of sand, and because I have a ton of cobblestone I figured I'd go the cobblestone -> gravel -> sand route. However, due to world gen, most of my cobblestone is various versions like Limestone and Gabbro, which doesn't turn to gravel without getting into FE generating mods.

**Comment by MuteTiefling** [comment]
Can take another look, but I recall this breaking something... Some of the other stones are used to generate other resources in the create crusher I think.

**Comment by MuteTiefling** [comment]
Yeah, this ends up breaking a few fun recipes that I think are better to keep than to lose in this sort of standardization. Granite to Red Sand, for instance.
