### ISSUE TITLE
Archmage Armor uncraftable

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4560]
### Modpack Version

1.1.2 Expert

### Describe your issue.

Because of spell damage potions being bugged (see https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4102)
the change to the Wicked Weave recipe in 1.1.2 expert has caused archmage robes to become uncraftable. Was this an intended change to make the armor uncraftable or just oversight because of https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4544 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Duplicate #4102
