### ISSUE TITLE
Astral sorcery uncraftable recipes

### ISSUE THREAD

**Issue by ItsHimm** [EnigmaticaModpacks/Enigmatica6#4565]
### Modpack Version

1.0.0

### Describe your issue.

Astra sorcery recipes are not craftable past luminous crafting table, indication bar will not show either.

Recipes tried are:

Fluid laser base
Celestial Gateway
Telescope

### Latest Log

https://gist.github.com/ItsHimm/2e36b28da99977b36e357bff392c95b8

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

![image](https://user-images.githubusercontent.com/101298108/161466348-9ef74f9a-dfd6-4851-96fe-8c033acfe90f.png)

**Comment by NillerMedDild** [comment]
Why did you close this issue? :)
