### ISSUE TITLE
[Expert] Immersive Squeezer not buildable despite gamestage and build correct

### ISSUE THREAD

**Issue by gruff8** [EnigmaticaModpacks/Enigmatica6#4569]
### Modpack Version

dev branch b769db4c84b8bf6876a1ffd23c0ebd37852dbf50

### Describe your issue.

I have built the Medium Machinery Schematic and have constructed the squeezer using the projector which has turned green.
I still get the error message "Invalid structure or missing gamestage..."

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/8487636/161614133-6e9ff149-4a42-4deb-a814-3befc70b01cd.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
You need to right click the correct block with the engineer hammer, it will give that message otherwise... I think it's the red block?

**Comment by gruff8** [comment]
I spam clicked the whole structure and got it working.
It was the barrel under the piston while looking with the redstone engineering block to the right.
The same block looking at it with the redstone engineerng block on the left did not work.

Maybe a suggestion that this should be added to the error message.

Thanks.
