### ISSUE TITLE
Plastic Sheet Quest in Pneumaticraft not completing

### ISSUE THREAD

**Issue by vanpunch** [EnigmaticaModpacks/Enigmatica6#4573]
### Modpack Version

1.1.2

### Describe your issue.

"Plastic Sheets" Quest is not completing even though I ahve the required qty of sheets in my inventory.

### Latest Log

<script src="https://gist.github.com/vanpunch/fabaa57605637f7b0a2492336a9fb5bf.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Did you complete the dependencies?

![image](https://user-images.githubusercontent.com/9543430/161832927-7e1b653f-41ee-4577-a391-351d10cb65cb.png)

**Comment by vanpunch** [comment]
Woops, my bad.  Didn't realize you could see dependencies that way.
