### ISSUE TITLE
[E6E] Tinker Smeltery have the wrong amount output 

### ISSUE THREAD

**Issue by StarskyXIII** [EnigmaticaModpacks/Enigmatica6#4579]
### Modpack Version

1.0.0

### Describe your issue.

Put Utherium Ore in the Smeltery only output 32mb Molten Utherium.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.
