### ISSUE TITLE
Occultism Familiar summoning script

### ISSUE THREAD

**Issue by Tarod7** [EnigmaticaModpacks/Enigmatica6#4580]
### Modpack Version

1.1.2

### Describe your issue.

Auto-repair lost trinket makes the terminite Hammer unusable to summon blacksmithing familiar. Minor change to script fixed it.
I've attached the change. Basically just allowing other nbt options

Item.of('betterendforge:terminite_hammer', '{Damage:0]}').weakNBT(),

[ritual - Copy.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/8422449/ritual.-.Copy.txt)
 

### Have you modified the modpack?

No

### User Modifications

Unchanged till I changed that script.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Feel free to PR this change to the dev branch if you want!

**Comment by Tarod7** [comment]
I would, but I haven't learned Git yet :/

**Comment by MuteTiefling** [comment]
It's all good. I'll fix it up in a bit

**Comment by dodieboy** [comment]
I created a PR for u alr
