### ISSUE TITLE
[Quest][E6E] Wording aligned to Non-Expert - PNC 

### ISSUE THREAD

**Issue by b0bst3r** [EnigmaticaModpacks/Enigmatica6#4588]
### Modpack Version

1.1.2

### Describe your issue.

![image](https://user-images.githubusercontent.com/2760085/162215927-d69d5c48-a5cf-4df1-a03d-ebc449a325a2.png)

Technology - PneumaticCraft:Repressurized - Ethically Sourced quest

Quest wording is for non-expert - needs changing to encorporate superheated steel process.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report. This'll be fixed next release.
