### ISSUE TITLE
[Quest][E6E] Wording aligned to Non-Expert - PNC 

### ISSUE THREAD

**Issue by b0bst3r** [EnigmaticaModpacks/Enigmatica6#4589]
### Modpack Version

1.1.2

### Describe your issue.

![image](https://user-images.githubusercontent.com/2760085/162218865-86597615-2797-44bd-b5f3-564ac047d4eb.png)

Air Compressor is disabled in Expert mode, although the quest can be completed by making the fuel compressor the wording and ques doesn't align with Expert mode.  Next to the Air Compressor quest is the liquid compressor quest already.

Suggestion - move the pressure tube and valve required of the Air compressor quest (along with the rewards) to the liquid compressor quest and delete the air compressor quest completely.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
These quests serve both Expert and Normal. Concessions have already been made to allow it to be completed in Expert, but it won't be removed.
