### ISSUE TITLE
Sentient Pickaxe unable to mine naturally spawned Iesnium

### ISSUE THREAD

**Issue by thatGuyCalledMax** [EnigmaticaModpacks/Enigmatica6#4590]
### Modpack Version

1.1.2

### Describe your issue.

When mining Iesnium with the goggle equipped, mining a user placed block of iesnium would be mined correctly, but breaking a naturally spawned block of iesnium only resulted in netherrack being dropped
![iesnium failure](https://user-images.githubusercontent.com/103206589/162248342-cd3b7d1c-3cf5-4ff8-8928-326af5947214.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Toonlink264** [comment]
were you using an infused pickaxe or iesnium pickaxe. this is part of the mod.

**Comment by Toonlink264** [comment]
ohhh i see the issue. sentient pickaxe isn't mining when it says it should

**Comment by thatGuyCalledMax** [comment]
A sentient pickaxe from blood magic, but its tool tip says it should be able to mine iesnium

**Comment by Toonlink264** [comment]
until it's fixed the occultism quest for the goggles gives you 3 iesnium which is enough for a tinkers pickaxe which iesnium can mine itself

**Comment by thatGuyCalledMax** [comment]
Can also use an infused pickaxe too, since it doesnt need iesnium

**Comment by MuteTiefling** [comment]
I wonder if this has anything to do with it being 'activated' too... will test some more in dev here shortly.

**Comment by MuteTiefling** [comment]
Did you happen to get this one from the quests?

**Comment by MuteTiefling** [comment]
Confirmed on discord, pick axe was from quests/cheated in, meaning it won't have the correct NBT to break Iesnium. So removing it from the quest rewards should prevent others from having this issue in the future.
