### ISSUE TITLE
Dupe bug with IE multiblocks

### ISSUE THREAD

**Issue by SammyWhamy** [EnigmaticaModpacks/Enigmatica6#4591]
### Modpack Version

Expert 1.0.0

### Describe your issue.

You can dupe a few IE blocks (Radiator, steel scaffolding, reinforced blast brick, blast brick, kiln brick, coke brick, probably more but these are the ones I tested).

To do this all you need to do is get a Building Gadget, shift right click an IE multiblock, and then use the gadget to place down the multiblock, this animates like its placing the full block and then just spawns in a single glitched block, but you can mine these to get the abovementioned items

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
this is fixed in e6/e6e v1.1.0 and later
