### ISSUE TITLE
Cardboard boxes don't open on rightclick.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#4592]
### Modpack Version

E6E 1.1.2

### Describe your issue.

Packed up some stuff, and can't open it. First use of a cardboard box since fresh server start.

Nothing in the logs on either client or server side while attempting to rightclick the boxes.

Other player also appears to have issues with bee nests, not sure if related.

Java 1.8.0_321

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. Have you attempted to restart the server?

**Comment by Splutty** [comment]
Restarted the client, restarted the server, reinstalled the client, reinstalled the server. Other player can't unpack the boxes either.

Upgraded java from _311 to _321. None of that made any difference.

Tried opening it inside a claimed area, outside a claimed area.

I can break them and pick them up, but use/interact does nothing. No errors in either server or client log, no errors in game, nothing.

**Comment by Splutty** [comment]
Completely new server set up, no changes except setting a forced java path.

Log in, /op myself, clone a cardboard box, wrap a dirt block, try to use/interact to unpack, nothing.

Going to try MultiMC instead of GD as client now.

**Comment by Splutty** [comment]
MultiMC client: Exactly the same issue.

**Comment by Splutty** [comment]
Mekanism cardboard, by the way, but I thought that was obvious :)

**Comment by RobuxShooters** [comment]
Just to confirm, are you sneaking when right-clicking the cardboard box to unpack it?

**Comment by Splutty** [comment]
*sigh* I was 100% certain I tried that. But apparently not. Thanks. I feel stupid now. Also damn you people in Discord for not telling me that :D Hehe.
