### ISSUE TITLE
Add Quark Myalite to Custom Cobble/Stone Generator

### ISSUE THREAD

**Issue by jwalty** [EnigmaticaModpacks/Enigmatica6#4602]
### Describe your suggestion

Add Quark's Myalite block to the custom cobble/stone generators

### Why would you like this added/changed?

Quark Myalite is just another stone replacement with some cool color effects but afaik is only available in The End. Would be cool to make more at home.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by MuteTiefling** [comment]
Doesn't appear to cause any issues :D
