### ISSUE TITLE
[E6E]Hepatizon recipe has different ingredients

### ISSUE THREAD

**Issue by b0bst3r** [EnigmaticaModpacks/Enigmatica6#4603]
### Modpack Version

1.1.2

### Describe your issue.

Hepatizon ingot - Copper, cobalt and obsidian in the Induction Smelter
In the smeltery - copper, cobalt and quartz

Not sure if this is a bug or intended so I asked in discord and was asked to pop this on Github.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.
