### ISSUE TITLE
Saplings have tags for forge: but some singular some plural

### ISSUE THREAD

**Issue by CoteRL** [EnigmaticaModpacks/Enigmatica6#4604]
### Modpack Version

1.1.2

### Describe your issue.

Saplings all have a tag forge: but some are forge:saplings and others are forge:sapling. Recipes call for forge:saplings so anything mistagged can't be used. Not every sapling has a forge: tag so it doesn't seem like the mistagged ones are just not intended for recipes.

Examples:
Green Enchanted Sapling has forge:saplings
Dark Oak Sapling has forge:sapling

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.

**Comment by GManCometh** [comment]
Yeah, I was talking to Motoko on Discord, and they pointed out that vanilla saplings have a typo in the tag. 
forge:sapling
insead of:
forge:saplings

**Comment by GManCometh** [comment]
It's just vanilla saplings with the issue

**Comment by MuteTiefling** [comment]
Ok, after some review, it appears the only recipe that was using `forge:sapling` has been fixed (#4651). Everything else appropriately uses `minecraft:saplings` or is hard coded to a specific sapling. 

I'm a little leary removing the forge tag entirely, however, as we didn't add it. It really appears to be one added by forge for... whatever reason.
