### ISSUE TITLE
Typo in Quest "Create Building Tools"

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#4607]
### Modpack Version

E6E 1.1.2

### Describe your issue.

"the Extendo Grip and the Wand of Symmatry." -> SymmEtry.

Especially funny since the wand's text is: "Lay your weary OCD to rest" :D

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report. that's all fixed up for next version
