### ISSUE TITLE
[expert]Blood bee recipe not working

### ISSUE THREAD

**Issue by pun2712** [EnigmaticaModpacks/Enigmatica6#4609]
### Modpack Version

1.1.2

### Describe your issue.

blood bee recipe seem not do anythin
![2022-04-10_11 14 07](https://user-images.githubusercontent.com/11716176/162601202-7e6cfb2c-c4f7-4211-b8a5-51ec517904aa.png)
![2022-04-10_11 13 39](https://user-images.githubusercontent.com/11716176/162601205-1ce409ca-52c0-40d2-8724-603c00ca2a89.png)
![2022-04-10_11 13 49](https://user-images.githubusercontent.com/11716176/162601207-5bc87794-de0b-449a-8cf7-88f11cba0e42.png)
g

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
To confirm, the bee you're trying to convert is a Bronze Bee?

**Comment by pun2712** [comment]
Yes, in picture no.2 is jar with Bronze Bee, Fresh form Thermal series Induction smelter

**Comment by pun2712** [comment]
OK, I think it "Too Fresh" ,Releaseing the bee and recapture it ,Now Recipe is working ,Maybe some NBT tag missing?

**Comment by MuteTiefling** [comment]
Odd, a freshly crafted one worked fine for me in test just now.  The recipe only requires the entity tag, which is one of the only 2 present when crafted. Gonna close this one up as it appears to have fixed itself regardless.
