### ISSUE TITLE
Thermal sawblade Jei bug

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4611]
### Modpack Version

1.1.2 Expert

### Describe your issue.

Thermal Sawblade requires "missing materialis:invar" large plate in jei, there is a random I in materials:invar, the recipe still works but I had assumed it was broken because it said missing data. If you can fix it in jei great, if not, maybe a tool tip on the sawblade explaining to the bug?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks for the report. 

`materialis` is the name of the mod that was adding Invar to Tinker's. That and all the Thermal metals have been moved into core Tinker's now, however. Should be fixed next update.
