### ISSUE TITLE
Server crashes on startup - Atum ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Daschi1** [EnigmaticaModpacks/Enigmatica6#4617]
### Modpack Version

1.1.2

### Describe your issue.

 I downloaded the newest version from git and executed all scripts as described in the readme. However, Atum throws an ArrayIndexOutOfBoundsException on startup. Is this a known problem and if yes, is there something I can do? Or should I report the bug to the mod author?

### Crash Report

https://gist.github.com/Daschi1/0e1f87a414e0f7856478cb045add1deb

### Latest Log

https://gist.github.com/Daschi1/d4c23cc0f0827bf68321a2c4904fa844

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
likely caused by openj9

**Comment by Daschi1** [comment]
Thanks for the quick response, I'll investigate and test this with hotspotvm

**Comment by Daschi1** [comment]
Thanks, that fixed it!
