### ISSUE TITLE
When filling the "crystal chest" into the "Pretty Pipes" Crafting Terminal using JEI on a server, your client will instantly disconnect from the server.

### ISSUE THREAD

**Issue by SweptWasTaken** [EnigmaticaModpacks/Enigmatica6#4618]
### Modpack Version

Enigmatica 6 1.1.2

### Describe your issue.

When filling the "crystal chest" into the "Pretty Pipes" Crafting Terminal using JEI on a server, your client will instantly disconnect from the server with this error.

![image](https://user-images.githubusercontent.com/49448379/162628506-5bcb057c-bd6e-4245-b009-dc03510bb8eb.png)

Tried this multiple times and it works consistently.

The only thing in the latest.log is the error shown.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I lazily relayed it 😄

**Comment by NillerMedDild** [comment]
The PP mod-dev request your latest.log and the server latest.log if possible, please :)
https://github.com/Ellpeck/PrettyPipes/issues/126#issuecomment-1094337824

**Comment by Splutty** [comment]
Posted what info I had.
