### ISSUE TITLE
[E6E] I can't finish Iridescent Altar Crafting

### ISSUE THREAD

**Issue by StarskyXIII** [EnigmaticaModpacks/Enigmatica6#4619]
### Modpack Version

1.1.2

### Describe your issue.

When I craft the Gaia Mana Spread or Solar Neutron Activator, it will stop at early step.

https://drive.google.com/file/d/1e3dKTpVTnDNnnpjATbdFrt9sTBCTGYrY/view?usp=sharing

https://drive.google.com/file/d/1J-CqsvXG7PGGsn6y-su8K2EBg94-qe5V/view?usp=sharing

### Have you modified the modpack?

Yes

### User Modifications

Remove BetterEnd, Add BetterEnd Reforked

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Dupicate #4465
