### ISSUE TITLE
Easy bee dupe

### ISSUE THREAD

**Issue by Prolixitas** [EnigmaticaModpacks/Enigmatica6#4624]
### Modpack Version

1.0.0.

### Describe your issue.

It appears that you can easily dupe bees by having an empty soul gem in your off hand slot and an empty bee jar in your main hand slot. When attempting to pick up a bee with right click the bee is stored in both items and can be emptied from both items, resulting in 2 bees from one. Both seem to function normally.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Ah crap :P thanks for the report.

**Comment by NillerMedDild** [comment]
@klikli-dev could you perhaps disable the ability for the Soul Gem to capture entities while in the off-hand? It appears that it allows players to dupe entities by holding two entity-capturing devices at the same time.

**Comment by klikli-dev** [comment]
@NillerMedDild absolutely, I'll try to squeeze in a patch tomorrow

**Comment by ThatGravyBoat** [comment]
I think this is a problem with resourcefulbees too we were returning pass instead of success on our interact method I fixed that [here](https://github.com/Resourceful-Bees/ResourcefulBees/commit/ac21c7af7f4eb6d2b60d71b7fad1f1dd27381cce)  but we also call the remove method so I'm assuming the soul gem may not check if the entity is alive?

**Comment by klikli-dev** [comment]
Good point - I don't recall right now how I'm handling that in the soul gem, but I'll double check for that. Thanks for your input!!

**Comment by klikli-dev** [comment]
Fixed in: 
[1.16.5-1.26.7](https://github.com/klikli-dev/occultism/milestone/192)
[1.18.2-1.29.1](https://github.com/klikli-dev/occultism/milestone/191)

**Comment by NillerMedDild** [comment]
Thank you kindly  😊
