### ISSUE TITLE
Add blazing blood to the description of heat one could apply to PNC refinery

### ISSUE THREAD

**Issue by gkurmaev** [EnigmaticaModpacks/Enigmatica6#4632]
### Describe your suggestion

Basically the title. Currently, the "Heat" section in the refinery interface only mentions lava and torches as potential heat sources, but blazing blood works too.

### Why would you like this added/changed?

So that people won't bother others in discord, like I did :P

**Comment by tyler489** [comment]
If you hit the Useage key on any heat source then click the text "block heat properties" to see all of the available sources.

**Comment by gkurmaev** [comment]
> If you hit the Useage key on any heat source then click the text "block heat properties" to see all of the available sources.

Does not necessarily mean one could use it with PNC refinery. Also, one of the discord mods asked me to post a suggestion here, I don't really care either way

**Comment by MuteTiefling** [comment]
Yeah, I wasn't in game to validate at the time, but it already has PNC Compat: 

![image](https://user-images.githubusercontent.com/9543430/163185071-df94b33a-8e76-435a-8375-07f030b55a64.png)
