### ISSUE TITLE
Buff Starry and Oreo Bees

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4633]
### Describe your suggestion

The starry bee and oreo bees are quite rare, unable to be bred, and quite frankly arn't really that usefull.
Regardless of apiary stary bees according to their beepedia entry only produce 1 comb, which has a 10% chance of producing 5 mb of honey, every 60 seconds. this means to make one block of honey (1000 mb) you need approx 2000 combs. 2000 combs at 60 seconds a comb would take 120000 seconds, 2000 minutes or 33 hrs for one nether star, this excludes processing time of the combs, the power cost of processing the comb, or the crafting time/infrastructure needed to autoplace honey blocks for mutation. Oreo bees, while a novel food source, are the equivalent of eating an enchanted golden apple, neat, but not really useful, especially since they are only in the sugar food group. I would like to see the stary bee either produce more honey, or guaranteed to produce 5mb a comb. (200 minutes). Not sure what would work on oreo bees, maybe give them more hunger haunches (they give saturation anyway so its not a big deal) that means they could be used in a gourmallis farm

### Why would you like this added/changed?

See above

**Comment by TemperedFool** [comment]
These are both Resourceful Bees dev bees - they were made and specced by the developers of the mod. They're Easter eggs, rather than being intended to be particularly powerful.

That said, Oreo Bee is a no-cost source of very good food with very good effects; Starry allows you to bypass wither farming for nether star production. Neither really seems like it needs a buff - if anything they both probably need a power reduction.

**Comment by tyler489** [comment]
1 nether star every 33 hrs, assuming your server is running at 20 tps, and requires a beacon as a flower, not really viable as a nether star farm. but ok

**Comment by TemperedFool** [comment]
Assuming you only run one bee, I trust your math; and again, it's an Easter egg, not an intended method of farming nether stars.

**Comment by MuteTiefling** [comment]
There's another side here, in that we don't want bees to be the one and only resource generation. They're already really powerful. We don't need to have them be best in class for even more resources.
