### ISSUE TITLE
JEI search bar looses focus

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica6#4634]
### Modpack Version

1.1.2 Expert

### Describe your issue.

JEI search bar looses focus after ~3 seconds (can even happen while typing!)

### Have you modified the modpack?

Yes

### User Modifications

Added [Visual Workbench](https://www.curseforge.com/minecraft/mc-mods/visual-workbench), updated Just Enough Calculations to beta version from author's github.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NurikSakura** [comment]
The beta version of Just Enough Calculations is the problem of that. Had the same issue, reverted back to normal JEC version and it got fixed.
