### ISSUE TITLE
Remove Shutup Experimental Settings!

### ISSUE THREAD

**Issue by Esteria** [EnigmaticaModpacks/Enigmatica6#4641]
### Describe your suggestion

title

### Why would you like this added/changed?

looks like RandomPatches does same thing.
but DFU removal disabled by default.
https://github.com/TheRandomLabs/RandomPatches

**Comment by NillerMedDild** [comment]
LazyDFU is different from what RandomPatches does, it doesn't disable it entirely and is safer.
Shutup Experimental Settings will be removed.

Thanks! :)
