### ISSUE TITLE
Sandy Bee Inconsistency.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#4645]
### Modpack Version

E6E 1.1.2

### Describe your issue.

The "Sandy Bee" is called "Sandy Bee" everywhere but can only be found in JEI as "Sand Bee".

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. 

We're aware of the issue, but fixing it would cause existing Sandy Bees to disappear unfortunately :/ we'll fix it if we ever have to make a world breaking update again.
