### ISSUE TITLE
[Expert] Can't craft BM Growth Reagent

### ISSUE THREAD

**Issue by GManCometh** [EnigmaticaModpacks/Enigmatica6#4651]
### Modpack Version

1.0.0

### Describe your issue.

Trying to make a growth reagent in the BM Alchemy Table.
Added ingredients, added Apprentice Blood Orb, no errors, no progress.
LP Network is full.
![image](https://user-images.githubusercontent.com/63400107/163525091-5ac0aa0c-0e44-4e44-b914-6396aadf7a5d.png)

### Have you modified the modpack?

Yes

### User Modifications

Simple Voice Chat

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Probably related to #4604. Gonna have to review some recipes I think... Make sure they all use the right tag and get everything standardized.
