### ISSUE TITLE
Travel Anchor elevator mode only accepts Shift as the sneak key

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#4654]
### Modpack Version

1.1.2

### Describe your issue.

Travel Anchor elevator mode only accepts Shift as the sneak key. Pressing Shift and Ctrl (what is usually my Sneak key) at the same time did not teleported me downwards. Jump key seems to be able to rebound however

### Have you modified the modpack?

Yes

### User Modifications

Better Ping Display 1.0

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NillerMedDild** [comment]
I rebound sneak to T and it worked just fine, my guess is the key you rebound it to has a conflict :)

**Comment by HaxtonSale1** [comment]
Ah. alright, 
I found Mekanism Boost key and Advanced Peripherals Show Description key conflicts with it.
