### ISSUE TITLE
[EnigmaticaModpacks/Enigmatica6] Issue opened: [Expert] Treated Wood recipe

### ISSUE THREAD

**Issue by Infernalballista** [EnigmaticaModpacks/Enigmatica6#4655]
### Modpack Version

1.1.2

### Describe your issue.

When crafting treated wood in expert it wont accept bucket form and the recipes dont show any crafting table or mechanical crafter recipe but when using a basic fluid tank from mekanism in a crafting table it allows the treated wood to be crafted in a crafting terminal. I did not test in a vanilla table but id assume the same.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I can't reproduce this in a crafting table, could you please provide screenshots of the error?

**Comment by Infernalballista** [comment]
https://imgur.com/gallery/KKWvbrU

**Comment by Darkere** [comment]
wrong screenshot?

**Comment by NillerMedDild** [comment]
I don't really see an issue? :)
