### ISSUE TITLE
Add Krate as a replace of iron chest or a storage upgrade after iron chest.

### ISSUE THREAD

**Issue by kingdom84521** [EnigmaticaModpacks/Enigmatica6#4656]
### URL

https://www.curseforge.com/minecraft/mc-mods/krate

### Why would you like the mod added?

This is a better basic storage for starters, it can give bigger space and more options for logistics than iron chest. As it was actually more powerful than iron chest, make it a upgrade after iron chest would be a good change, too.

This mod is also in ftb oceanblock, as a basic storage in it. It worked pretty well.

**Comment by NillerMedDild** [comment]
I like the mod, but I can't really justify adding it, we don't have a need for it.
