### ISSUE TITLE
Slimes not dropping slime eggs?

### ISSUE THREAD

**Issue by mrlamb** [EnigmaticaModpacks/Enigmatica6#4657]
### Modpack Version

1.1.2

### Describe your issue.

I know it's not an exact kill count but I have a gold backpack with over 3k slime balls having been killed by a sword with capturing 3 and no slime egg. 

If you tell me it's working as intended I'll grind some more but it seemed to stretch probability a bit to be that unlucky. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
RNG sucks sometimes. But this does work, and your can get them.

**Comment by mrlamb** [comment]
Very well, thanks for the confirmation! After 45 minutes of straight killing I was starting to suspect but I will take your word for it and keep plugging away!

**Comment by TemperedFool** [comment]
Are these vanilla slimes, or the green slimes on Tinkers islands?

@MuteTiefling are we sure the Tinkers ones will drop an egg to capturing? They wouldn't go in the bucket after all >.>

**Comment by StarskyXIII** [comment]
Have the similar question, does Iron Golem drop spawn egg? 
Guard Villagers mod added the spawn egg for it, I tried to kill 200+ Iron Golem with Capturing V, but still not drop.

**Comment by mrlamb** [comment]
They were in fact over 2400 slimes from a tinkers island. I have since moved on to learning how slime chunks work as an alternate route :D

**Comment by mrlamb** [comment]
After about 10 minutes of getting slimes to spawn down near bedrock on a slime chunk, I got an egg. Could be RNG finally favored me but it does seem statistically improbable.

![image](https://user-images.githubusercontent.com/11540846/163682701-851faea9-2fa8-4b80-9a6c-60731c724b4e.png)
