### ISSUE TITLE
Imperceptible builder consumes blocks, plays particle effects but doesn't place blocks (server only)

### ISSUE THREAD

**Issue by mrlamb** [EnigmaticaModpacks/Enigmatica6#4658]
### Modpack Version

1.1.2

### Describe your issue.

Came up with a build for livingrock that used imperceptible builder to place the sunstone, taking from a backpack for it's inventory. I was happy with how it turned out so went to try it out on our survival server. It began consuming the sunstone but not placing the blocks like it was supposed to. The particle effects would play as if it was placing, but nothing would happen.

I immediately thought it might be a fake player problem so I un claimed the chunks. Still no success, so I moved far outside the borders where no one has a claim or ever has claimed. Still no luck. I've included some pictures of the setup and some showing the particles going off. After awhile of the particles happening it stops like it's placed everywhere it thinks it can and consumes no more blocks after that.
![2022-04-16_23 04 02](https://user-images.githubusercontent.com/11540846/163699918-04812ae0-2285-4b29-bc8e-5a94e439cfa2.png)
![2022-04-16_23 01 55](https://user-images.githubusercontent.com/11540846/163699923-aee56258-f665-4b2f-9c6c-8126b6f3c4c5.png)
![2022-04-16_23 01 43](https://user-images.githubusercontent.com/11540846/163699931-8940a78b-7696-40d8-8a65-7b9908b67432.png)

Really stumped on this one.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by mrlamb** [comment]
Adding a screenshot of the same setup in single player working well.
![2022-04-16_23 09 32](https://user-images.githubusercontent.com/11540846/163700003-5452cef3-6c37-472e-a9b5-6f12ab72f1a0.png)

**Comment by mrlamb** [comment]
While I was writing up the bug report it occurred to me to try a server restart, since that's basically what happens when you start single player - it spools up a server instance. 

Things are working as expected on the server now with the imperceptible builder placing blocks, consuming the correct quantity of blocks and no other weirdness. We had no indications of anything being out of sync on the server, everyone else was placing, interacting and playing with no issues, so it seemed odd it was just this one thing (admittedly that we noticed). 

I don't know if this needs to be closed now, or if it should be forwarded to the developer so they are aware.

**Comment by NillerMedDild** [comment]
Thanks for the report, and for fixing it yourself 😀 let's close the issue for the time being, I'll reopen if needed.
