### ISSUE TITLE
[Expert] Afrit ritual not completing.

### ISSUE THREAD

**Issue by eliminat** [EnigmaticaModpacks/Enigmatica6#4664]
### Modpack Version

1.1.2

### Describe your issue.

Other Occultism rituals have been completed successfully, but the unbound afrit is not spawning for me to kill.
The ritual is set up properly, and right-clicking with the bound book triggers the sound and particles to start, but items are not consumed and no afrit ever spawns.

Have interrupted and re-triggered it multiple times, with no change. 
Also restarted server and re-attempted.
Have waited more than 10 minutes with no items consumed.
![2022-04-17_15 12 21](https://user-images.githubusercontent.com/7636368/163730730-f057f882-b55f-4226-bf77-9aaa8272c57e.png)

Performing in Atum as needed in expert.

broke it down and rebuit it again, no change.
![2022-04-17_15 23 34](https://user-images.githubusercontent.com/7636368/163730922-1c6ecc26-c290-405a-b069-10296d882208.png)

Also tried single-player creative in Atum
![2022-04-17_15 36 11](https://user-images.githubusercontent.com/7636368/163731250-9e0f41de-f3c8-48ad-9ffe-96831ca079e3.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
It's waiting for you to sacrifice a camel.
