### ISSUE TITLE
[expert] RS Ignore Blaze Blood in Crafting Recipe

### ISSUE THREAD

**Issue by pun2712** [EnigmaticaModpacks/Enigmatica6#4667]
### Modpack Version

1.1.2

### Describe your issue.

I try to craft blaze fiber with RS Crafter , but it not working , so I see in crafting moniter  and They not recognize Blaze Blood in recipe, 
![image](https://user-images.githubusercontent.com/11716176/163799254-a287765d-8149-473e-bb53-b5ba4e5a0e68.png)
![image](https://user-images.githubusercontent.com/11716176/163799270-a57f2119-bcbd-4186-a18a-1c9294fd3fa6.png)
I think oh ,Maybe Crafter with basin for Mixer Have Problem with fluid recipe, So I Try other recipe ,like asphalt concrete that have water in recipe, And it work,i have enorge blaze blood in system 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
Make sure you don't have a second pattern in your system for blazing fibre. Use the crafter manager to see.

**Comment by pun2712** [comment]
I'm back to say that, like Darkere mention above , I found I have wrong recipe stay in one of my crafter ,False alarm , Sorry.
