### ISSUE TITLE
[Expert] Sludge Refiner FE requirement disproportionately high given its recipe

### ISSUE THREAD

**Issue by matthewd** [EnigmaticaModpacks/Enigmatica6#4674]
### Modpack Version

1.1.2

### Describe your issue.

The Sludge Refiner recipe makes it available as soon as you can craft a Pity Machine Frame, along with the Plant Gatherer and friends -- but unlike those, which seem to have Normal-level FE requirements, the Refiner asks for 60x the standard power level: https://github.com/EnigmaticaModpacks/Enigmatica6/blob/32c1b84b2fe6ac5b5b6f417e9772a4668676451a/config/configswapper/expert/config/industrialforegoing/machine-resource-production.toml#L22-L24

As far as I can see, at the time it becomes available, 2.5k FE/t is... not practically achievable.

Assuming the intention is for it to be available this early (as confirmed by @MuteTiefling on Discord), it seems like it should probably use the default 40 FE/t (following the precedent of similar-stage IF machines, which copy the Normal values), or perhaps a more in-reach inconvenience like 100 FE/t.

Otherwise, it'd be better to give it a harder recipe, gating it to a time when massive power is more plausibly available. I haven't progressed enough to have a strong grasp of when that is, but perhaps a higher tier of machine frame would do it? 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Well, no not default. But 1500 is too high. Probably a few hundred would be more reasonable.
