### ISSUE TITLE
Pcbee Comb now working in any centrifuges

### ISSUE THREAD

**Issue by mooshickc** [EnigmaticaModpacks/Enigmatica6#4677]
### Modpack Version

1.1.2

### Describe your issue.

pcbee combs don't seem to be processing in any of the 4 centrifuges from resourceful bees.

I thought it may have been my world because i did some changes to it so I created a brand new instance of E6E with no changes to any configs or mods added to test this out and same issue still applies.

Cheated in a stack of pcbee combs and the 4 centrifuges and they don't seem to be processing.

Thank you!

### Latest Log

https://gist.github.com/mooshickc/d24c14fb0adc329bd2c2af719b907a42

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
Place bottles in the centrifuge before placing the combs; the recipe requires them & the centrifuge will not recheck the recipe unless the bottles go in first.
