### ISSUE TITLE
[Expert] Aux Cactus upgrade for Phytogenic Insolator not working properly

### ISSUE THREAD

**Issue by GManCometh** [EnigmaticaModpacks/Enigmatica6#4678]
### Modpack Version

1.1.2

### Describe your issue.

The Auxiliary Cactus upgrade isn't voiding all of the secondary items (seeds in this case) when growing things in the Phytogenic Insolator. You are able to get multiple secondary items from a process, but the Aux Cactus is only voiding one, so you can still get secondary items.

### Have you modified the modpack?

Yes

### User Modifications

Added Simple Voice Chat

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Going to hazard a guess here that it considers things to be secondary if they have a chance based output. Seeds are guaranteed so you can cycle them back in.
