### ISSUE TITLE
the `RS Bridge` from `Advanced Peripherals` sometimes voids `nbt` whilst importing

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4680]
### Modpack Version

1.1.2

### Describe your issue.

When you use `importItem` or `importItemFromPeripheral` on an item with nbt there is a chance it gets voided.

I have personally encountered it with full pnc canisters extracted from the charging station being returned as empty but thought nothing more of it. (specific mod<->mod interaction)

Now today when I tried to write a script to export the highest levels of enchanted books to a chest and back some (170 ish) high/god tier level enchanted books lost their nbt and turned useless, prompting me to look deeper, and then I found this:

https://github.com/Seniorendi/AdvancedPeripherals/issues/258

Importing water bottles via the same script that voided my enchanted books resulted in the same type of bottles, so it's probably the same issue.

It got fixed by @Seniorendi on the 16th of march on the 1.16.5 branch, but to this date there does not seem to have been a curseforge release, though there seems to be a build from a few hours later that day in another issue: https://github.com/Seniorendi/AdvancedPeripherals/issues/202#issuecomment-1069364453

For now i can only recommend to maybe put a warning on the block to not import items with nbt, similar to how expert mode modifies the description of blocks disabled in it.

My workaround for both of my scripts was an importer, the one on the pnc charging station extracting full bottles, but for random nbt like automatically charging drones in the system or importing random enchanted books my workaround is just having the importer respond to redstone & toggle it via computercraft on-demand, but that's all or nothing.

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Seniorendi** [comment]
Time to make a release

**Comment by Quezler** [comment]
Neat, thanks 👍

**Comment by Seniorendi** [comment]
Not sure if closing this was a right decision
If "fixed in next release" means in the next modpack release. I would not count on me that I'll release a new version in the near future. I currently work on a rs bridge rewrite and this will take a while.

**Comment by NielsPilgaard** [comment]
Ah my bad, thanks for the heads up.

**Comment by Quezler** [comment]
for now it can be used to intentionally reset nbt, like unbinding blood magic orbs or activators on multiplayer 😄

**Comment by Seniorendi** [comment]
Fixed in 0.7.8r
