### ISSUE TITLE
Lesser soul gem recipe uses too much life essence

### ISSUE THREAD

**Issue by Paulson90** [EnigmaticaModpacks/Enigmatica6#4683]
### Modpack Version

1.1.2

### Describe your issue.

In JEI the recipe for the lesser soul gem calls for 10 mb of life essence but uses 4000 mb.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
As I understand it, fluids in masterful machine recipe inputs are *per tick*, and that recipe takes 400 ticks to complete which is why it takes 4000mb to complete the recipe...

They really don't show that very well, maybe we need to add info about that somewhere but idk where a good place would be

**Comment by Paulson90** [comment]
Ah, that makes sense. Yeah, it's really confusing as it is and even knowing that doesn't help much without knowing how many ticks a recipe takes to complete.

**Comment by MuteTiefling** [comment]
The only fix I can offer for this is to change these recipes to take it all up front. I don't think there's any downside to that...
