### ISSUE TITLE
Change Pink Enderslime ratio

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4684]
### Describe your suggestion

In tinkers, slimeballs melt to 250mb each, not 144mb like ingots. This makes the 144mb pink slime 144 mb end slime to 288mb pink enderslime ratio wierd. Consider changing the pink enderslime to use 125 125, 250 or 250 250, 500, The only recipe that is not a multiple of 250mb is the Dimensional card recipe from RSinfinityBooster Mod which uses 144*9 mb, this could be changed to use the new outputs of 2250 or 4500 mb

### Why would you like this added/changed?

Consistency, all other slime balls melt to 250, so currently you will always end up with some pink slime or purple slime in the smeltery

**Comment by NillerMedDild** [comment]
Good idea, we'll get that fixed :)

**Comment by tyler489** [comment]
> Good idea, we'll get that fixed :)

Would you like it 125 +125= 250 or 250+250 = 500

**Comment by NillerMedDild** [comment]
250+250=500 :)
