### ISSUE TITLE
Change the pnc spawner extractor recipe / pnc spawner agitator cannot be right clicked into a mechanical crafter

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4694]
### Describe your suggestion

![Screen Shot 2022-04-22 at 19 57 17](https://user-images.githubusercontent.com/3179271/164769060-9b76b566-a3fa-4366-9098-66c570cf82f9.png)
![2022-04-22_19 56 08](https://user-images.githubusercontent.com/3179271/164768980-8a7f3fd6-1ad9-4b40-ab2d-f06307054b46.png)

### Why would you like this added/changed?

[discord context](https://discord.com/channels/195234321836146688/858470513817813012/966808678927826994)

**Comment by Quezler** [comment]
same category: cardboard box used packing the laser drill to keep the children happy can't be rightclicked in either

**Comment by MuteTiefling** [comment]
Should be fixed up next release
