### ISSUE TITLE
Terminite hammer not working for ritual to summon blacksmith familiar

### ISSUE THREAD

**Issue by ABowlOfNoodles1116** [EnigmaticaModpacks/Enigmatica6#4697]
### Modpack Version

1.1.2

### Describe your issue.

The terminite hammer is not registering for the ritual. Says it is missing despite it being there

### Have you modified the modpack?

Yes

### User Modifications

Added gravestone mod

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate: #4581
