### ISSUE TITLE
Improve server-setup-config.yaml to allow serverpack to also run on java16+ without user intervention

### ISSUE THREAD

**Issue by radiomike** [EnigmaticaModpacks/Enigmatica6#4701]
### Describe your suggestion

Add the following to `server-setup-config.yaml`
```
    - "--add-opens=java.base/sun.security.util=ALL-UNNAMED"
    - "--add-opens=java.base/java.util.jar=ALL-UNNAMED"
    - "-XX:+IgnoreUnrecognizedVMOptions"
```

### Why would you like this added/changed?

This will allow the server pack to run on java 16+ without needing additional user intervention. Because of the inclusion of `-XX:+IgnoreUnrecognizedVMOptions` earlier java versions will ignore the other lines and won't break.

**Comment by NielsPilgaard** [comment]
Solid suggestion, have you tried it out yourself? :)

**Comment by radiomike** [comment]
I've been using them in a few packs in multimc with various different java versions.
