### ISSUE TITLE
Building Gadgets blueprint for Advanced Assembly contains tubes

### ISSUE THREAD

**Issue by Xavion3** [EnigmaticaModpacks/Enigmatica6#4704]
### Modpack Version

1.1.2

### Describe your issue.

The Building Gadgets blueprint for the Advanced Assembly Table contains advanced pressure tubes which are not actually part of the multiblock.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks! Should be all fixed up in the next version.
