### ISSUE TITLE
Blood Magic Dagger of Sacrifice and Level 2 Blood Altar Quests are out of order

### ISSUE THREAD

**Issue by Gayfarer** [EnigmaticaModpacks/Enigmatica6#4708]
### Describe your suggestion

![image](https://user-images.githubusercontent.com/104288265/164955368-6746b68f-6180-41e9-91c6-02a512bf755f.png)
Dagger of Sacrifice must be obtained first before the player can use the Blood Altar in Enigmatica 6 Expert.
![image](https://user-images.githubusercontent.com/104288265/164955385-4edf83ad-47b2-47dc-8d3a-5f408f018d3a.png)
This is because the Sacrificial Knife requires a working tier 2 blood altar to craft (Recipe above) rather than the Dagger of Sacrifice, which just needs a crafting table and minor progression (Recipe Below).
![image](https://user-images.githubusercontent.com/104288265/164955702-669ff7c9-01ae-40c4-8eb9-18d78fa398ac.png)
As the same quest book is used for both E6 and E6E, it's recommended that the quests are rearranged to accommodate for both versions.

### Why would you like this added/changed?

It would be better from a guided progression point of view - requiring the DoS to start BM, and then having a later quest to _craft_ it, doesn't make sense.

**Comment by TemperedFool** [comment]
The quests you're referring to are the Normal mode quests; we've left them as general info/guided to the mods, and for the rewards you'll get from them, but they aren't an indicator of expert progression the expert quests are.

**Comment by MuteTiefling** [comment]
Just to add a little here, this can all still be completed in expert.

Thinks that would need fixing are quests that, due to changes in progression in expert, cannot be completed. 

I believe this one was already changed to put the dagger out of the direct pregression as an accommodation to expert players without breaking things for normal players.
