### ISSUE TITLE
[1.2.0] Tactical Fishing causing registry errors in E6E 1.2.0 server, fails to launch 

### ISSUE THREAD

**Issue by Tynk3r** [EnigmaticaModpacks/Enigmatica6#4713]
### Modpack Version

1.2.0

### Describe your issue.

Server 1.2.0 fails to launch, error in crash report/logs is that Tactical Fishing encountered an error during the load_registries event phase. Previous versions of server (1.0.0, 1.1.2) work fine on same machine.

Running Ubuntu 20.04.4 LTS with 16GB of memory

Steps to reproduce:
1. Download server files from curse for 1.2.0 (https://www.curseforge.com/minecraft/modpacks/enigmatica6expert/download/3767448)
2. Give execute permissions to start-server.sh
3. Launch through linux terminal
4. Accept EULA
5. crash

### Crash Report

https://gist.github.com/Tynk3r/77a957c6af60335d690f43bacb755f2b

### Latest Log

https://gist.github.com/Tynk3r/259dc21ebbd2018d40c44e476adf4a53

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Discomanco** [comment]
Did a bit of testing, Tactical Fishing v1.1 is simply broken on its own too on servers (works fine on SP)
Fuffled-Fuffles/TacticalFishing#1
