### ISSUE TITLE
Dimensional Shard unification?

### ISSUE THREAD

**Issue by atlgeek007** [EnigmaticaModpacks/Enigmatica6#4717]
### Describe your suggestion

There are two types of dimensional shards in the pack - the one you get from the ore ( tagged as ```emendatusenigmatica:dimensional_gem```), and the "base" type (I assume), tagged as ```rftoolsbase:dimensionalshard```)

Both types are usable in all recipes, and the first kind will craft into the second on a crafting grid, but the first type cannot be used in the machine infuser, it only accepts the second type.  

Is there a way to get the machine infuser to accept both types?

### Why would you like this added/changed?

Mostly convenience, since every other recipe seems to be able to use both types of shards.

**Comment by NielsPilgaard** [comment]
We've tried, but no luck ><

https://github.com/McJtyMods/RFToolsBase/pull/50
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/1456
