### ISSUE TITLE
Crafting Potion of Spell Damage II

### ISSUE THREAD

**Issue by demethan** [EnigmaticaModpacks/Enigmatica6#4719]
### Modpack Version

1.1.2

### Describe your issue.

Crafting the Potion of Spell Damage II, on the 3rd part when adding the glowston dust, the potion turn into potion of calming. 

JEI shows the correct recipe.  (nether wart)awkward-->(MageBloom) Spell Damage 3:00-->(glowstone dust)Spell Damage II  3:00

![image](https://user-images.githubusercontent.com/5810363/165431617-3fbbf8d5-8f20-431e-ae63-f1ee700a4435.png)
![image](https://user-images.githubusercontent.com/5810363/165431652-b5b06054-f284-41e6-8b08-331e37841cc2.png)
![image](https://user-images.githubusercontent.com/5810363/165431673-f45f5b13-bf75-42a1-9eb1-7d0854c970a8.png)
![image](https://user-images.githubusercontent.com/5810363/165431710-0086d263-1a26-48a9-85ce-28deb331a295.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Duplicate: #4716 4102
