### ISSUE TITLE
[E6E] Create Mechanical Harvesters void Ditchbulbs

### ISSUE THREAD

**Issue by bevilp** [EnigmaticaModpacks/Enigmatica6#4725]
### Modpack Version

1.2.1

### Describe your issue.

Mechanical Harvesters seem to void ditchbulbs. They get harvested but never get transferred to attached inventory or to other storage through storage interface.

### Have you modified the modpack?

No

### User Modifications

Added effortless building, easy villagers

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
I believe this is due to how Create determines harvestability, sorta duplicate of #3806
