### ISSUE TITLE
Quest "Blood Altar MK4" Does Not Accept Large Bloodstone Brick

### ISSUE THREAD

**Issue by fistsh** [EnigmaticaModpacks/Enigmatica6#4728]
### Modpack Version

1.1.2

### Describe your issue.

The **Tier IV Blood Altar** in _Blood Magic_ accepts 4 of either Large Bloodstone Brick and/or Bloodstone Brick as the outmost altar pillar caps (according to the book _and_ to in-game testing in E6E). However, the corresponding quest ("Blood Altar MK4" under the "Blood Magic" questline) **ONLY accepts Bloodstone Brick**.

It seems odd that the quest would only accept one of the 2 valid forms, especially as - at least in E6E - you have to craft the Large Bloodstone Brick (which is currently NOT accepted by the quest) in order to be able to craft the other kind.

(FWIW: Two[?] item tags already exist which contain only those two blocks, including `$enigmatica:stonecuttables/bloodstone` and `$chisel:bloodstone`.)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by fistsh** [comment]
I just tested in E6(E) 1.2.1 and **the issue is still present**. The above commit changed _one_ of the quests related to this (from the "Magic - Master" Expert quest chapter), but not the specific one I had mentioned (from the "Blood Magic" quest chapter), which is still only accepting one form of Bloodstone Bricks. See attached screenshot depicting the task in question.

![e121bamk4](https://user-images.githubusercontent.com/104248331/166831825-db4cf7c1-bf7d-4b40-a994-95b5017a8f3a.png)

**Comment by MuteTiefling** [comment]
It's still present because it's in the _next release_
