### ISSUE TITLE
Crash with Copy tool and Xnet facade

### ISSUE THREAD

**Issue by tyler489** [EnigmaticaModpacks/Enigmatica6#4732]
### Modpack Version

1.1.2 Expert

### Describe your issue.

When using the copy tool from building gadgets, if a structure contains an xnet facade the server will crash when pasting it in. 

### Crash Report

https://crash.sverd.eu/e6e/crash-2022-04-29_06.01.12-server.txt

### Have you modified the modpack?

No

### User Modifications

NBT viewer on my client, but that is unrelated to this server crash

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report, we'll blacklist XNet facades from being placed by all Building Gadgets :)
