### ISSUE TITLE
An opportunity to finish powah quest section

### ISSUE THREAD

**Issue by Al1sa** [EnigmaticaModpacks/Enigmatica6#4738]
### Describe your suggestion

Because powah cables are disabled, you can't finish powah quest section. I think you should add an opportunity for players to mark this and other impossible quests finished

### Why would you like this added/changed?

So OCD people like me can mark this section finished

**Comment by NielsPilgaard** [comment]
We've marked it as optional, but for some reason FTBQ still includes is as something the player *must* complete to complete the chapter.

**Comment by Al1sa** [comment]
> We've marked it as optional, but for some reason FTBQ still includes is as something the player _must_ complete to complete the chapter.

You can make the player craft something else instead of cables. Like with air compressor

**Comment by NielsPilgaard** [comment]
Myeah, I suppose we ought to. Sure.
