### ISSUE TITLE
seemingly random server crashes

### ISSUE THREAD

**Issue by Xexanos** [EnigmaticaModpacks/Enigmatica6#4741]
### Modpack Version

1.1.2

### Describe your issue.

I just setup a Server with E6E and it keeps on crashing seemingly random.

### Crash Report

https://gist.github.com/Xexanos/d1728aa8f7cb0eb13a7eebc4fed906f8

### Latest Log

https://gist.github.com/Xexanos/f95e08d6880e6976670de586ef0cf744

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
It looks like a config was corrupted, a reinstall ought to fix this :)
