### ISSUE TITLE
Difference in expected yield from a `core sample` vs `/ie mineral get`

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4743]
### Modpack Version

1.1.2

### Describe your issue.

![Screen Shot 2022-05-01 at 21 06 17](https://user-images.githubusercontent.com/3179271/166160738-59d7fae0-e938-4014-987e-6f4dc80811e4.png)
![Screen Shot 2022-05-01 at 21 06 24](https://user-images.githubusercontent.com/3179271/166160739-cb00c674-5162-4e4d-8c04-b042dd0b07d3.png)

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
If I understand that correctly, it found a mineral that is spread out to a radius of 29 blocks? Not sure if the core sample finds all of that.

**Comment by Quezler** [comment]
Wasn't sure if it was because e6 changes vein sizes or if the mod intends to show way less ores on a sample even if its taken at the exact center 🤔

**Comment by theboo** [comment]
pretty sure those are IE/IP default sizes, our boosted vein size was brought back in 1.2.0+... should be seeing samples of like 200-500k vs 10-20k

**Comment by Quezler** [comment]
that's what confused me as well, pretty sure i saw veins being boosted [long ago](https://github.com/EnigmaticaModpacks/Enigmatica6/commit/3257c99b78604c33c5f76b9a7dc4d1d94e2391a7), but they were lowered & increased again recently?

**Comment by theboo** [comment]
the config was refreshed in january but they forgot to put our boosts back when they did it
