### ISSUE TITLE
Arcane Ashes recipe never seems to complete

### ISSUE THREAD

**Issue by codeka** [EnigmaticaModpacks/Enigmatica6#4744]
### Modpack Version

1.2.1

### Describe your issue.

I put some arcane ashes on the ground, add a feather, then redstone. The little glyph thingy starts spinning, but it never finnishes. I waited several minutes.

![2022-05-01_18 31 51](https://user-images.githubusercontent.com/1569910/166174410-c5a79b6b-2a2c-4f06-a00c-d19deac53d22.png)

There also seems to be a bone+bone recipe (which may be a mistake?) that doesn't even start spinning.

### Latest Log

https://gist.github.com/codeka/9de189201a1182675f19ca24914d5171

### Have you modified the modpack?

Yes

### User Modifications

My server is unmodified, but on the client I added optifine, DynamicSurroundings and FreeCam mods.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
this is an unfortunate result of the way blood magic displays these array recipes in jei... those are not recipes to duplicate ashes, they all do different things... 
for example, the one you are doing is a movement array that should throw a player/mob/items in a certain direction..

![image](https://user-images.githubusercontent.com/3585761/166175800-fca3a5f1-f12b-4925-a87d-5357bcfe16c4.png)

**Comment by codeka** [comment]
Oooh! Thanks, that makes sense.
