### ISSUE TITLE
Being able to craft `atum`'s `strange sand layer` for decoration

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4746]
### Describe your suggestion

A way to obtain the strange sand layer in a similar fashion to snowballs, or something with e.g. a saw or stonecutter:
![Screen Shot 2022-05-02 at 16 50 43](https://user-images.githubusercontent.com/3179271/166255668-dbca7964-ce9d-4b44-b9af-9b9766f45ac3.png)

snow recipe for comparison so it makes sense: 
![Screen Shot 2022-05-02 at 16 49 44](https://user-images.githubusercontent.com/3179271/166255664-8a52a293-1b68-4f76-87a5-653ab7c512f1.png)

### Why would you like this added/changed?

I feel the need to be able to decorate with this sand, but without cardboarding up the desert for the exact heights i want. 😗

**Comment by tyler489** [comment]
I would like to point out that this sand spawns naturally during sand storms, and I believe u can pick it up with a silk touch shovel
