### ISSUE TITLE
Magma Cube spawners only spawn small ones

### ISSUE THREAD

**Issue by gkurmaev** [EnigmaticaModpacks/Enigmatica6#4748]
### Modpack Version

1.2.1

### Describe your issue.

Was trying to setup aura gen with offshoot observer and noticed that my spawner only spawned small magma cubes causing observer to not collect any mana, since there is no 'split'. For reference, spawner did not have spawner agitator on it, but i did maximize amount of spawns and minimize minimum spawn time, while also enabling redstone signal and removing the need for the player to be there.

After killing the small ones for some time with capturing, I got couple of eggs. Using an egg in the world spawned the big one, but using the second one on another spawner (without any modifications) still spawned only small cubes.

After being told in discord to find a fresh one in another bastion and finally finding one, without me even collecting the spawner (or doing anything else with it for that matter), it still spawned only the small cubes.

Boo wrote the following about the issue:

The Boo — Today at 7:54 PM
I think apo update is borking even the natural ones

The Boo — Today at 7:55 PM
World gen spawners*

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
Fixed in apotheosis version 4.8.99D
