### ISSUE TITLE
Increase liquid starlight yields from fluid laser base

### ISSUE THREAD

**Issue by Ratlanta** [EnigmaticaModpacks/Enigmatica6#4749]
### Describe your suggestion

Liquid starlight yield from fluid lases base should be scaled up.

### Why would you like this added/changed?

Currently the fluid laser base yields 10mb of starlight per completed operation. Even when scaling up drills with speed upgrades, the output is still abysmal and probably less than a single lightwell running on resonating gems. 

In late game, most players will probably want to scale up their lightwell generation to fuel a gaia reactor. The primary method of starlight generation (aquamarine to lightwells) is not very server friendly. The fluid laser base makes sense as a viable late game alterative for starlight generation.

**Comment by OneEyeMaker** [comment]
Also what about alternative ways of obtaining liquid starlight? Maybe a "fluid" bee (requiring Celestial bee in recipe/mutation)?

**Comment by MuteTiefling** [comment]
I do like alternates. It won't be a bee, but I've been giving mulling over some other ideas as alternatives.

**Comment by NielsPilgaard** [comment]
I think ramping up the output from the Fluid Laser would be good too, even if there are alternates.

**Comment by Quezler** [comment]
> Status: Fixed In Next Release?
