### ISSUE TITLE
Typo in flavour text of Tree of life controller quest [E6E]

### ISSUE THREAD

**Issue by thatGuyCalledMax** [EnigmaticaModpacks/Enigmatica6#4751]
### Modpack Version

1.1.2

### Describe your issue.

![image](https://user-images.githubusercontent.com/103206589/166331204-8bd88c2a-c93f-4c99-bd11-b350547673b9.png)
Simple typo in the quest description of the Enigmatic Tree of life controller quest

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Fixed (I hope) thanks 👍

**Comment by MuteTiefling** [comment]
one more :D
