### ISSUE TITLE
Server start error Engimatica6ExpertServer-1.2.1

### ISSUE THREAD

**Issue by Gregie** [EnigmaticaModpacks/Enigmatica6#4752]
### Modpack Version

Latest

### Describe your issue.

Running the start-server.bat encounters an error rather early on. Not sure of a crash report location but the console output is attached.

### Crash Report

https://gist.github.com/Gregie/aedab6880db84cfd5be27b270c6ffd39

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
reinstall
