### ISSUE TITLE
Soul Soil turns into Strange Sand in Atum

### ISSUE THREAD

**Issue by sarkahn** [EnigmaticaModpacks/Enigmatica6#4766]
### Modpack Version

E6 Expert v1.0

### Describe your issue.

When I place soul soil in atum it turns into strange sand. This makes it so I can't summon the wither for the pink wither ritual

https://user-images.githubusercontent.com/477520/166588239-0b6b8cd6-1f43-42eb-b509-0822946bf21e.mp4

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
The Wither needs _soul sand_, not soil. 😸 That will place without issue in Atum.

**Comment by sarkahn** [comment]
Soul soil does (normally) work for the record, but yeah using soul sand instead in atum did the trick, thank you!
