### ISSUE TITLE
Remove some of the annoyance with Occultism based crafts

### ISSUE THREAD

**Issue by Swedz** [EnigmaticaModpacks/Enigmatica6#4771]
### Describe your suggestion

Items that have been crafted using Occultism pentacles currently have randomly generated names of spirits attached to them, creating unique NBT data for each item created. It would be nice if this was not the case. This can be done easily by modifying the recipes in `server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js` to use the `ritual_type` of `occultism:craft` instead of `occultism:craft_with_spirit_name`.

### Why would you like this added/changed?

Especially in Expert Mode where almost all things need to be automated, it makes it quite annoying to set up crafts with Refined Storage since each item will have a different NBT and will never fulfill the request. Not only does it prevent RS from completing crafts automatically, but it makes the items no longer stackable.

**Comment by DoomSquirter** [comment]
I would go so far as to ask not just the obvious ones that shouldn't have demon names, but any that are used in recipes.  like the satchel, etc.  it would help a lot to be able to subcraft these things instead of pulling together a long list of stuff to accomodate the items.

**Comment by MuteTiefling** [comment]
I've mixed feelings on this, honestly.

First, they provide a nice bit of theme to the game that really puts a finger on the fact that you've bound spirits into these items.
Second, while it does make it impossible to do 'simple' recipes in RS, the tools are there to manage this.

I set these recipes knowing full well that RS wouldn't deal with them cleanly by itself; that the player would have to get creative in how they approach them. I even went so far as to show an [example](https://wiki.enigmatica.net/enigmatica6/gameplay/how-to.../occultism-automating-rituals) of it in our Wiki to help people wrap their heads around the process. 

I fully understand that some people find this to be an annoying process, but I don't see it as all that different from many other 'off RS' automations required here, or even in other packs. It's not uncommon that you need to send a batch of items out to a chest to have some other smarter system handle the craft for you. That's all that's happening here.

**Comment by NielsPilgaard** [comment]
I think it provides a nice extra challenge, albeit annoying 😄

**Comment by Buuz135** [comment]
It is a problem when an output has a random name and RS keeps waiting for it to finish the crafting, like the Dimensional Matrix.

**Comment by Swedz** [comment]
I fully understand the interest in setting up unique automations for things you wouldn't normally need to, as I myself feel that way as well. However, when it comes to this, this isn't anything special or interesting, it is just pumping items into a RFTools crafter (or something similar) instead of letting RS handle it. It doesn't add any interest or extra work at the stage in the game where you'd be automating this anyway, just an annoyance. It just doesn't make any sense to me as to why an RFTools crafter should work but RS not.

It is also very inconsistent. Some recipes have this trait, some do not. It doesn't seem there's any criteria for items that make them less or more likely to have this spirit name attached, it's just haphazardly around.

The theme of the spirit names is cool, I'll admit, but it doesn't even work properly. Names will change spontaneously on items and the name on the bound books don't even get retained on the resulted craft most of the time.

**Comment by MuteTiefling** [comment]
> It is also very inconsistent. Some recipes have this trait, some do not. It doesn't seem there's any criteria for items that make them less or more likely to have this spirit name attached, it's just haphazardly around.

The general rule I followed was, if the item will be used on it's own and can retain the name through normal usage, then give it a name.

I admit there may be a few things that break this rule. Satchels, however, meet the criteria. You'll use it on it's own (or could anyway) and using won't remove the name. Same for the Sophisticated Backpacks upgrades. Those names are retained when installed in a backpack. 

Mycelial Generators, on the other hand, don't retain that info as a general rule. As soon as they're placed, it's lost. I knew this would 100% lead to people opening bug reports complaining that the name was not kept when the machine was placed, so I just avoided it altogether as we can't force that data to be retained on blocks.

Again, however, that's just the overall rule. There are plenty of exceptions where the name was added (or kept) where the final result doesn't keep the name. Examples being the dimensional crystal matrix (lost when crafted into the storage actuator), logic directors (again, lost when used in recipes)

**Comment by Ommina** [comment]
One person's feedback:

I quite like the additional bit of work required for processing the spirit-named items.  However, I _dislike_ it when I have to request a wholly different item in RS to make it happen.

The Dimensional Storage Crystal, for example - totally fine, since everything happens at the ritual, and RS gets the completed crystals back.  Super!  I request crystals, I get back crystals.

The satchel, on the other hand, is yuck.  To get a satchel, I have to order a glazed terracotta.  That is, when I want the actual named product, and not a different item made _from_ the named product (eg: ender chest), weirdness has to happen.   I request glazed terracotta, I get back a satchel.  Bleh.

(In fairness, the same trick had to be used is E2E as well.  Didn't like it there either.)

**Comment by NielsPilgaard** [comment]
> Again, however, that's just the overall rule. There are plenty of exceptions where the name was added (or kept) where the final result doesn't keep the name. Examples being the dimensional crystal matrix (lost when crafted into the storage actuator), logic directors (again, lost when used in recipes)

Sounds like these ought to be non-named crafts if the final result doesn't keep the name anyway.
