### ISSUE TITLE
Rope Pulley infinite can be archived without the need of 10k fluid source blocks

### ISSUE THREAD

**Issue by Kenshij** [EnigmaticaModpacks/Enigmatica6#4772]
### Modpack Version

1.2.1

### Describe your issue.

have opend a issue at create, don't know if it's a modpack related issue  
https://github.com/Creators-of-Create/Create/issues/3010

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
This is most likely fixed next release due to the way we're doing blacklisting now.

**Comment by MuteTiefling** [comment]
Seems good after a short test. :D

**Comment by Kenshij** [comment]
![image](https://user-images.githubusercontent.com/11033477/173206284-b63ebd44-a302-4516-876a-ed8cf0a81f9e.png)

**Comment by Kenshij** [comment]
Not fixed for me in 1.3.0
![image](https://user-images.githubusercontent.com/11033477/173206296-495aea2d-f282-47a0-aa94-03d8d0eb70f6.png)

**Comment by Kenshij** [comment]
Sorry false button

**Comment by Quezler** [comment]
1.3.0 does not contain this fix yet, wait for the next release.
