### ISSUE TITLE
Arc Furnace doesn't accept Shard of Laputa

### ISSUE THREAD

**Issue by StarskyXIII** [EnigmaticaModpacks/Enigmatica6#4773]
### Modpack Version

1.1.2

### Describe your issue.

If player want to craft a Laputial Ingot, it should put 2 Shard of Laputa in the right side slots.
![image](https://user-images.githubusercontent.com/71606873/166716860-dcf33f82-f80c-4e13-b55f-2a103336e138.png)

But it seems we can't put Shard in the right side slots.
I had tried tier1 to 20, it still doesn't work for me.
![image](https://user-images.githubusercontent.com/71606873/166716721-01e73e8f-c527-4030-a4bf-5413ae68e178.png)

If we use hoppers to input shard forcibly, Shards is not stackable to start crafting process.
![image](https://user-images.githubusercontent.com/71606873/166716639-74d74861-e8b7-4f6a-bc2c-804df9dc8be8.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
So weird. I swear this was working for me in my original testing. Will have to re-work I suppose! Thanks for the report!
