### ISSUE TITLE
Chronicles of Shadows Apotheosis book uncraftable

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica6#4775]
### Modpack Version

1.2.1

### Describe your issue.

Making this issue because i dont have time to fix it right now and i know ill forget lol... Apo book has no recipe, should be a book and gold ingot by default... It does come with the tome so isnt a huge deal but should still be craftable for people to either add to their older tomes or just craft if they want

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Shadows-of-Fire** [comment]
Kinda piggybacking on this issue - the Akashic Tome you get as a quest reward has a different selection than the one that is crafted.  The Chronicle of Shadows is among those missed
## Crafted
 ![](https://i.imgur.com/f1YOWTD.png)
 ## Quest Reward
 ![](https://i.imgur.com/qm5dm86.png)
