### ISSUE TITLE
Apotheosis Spawner Config has errors (trailing commas)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [EnigmaticaModpacks/Enigmatica6#4776]
### Modpack Version

1.2.1

### Describe your issue.

Title, relevant log snippet: https://gist.github.com/Shadows-of-Fire/9c3de48f6c0212f72d4d029ad0e89f39

.cfg lists are newline separated, so the comma is treated as part of the entry.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report, fixed in dev 😄
