### ISSUE TITLE
[expert?] Add recipe to convert IE Lubricant  to PNC Lubricant

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4779]
### Describe your suggestion

After unlock distillation tower, we can convert oil to diesel , lubicant , and gasoline.
Diesel go Power Production (I know ,I should go Nuclear Power , but.. why not it NEAT! ).
gasoline go LPG for Plastic.
but lubicant ? notting for IE Lubricant that need in large amount , while PNC Lubicant have 20++ recipe to use . Why can't they convert ,or Can we use any type of Lubricant  in all recipe ?

### Why would you like this added/changed?

Add recipe to convert IE Lubricant  to PNC Lubricant / make we can use any type of Lubricant  in all recipe

**Comment by MuteTiefling** [comment]
I recall attempting to unify these, once upon a time, and being unable to because IP's lubricator machine wouldn't accept PNC lubricant or tags. I don't know if that has changed now, but it may be worth revisiting.

**Comment by AlphaP2712** [comment]
Can we have some Exchange recipe like memory essence <-> experiment cycle? maybe with IF Disolution chember or Thermal Fractionating Still

**Comment by MuteTiefling** [comment]
Seems the Automatic Lubricator was fixed, so the distillation tower will simply output PNC lubricant now. Most recipes already accept tags where feasible, so your old lubricant will still be useful without a conversion recipe.
