### ISSUE TITLE
Typo in TiCon bees description

### ISSUE THREAD

**Issue by LowEntropyZone** [EnigmaticaModpacks/Enigmatica6#4782]
### Modpack Version

E6E 1.2.1

### Describe your issue.

![typo_lol](https://user-images.githubusercontent.com/34612979/167050944-a6999422-edec-49f8-a713-dcd1f633c50f.png)

The description of the Tinkers' Construct bees (Ichor, Skyslime, Enderslime, Cobalt) contains a typo with the word "skilled" having 3 L's.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
That's embarrassing - should be fixed in the next update, presuming "tinkerer" isn't controversial...
