### ISSUE TITLE
`brine` and `lithium` via the immersive petroleum `distilation tower`

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4785]
### Describe your suggestion

Currently the `pnc` refinery can turn `water` into `brine` and `steam`, and `brine` into `liquid lithium` and `steam`, as well as process oil into several other products:

![Screen Shot 2022-05-06 at 13 06 05](https://user-images.githubusercontent.com/3179271/167120262-b7643d0d-6f5c-4e04-9461-756135a02151.png)

It would be neat if the `distillation tower` (gated after the heavy machinery schematics) could also process `water` and `brine`, instead of only oil into the 3 immersive petroleum products. (i mean, it does the same as the pnc minus the brine)

I have dug up the recipe format in case this gets accepted:
```
  "immersivepetroleum:distillation/oilcracking": {
    "type": "immersivepetroleum:distillation",
    "byproducts": [
      {
        "item": "emendatusenigmatica:bitumen_gem"
      }
    ],
    "results": [
      {
        "fluid": "immersivepetroleum:lubricant",
        "amount": 9
      },
      {
        "fluid": "immersivepetroleum:diesel_sulfur",
        "amount": 14
      },
      {
        "fluid": "immersivepetroleum:gasoline",
        "amount": 39
      }
    ],
    "input": {
      "tag": "forge:crude_oil",
      "amount": 75
    },
    "time": 1,
    "energy": 2048,
    "id": "oilcracking"
  },
```

### Why would you like this added/changed?

This is just a personal preference, but i'd rather have two distillation towers vs two thermal evaporation plants, it just looks better, and using two sets of small pnc refineries is just not fast enough for our lategame needs, and ie multiblocks are fun.

**Comment by NielsPilgaard** [comment]
I think this is a great idea 👌
