### ISSUE TITLE
Broad Axe Tinker's quest has incorrect dependencies

### ISSUE THREAD

**Issue by cinnamennen** [EnigmaticaModpacks/Enigmatica6#4787]
### Modpack Version

1.1.2

### Describe your issue.

In the thinkers quest the broad axe quest asks for a large plate instead of a tough binding

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report, we'll get that fixed :)
