### ISSUE TITLE
[Mod bug] Items imported by RS Bridge doesn't count to autocrafting!

### ISSUE THREAD

**Issue by KacproPL132** [EnigmaticaModpacks/Enigmatica6#4788]
### Modpack Version

1.2.1

### Describe your issue.

I've wrote a program to automate flux, added crafter from RS to barrel, put in Redstone, and was importing flux with RS Bridge via CC program. However after finishing import, RS didn't see that Flux got imported and was still waiting for Flux autocrafting to be done.
I could probably mess something up in a code, however no idea what because import actually works.

```
local rs = peripheral.find("rsBridge") or error("No RS Bridge found!")
local vacuum = peripheral.wrap("thermal:device_collector_0") or error("No Vacuumulator found!")

local function pName(peripherals)
    local cache = peripheral.getName(peripherals)
    return cache
end

local function flux_import()
    os.sleep(5)
    local loop_condition = 1
    while loop_condition == 1 do
        loop_condition = rs.importItemFromPeripheral({name="fluxnetworks:flux_dust"},pName(vacuum))
    end
end
```

If this is intented, or there is some problem with my code, then sorry for the report ^^"

### Have you modified the modpack?

Yes

### User Modifications

Changed NBT Max Packet size to max-1 that is possible in RandomPatches config.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
its probably a bug with the advanced peripherals mod, rs doesn't like it when you insert it directly into storage either, it only seems to notice importers & interfaces when it comes to allocating fresh items to crafting tasks.

also, be careful importing anything with nbt over the rs bridge, since it can wipe it.

**Comment by KacproPL132** [comment]
> also, be careful importing anything with nbt over the rs bridge, since it can wipe it.
Alright  good to  know thx :D

> its probably a bug with the advanced peripherals mod, rs doesn't like it when you insert it directly into storage either, it only seems to notice importers & interfaces when it comes to allocating fresh items to crafting tasks.
Sad :c Its much cleaner to just import stuff via RS Bridge, however I'm guessing there isn't gonna be fix for that soon-ish.
Gonna just use normal importer and disable that part of the code ig. Thx for letting me know

**Comment by NielsPilgaard** [comment]
Would you consider this issue to be resolved by the workaround?

**Comment by KacproPL132** [comment]
I'm sure Advanced Peripherals Creators will not fix that issue, so I think workaround is only "fix" for that.
