### ISSUE TITLE
Water bottle with shrunken entity disappears when full inventory 

### ISSUE THREAD

**Issue by SenninMoodo** [EnigmaticaModpacks/Enigmatica6#4793]
### Modpack Version

1.2.1

### Describe your issue.

When your inventory is completely full and you are going to capture a shrunken entity with a glass bottle, the bottle simply disappears instead of dropping to the ground.
Re-created in Single Player and got the problem every single time. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Duplicate of #3940
