### ISSUE TITLE
[E6E] Creating crafting pattern for Display Panel causes the client to crash

### ISSUE THREAD

**Issue by vertexofvortex** [EnigmaticaModpacks/Enigmatica6#4802]
### Modpack Version

Enigmaitca 6 Expert 1.2.1

### Describe your issue.

I tried to make an autocrafting pattern for Display Panel from Integrated Dynamics (it requires 1 Static Light Panel and 8 Bottled Ghosts). When the pattern was written, the client crashed (the server was still running, it's working separately on VDS). Crash-report can be found [here](https://gist.github.com/vertexofvortex/fd0ea7ae99c500e1170793aa3a839d25).

At that time I was using OptiFine, yes, I know it's proprietary and has a lot of incompatibilities with other mods, so I decided to temporary remove it (btw, it mentioned in crash-report). Then I started the game without it, logged into the server and saw THIS:

![2022-05-08_17 27 23](https://user-images.githubusercontent.com/31506708/167302263-7841b4e5-d9d5-42c5-868e-0f3f4d71b48d.png)

Player model wasn't rendering correctly, hotbar items disappeared. Then I broke the pattern grid and was [crashed again](https://gist.github.com/vertexofvortex/24d8ea21a97fb2059188334f89c21aaf). My friend also tried to login and was crashed (he does not using any performance mods and hasn't modified the game), I could post his crash-log after some time when I'll get it, but think it would be similar to mine.

I decided to restart the server, after that I successfully logged in, picked up the pattern dropped from broken pattern grid and now it's working well...

![2022-05-08 180751](https://user-images.githubusercontent.com/31506708/167302573-913268b0-4f5b-4d6f-8046-1610292f5bc6.png)

Don't know what, don't know how. But everything is fine now, maybe the error appears when written pattern is inside the grid?
**EDIT**: Started the game with OptiFine again, got crashed when opened the inventory (there are patterns in it). Seems like it's probably OptiFine issue, but this doesn't negate the fact that the game also crashes without it...
**EDIT 2**: Started the game without OptiFine. Got crashed when opened inventory. Going to remove the patterns from it with help of NBTExplorer.

P.S. Checked the issue tracker for similar problems but found nothing. Sorry if I'm duplicating someone's issue.

### Crash Report

https://gist.github.com/vertexofvortex/fd0ea7ae99c500e1170793aa3a839d25, https://gist.github.com/vertexofvortex/24d8ea21a97fb2059188334f89c21aaf

### Latest Log

https://gist.github.com/vertexofvortex/36b37f913be02c534faf32f8ace562d7 (client)

### Have you modified the modpack?

Yes

### User Modifications

OptiFine, but then removed (described above).

### Did the issue happen in singleplayer or on a server?

Server

**Comment by vertexofvortex** [comment]
There's my friend's crash-report: https://gist.github.com/vertexofvortex/b34edd118537b1ad364837b1859b8884.

**Comment by NielsPilgaard** [comment]
Thanks for the report, this is certainly odd 😄 
Master of things that are Refined, @Darkere, do you know what's up? :P

**Comment by Darkere** [comment]
I have actually investigated this one some time ago and never quite figured it out. 

From what I was able to tell, Oracle Java has a bug that causes the recipemanager to give back the wrong recipe type. If anyone can reproduce this, I would be interested in how. 

For a fix, please try downloading Adoptium java 8 found here: https://adoptium.net/temurin/releases (you need to filter for java 8)

To actually use it add `version1.8+` to your java arguments in the curseforge settings.

**Comment by vertexofvortex** [comment]
Reproduced the same bug in singleplayer and recorded it, maybe [this video](https://youtu.be/qkQ2N8DhzRg) would be helpful.

> For a fix, please try downloading Adoptium java 8 found here: https://adoptium.net/temurin/releases (you need to filter for java 8)

Using Adoptium JDK 8 solves this problem (the second part of the video is dedicated to it, I don't know for what purpose).

**Comment by lavraleksej** [comment]
Just had this crash happen when manually crafting a display panel, using Adoptium Java 8 and optifine+optiforge
https://gist.github.com/lavraleksej/6917de4256c866d2b483d03c4ee8e431

**Comment by Darkere** [comment]
Hmm then we should maybe consider changing the corresponding recipe that it is conflicting with. 
Either NA or Kjs are registering the recipe wrong.

**Comment by MuteTiefling** [comment]
Looks like the two recipes have the same ID somehow. I'll change that, maybe that's all this is.
