### ISSUE TITLE
E6E remove Alchemy array recepies for arcane ashes from JEI

### ISSUE THREAD

**Issue by yuri0r** [EnigmaticaModpacks/Enigmatica6#4804]
### Describe your suggestion

there are leftover recepies suggesting you can craft more arcane ashes using alchemy array crafting. this is supposed to be disabled in [Expert](https://discord.com/channels/195234321836146688/947932229143760957/972916047441170452)

when trying the recepies it will get stuck in the animation. 

### Why would you like this added/changed?

this is very confusing as most people probaply rely on JEI when navigating an expert pack.

**Comment by MuteTiefling** [comment]
These are functional arrays, not crafting arrays. The book explains better. Each one has its own effect, like tossing you into the air, changing day to night, etc.

Check the BM book for more info.
