### ISSUE TITLE
Reduce the overall cost of the excavation mastery shard [E6E]

### ISSUE THREAD

**Issue by thatGuyCalledMax** [EnigmaticaModpacks/Enigmatica6#4805]
### Describe your suggestion

To reduce the overall price of the mastery shard for excavation.

### Why would you like this added/changed?

Its understandably meant to be expensive, but its just not in the same ball park as the other the other mastery shards. Maybe 5x shards per craft would be a better number? Its not impossible to make now, its just significantly more then all the other shards

**Comment by thatGuyCalledMax** [comment]
Another request in this vein would be to reduce the cost of the battle mastery shard. The offender there is mainly the 400 total energy upgrades you need

**Comment by MuteTiefling** [comment]
Thanks, will have a look at these soonish.

**Comment by Ratlanta** [comment]
Agree with Max on battle mastery. I think I can actually pull off excavation in it's current form although it doesn't remotely match up to the requirements for other shards. Even if excavation was 5 per craft, it would still be exponentially more expensive than all shards short of battle. 

Battle Mastery in it's current form will probably require several weeks or even longer AFK to get the mats required. That's assuming I massively scale up my entire production. I'm currently around 15 TPS so I don't know how much scaling I can realistically do at this point. The end of omnifactory was quite similar so I understand if that is the intent. 

Graphite and starlight changes I believe you already have planned is going to be a big help compared to what we have on 1.2.1 as well.

**Comment by MuteTiefling** [comment]
The intent was for them to be tough, but not weeks of AFK. I'll for sure be reviewing these to bring the material requirements down. You guys are some of the first to get this far, so there was not a lot of feedback on how rough these get :D
