### ISSUE TITLE
Recipes for using are Aura Cache broken

### ISSUE THREAD

**Issue by SaanMcC** [EnigmaticaModpacks/Enigmatica6#4812]
### Modpack Version

1.2.1

### Describe your issue.

There are different recipes for using the full vs empty Aura Cache (from Nature's Aura), both of the ones that use the full Aura Cache don't work.  The recipes for using the full Aura Cache are:
- Runic Altar
- Altar of Birthing

Haven't tested the empty Aura Cache recipe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
Have you confirmed the aura cache is completely full? Absorbing high aura won't do it, you need to place it in a natural altar.

**Comment by SaanMcC** [comment]
Confirmed you're correct, wasn't completely full.  Went back and saw the notes in Quest book note on the Aura cache. 

Apologies.
