### ISSUE TITLE
Infinity bucket Source with routers Activator

### ISSUE THREAD

**Issue by GiaruDK** [EnigmaticaModpacks/Enigmatica6#4816]
### Modpack Version

1.2.1

### Describe your issue.

Just all on video

https://user-images.githubusercontent.com/49821276/167689623-26a70727-3302-4c16-b895-921a317fb22b.mp4

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report. Would you mind checking if it works with any liquid / tank combination?

**Comment by GiaruDK** [comment]
> Thanks for the report. Would you mind checking if it works with any liquid / tank combination?

I tested only source, try check another liquid

**Comment by GiaruDK** [comment]
Only liquid source
![2022-05-10_22 30 10](https://user-images.githubusercontent.com/49821276/167707377-fc084e51-4554-49a5-82e0-daf78203ea9f.png)
![2022-05-10_22 30 08](https://user-images.githubusercontent.com/49821276/167707382-d905fed1-55a4-4f30-b4ae-3860675d0c14.png)

**Comment by NielsPilgaard** [comment]
I made a super lazy relay here: https://github.com/baileyholl/Ars-Nouveau/issues/525 😄 thanks for doing the leg-work you two!
