### ISSUE TITLE
Add a Masterful Machine for Starlight Infuser

### ISSUE THREAD

**Issue by TheDragonicSlayer** [EnigmaticaModpacks/Enigmatica6#4825]
### Describe your suggestion

Add a Masterful Machinery machine to automate Starlight infuser in endgame

### Why would you like this added/changed?

Right now Starlight infuser is not possible to automate. As we need stuff from the Starlight infuser for a lot a of crafts, it would be nice to have a masterful machine fort he Starlight infuser to automate it

**Comment by MuteTiefling** [comment]
After a quick glance through the recipes, all I'm seeing that you'd need in largish quantities that can't also be gotten elsewhere, is Vibrant Infused Wood. 

I'm not against an automated version of this, but we also need to consider what's actually useful to put on such a machine before spending the time to make it. It would be far easier to toss Vibrant Infused Wood into something like the Dissolution Chamber (where lenses already reside) as an automatable option for this resource, than to build up and test a new MM and port over all 78 recipes on it.

**Comment by Xavion3** [comment]
The other main recipe that makes use of it is processing celestial combs from bees, getting starmetal from them requires infusion

**Comment by MuteTiefling** [comment]
Yes, but star metal has other sources. The return on that comb is as large as it is because the altar can't be automated.

**Comment by MuteTiefling** [comment]
Closing as we've gone ahead with the alternate astral wood recipes instead of making a separate machine.
