### ISSUE TITLE
DIY Meka-Tool Kit not craftable

### ISSUE THREAD

**Issue by Ratlanta** [EnigmaticaModpacks/Enigmatica6#4826]
### Modpack Version

1.2.1

### Describe your issue.

The DIY Meka-Tool kit is not craftable. I ran into this on dev but verified the issue also exists on 1.2.1. The PC pressure Chamber will not allow the insertion of Laser-Dissipation Units and 4 are required per recipe. Laser Dissipation units are not stackable while the other mek units seem to be. 

Also, Laser dissipation units are an armor upgrade and not used on the Meka-tool. Maybe add one to each armor piece DIY instead? This would not change the cost of Battle Mastery Shards.
![image](https://user-images.githubusercontent.com/59396659/168186117-b9610c82-c71d-41d0-80a6-e500ec7a3bd3.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
We keep issues open until a release.

**Comment by Ratlanta** [comment]
Oops, my bad!

**Comment by MuteTiefling** [comment]
No worries
