### ISSUE TITLE
Immersive engineer villager OP trade

### ISSUE THREAD

**Issue by krikos** [EnigmaticaModpacks/Enigmatica6#4829]
### Describe your suggestion

I was shuffling the Immersive Engineers villager using the Immersive Engineers workbench and noticed that the villager got two starting trades that were:
1 emerald -> 9 treated wood planks
8 treated wood sticks -> 1 emerald

I was wondering if this was intentional.
Maybe remove the treated wood sticks trade from the villager?

### Why would you like this added/changed?

In my opinion, this allows farming emeralds way too easily. Even without curing the villager.

**Comment by NielsPilgaard** [comment]
I think that's just fine to be honest.
