### ISSUE TITLE
On-Screen message not going away

### ISSUE THREAD

**Issue by GrimReaper1982** [EnigmaticaModpacks/Enigmatica6#4830]
### Modpack Version

1.1.2

### Describe your issue.

Hello everyone,

i just had a gamecrash yesterday after building the alloy kiln from immersive engineering
and hitting it with the engineers hammer to finalize it.

The message "The Logical Path Forward 100%" appered in my right screen side and won`t
go away anymore:
![grafik](https://user-images.githubusercontent.com/105487926/168252948-5f9fe742-7cdb-4013-95ca-14ba85dad894.png)

This occurs only on my server. In singleplay it is not shown.

How can i get rid of it? Not sure where this message even came from...

Can someone help me with this, please? :)

Kind regards.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
Find the quest with that name and unpin it. (quest got pinned by another party member before you connected to it)
