### ISSUE TITLE
Affixes breaking AIOT leveling

### ISSUE THREAD

**Issue by Raeis-Eikr** [EnigmaticaModpacks/Enigmatica6#4837]
### Modpack Version

Enigmatica 6 Expert 1.2.1

### Describe your issue.

A few players on my servers have AIOT with affixes. The affixes are not allowing the AIOT to level. Have tested fresh AIOT and it is fine. Applied affixes again and nothing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
I don't quite understand `The affixes are not allowing the AIOT to level`? What do you mean by leveling of AIOTs?

**Comment by Raeis-Eikr** [comment]
I'm asking the members of my server, that are experiencing the issue specifically, to elaborate more. I'm trying to get them to come here and post more info in the comment section.

**Comment by theboo** [comment]
what affix specifically is on their tools?  i cant seem to put any on the AIOT, ive tried axe and pick affixes

**Comment by Shadows-of-Fire** [comment]
aiots should be categorized as swords as per https://github.com/EnigmaticaModpacks/Enigmatica6/pull/3958

Honestly I don't even know what levelling refers to in this context, much less how an affix could prevent it

**Comment by Raeis-Eikr** [comment]
Item.of('aiotbotania:alfsteel_aiot', "{RepairCost:63,mana:0,display:{Name:'{"text":"Deez"}'},tipped:1b,AS_Amulet_Holder:[I;1066134146,947146425,-1670184600,1182040276],Damage:14,Affixes:{"apotheosis:cold_damage":6.4311237f,"apotheosis:life_steal":0

**Comment by MuteTiefling** [comment]
This still doesn't clear up what levelling you're talking about, I'm afraid.

Enchants I'm a soul enchanter? Something else?

**Comment by Raeis-Eikr** [comment]
"Basically what's going on is the Apotheosis affixes mess up the leveling system the AIOT has
Where you throw it into a mana pool to level it from D -> C -> B -> A -> S
Normally that works with an AIOT, a Terra Shatterer, etc. but when you put on the affixes the NBT data probably gets messed up too much to have it work
I tested an AIOT with and an AIOT without affixes, the one without worked even with the Elementium Pickaxe tip"

This is the statement made in my discord about it.

**Comment by theboo** [comment]
Are they sure the pool was set to "give" mode?
Just made an AIOT with a couple affixes and it seems to be leveling up in a pool just fine.
https://gyazo.com/2950819ee4dddce505d233ec95c78b6c
And just after i took the gif it leveled up to B rank.
![image](https://user-images.githubusercontent.com/3585761/168454302-9367d301-2487-478d-a615-b7b423caa462.png)

**Comment by rguy98** [comment]
That did the trick - thanks!

**Comment by theboo** [comment]
woop woop
