### ISSUE TITLE
Powah reactor output power far more than wiki said

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4838]
### Modpack Version

1.2.1

### Describe your issue.

![image](https://user-images.githubusercontent.com/74948675/168415741-2abb1bb8-95d6-4b46-b45d-660dacd00155.png)
![image](https://user-images.githubusercontent.com/74948675/168415763-f7b63f0a-91c3-4a53-a39e-fa153a41f1fa.png)
not sure that I misunderstand something or bug but like it said , wiki said 100 k FE , in game is 500k FE .  

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Ommina** [comment]
Like almost everything in this pack, generator values have been adjusted ( see [here](https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/config/configswapper/expert/config/powah/energy/generators/reactor.toml) ).

Sure, crafting table recipes are unchanged, but I'm working under the assumption that they just havn't got to them yet.

**Comment by NielsPilgaard** [comment]
We have indeed delibarately changed the values :)

**Comment by AlphaP2712** [comment]
butttt ... it for this pack wiki ....
![image](https://user-images.githubusercontent.com/74948675/168418552-83df59f8-0fb9-4afd-ab5a-c95f9e96b12e.png)

**Comment by AlphaP2712** [comment]
so... wiki is invalid? , even wiki IN THIS GITHUB
![image](https://user-images.githubusercontent.com/74948675/168418657-218aa5ef-ee48-4742-8b99-ecc1fe9df2bb.png)

**Comment by NielsPilgaard** [comment]
Woops my bad. Those values are for normal mode.

**Comment by MuteTiefling** [comment]
It's an issue of time. If you'd care to settle in and test each machine to give a thorough evaluation of what each does in all of these same situations, I'd be more than happy to update the wiki.

Until someone can give it to me though, I'm afraid it'll wait until I have the time to do so myself. The best I can do right now is to toss up a note that the values are increased further for Expert.

**Comment by MuteTiefling** [comment]
note added to the wiki indicating the discrepency. Fully updating the wiki is a project for later.
