### ISSUE TITLE
Missing Multiservo Press 3x3 Compacting Recipes

### ISSUE THREAD

**Issue by FallenRosemary** [EnigmaticaModpacks/Enigmatica6#4857]
### Modpack Version

1.2.1

### Describe your issue.

There seems to be a bunch of 3x3 compacting recipes missing from the multiservo press for resource storage blocks like source gems and lead
discovered this after trying to get ore processing running and using multiservos to compact everything down into blocks

### Have you modified the modpack?

Yes

### User Modifications

added optifine, buddycards and metal barrels

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
I believe this should be resolved by #4724; are there actually block recipes missing? This adds nugget -> ingot recipes.

**Comment by FallenRosemary** [comment]
most of the storage block recipes are missing, yep

**Comment by NielsPilgaard** [comment]
Can confirm, they're still missing sadly.

**Comment by Sampppppppppppppppppppppppp** [comment]
immersive engineering metal press and multi servo press have inconsistant/conflicting recipes. Servo dies can't be crafted, IE unpacking/packing dies can't be used on the metal press

**Comment by MuteTiefling** [comment]
> immersive engineering metal press and multi servo press have inconsistant/conflicting recipes. Servo dies can't be crafted, IE unpacking/packing dies can't be used on the metal press

These have been unified to the extent that they can be. Thermal dies were removed (with the exception of numismatic) in favor of the IE molds. Thermal machines use the IE molds instead. 
The unpacking is surprising, however, since those should be automatic recipes.

**Comment by Sampppppppppppppppppppppppp** [comment]
> 

When I tried to use the IE metal press with the IE unpacking mold with melons/pumpkins, it did not work. However, it did work when using the Thermal unpacking die on the metal press as the JEI recipe shows. In kubejs\server_scripts\enigmatica\kubejs\constants\dies.js I added "unpacking" to the list of IE dies and that seemed to fix the metal press working with the IE unpacking die.

**Comment by MuteTiefling** [comment]
alright, I think I see part of the issue. The IE machine doesn't like our tags. It's picking one randomly out of the tag and going with that.

Still doesn't explain why neither machine is doing auto block > ingot recipes based on standard tags... but that's an easy fix to. Will work on this this evening.
