### ISSUE TITLE
Not full translation and not all correct.

### ISSUE THREAD

**Issue by GiaruDK** [EnigmaticaModpacks/Enigmatica6#4864]
### Describe your suggestion

And this is not all )

![2022-05-19_02 05 10](https://user-images.githubusercontent.com/49821276/169169643-0efdbde9-88dc-4d68-89e3-133bdb454c5f.png)

![2022-05-19_02 05 42](https://user-images.githubusercontent.com/49821276/169169650-68e223eb-162c-4624-a008-705840c77414.png)

![2022-05-19_02 06 06](https://user-images.githubusercontent.com/49821276/169169653-52c5e075-7157-493b-8243-aa962b8907fa.png)

Collector mana have ru translate in Mod / Petrunia not have page in Crowdin and Gjalhorn too

### Why would you like this added/changed?

Fix collector and add Gjalhorn and Petra in Crowdin

**Comment by NielsPilgaard** [comment]
We don't have control over these I'm afraid, the respective mods do.
