### ISSUE TITLE
ID/T energy transfer hard capped at 6K/t.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#4866]
### Modpack Version

E6E 1.2.1

### Describe your issue.

The tooltip on the energy interfaces says the transfer rate is capped at 64K/t. It's not. It's capped at 6.4K/t because it's also hardcapped at 1 per 10 ticks. If I set the 'Ticks/Operation' to anything lower than 10, it just gets completely ignore, this capping the energy transfer at a tenth of what it states on the tooltip.

Is this intentional? Because that makes ID/T energy transfers pretty much completely pointless.

### Have you modified the modpack?

Yes

### User Modifications

Easy Villagers. Should have no impact.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
`!()[image link]`

**Comment by Splutty** [comment]
I'm going to guess fluid transfer rates suffer from the same issue, by the way. But have not actually tested that.

**Comment by Splutty** [comment]
Got confirmation from someone in Discord that fluids have the same issue as I thought.

**Comment by TemperedFool** [comment]
This is from my test world, demonstrating 65k/t worth of throughput:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/13169307/169562863-2df46922-adc0-4551-a80a-efa2bf51f807.png">

Set the extractor to 1/t per operation to achieve this. It's not capped to 10t/operation, that's just the default.

**Comment by TemperedFool** [comment]
Using the energy monitor to be thorough:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/13169307/169563179-06cdb70d-21c3-4dff-b24e-ebb17684511c.png">

**Comment by Splutty** [comment]
Yes. I'm not using the exporter. I'm using the importer. And setting ticks to 1 in the interface has no effect on the throughput of the importer.

As shown in the pictures I linked.

**Comment by Splutty** [comment]
I can't reproduce your successful setup either:

![image](https://user-images.githubusercontent.com/28677475/169578334-3d3b2123-e2f4-430f-9c3f-86c1fb604d40.png)

**Comment by TemperedFool** [comment]
Seems to work fine:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/13169307/169580137-03ecd24d-0695-45cd-b58b-412bb6129ba0.png">

**Comment by Splutty** [comment]
Yeah... So... Yours works, mine doesn't. Which  version are you on? (1.2.1 here)

Otherwise I have absolutely no clue anymore. It doesn't work for me, 100%, both in these minimal test scenarios as in a real life scenario driving Powah rods. As in.. See the pics.. lol

**Comment by TemperedFool** [comment]
Oh I don't doubt your pictures, but I also just tested on e6e-b, running 1.2.1:

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13169307/169582344-81aa4661-d500-47cc-bb68-ce15a410b78b.png">

**Comment by Darkere** [comment]
![image](https://user-images.githubusercontent.com/4283717/169582877-fc41fee8-35b8-469b-a694-e811e7568a65.png)

Make sure to set the tickrate to 1 on both sides.

**Comment by Splutty** [comment]
Well. I'm lost.

100% reproducable for me that the ID/T tunnels allow 10% of the rate I set through, and nothing more or less, regardless of the setting of my ticks/operation value... Something's super screwy.

This makes no sense whatsoever.

All integrated configs in the serverconfig directory are empty. And the ones in the config directory look fine (limit there is set to 65536 as expected).

**Comment by Splutty** [comment]
> @Splutty Probably you're using low-tier energy cell (with low transfer rate). Noticed that after looking at color of energy cubes.

No. Definitely not the problem. I have exactly the same problem if I hook it directly into my Powah reactor. And even if it would impact it, the energy cell I used has a rated 100KRF/t, so it then pulling 6.5K makes no sense :D

**Comment by TemperedFool** [comment]
Can you test by grabbing a creative Powah cell out of JEI, if you have op access?

**Comment by Splutty** [comment]
![image](https://user-images.githubusercontent.com/28677475/169618696-c477061d-6e61-4b49-b3a7-f488b17c6578.png)

**Comment by TemperedFool** [comment]
🤯

**Comment by Splutty** [comment]
Yep.. I'm lost...

**Comment by Splutty** [comment]
Well. Can't test with a newly installed server, because can't install new servers anymore.
