### ISSUE TITLE
IntegratedAdditions can teleport any player to any location. This can wreak havoc on public servers. 

### ISSUE THREAD

**Issue by cyb0124** [EnigmaticaModpacks/Enigmatica6#4871]
### Modpack Version

1.2.1

### Describe your issue.

Using IntegratedAdditions's "Teleporter Entity" aspect, you can teleport any player on the server to any location you want. This can wreak havoc on public servers, so should be considered a bug. Steps to reproduce:
- Build an Integrated Dynamics network with a variable store, a world reader and an entity writer.
- Store the `Players` aspect from the world reader to a variable card.
- Select a player you want to teleport from the `Players` list. Various methods exist. The easiest way is to just use a `head` variable card to select the first player.
- Put the variable card to the `Teleporter Entity` aspect on the entity writer, and the player will be continuously teleported to the entity writer's location.
- You can also configure an offset on the `Teleporter Entity` aspect, so that player can be teleported to arbitrary location. There is no range check on this offset.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report. I've relayed it to the appropriate mod's issue tracker.

**Comment by TechGeekMonster** [comment]
Cry Havoc! And let loose the dogs of war!

**Comment by hanxiaoxin778** [comment]
> ### Modpack Version
> 1.2.1
> 
> ### Describe your issue.
> Using IntegratedAdditions's "Teleporter Entity" aspect, you can teleport any player on the server to any location you want. This can wreak havoc on public servers, so should be considered a bug. Steps to reproduce:
> 
> * Build an Integrated Dynamics network with a variable store, a world reader and an entity writer.
> * Store the `Players` aspect from the world reader to a variable card.
> * Select a player you want to teleport from the `Players` list. Various methods exist. The easiest way is to just use a `head` variable card to select the first player.
> * Put the variable card to the `Teleporter Entity` aspect on the entity writer, and the player will be continuously teleported to the entity writer's location.
> * You can also configure an offset on the `Teleporter Entity` aspect, so that player can be teleported to arbitrary location. There is no range check on this offset.
> 
> ### Crash Report
> _No response_
> 
> ### Latest Log
> _No response_
> 
> ### Have you modified the modpack?
> No
> 
> ### User Modifications
> _No response_
> 
> ### Did the issue happen in singleplayer or on a server?
> Server

When I was going to add this feature before, I specifically asked kroeser, he thought it was very interesting, I also tried adding scope restrictions before, but Integrated Dynamics itself only did parameter verification on the client side, so it failed to meet expectations.

The entity writer recipe can be removed if you want to fix this.

**Comment by NielsPilgaard** [comment]
I'll remove the Entity Writer, thanks :)

It's not so much a balance issue, as I am worried this'll be used to kill/trap players on public servers.
