### ISSUE TITLE
[E6E] Buff Immersive Petroleum Coker Unit multiblock

### ISSUE THREAD

**Issue by SoulfieUwU** [EnigmaticaModpacks/Enigmatica6#4878]
### Describe your suggestion

The Coker should be buffed to provide the player with an alternative way to supply their HOP Graphite Dust needs rather than the only viable option for it is to spam Pyrolyzers as even with it maxed out can still be too slow.

### Why would you like this added/changed?

As the Coker is currently gated by Heavy Machinery Schematics, it will provide players another incentive to get the schematics as well as reduce the need for Pyrolyzer spamming. 

In its current form it is pretty underwhelming as it only converts 2 Bitumen to 1 Petcoke in about 3 seconds while you can get much more for how much space it takes with a couple Pyrolyzers.

Buff ideas might be to add block recipes to it like the Pyrolyzer already has and/or increase overall speed for its current recipe but increase power consumption so the player would still need to commit a fair bit of their power network if they want to run it constantly.

Pyrolyzer would still have a use since it's the only viable way to produce Coal Coke which in most cases Petcoke does not substitute for.

**Comment by MuteTiefling** [comment]
Sounds good, will look into it.
