### ISSUE TITLE
Add little logistic's patchouli book to the QUEST GIVEN akeshic tome

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4879]
### Describe your suggestion

-

### Why would you like this added/changed?

-

**Comment by MuteTiefling** [comment]
It's already there : D

**Comment by Quezler** [comment]
fixes it minutes before in #4921 only to then mark this as invalid 👀

**Comment by MuteTiefling** [comment]
That didn't fix this though. It was already in the book.

All that really did was fix missing nbt on the quest given book.

**Comment by Quezler** [comment]
which is the book i was talking about, never had to craft a new once since we've never lost the original one you get from quests 😃

**Comment by MuteTiefling** [comment]
well.. I guess fill out your reports better next time :P

**Comment by Quezler** [comment]
(つ･･)つ¤=[]:::::::>
