### ISSUE TITLE
[E6E] Ticking Entity Crash Spam

### ISSUE THREAD

**Issue by perennialpersephone** [EnigmaticaModpacks/Enigmatica6#4880]
### Modpack Version

Enigmatica 6 Expert 1.2.1

### Describe your issue.

As it currently stands I've set up the latest version (1.2.1) of Enigmatica 6 Expert and within 5 minutes of having people join, the server crashed due to: java.lang.NullPointerException: Ticking entity

The server has been crashing upwards of 3x times a day, maybe more, all for the same reason, Resourceful Bees being the most common issue, but things as simple as a Minecraft Villager are doing so as well.

[5/18/22 When the server First Launched.](https://gist.github.com/perennialpersephone/d14edab3f061ee542f84a7b179835331)
[5/22/22 a few days after the server had been running.](https://gist.github.com/perennialpersephone/f9769e1641b468c534975c390ded1c6b)

Posting a few crash logs, just to see if you guys can find anything.

### Crash Report

https://gist.github.com/perennialpersephone/66c1d8ea9c9d1b8d5054c95b6360d88c

### Have you modified the modpack?

Yes

### User Modifications

Small changes to FTB related plugins to allow people to have extra set homes and reduction to times for rtp and other commands.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
To resolve the issue, you need to remove the ticking entities: 

- Go into your servers `defaultconfigs` folder 
- Find the file `forge-server.toml`
- Open it (with Notepad for example)
- Change `removeErroringEntities = false` on line 14 to `removeErroringEntities = true`

I'm afraid I don't know what's causing the issue, but that change should remove the ticking entities. The server needs to be restarted in order for the change to take effect - `/reload` also does the trick.

**Comment by Darkere** [comment]
!!! not in default configs

config needs to be changed under world/serverconfig/ to have any effect on existing worlds.

**Comment by perennialpersephone** [comment]
I believe I found the issue for this problem, I removed AI-Improvements from my server, so far it hasn't had any ticking entity crashes, nor is the console being spammed with the issue either. As far as I can tell from their github page the mod doesn't currently support bees either... so maybe that's the issue?

**Comment by NielsPilgaard** [comment]
Did you also make the config change?

**Comment by perennialpersephone** [comment]
No, I removed this mod before I even made this report and have not had any issues since.

**Comment by NielsPilgaard** [comment]
Interesting, I guess that could be it. I wonder why other people don't get the issue though.

**Comment by perennialpersephone** [comment]
I'm not sure, it could just be one of those things that Java loves, it causes problems with some and works for others?
