### ISSUE TITLE
Enigmatica 6 1.3.0 Server Issue, Mods not installing on server

### ISSUE THREAD

**Issue by Burn98** [EnigmaticaModpacks/Enigmatica6#4883]
### Modpack Version

1.3.0 Alpha

### Describe your issue.

Hello everyone, I wanted to report this issue in hopes it would be resolved quickly as me and my friends would like to play this mod pack on a server. The issue we are having is that when we go to install the mod pack with version 1.3.0, the mods don't get added to the mods folder on the server side. Because of this obviously we cannot join the server as none of the mods are there. I talked to the people at the server hosting website as well as doing my own research and this seems to be an issue with the installer for 1.3.0. If I'm wrong I would love to know what could be possibly wrong with the way we have been installing it. If anyone has any further questions about this issue please do ask, I will answer them as soon as I can.

Thanks in advance everyone!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
did you install through the start-server.sh/bat, or are you using a panel?

**Comment by Darkere** [comment]
Please make sure you download a fresh server pack from the website (not from the launcher). 1.3 is the version was released specifically to address that problem.

**Comment by Burn98** [comment]
To sort of answer both of your responses in one. I'm using a server hosting site, the one in particular being ggservers. They way I went about installing it was through their panel which just has you select which mod pack to run on the server and it does the setup part for you. As such I'm not sure as to how it goes about doing so, I'm assuming it grabs the server pack for the most recent version and installs it but I'm certain about that. If there is a way to do it on there using the file from the website, please do let me know. Thanks!

**Comment by Darkere** [comment]
I see. Then the issue is unfortunately caused by your server provider not handling the new API changes. 

You may want to message them, or manually install the server if you do have ftp access. 

To do so, download the server pack from the website, launch locally once to download all the files and then upload the folder onto the server. There is a readme in the server files.
