### ISSUE TITLE
Tip Suggestion: Witches and NoAI spawners

### ISSUE THREAD

**Issue by Targren** [EnigmaticaModpacks/Enigmatica6#4884]
### Describe your suggestion

Tip: Witches spawned with the No AI Spawner Modifier will still drink heal potions when injured. This can be used to make your Well of Suffering less laggy.

### Why would you like this added/changed?

Seems like a useful tip

**Comment by Quezler** [comment]
> Status: Fixed In Next Release

**Comment by MuteTiefling** [comment]
I feel like that would take a bit too long to explain properly in a tip. Better to let people discover that one on their own, I think.
