### ISSUE TITLE
Have the expert blast brick quest depend on the atum scarab under adventure

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4899]
### Describe your suggestion

![Screen Shot 2022-05-26 at 14 42 10](https://user-images.githubusercontent.com/3179271/170489968-5abbd5e0-942f-4873-9fb3-52de9cb489af.png)
![Screen Shot 2022-05-26 at 14 43 23](https://user-images.githubusercontent.com/3179271/170489971-943b0558-4d26-4ad0-afc0-632ce6f311eb.png)

### Why would you like this added/changed?

An ingredient for the blast bricks is marl, which requires sand from atum, having the scarab as a dependency helps planning.

**Comment by MuteTiefling** [comment]
Counter argument. These hidden dependencies throw people off and lead to a lot of confusion. They don't seem to know they can look in the top left.

They're used in some chapters and we get constant questions about them. Not sure it's worth it to add them here as well.

**Comment by Quezler** [comment]
i can understand that with normal mode (e.g. the top right most node for mekanism is a checkbox with a dependency),
expert players however should be able to figure this out.

of course ftb quests is partially to blame for not showing a missing/completed dependency number at the arrow.

but to "think" you can finally craft something (since the quest is not greyed out) only to run into an unlinked dependency is more a pain in the butt then saving all of humanity from pressing a triangle.

(perhaps a quest to educate about the dependency arrows? you can go to hidden chapters for e.g. a checkbox quest)

**Comment by MuteTiefling** [comment]
A quest to tell people how to use the quest book just feels like way too much hand holding, and will just be one more thing that's ignored. I already regret using hidden dependencies in a lot of the rest of the quest book, so I won't be adding more here. JEI does an admirable job letting you know you need to go to atum.
