### ISSUE TITLE
Typo: Infused Pickaxe quest.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#4901]
### Modpack Version

E6E 1.2.1

### Describe your issue.

Occultism - Infused Pickaxe quest:
"Normally, Otherworldly ores such are Iesnium"
are -> as

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Fixed, thanks! Nice and easy to fix with the text you provided :D
