### ISSUE TITLE
Replace Inventory Tweaks with Inventory Profiles Next for superior sorting

### ISSUE THREAD

**Issue by InsanityPrelude** [EnigmaticaModpacks/Enigmatica6#4908]
### URL

https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

### Why would you like the mod added?

The default mod used for sorting inventories is flaming garbage.  It's unsupported, doesn't have the old sorting rules it used to (and those were awful too!), and doesn't support a wide variety of important features for doing anything more complex than naively alphabetizing your inventory.

I strongly suggest that it be replaced with the 1.16.5 Forge version of the mod "Inventory Profiles Next."  With some work in the configuration (moving inventory buttons around, changing default hotkeys, etc), it can recreate every important feature from Inventory Tweaks that I've been able to name, and supports a massively more advanced set of sorting rules, allowing for things like sorting by item tags, by NBT data, subsorts based on display name or count or durability or whatever, etc.  It's also much more actively developed, having a release only five days ago for both Fabric and Forge across multiple versions, which is good for the long-term health and maintainability of the project.

As an example of how much nicer it is, I've included here a series of three screenshots of a chest of mine.  The left image is of Inventory Tweaks' default sorting, crude alphabetical sorting which doesn't really help at all.  In the middle is a fresh installation of Inventory Profiles Next which I sorted that chest with, which is already surpassingly better at simple things like "sort ingots kind of next to each other."  On the right is that same chest sorted with a custom ruleset I'm working on which uses the tagging system to do complex things such as "sort all ingots together with vanilla ingots first followed by all dusts then all gems."

![image](https://user-images.githubusercontent.com/38642020/170764661-77f67788-9a09-4456-89ac-5b791e505df0.png)

**Comment by NielsPilgaard** [comment]
To be honest I don't think we have a need for this, although it looks cool. Simple sorting is what I want :)
