### ISSUE TITLE
Missing Forge:Ingots tags on several metals.  

### ISSUE THREAD

**Issue by InsanityPrelude** [EnigmaticaModpacks/Enigmatica6#4909]
### Modpack Version

1.3.0

### Describe your issue.

The following metals all have tags of the type "forge:ingots\ingot_name" but are missing the generic "forge:ingots" tag.

- Pewter
- Arcane Gold
- Sunmetal Bricks
- Hellforged Ingots
- Energized Steel
- Netherite Scrap (classed by forge as an ingot?)

For comparison, two screenshots.  One of copper (correctly configured), and one of arcane gold (incorrect).
![image](https://user-images.githubusercontent.com/38642020/170765567-daa981d4-902e-4bbe-bddc-2657f7ab8c8a.png)
![image](https://user-images.githubusercontent.com/38642020/170765605-ca95316f-5117-4604-b2fe-5abc69ef5f5d.png)

The following nuggets are also missing the "forge:nuggets" tag.

- Arcane Gold Nuggets
- Pewter Nuggets
- Netherite Nuggets
- Debris Scrap (technically outputs one nugget)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will get that fixed :)

**Comment by MuteTiefling** [comment]
Thanks for providing a list :D
