### ISSUE TITLE
[expert] improve spirit crystal block recipe

### ISSUE THREAD

**Issue by pun2712** [EnigmaticaModpacks/Enigmatica6#4911]
### Describe your suggestion

after update to 1.3.0 cost to craft spirit crystal is reduce to 1 god shard to 2 crystal ,So for 1 block use 4.5 god shard while recipe for crystals block are antimater and god block that use 4 god shard and nebu ore  
![image](https://user-images.githubusercontent.com/11716176/170819687-20036152-728c-4801-b0a8-81ae0e81a173.png)

![image](https://user-images.githubusercontent.com/11716176/170819695-955af3cc-4e68-49c4-b871-5b7649fe4eb8.png)

![image](https://user-images.githubusercontent.com/11716176/170819714-994ece6f-a4f5-4470-9587-6c08a56af97d.png)

![image](https://user-images.githubusercontent.com/11716176/170819724-9b3d5f26-a04d-44fd-a43b-60f095f970b7.png)

I feel it get more expenseve when go antimatter recipe

### Why would you like this added/changed?

I'm not sure how antiprotonic recipe work, but can it make 2 crystal block for 1 god block?

**Comment by GiaruDK** [comment]
Make sence, but in theory max output this machine 1item per craft >.<

**Comment by pun2712** [comment]
![image](https://user-images.githubusercontent.com/11716176/170839828-ee6caeb1-6261-4277-bd4b-2de52c6a6c26.png)
how about use god lantern?
