### ISSUE TITLE
Buff Digital Miner in E6E

### ISSUE THREAD

**Issue by TheDragonicSlayer** [EnigmaticaModpacks/Enigmatica6#4912]
### Describe your suggestion

In expert to make the digital miner a more viable option for ores, I suggest increasing the max radius of the digital miner to something like 512 and buff the speed a lot

### Why would you like this added/changed?

In order to make it a more viable option for ores late game

**Comment by MuteTiefling** [comment]
This creates terrible lag, the higher the radius is.
