### ISSUE TITLE
Materialis molten metals are not blacklisted for create draining

### ISSUE THREAD

**Issue by JDDelrosario** [EnigmaticaModpacks/Enigmatica6#4913]
### Modpack Version

1.3 (expert)

### Describe your issue.

Materialis molten metals are not blacklisted for create infinite draining. This includes some valuable metals like Terrasteel and Arcane Gold. Granted, it would take ~10k blocks of the stuff melted down to make the infinite source, but for consistency with other molten metals I would assume this is an oversight.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
We'll get those blacklisted as well then, thanks :)
