### ISSUE TITLE
Molds consumed when using multiservo press

### ISSUE THREAD

**Issue by FallenRosemary** [EnigmaticaModpacks/Enigmatica6#4914]
### Modpack Version

1.3.0

### Describe your issue.

a bunch of molds get consumed whenever the multiservo press crafts a recipe
haven't tried it out with all the molds but I've confirmed both the 3x3 packing mold and gear mold get consumed

### Have you modified the modpack?

Yes

### User Modifications

added optifine, metal barrels and buddycards

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Which recipes, exactly? Might help narrow it down

**Comment by FallenRosemary** [comment]
all of the gear and packing recipes seem to be consuming the molds

**Comment by MuteTiefling** [comment]
Ok. I've been doing gears this way without issue for some time on 1.3. Haven't done any unpacking though. 

Will investigate in a bit, but I'm the meantime if you can test in a clean instance without any of your modifications, that'd be helpful.

**Comment by FallenRosemary** [comment]
I'll try to launch a clean instance but I'm not sure if I'll be able to get any testing done on it due to the game running horrible without optfine

**Comment by MuteTiefling** [comment]
Nevermind, was able to confirm it and fix it.
