### ISSUE TITLE
Blast Chiller: Blazing Blood -> Blaze Rod

### ISSUE THREAD

**Issue by KB-93** [EnigmaticaModpacks/Enigmatica6#4928]
### Describe your suggestion

Can you add Blazing Blood to the recipe list for the Blast Chiller?

### Why would you like this added/changed?

This would mostly be a QoL improvement to make this autocraft more compact. I think it also makes it more consistent with the other rod cast recipes.

**Comment by NielsPilgaard** [comment]
I think this is a good idea, don't see why not 👍

**Comment by MuteTiefling** [comment]
Went ahead and added slime balls while I was at it.
