### ISSUE TITLE
No texture pack?

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#4931]
### Modpack Version

1.3.0

### Describe your issue.

So after I installed 1.3.0 the e6e texture pack was gone from the texture pack menu.

All of the other ones are still there.

### Have you modified the modpack?

Yes

### User Modifications

I installed optifine+optiforge but that shouldn’t affect texture packs.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Gcat101** [comment]
Fixed by installing [this](https://www.curseforge.com/minecraft/texture-packs/the-official-enigmatica-resource-pack-16x16)

**Comment by NielsPilgaard** [comment]
Thanks for the report. I downloaded a fresh instance to check, and did not encounter the issue :)
