### ISSUE TITLE
Make ID player simulators cheaper

### ISSUE THREAD

**Issue by CoolerGangster** [EnigmaticaModpacks/Enigmatica6#4932]
### Describe your suggestion

1 player simulator requires 4 logic directors which is quite expensive

### Why would you like this added/changed?

In comparison to other fake players its very expensive, yes it is a very powerful player simulator, but it shouldnt be this expensive, although I agree it should be more expensive than other fake players

**Comment by MuteTiefling** [comment]
Logic Directors were made cheaper some time ago. Gonna close this out as I don't actually remember which version it made it into.
