### ISSUE TITLE
Catnip Larva name appears incorrectly as "item.kube.js.catnip_larva"

### ISSUE THREAD

**Issue by InsanityPrelude** [EnigmaticaModpacks/Enigmatica6#4937]
### Modpack Version

1.3.0

### Describe your issue.

Catnip Larva apparently has an incorrect display name in JEI.
![image](https://user-images.githubusercontent.com/38642020/171038302-c6c7bd61-4049-467f-9cf5-cfad75bd0bba.png)

### Have you modified the modpack?

No

### User Modifications

Replaced Inventory Tweaks with Inventory Profiles Next.  

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by InsanityPrelude** [comment]
Actually, catnip larva also apparently makes "Filled Bee Jar - Pig" instead of a Kitten Bees?  JEI is kind of confusing me here.  I think there might not be a filled jar recipe for Kitten Bees, or a real "Pig" bee?  Seems like it's just a bit messed up.

**Comment by Quezler** [comment]
Yes i noticed that issue too while fixing this one, currently lacking the time to dig into the bee larva scripts:
![Screen Shot 2022-05-30 at 19 33 08](https://user-images.githubusercontent.com/3179271/171039144-29b06161-7c86-491e-b3e2-004191205f0c.png)

**Comment by TemperedFool** [comment]
I need to look at that one, I probably need to add some extra code to handle that particular discrepancy...

**Comment by Quezler** [comment]
#4938 might not have actually fixed the lang problem, since there is a kitten AND a catnip larva/comb, i have spotted this issue while working on #4944 but can't cleanly fix it before the latter is merged, i would be straying to far from the path. 🤔
