### ISSUE TITLE
The MmmMmmMmmMmm (Target Dummy) mod is included in the 1.3.0 modlist but not modpack

### ISSUE THREAD

**Issue by Sampppppppppppppppppppppppp** [EnigmaticaModpacks/Enigmatica6#4943]
### Modpack Version

1.3.0

### Describe your issue.

MmmMmmMmmMmm (Target Dummy) is stated to be included in 1.3.0 in the changelog/modlist, but is not in the mods folder for both client and server

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Fixed, thanks :)
