### ISSUE TITLE
[Expert] Add limestone types to Quern recipe

### ISSUE THREAD

**Issue by dawidmachon** [EnigmaticaModpacks/Enigmatica6#4946]
### Describe your suggestion

Actually, Quern from Atum 2 can be created only from Atum2 limestone. It should be interchangeable with vanilla limestone.

![image](https://user-images.githubusercontent.com/44931854/171506782-858e23ba-4db3-4e12-b7e8-f63003be3f98.png)

### Why would you like this added/changed?

LimeStone is LimeStone, I know this can push players to explore new dimension - but this is Quern only - basic tool.

**Comment by Quezler** [comment]
> **vanilla** limestone 🤔

**Comment by dawidmachon** [comment]
> > **vanilla** limestone 🤔

It was late Oo.
Any other limestone origin. ; )

**Comment by MuteTiefling** [comment]
There kinda isn't a good option for this.

Create limestone has no plain slab. just chiseled varieties, which seems odd for a hand mill. As I recall, Create's is what currently spawns in the overworld.
Quark and Architect's Palette limestone has plain slabs/blocks... 

It's also already possible to chisel between limestone types and all of these can be obtained via randomized cobblegen. Added to that, the Quern isn't even something that can be automated and is mostly just an dye mill (and not even very good one at that). 

I know it's already accepted, but I'm just not seeing a good way to do this, short of tagging all the limestones with a new tag (which we'd then need to do with all other types of stones for consistency's sake) and just ignoring the lack of decent slab options.

**Comment by NielsPilgaard** [comment]
Fair enough, we won't be making this change after all then :)

**Comment by dawidmachon** [comment]
With such a reasoned comment, I will not debate. I like everything that has been said ;)
