### ISSUE TITLE
[Expert] Pink slime not collected in non-overworld biomes.

### ISSUE THREAD

**Issue by TahoeBennie** [EnigmaticaModpacks/Enigmatica6#4947]
### Modpack Version

1.3.0

### Describe your issue.

When harvesting pink slime like you do for ether gas, over a pink wither, the fluid laser base will not collect pink slime in compact machines, nether, or end as it has all of those biomes blacklisted. I'm pretty sure it is unintentional this way as ether gas works fine in these biomes, but pink slime should work this way as it has nothing to do with the biome its in, just that it is over the pink wither.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
It was intentional, but I don't think there's any real harm in removing the restriction either.
