### ISSUE TITLE
Have baby bees drop larva as well

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4948]
### Describe your suggestion

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/develop/kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/resourcefulbees/bees.js

### Why would you like this added/changed?

Currently only grown-up bees drop larva, leaving a window open for bees that meet their end before they can come of age.

**Comment by TemperedFool** [comment]
Why would entity age affect whether or not it rolls its loot table on death? Do baby pigs and sheep not drop stuff when the perish?

**Comment by MuteTiefling** [comment]
I don't think babies drop anything, no. Of any animal.

**Comment by Quezler** [comment]
As far as i could tell their loot table files are suffixed with _baby, but that did not seem to work for bees, created this in the hope someone more knowledgeable knows how 😅
