### ISSUE TITLE
[Expert] Recipe for Redstone control on spawners is wrong

### ISSUE THREAD

**Issue by lephro** [EnigmaticaModpacks/Enigmatica6#4950]
### Modpack Version

1.3.0

### Describe your issue.

The recipe  for redstone control on spawners says that you should have a token of sorrow in your offhand.
It doesnt work with the token of sorrow, but with a token of joy, instead.

Since the token of joy is used to "add"  things, the JEI recipe should be corrected to reflect that.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This is intended.

+redstone control adds redstone control. All the + recipes use joy.

Sorrow removes the upgrade.

**Comment by lephro** [comment]
So it is intended that JEI shows Token of  Sorrow, but you have to use token of Joy ?
How does this make sense?
