### ISSUE TITLE
`Questbook` pnc etching quest text spelling 

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4951]
### Modpack Version

1.3.0

### Describe your issue.

the `, however, and a` doesn't look like proper english:

![Screen Shot 2022-06-03 at 19 57 18](https://user-images.githubusercontent.com/3179271/171920154-8ec456d9-c498-4ebb-8dc5-8ee8fcc6cc16.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
That does indeed look misplaced.

**Comment by NielsPilgaard** [comment]
Ah that makes more sense, I was a bit too quick to edit then ^^' Would you like it changed back?

**Comment by MuteTiefling** [comment]
It's probably ok without it. There's an extra comma now though before the and.
