### ISSUE TITLE
[Expert] Wrong JEI recipe for redstone control on spawners

### ISSUE THREAD

**Issue by lephro** [EnigmaticaModpacks/Enigmatica6#4952]
### Modpack Version

1.3.0

### Describe your issue.

Bug:
JEI recipe for redstone control shows token of sorrow in offhand. (Does not work)

Expected:
JEI should show token token of joy (works)

I've already reported this, but either its my english or you guys don't read properly: 
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4950#issue-1258296768

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
in order to avoid dragging this on, include a screenshot of the jei recipe you believe adds redstone control.

**Comment by lephro** [comment]
![grafik](https://user-images.githubusercontent.com/40739111/171955076-215c9126-52d3-4863-9b37-09a60b24d1d6.png)

Ok this was my bad... iam sorry!

Problem is that both recipes are fairly spread appart.. Even the veterans on the server were confused about this and though that its a bug. Sry!
