### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Phat-Joe** [EnigmaticaModpacks/Enigmatica6#4956]
### Modpack Version

1.3.0

### Describe your issue.

When throwing items into a petal apothecary, and then throwing vines into it, it converts the apothecary into a mossy one and returns items thrown in before the transformation. The issue is the items remain in the apothecary as well, and if you break it you duplicate the items.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
#4652
