### ISSUE TITLE
Aura trove collected in survival doesn't work for sink recipe

### ISSUE THREAD

**Issue by TahoeBennie** [EnigmaticaModpacks/Enigmatica6#4963]
### Modpack Version

1.3.0

### Describe your issue.

When making a sink from cooking for blockheads (the expert mode recipe) collecting a full aura trove in survival, by letting it fill up, doesn't work for the recipe. The one grabbed out of the creative menu will let it craft fine but it doesn't work with a regular aura trove that was filled up manually.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Quezler** [comment]
did you put it in the altar, or did it only charge in your inventory?

**Comment by TahoeBennie** [comment]
I charged it in my inventory, but if putting it in the natural altar actually charges it and then it works fine, that’s my bad for not knowing about that method.
