### ISSUE TITLE
[expert] Stellar neutron activator don't consume mana

### ISSUE THREAD

**Issue by pun2712** [EnigmaticaModpacks/Enigmatica6#4964]
### Modpack Version

1.3.0

### Describe your issue.

![image](https://user-images.githubusercontent.com/11716176/172071300-3d71952c-cfe9-4931-b0d9-2eaef85c728d.png)
after i fill it with full mana , it don't consume it anymore ,so can make 512000++ mb with only 4 mana pool 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
I'm unable to replicate this.

The structure is set to consume the entire amount of mana at the start, then over the course of the recipe, it outputs deuterium per tick. Once it hits 100%, it takes another chunk of mana and starts on the next 'recipe'. Depending on how fast you're feeding mana, it's entirely possible it sits 'full' for a while before it takes the mana gain.

In my test world, I've got 4 gaia spreaders shooting each input and the mana pools end up full again around the 60% mark of the recipe. So 40% of the time, the spreaders are not firing.

**Comment by MuteTiefling** [comment]
If the described behavior isn't what you're seeing, ultimately, we'll need to see your logs to see if any of the scripts failed to run. Otherwise, I'd recommend re-installing the pack to ensure it's installed correctly.

**Comment by pun2712** [comment]
in my world  i use spark ,with recipe said  640mb per 4000000mana it should like. see a mana form the supply pools are draining  but in like 3 min. i have  full 512000mB in buffer + 256000mB in tank  for that ,it should consume ... 768000/640 = 1200 cycle = 4800 pool of mana , I'am sure that all my mana  source should not supply that much mana in 3 min, what log should I see?

**Comment by pun2712** [comment]
Wait , or I just confused in recipe , in working like consume 4000000mana 1 time  and continueus generate 640mb of tritium until it machine progress up to 100 %  ,So it like 640000 mb of tritium per 4 mana pool ?

**Comment by NielsPilgaard** [comment]
It does indeed consume all the mana upfront, I thought that was stated in the recipe 🤔

**Comment by pun2712** [comment]
I understand that this not a bug ,so it invalid, but I have suggestion about this. , should I go create new suggestion issue?

**Comment by pun2712** [comment]
oh ,and don't see any infomation about the way mechine consume anywhere, a least in normal playing day.

**Comment by NielsPilgaard** [comment]
We'll add some info 👍
