### ISSUE TITLE
PCBee honeycomb does not work in a centrifuge unless there are no bottles in the centrifuge

### ISSUE THREAD

**Issue by TahoeBennie** [EnigmaticaModpacks/Enigmatica6#4965]
### Modpack Version

1.3.0

### Describe your issue.

When centrifuging PCBee honeycomb, it will not work if there are bottles in the centrifuge to collect honey, because it produces etching acid, which is not collectible in a bottle. The issue comes from the fact that the etching acid is in the honey output slot, rather than the item output. This is also the only honeycomb that does this. Some other honeycombs that make liquid (milk and latex) are in the normal output slot because there is only one other item to be produced, which works fine, but with PCBee, it makes 2 items and a liquid, so the liquid has to be in the honey slot. This causes it to not refine at all while there are bottles. To fix this, there either needs to be an added recipe that is done with bottles and pcbee honeycomb, but when it is made, the outputs are the same as without bottles and the bottles remain unchanged, or somehow make it so the bottles are ignored. What could also happen is the empty pcbs become the honey output slot, and etching acid is the regular output, and pcbee honeycomb will not refine WITHOUT bottles (as opposed to this issue, which is that it doesn't go with bottles) and the pcbee honeycomb becomes one of the honeycombs that requires a bottle to work, and it changes the bottle into the empty pcbs upon the success of the pcb 1% chance.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
This is by design; the choice was to have it require bottles and produce items in that slot, or produce a fluid and not work with bottles. There is no bottle of etching acid, so we can't have it produce one.
