### ISSUE TITLE
[E]Botany Pot Recipe gone

### ISSUE THREAD

**Issue by dawidmachon** [EnigmaticaModpacks/Enigmatica6#4966]
### Modpack Version

1.3.0

### Describe your issue.

Botany Pot recipe in JEI is missing.Is it intended?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
no dissolution chamber tab?

**Comment by NielsPilgaard** [comment]
Please provide your server and client latest logs :)

**Comment by dawidmachon** [comment]
My bad!
Sorry for your inconvenience!

Good modpack, still working hard on expert inside 👍
