### ISSUE TITLE
Building Gadgets copy and paste block duplication with Immersive Engineering multi-blocks

### ISSUE THREAD

**Issue by Sampppppppppppppppppppppppp** [EnigmaticaModpacks/Enigmatica6#4967]
### Modpack Version

1.3.0

### Describe your issue.

When using the Building Gadgets copy and paste tool with formed Immersive Engineering multi-block machines, the tool tries to place down the machine's tiles instead of it's actual components (i.e. steel scaffolding). When pasting in the structure with the tool, the machine tiles are placed in the world without taking anything from the player, and when broken, certain components of the machine are dropped resulting in a duplication.

![copying structure](https://user-images.githubusercontent.com/93164558/172234597-f68a5654-785f-4891-8cf9-6c2f8bf12c57.png)

![structure preview](https://user-images.githubusercontent.com/93164558/172234594-caa40d66-3fea-4818-86a3-ca612db11413.png)

![pasting structure](https://user-images.githubusercontent.com/93164558/172234590-f32d28ad-8333-44c3-87b7-2e43be1f0cfd.png)

![block drop](https://user-images.githubusercontent.com/93164558/172234588-a1a5898b-4be3-4c7d-9bc5-f4fc1cba20d2.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thought we had blacklisted these...

**Comment by NielsPilgaard** [comment]
Me too. Perhaps only in expert?

**Comment by Darkere** [comment]
#4475

**Comment by NielsPilgaard** [comment]
Nooo 😂

**Comment by MuteTiefling** [comment]
I mean, it looks like it was fixed at some point. Typo was gone in your last commit... but I can still replicate this in dev.
