### ISSUE TITLE
Removal of mods that disable third-party APIs

### ISSUE THREAD

**Issue by FrederikRasmussen** [EnigmaticaModpacks/Enigmatica6#4975]
### Describe your suggestion

I would like to remove the 6 mods currently in the pack that do not allow third-party API downloads:

- Save Your Pets
- Fix Experience Bug
- Small Ships
- Spawner Bug Fix
- More Overlays Updated
- Masonry

For some of these, suitable alternatives are available, or the mod is wholly unnecessary to the experience of E6 as it is.

The initial discussion should probably revolve around whether or not this is a desirable change at all, rather than _how_ it might be accomplished..

### Why would you like this added/changed?

The removal of mods that do not allow third-party API downloads simplify the installation procedure for users in launchers that do not yet support CurseForge's new feature. This includes GDLauncher. It also simplifies installation for other third-party launchers as the user does not have to manually download the 6 mods in question.

Personally, I think it is reasonable to implement this, as it sends a message that the modpack is hassle-free and easy to use for all, not just those who use specific software or have the know-how to manually install a pack in their unsupported launcher of choice.

This was [briefly discussed](https://discord.com/channels/195234321836146688/544822403230859283/984422268862070845) on Discord under my tag Nuzzleskatev#0001, and some points were brought up that speculated on why mod developers may have enabled the feature for their mods. To me this seemed to mostly centre around the idea that developers use the feature to get more ad revenue and removing the mods would send a signal that this is undesired.

From a practical point of view, removing these mods may have impact on forward compatibility, as removing Masonry, Save Your Pets, and Small Ships will result in the loss of blocks and items.

Shut this down as desired, I would just like it documented, if it is not implemented.

**Comment by TemperedFool** [comment]
> To me this seemed to mostly centre around the idea that developers use the feature to get more ad revenue and removing the mods would send a signal that this is undesired.

It seems very hostile to mod developers to punish them for wanting to be paid for their work.

**Comment by NielsPilgaard** [comment]
Hi there! We will not be removing mods that have opted out of 3rd party distribution :)
