### ISSUE TITLE
Eidolon magic workbench item duplication

### ISSUE THREAD

**Issue by 12-4-25** [EnigmaticaModpacks/Enigmatica6#4979]
### Modpack Version

1.3.0

### Describe your issue.

Putting items that are stackable (need at least 3 of each) on the additional slots of the Eidolon magic workbench allows item duplication. 
Video links:
https://youtu.be/3Xqs8zlo-Ms
https://youtu.be/eTlZz8Mjg4M

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Duplicate of #4544
