### ISSUE TITLE
Unable to legitimately acquire Eidolon's Polished Wood Stairs

### ISSUE THREAD

**Issue by FistoDaOrc** [EnigmaticaModpacks/Enigmatica6#4982]
### Modpack Version

1.3.0

### Describe your issue.

First off; Sorry if I've mislabeled this or anything of the sort, this felt like it struck a middle ground between bug report and suggestion.

That aside, the problem can be summed up by the title. While all other Polished Wood items from the mod Eidolon are able to be crafted perfectly fine, there's no associated recipe of any kind for the respective stairs of the set.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report :)

@MuteTiefling you recently worked on recipes with Polished Wood right, was this included?

**Comment by MuteTiefling** [comment]
I'll double check them. How weird though, that should be a standard 3x3 recipe.
