### ISSUE TITLE
All Thermal Dynamos become waterlogged upon updating to 1.3

### ISSUE THREAD

**Issue by Butternubbs** [EnigmaticaModpacks/Enigmatica6#4987]
### Modpack Version

1.3.0

### Describe your issue.

When I updated my world from 1.2.2 to 1.3, all of my dynamos became waterlogged in world.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Known issue, there's nothing to do about it I'm afraid :P thanks for the report anyway.

![image](https://user-images.githubusercontent.com/21295394/173245434-05a5dd5f-4e15-406e-a43e-88b07bde5f57.png)
