### ISSUE TITLE
Bucket dupe with PNC fluids and pretty fluid pipes

### ISSUE THREAD

**Issue by Vashal0** [EnigmaticaModpacks/Enigmatica6#4988]
### Modpack Version

1.3.0

### Describe your issue.

If you get a fluid container filled with any amount of the burnable PNC fluids(from over sending, or breaking the pipe), and use that as fuel in a furnace, then it not only works as full bucket of fuel but also returns an empty bucket. 

Similarly, a mekanism tank of pnc burnable fluid is consumed, regardless of the amount of fuel, and returns no output at all.

here is a short video if that's allowed showing both bugs [https://www.youtube.com/watch?v=F2TRSG0Nx-w](url)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by desht** [comment]
Just happened to notice this so I'll save you some time by stating this one's on PNC.

Any PNC fuel in any container item is admissible as furnace fuel, which is intended behaviour.  However there are a couple of bugs right now:
* The container is always considered to have 1 bucket of fuel for determining burn time, regardless of the actual amount.
* Not all container items actually support being used as a smelting input like this (specifically `item.hasContainer()` must be true). Mekanism tanks are an example of such a container item (not a Mekanism bug, I should stress).  Such items should be disallowed from being placed in the Furnace fuel slot.

I do not see the behaviour mentioned above (always returning an empty bucket); that might be down to the item in particular, but PNC tank items always return themselves with (up to) 1000mB of fuel removed.

I will be remedying this in the next PNC release; if you want to forward me on an issue as a reminder, that would be fine :)

**Comment by NielsPilgaard** [comment]
Thank you :D
