### ISSUE TITLE
Infinite Papyrus glitch with Create

### ISSUE THREAD

**Issue by timeconsumer06** [EnigmaticaModpacks/Enigmatica6#4997]
### Modpack Version

1.3.0

### Describe your issue.

Set up a farm with Create's Harvester. The harvester will harvest Papyrus, once the papyrus has grown and the harvester can reach the Papyrus. Harvested papyrus will be transferred to the transfer pipes.

Problem is that once the papyrus is harvested, it wont be cut down, as other crops will be. So the same stalks of papyrus will be harvested on every go around of the harvester. I ended up with 50k+ papyrus within the span of <45 min. 

Not super game breaking, Papayrus isnt used for much, aside from scrolls. But figured its still worth a report.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report - The Create Harvester's logic regarding modded multi-block plants isn't the greatest, not much we can do about it I'm afraid 😅
