### ISSUE TITLE
Cyclic

### ISSUE THREAD

**Issue by dawidmachon** [EnigmaticaModpacks/Enigmatica6#4999]
### URL

https://www.curseforge.com/minecraft/mc-mods/cyclic

### Why would you like the mod added?

I saw previous comment, but start thinking if this mod (part of it) is not a good addition as unrelated, balanced somehow steps in start and in middle or as additional rare loot to add variety.  Like treat items from there as useful findings in chests only. i know in E2 It was present and there were problems, balancing, removing etc. But maybe now we have sad times and 'a little fun' in serious pack is not such bad idea? Ofc in proper, fitting way balanced ;) Enigmatic items to be found.

#37

**Comment by MuteTiefling** [comment]
We don't want the mod. The few things it offers that we do want are available from other mods.
