### ISSUE TITLE
On the mushroom fields spawn hostile mobs including Brutish Zombees and Spiders, Skeletons, Zombies and Creeper

### ISSUE THREAD

**Issue by DJMo13** [EnigmaticaModpacks/Enigmatica6#5006]
### Modpack Version

1.3.0

### Describe your issue.

The mushroom fields are normally the only biome where only bats and mushroom cows can spawn, at every daytime, but there spawn hostile mobs as well, even it is the only biome where naturally, only these friendly mobs can spawn

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Isn't the peaceful biome called Mushroom Island?

**Comment by MuteTiefling** [comment]
mushroom islands are made up of 1-2 biomes I think. mushroom fields and mushroom shores.

**Comment by FooterMan14** [comment]
It's one biome, Mushroom Fields. Commonly referred to as Mushroom Island. Just came to drop that in cause it looks like y'all are having trouble with it 😀
