### ISSUE TITLE
Quest reward Loot Boxes not giving items upon completion 

### ISSUE THREAD

**Issue by Secondbreakfastpip** [EnigmaticaModpacks/Enigmatica6#5018]
### Modpack Version

1.3.0

### Describe your issue.

When collecting the various mod loot boxes after completing a quest, nothing is given to the player, only individual items an Xp are given to the player if they were the quest reward. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
I'm guessing something went wrong during the server install, and you're missing the loot table files that those rewards reference. I recommend a reinstall of the server :)

**Comment by Secondbreakfastpip** [comment]
Ah thanks for the advice, this seems to have fixed the issue!
