### ISSUE TITLE
Throwing items to the ground from a Sophisticated Backpack can throw the backpack itself

### ISSUE THREAD

**Issue by emoran0403** [EnigmaticaModpacks/Enigmatica6#5023]
### Modpack Version

Enigmatica 6, 1.3.0

### Describe your issue.

I had tons of netherrack after mining in the nether.  I wanted a quick and easy way to dispose of them, so I opened my diamond backpack from Sophisticated Backpacks in front of lava.  I held down CTRL + Q to throw stacks of items at a time.  I began to move my cursor over the items I wanted to get rid of in the lava.  After moving over a few stacks, the interface closed, and the backpack itself was thrown into the lava, deleting it and the contents.

After some testing it seems that:
- Holding CTRL, and pressing Q one at a time over an item does not throw the backpack.
- Holding CTRL, and pressing Q one at a time over an empty slot does not throw the backpack.
- Holding CTRL and holding Q  at the same time over an empty space throws the backpack after ~1 second.
- Holding CTRL and holding Q  at the same time over and moving over items or empty spaces throws the backpack after ~1 second.
- Holding CTRL and holding Q  at the same time while the mouse is over any part of the interface will throw the backpack after ~1 second.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, and nice work testing!

@P3pp3rF1y got an interesting bug for you here 😄

**Comment by P3pp3rF1y** [comment]
This was fixed in the latest version of backpacks for 1.16 through 1.19

**Comment by Quezler** [comment]
just gonna link this for reference: https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3847445
