### ISSUE TITLE
Replace discord rpc mod

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#5032]
### Describe your suggestion

Replace [Simple Discord Rich Presence by Sunekaer](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence) with [Simple Discord RPC by 
hypherionsa](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc/)

### Why would you like this added/changed?

Linux support

**Comment by NielsPilgaard** [comment]
I think there would be too much work in switching to be frank, sorry.
