### ISSUE TITLE
Green and brown dyes aren’t craftable with other dyes in create’s mechanical mixer

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#5033]
### Modpack Version

1.3.0

### Describe your issue.

Title.

### Have you modified the modpack?

Yes

### User Modifications

Added optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Gcat101** [comment]
LIght blue dye (for example):

![light blue](https://user-images.githubusercontent.com/79367505/175534104-b77bcd6f-a3d5-4f7c-a932-6f7bb7df49c9.png)

Green and brown dye:

![green](https://user-images.githubusercontent.com/79367505/175534344-6ff6bd8f-f210-413c-888b-46a30452a7d5.png)
![brown](https://user-images.githubusercontent.com/79367505/175534511-1f3c1b35-0cc5-4fcc-b52e-40ec126b5012.png)

**Comment by Gcat101** [comment]
The ones added by enigmatica mod:

![brown](https://user-images.githubusercontent.com/79367505/175540072-0949ca2c-bed8-4d2f-9ea3-927e01b718f5.png)
![green](https://user-images.githubusercontent.com/79367505/175540075-31f7bcbb-9509-42ae-93c1-8c8e39ca71cb.png)

**Comment by MuteTiefling** [comment]
No clue why _auto shapeless_ isn't picking these up, but yeah we can add them to the mixer too
