### ISSUE TITLE
SophisticatedBackpacks sharing the same inventory enabling Item Duplication; possibly Pretty Pipes related

### ISSUE THREAD

**Issue by edbrenn** [EnigmaticaModpacks/Enigmatica6#5034]
### Modpack Version

1.3.0

### Describe your issue.

I have 3 iron backpacks that share the same inventory. 
Adding items to one of them allows you to pull those items from the other two and the original backpack again, enabling you to duplicate/triplicate any items put in the backpack. 
I haven't tested but I would assume that the upgrade that allows you to put backpacks inside of backpacks would also enable duplication of these backpacks themselves.

I believe I acquired these backpacks in 1.2.0 and whatever happened to cause this may have occurred in 1.2.0.
I'm not sure when exactly this happened since I only noticed it after migrating everything to Refined Storage. Normally in Refined Storage, backpacks (and other items with metadata) show as separated but these ones show as a stack.

I haven't found a way to replicate it.

This may be due to Lootr or world-generation issues as I think these backpacks were mob drops or found in Lootr chests.

My other theory is Pretty Pipes, because Pretty Pipes Crafting Manager GUI shows items with unique metadata like backpacks as single "stack". I remember requesting backpacks from those "stacks" to use.
These items may have been sent back to Crafting Manager due to the chest they were sent to having no space or have been pulled from or entered a drawer, drawer controller, or PNC reinforced chest. The inventory they were in may have been put in a Cardboard Box. They also may have been together in a gravestone.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Huh, I thought the inventory sharing bug was fixed a while ago. I'm not sure what we can do if you can't replicate it yourself though, tbh.

**Comment by edbrenn** [comment]
No worries, figured I'd report it just in case since it enables duplication of basically anything. Not an issue for me on SP since I can just ignore/delete them, but if you see others reporting this where it can have an impact (e.g. Servers), hopefully, the possible Pretty Pipe connection helps. 
I'm pretty sure it's something to do with pulling them out of inventories because I found two more backpacks in my RS system that share an inventory. Seems too unlikely that they're all world-gen.
