### ISSUE TITLE
Ender Bees becomes agroed when trying to breed them / makes them unbreedable

### ISSUE THREAD

**Issue by Porcy** [EnigmaticaModpacks/Enigmatica6#5035]
### Modpack Version

1.3.0

### Describe your issue.

Right-clicked ender bees with ender pearls to breed them. They agroed and died because of my thorn armor. 

### Have you modified the modpack?

Yes

### User Modifications

Added Vanilla Food Pantry and Pam's HarvestCraft suite, NoFog and FarSight.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by FooterMan14** [comment]
Why not just take off the armor...?

**Comment by Porcy** [comment]
You're missing the point. Ender bees are not breedable. Giving them their listed breeding item makes them aggro.

**Comment by MuteTiefling** [comment]
Tested, yes it is difficult to do this by hand since it tends to throw the pearl at them instead of just giving it to them. You can use an apiary breeder, of course, but it's a simple thing to fix too. They'll be bred with ender pearl dust now.
