### ISSUE TITLE
JEI search focus loss with Time in a Bottle in inventory

### ISSUE THREAD

**Issue by Stratous42** [EnigmaticaModpacks/Enigmatica6#5037]
### Modpack Version

1.3.0

### Describe your issue.

While I have the Time in a Bottle in my inventory and click on the JEI search bar when the bottle ticks up a second the cursor disappears from the search bar.  It only happens when the bottle is visible on screen and gaining time.  For example if the bottle is in the 2x2 crafting area it doesn't gain time and the cursor doesn't disappear, or if the crafting list is open the search bar works because the bottle isn't on screen.

EDIT:  I forgot that I switched the version of Just Enough Calculations to be the version with the widget, and it seems like it might be combination of that and the Time in a Bottle somehow interacting to cause the bug.

### Have you modified the modpack?

Yes

### User Modifications

Installed the widget version on Just Enough Calculations

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Boy that is weird :P I'm surprised I haven't heard about this before tbh, can anyone confirm this?

**Comment by damian2603** [comment]
i have the same issue

**Comment by MuteTiefling** [comment]
I've had a TIAB in my inventory for ages now while playing e6e and have not encountered this. I'd think this isn't as simple as 'have TIAB in inventory'. There must be something else you two have in common.

**Comment by Stratous42** [comment]
So I forgot that I switched the version of Just Enough Calculations to be the version with the widget, and it seems like it might be combination of that and the Time in a Bottle somehow interacting to cause the bug.
