### ISSUE TITLE
Item Tunnel Quest Uncompletable

### ISSUE THREAD

**Issue by IlleareanDiamond** [EnigmaticaModpacks/Enigmatica6#5039]
### Modpack Version

1.3.0

### Describe your issue.

The item tunnel quest under the storage tab is not completable due to the item tunnel having no recipe

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Fixed this by removing the quest. Already live in 1.4
