### ISSUE TITLE
Atum Animal Armor processing

### ISSUE THREAD

**Issue by Alex-hawks** [EnigmaticaModpacks/Enigmatica6#5040]
### Describe your suggestion

Atum animal armor items (camel and wolf) only have the vanilla recovery recipes, that is, smelting the iron and gold ones into a nugget. I'm suggesting adding the same smeltery, foundry, and crushing wheel recipes with appropriately adjusted values for animal size.

### Why would you like this added/changed?

Just for consistency with the existing horse armor recovery recipes

**Comment by NielsPilgaard** [comment]
Good suggestion, but I'm not sure we have the time to actually implement it 😄

**Comment by MuteTiefling** [comment]
took the lazy route and made them all the same.
