### ISSUE TITLE
cant start server for enigmatica 6 expert 

### ISSUE THREAD

**Issue by triplesixdegrees** [EnigmaticaModpacks/Enigmatica6#5043]
### Modpack Version

1.1.2 Modpack / 1.3.0 Server

### Describe your issue.

Just installed everything, accepted eula and its not starting up. i have java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
and installed JDK jdk-18_windows-x64_bin

both crash report and latest: https://gist.github.com/triplesixdegrees/6285241b70dd71ea720a077d1f1a8ba7
if u need something else i can provide

### Crash Report

https://gist.githubusercontent.com/triplesixdegrees/6285241b70dd71ea720a077d1f1a8ba7/raw/0f91b2e75b6c749b3a063160ce266a6f79f78361/2022-06-29-10.log

### Latest Log

https://gist.githubusercontent.com/triplesixdegrees/6285241b70dd71ea720a077d1f1a8ba7/raw/0f91b2e75b6c749b3a063160ce266a6f79f78361/latest.log

### Have you modified the modpack?

No

### User Modifications

changed in server settings file:
server-setup-config.yaml

from:
    # specifies the max amount of ram the server is supposed to launch with
    maxRam: 5G

    # specifies the min amount of ram the server is supposed to launch with
    minRam: 2G
to:
    # specifies the max amount of ram the server is supposed to launch with
    maxRam: 12G

    # specifies the min amount of ram the server is supposed to launch with
    minRam: 8G

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
1.16 needs java 8 not 18

**Comment by triplesixdegrees** [comment]
u mean just java not JDK?

**Comment by triplesixdegrees** [comment]
ill try give me a minute

**Comment by triplesixdegrees** [comment]
i already have java 8 update 321 but ill update it for u and try

**Comment by triplesixdegrees** [comment]
reinstalled nothing change
![изображение_2022-06-30_002539196](https://user-images.githubusercontent.com/103490220/176547686-6203d3dd-42b5-4908-8fa3-33c24120e11e.png)
d

**Comment by triplesixdegrees** [comment]
ok gonna try to type in discord server my problem

**Comment by triplesixdegrees** [comment]
i got it u mean that 16+ java version causes some sort of trouble, yeah thanks
