### ISSUE TITLE
Energized Glowstone should have Tinker's Construct Recipes.

### ISSUE THREAD

**Issue by vidal-adrien** [EnigmaticaModpacks/Enigmatica6#5047]
### Describe your suggestion

Energized Glowstone (Thermal Series fluid) should have a recipe in the Tinker's Construct Smeltery and Foundry. 

### Why would you like this added/changed?

Since the basically everything else can be smelted in TC, this seems to be an oversight.

**Comment by NielsPilgaard** [comment]
Iirc we removed it intentionally as it provided too easy access to certain metals. I could be wrong though :P

**Comment by Kanzaji** [comment]
Afaik Motoko said to @vidal-adrien to create a github issue about this and that for E6E its not intentional. Here is the link to the discussion https://canary.discord.com/channels/195234321836146688/947932229143760957/992135497218543626
And Motoko Message: https://canary.discord.com/channels/195234321836146688/947932229143760957/992145965857374208

**Comment by MuteTiefling** [comment]
I think it's worth a closer look. I can't think of any reason why melting glowstone itself would be problematic. Worst case, we might need to remove some of the alloys from the smeltery.

Either way, we have a recipe that exists but is broken.

**Comment by vidal-adrien** [comment]
The only alloy that uses energized glowstone is lumium which can be made in the induction smelter behind which the smeltery is gated. 
And energised glowstone itself can be made in the magma crucible behind which the smeltery is also gated.

**Comment by NielsPilgaard** [comment]
Ah right, I stand corrected 😅

**Comment by MuteTiefling** [comment]
Yeah, not seeing any blatant issues. was probably just an oversight when things got shuffled around between materialis and tcon
