### ISSUE TITLE
Pushing Pedestals w/ Mechanical Piston from Create causes a game crash (or server crash).

### ISSUE THREAD

**Issue by SoulfieUwU** [EnigmaticaModpacks/Enigmatica6#5054]
### Modpack Version

1.3.0

### Describe your issue.

Pushing a pedestal from the mod Pedestal using a Mechanical Piston from Create causes the game and/or server to crash.

https://user-images.githubusercontent.com/104746680/177456943-21b96464-7ea5-4ab3-b708-2ce99a5b1d73.mp4

### Crash Report

https://gist.github.com/SoulfieUwU/a068cd0d4e7fbd3fdd37ead1bad4561b

### Latest Log

https://gist.github.com/SoulfieUwU/6561d2047580a4f02fda25b0fb1dfcf3

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks! All fixed up for next release
