### ISSUE TITLE
Can't connect to a 'Open to LAN' server

### ISSUE THREAD

**Issue by KwtanL** [EnigmaticaModpacks/Enigmatica6#5069]
### Modpack Version

1.3

### Describe your issue.

I have been trying to connect to a server hosted by a friend with the 'open to lan' option with port forwarding and his ip
However, when I tried to join the world. The normal joining process would be the same except for when the 'Joining world' screen pops up. The game would seem to be able to load the world for around a second with 1 frame of the world rendered. Then, the connecting player would be instantly disconnected from the world. Sometimes, the screen would only display "disconnected". Sometimes, the screen would display "io.netty.util.IllegalReferenceCountException: refCnt: 0"
This has only been a thing starting from a few days back after we started crafting the endgame tokens.
Before that, there has always been an issue of disconnecting because of "Illegal package received. Terminating connection"

### Latest Log

https://gist.github.com/KwtanL/c7a02632d161bcac974e4663e7d013da

### Have you modified the modpack?

Yes

### User Modifications

added https://www.curseforge.com/minecraft/mc-mods/out-of-sight
changed the entity-culling setting

### Did the issue happen in singleplayer or on a server?

Server

**Comment by KwtanL** [comment]
Would like to add a comment on the situation.
I noticed an error  "[Netty Client IO #11/ERROR]: Error adding element: Unknown registry element mod.beethoven92.betterendforge.common.world.feature.SinglePlantFeature@35eb94a"
This is consistent to every failed connection

**Comment by MuteTiefling** [comment]
Mods don't generally work nicely with Open to LAN. You'll need to set up a server instead.
