### ISSUE TITLE
Addition: 'Falling Leaves' Mod

### ISSUE THREAD

**Issue by AnUmbreon** [EnigmaticaModpacks/Enigmatica6#5070]
### URL

https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge

### Why would you like the mod added?

Falling Leaves adds particle effects in the form of leaves falling from leaf blocks on trees. I wanted to suggest this as an addition as it adds a little bit of extra life/atmosphere to trees, whether they're part of a forest, a decoration within a build, or anywhere inbetween.

A nice bonus with the mod is it is very lightweight, showing minimal to no performance loss while running it as part of a single player world, alongside a config to minimize the amount/size/despawn of leaves if necessary.

**Comment by NielsPilgaard** [comment]
I don't really see a need for this, and the lack of response on many GitHub issues worries me, sorry but no.

**Comment by Gcat101** [comment]
No need? It looks cool. Add now
