### ISSUE TITLE
Enigmatica Dedicated Server Bug Crash

### ISSUE THREAD

**Issue by Fahrmut** [EnigmaticaModpacks/Enigmatica6#5075]
### Modpack Version

1.3.0

### Describe your issue.

When I open the server it starts to run fine, but after a while an error appears and it stops opening, I already tried to create the server from scratch and add the world but it keeps crashing, I'm pretty sure it's the world but I'd like to see if it can be solved without losing it.

### Latest Log

https://gist.github.com/Fahrmut/44f9520923b9184dd9dd2011e568f864

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Your `BiomeIdFixer.json` appears to be incorrect in some way, please find it in your world folder: `{worldname}/biomeidfixer/BiomeIdFixer.json` 

Paste the contents here or in a [gist](https://gist.github.com), and maybe we can fix it :)
