### ISSUE TITLE
Gaia reactor has stopped working after updating the pack (hypothesis: the mana output ports now have insufficient capacity)

### ISSUE THREAD

**Issue by Ieldra2** [EnigmaticaModpacks/Enigmatica6#5076]
### Modpack Version

1.4

### Describe your issue.

After updating to pack version 1.4, the gaia reactor has stopped working. I suspect the reason is that the gaia spirit recipe has changed to make 2.7m mana, but both output ports together only have a capacity of 2m.
 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. That's all fixed up in dev now.

**Comment by NielsPilgaard** [comment]
This warrants a hotfix I'd say, I'll try to get it out within a day or two :)

**Comment by MuteTiefling** [comment]
yep. another issue with the bragging rights quests not being visible too. Fixing that now
