### ISSUE TITLE
Liquid compressor quest bug when update from 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by mllightitup** [EnigmaticaModpacks/Enigmatica6#5080]
### Modpack Version

1.4.0

### Describe your issue.

![image](https://user-images.githubusercontent.com/43480503/178795293-93eb78f8-e9a7-4273-a8b7-ce36ea0a5afc.png)
![image](https://user-images.githubusercontent.com/43480503/178795331-6c156096-4bf3-42cd-8220-edbefa081d67.png)

This happened when upgrading from version 1.3.0 to 1.4.0. 

### Have you modified the modpack?

Yes

### User Modifications

Only clientside mods like (rubidium, forgetmechunk, magnesium extras)

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Err, what exactly happened? 😅

**Comment by MuteTiefling** [comment]
Pretty sure I removed the buckets from this as a required task... I'm guessing they didn't have the buckets complete before the update and the quest didn't update properly.

**Comment by mllightitup** [comment]
> Sorry if I shouldn't be chiming in here, but it looks like the quest is 100% done, but not "complete".

Yes it is.  The quest writes that it is 100% complete, but it is not

**Comment by mllightitup** [comment]
The quest is considered "in progress" even though it is 100% complete
