### ISSUE TITLE
Gaia reactor is still not working in 1.4.1

### ISSUE THREAD

**Issue by Ieldra2** [EnigmaticaModpacks/Enigmatica6#5084]
### Modpack Version

1.4.1

### Describe your issue.

The sympton is that the reactor switches between "Found structure" and "0%" about twice a second, uses up resources, but does not produce anything. 
The reason appears to be that the reactor now resets if supply of any resource is interrupted for even a fraction of a second. This wasn't the case in 1.3, and it means that it will not work at all unless you can supply every resource at maximum speed. Which is, if at all possible in the case of air, extraordinarily more difficult than it used to be. 
I confirmed that the reactor works if you supply it at maximum speed by using Creative power and air sources, and memory essence >16B/t. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
This wasn't an intentional change, but it doesn't mean it doesn't work. It just means you need to step up your air production game. 

So far, mine has been ok despite having it behave like yours initially after the change. I just needed to add another compressor.

If it proves to be too much, however, we can always reduce the amount of air required per tick.

**Comment by Ieldra2** [comment]
Let's just say that IMO a change that multiplies the minimum power requirements by two or more (you could easily run the gaia reactor with a single nitro reactor in 1.3, now you need 2MFE/t) for an already power-hungry end-game machine shouldn't be slipped in by an accidental change. Also, if this change is global to Masterful Machinery, other production processes may also be affected, such as those of the advanced assembly table, and that requires - IIRC since I can't check atm - more air per operation depending on recipe.

**Comment by CaptainAlkohol** [comment]
Yeah I have to agree that this is (although unintentional) not a good change. I feel like just having those machines run on passive instead of pooling insane amounts of power/air/starlight/stuff or cranking your production up to 9000 is better. Plenty of other things that require tons of setup already :)

**Comment by MuteTiefling** [comment]
>  now you need 2MFE/t) for an already power-hungry end-game machine shouldn't be slipped in by an accidental change.

The recipe resetting if you fail to supply the required inputs at the specified rate was an accident, the power costs never were. This machine was meant to be a power sink from the start, and the 2m FE/t requirement was probably _low_ if anything.

> Also, if this change is global to Masterful Machinery, other production processes may also be affected,

The mod didn't change. Some recipes changed to standardize them. If anything else is acting funky, please feel free to report them separately. So far I've not noticed anything beyond the Gaia Reactor. The advanced assembly table saw no recipe changes whatsoever during this standardization.

> I feel like just having those machines run on passive instead of pooling insane amounts of power/air/starlight/stuff or cranking your production up to 9000 is better.

I would honestly disagree. As stated above, this one in particular (and from this point on I'm only discussing the Gaia Reactor here, see above) was meant to be a power sink. By that point in the game, you should absolutely have the infrastructure to run this. 

Prior to the update, mine was running fine on a single Advanced Liquid Compressor burning Ethylene. That same compressor was also running a Witch spawner to provide the Memory Essence. As a result of the change, I noticed the reactor was now able to run without halting. This meant the essence was being drained faster and the spawner was running non stop.

To correct this, I simply added another compressor and switched the spawner over to a slime spawner. Now the spawner doesn't need to run as constantly (slimes result in far more xp per spawned mob) and the additional pressure allows the reactor to run again without incident.

Mind you, my power is also coming from a Fission reactor running non stop. Certainly, if you prefer to run nitro reactors instead, you'll need more of them. But you need Fission running anyway to produce polonium for antimatter, so you may as well be spending that power on something.

Again, I'm willing to adjust this further, but I'd ask you to take a step back from this kneejerk reaction and think about it objectively with these points in mind. Check your setup, adjust as necessary, and if those adjustments prove to be too extreme, let us know and we can see about further adjustments.

**Comment by MuteTiefling** [comment]
Just for the sake of testing, I've just put a mana void under my pools for this, so it'll run constantly for a while. We'll see what happens here.

**Comment by Ieldra2** [comment]
I have now connected three flux compressors, 8 speed upgrades each, and two of them at the upper input ports. This appears to supply enough air overall, but I'm seeing odd jumps in the input ports, as if the ports didn't synchronize correctly, and if a port that the reactor happens to use at the moment has low pressure, the production stops after the current production run has ended, to resume when the situation has changed, for whatever random reason the reactor switches input ports. So I'd say there is still something wrong, but no resources are lost in those pauses and the net result is just slower production, so with regard to the air situation things are workable.

However, the reactor still resets if power supply is interrupted. Please note: I do not mind the power expenditure to complete a single operation, I mind that I have to supply it at maximum speed. Also yes, I can do it, it's not more than a moderate hassle to set up, but not having the option to run the reactor at slower speed strikes me as undesirable.

**Comment by MuteTiefling** [comment]
>  but I'm seeing odd jumps in the input ports,

This is a necessary evil, sadly. In order to make the machine require 10+bar to work, I could only force that by adjusting the max volume of the input. This, combined with the consumption rate will cause it to bounce around. If I could have a higher volume of air in there while still maintaining the 10+ bar requirement, you'd see a lot less jumping around.

Could you screenshot the output rate of your compressors and post them here? Just open the top right tab in the compressor gui and send the whole thing.

**Comment by MuteTiefling** [comment]
Just to give you a better visual idea of my setup, this is it running. 

https://streamable.com/m1dxyo

You can see I'm just voiding all excess so it can run non stop for testing. Normally I let it back fill on mana and that's my 'off'. I then use the mana to charge rings and let this thing run whenever the pools permit it to. 

Power, as stated, is coming from a source that produces more than enough to run it full speed. You've got options here and I hear regularly that despite the steep power costs for a lot of things in the pack, they _still_ don't have enough stuff to spend it on. Generating 2m FE/t should not be considered extreme. 

As of this moment, this thing has been running for 6 hours straight without interruption. the pressure lines don't drop below 16 bar. So it's keeping up and doing so quite admirably.

**Comment by Ieldra2** [comment]
Here's my compressor stats. It's making considerably less air than yours, I don't know why the difference is so drastic - it says it's working at 80% efficiency - but I have three of them and together they make significantly more than 1200mB/t.

![GC2](https://user-images.githubusercontent.com/13123151/179300812-e685d87d-7eda-444a-907e-ecdae4bd17d4.jpg)

**Comment by Ieldra2** [comment]
So...the pause I observed was related to the mana voids not voiding fast enough, which hadn't occurred to me before I watched your video. Adding more mana voids made the reactor run without issue at full speed. Incidentally, this is also how you can slow the reactor down deliberately, by just using one or two mana voids instead of the four or so you need for full speed. 

So as far as I'm concerned, this issue is resolved. I haven't changed my opinion about mininum power requirements, but you're the one making the rules.
