### ISSUE TITLE
Blazing blood in powah magmatic generator

### ISSUE THREAD

**Issue by StevenDoesStuffs** [EnigmaticaModpacks/Enigmatica6#5088]
### Describe your suggestion

Currently, the magmatic dynamo (thermal series) takes blazing blood, but the magmatic generator (powah) doesn't. I think we should add a blazing blood recipe for the magmatic generator. 

### Why would you like this added/changed?

It'd make the magmatic generator a bit more useful and consistent.

**Comment by NielsPilgaard** [comment]
I don't think we can actually do this I'm afraid 😅 unless we can do it through their API with KubeJS. @Darkere what do you think?

**Comment by StevenDoesStuffs** [comment]
Apparently it's done through the configs. I'll make a PR for it soon.

**Comment by Darkere** [comment]
Yep appears to be a config option. https://github.com/owmii/Powah/blob/e9bf8bda0063cde604e6e1c3beb5eba6197e1b49/src/main/java/owmii/powah/config/generator/MagmatorConfig.java#L19

**Comment by NielsPilgaard** [comment]
We usually don't close issues until the code that fixes them is released :)
