### ISSUE TITLE
[Expert] Energy Discharger Upgrade path broken

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica6#5090]
### Modpack Version

1.3.0

### Describe your issue.

Recipe for upgrading Energy Discharger of any tier is just broken, it requires the same tier of Energy Discharger to craft "upgraded to that tier" Energy Discharger.
I already checked the code, found an issue isn't fixed on 1.4.1 and (hopefully) I will try to fix it, if I will be not successful then I will let you know in about 2/3 hours 😅 

![obraz](https://user-images.githubusercontent.com/60540476/179396358-9c61a898-c28d-4b42-9da1-65aa4255c26c.png)
![obraz](https://user-images.githubusercontent.com/60540476/179396359-baf3d1f0-87dc-4878-8181-1f10e6fdbf83.png)
![obraz](https://user-images.githubusercontent.com/60540476/179396365-672c0c28-22c4-470f-bc67-fcad63f4dcb0.png)
![obraz](https://user-images.githubusercontent.com/60540476/179396367-3fec4c25-8525-49f6-a508-fe7a133ece17.png)
![obraz](https://user-images.githubusercontent.com/60540476/179396373-f5bd90a2-c991-4ac8-9086-3d1231dcced0.png)
Every of those recipes require the same tier Energy Discharger. I'm guessing that it would need the same energy cell tier however as well what it doesn't 😅 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This one looks good to me in game. Thank it's all set
