### ISSUE TITLE
Scavenger can dupe Larvae

### ISSUE THREAD

**Issue by BooBeerb** [EnigmaticaModpacks/Enigmatica6#5095]
### Modpack Version

v1.4,1

### Describe your issue.

pretty explanatory i think. any bee that can be killed can be duped with the scavenger enchantment. i do not know if this is intentional or not, but i just thought i'd mention this!

### Have you modified the modpack?

Yes

### User Modifications

Rubidium and Rubidium Extras. I don't think these mess with scavenger but one never knows.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by BooBeerb** [comment]
pretty sure death events don't work. scavenger can dupe nether stars i believe.

**Comment by NielsPilgaard** [comment]
@Quezler do you know if you PR fixes this issue for realsies?

**Comment by Quezler** [comment]
it would be beyond weird if scavenger was somehow able to incercept item drops spawned by kubejs since it specifically checks for loot tables, and no i haven't tested it completely since i couldn't be bothered to get the command to enchant beyond max 👀
