### ISSUE TITLE
[Expert] Iesnium pickaxe melting recipe inconsistency.

### ISSUE THREAD

**Issue by enigmachinery** [EnigmaticaModpacks/Enigmatica6#5100]
### Describe your suggestion

In expert mode, an Iesnium pickaxe requires a block of Iesnium to craft.
![issue_iesnium_recipe1](https://user-images.githubusercontent.com/109678361/180011200-dbd633fb-fed5-4857-8bdb-1bcf1d9fc617.png)
![request_Iesnium](https://user-images.githubusercontent.com/109678361/180011220-83949aba-4707-4a84-9256-91c8294fd180.png)
However, melting an Iesnium pickaxe only returns 3 ingots worth of molten Iesnium.
![2022-07-20_09 10 19](https://user-images.githubusercontent.com/109678361/180011469-371715cf-b974-4264-a1ee-dec8eec99f10.png)
Suggestion: Change melting recipe to be consistent with crafting recipe.

### Why would you like this added/changed?

Makes more sense, to be honest with ya'.

**Comment by MuteTiefling** [comment]
Fair point :D We'll get that fixed up

**Comment by enigmachinery** [comment]
Thanks!
