### ISSUE TITLE
Vacuum trap blacklist not working/set correctly

### ISSUE THREAD

**Issue by Vashal0** [EnigmaticaModpacks/Enigmatica6#5101]
### Modpack Version

1.4.1

### Describe your issue.

Previously I successfully added an abbee into the vacuum trap, but couldn't add a Boobee, and Motoko said all bees should be blacklisted. 1.3.0

Then recently, also 1.3.0, I tried to make a silk moth spawner outside, and the vacuum trap sucked in all the fireflies which Motoko said should be blacklisted. 

Then out of curiosity since it came up twice, I tried with a mob that should definitely be blacklisted, the unbound afrit, and it worked. 1.4.1

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Vashal#1806

**Comment by MuteTiefling** [comment]
Seems they converted it fully over to an entity tag system. Quite nice, just missed the memo :D
