### ISSUE TITLE
Blaze rod duplication?

### ISSUE THREAD

**Issue by BooBeerb** [EnigmaticaModpacks/Enigmatica6#5111]
### Modpack Version

v1.4,1

### Describe your issue.

Blaze rod -> 9 powder with marids
4 powder -> one crystal
one rod makes two crystals plus an extra powder basically

then convert the crystals into blocks and cool them into blaze meshes and repeat

### Have you modified the modpack?

Yes

### User Modifications

Rubidium and rubidium extras

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Beerb#6034

**Comment by MuteTiefling** [comment]
Quite an odd loop there :D Probably not breaking much, but it's plugged up now. Thanks for the report!
