### ISSUE TITLE
Dragonstone should produce more RF than a regular diamond in a Lapidary Dynamo.

### ISSUE THREAD

**Issue by enigmachinery** [EnigmaticaModpacks/Enigmatica6#5112]
### Describe your suggestion

Currently, a diamond produces 20,000,000 RF in a Lapidary Dynamo.
![suggestion_diamondlapidary](https://user-images.githubusercontent.com/109678361/180661379-d1ec5ad2-755f-47f4-8eaa-17c876470499.png)
Dragonstone, which takes a lot of effort to obtain in both Normal mode and _especially_ Expert mode (Diamond -> Infused Diamond -> Mana Diamond -> Dragonstone), produces the same amount.
![suggestion_dragonstonelapidary](https://user-images.githubusercontent.com/109678361/180661484-3abbb9a7-70df-4c1e-98c0-7a17908a3513.png)
Suggestion: **Buff the amount RF you get from Dragonstone (probably also applies to other diamonds too, but I haven't checked.)**

### Why would you like this added/changed?

Why anyone would use such a valuable resource like Dragonstone as dynamo fuel is beyond you and I, **but I think it'd really help out that one guy who has, like, 40 lapidary dynamos powering their entire factory.**

**Comment by MuteTiefling** [comment]
Perhaps more importantly... Why are you still running on dynamos if you can make dragonstone?

**Comment by enigmachinery** [comment]
Masochism, I guess?

**Comment by Gcat101** [comment]
Wait it makes how much?

**Comment by enigmachinery** [comment]
20,000,000. A great amount of RF, don't get me wrong, but a regular diamond you can just mine up produces the same.
