### ISSUE TITLE
Failed to verify username issue only with this modpack

### ISSUE THREAD

**Issue by Kryvern** [EnigmaticaModpacks/Enigmatica6#5113]
### Modpack Version

1.4.1

### Describe your issue.

trying to play on the e6e modpack on my friends server, have also tried other servers and when joining I always get the **failed to verify username** error, I've done every solution I could find via google, I've asked in the discord (ignored?) hell I even changed my username and nothing I've tried is working and the issue seems isolated to me for what ever reason and I don't know what else to try I've played many other modpacks and can still log in and play them just fine, so something is going on with either this modpack  and my end or something idk

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Please understand that support is a community driven effort and it may take some time for someone knowledgeable to have the time to help you.

Looks like your request was only opened this morning. It's a weekend and the summer. Please have some patience and I'm sure someone will be able to offer some suggestions.
