### ISSUE TITLE
Stellar Neutron Activator + Industrial Deuterium Plant

### ISSUE THREAD

**Issue by BooBeerb** [EnigmaticaModpacks/Enigmatica6#5116]
### Describe your suggestion

It seems as though there exists absolutely nothing in the E6 pack that explains even remotely what these do. Just stating what they need to function and their uses would be nice.

### Why would you like this added/changed?

Because what it do???

**Comment by NielsPilgaard** [comment]
They were made for expert, and then also added to normal because they're cool 😄 I guess we need some info in non-expert quests, or tooltips or something.
