### ISSUE TITLE
Factory Hopper Item duping

### ISSUE THREAD

**Issue by pmytilin1984** [EnigmaticaModpacks/Enigmatica6#5118]
### Modpack Version

E6E 1.4.1

### Describe your issue.

Factory Hopper Item duping
when trying to load a steam tug with charcoal
reported issue to mod dev
including replication of the issue
[2022-07-29 20-01-45.webm](https://user-images.githubusercontent.com/16614257/181811650-d76234e5-276d-4e8e-b5c7-2cff66bdc719.webm)

### Have you modified the modpack?

Yes

### User Modifications

added optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

201472686096908288

**Comment by stfwi** [comment]
Hi guys, sorted out, `engineersdecor-1.16.5-forge-1.1.19` is pushed to Curse. Can you include this version in the next E6 release?
Cheers, wile

**Comment by NielsPilgaard** [comment]
Will do, thanks for the fix ❤️
