### ISSUE TITLE
Advanced assembler batch recipe for PNC advanced pressure tubes

### ISSUE THREAD

**Issue by cypren** [EnigmaticaModpacks/Enigmatica6#5120]
### Describe your suggestion

Please consider adding an advanced assembler batch recipe for advanced pressure tubes. 

### Why would you like this added/changed?

You need thousands of them to build the Mekanism boilers/turbines, and they stand out for being one of the few assembler items needed in high quantity that doesn't already have a batch version.

**Comment by SoulfieUwU** [comment]
![2022-07-29_19 01 34](https://user-images.githubusercontent.com/104746680/181856635-a0c8540f-6d44-4d69-8703-b5242e4abfb4.png)
I think it'd be reasonable to add the Machine Frame from RFToolsBase as well as it's used quite often as well.
