### ISSUE TITLE
The Tree of Life occasionally breaks

### ISSUE THREAD

**Issue by Ieldra2** [EnigmaticaModpacks/Enigmatica6#5124]
### Modpack Version

1.4.1

### Describe your issue.

The Tree of Life occasionally gives me the message "failed to construct the structure" after having been functional for a while, with no action by me which could have reasonably had that result. Rebuilding it appears to replace some blocks on the ground near the base of the tree, possibly decoration. I suspect snowfall destroyed some of the decoration. Also, the pattern of replaced blocks appears to mirrors the dried kelp bocks - this is only an impression though. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Ieldra@9172

**Comment by MuteTiefling** [comment]
A lot of that decoration isn't even checked by the machine, it's just part of the schematics to build it.

Will have to take a closer look to see if any more deco blocks could be reasonably removed though.

**Comment by Ieldra2** [comment]
I'll post a screenshot when it happens again. Might be a day or two.

**Comment by Ieldra2** [comment]
Here it is. Note the highlighted blocks as the blocks were placed. This came as a wave from the back of this image to the front.
![grafik](https://user-images.githubusercontent.com/13123151/182044208-b6e09ede-93fb-48c7-a40c-60f3e176452b.png)

**Comment by MuteTiefling** [comment]
Weird. I swear I removed all that grass from the actual structure. It's just left in the copy paste gadget pattern for decoration...

**Comment by MuteTiefling** [comment]
Ok, went back into my test world where I have 2 of these set up. One is the 'building gadget' version, and the other is the 'true' version which only contains the blocks required for the MM to form.

The 'true' version contains no grass or mushrooms. the only 'delicate' blocks that still remain as integral to the structure are leaves, the hanging wisteria vines, and path blocks.  

Is it possible your tree is getting struck by lightning and leaves are burning? If you `/gamerule doFireTick false` does it still happen?

Just the same, I think I may remove the path blocks and wisteria from the required blocks as well. If it does turn out to be fire... I'll look into possibly making 'fake' leaves that don't burn. that'll invalidate the structure for anyone who has alread built it, however.

**Comment by Ieldra2** [comment]
No structure break has occurred for about 12-16 hours after changing the gamerule. It think the problem might indeed be that the tree was struck by lightning. I don't recall any thunderstorm in this period, but there was never a period this long without the tree breaking before. And there was plenty of snow so it's very likely not that.

**Comment by MuteTiefling** [comment]
With fire tick off, you should actually see flames up there on the leaves. They'll get started by lightning still, but never go out or burn through the block. You see any up there with a quick fly through?

**Comment by MuteTiefling** [comment]
actually, the snow might be putting it out... still worth a check but I'm thinking it was probably fire. Will have a sit down here and see what fireproof leaves would look like

**Comment by Ieldra2** [comment]
I haven't seen anything, but I suppose the fires wouldn't last beyond the current session, right? I'd have to check around the end of a long playing session.

**Comment by MuteTiefling** [comment]
The fires could persist forever with fire tick off. But I suspect they'd get snowed on and that would put them out.

It's all good, I'm pretty convinced it was lightning at this point, so the tree has been made fireproof. At least on the outside.
