### ISSUE TITLE
IF Laser Drill in overworld getting End ores

### ISSUE THREAD

**Issue by AndyGHG** [EnigmaticaModpacks/Enigmatica6#5127]
### Modpack Version

1.4.1 Normal

### Describe your issue.

Since upgrading to 1.4.1, my Industrial Foregoing Laser Drill (setup in my base in a Blossom Valley biome in the overworld) has begun getting tons of ores normally only available in the End:  Amber ore, Ender ore, and Thallasium ore... enough that it overflowed a diamond chest (used as a buffer) in a matter of a few hours.

If this is intended behavior, please accept my apologies!  If intended, I can update my filters, no problem.  ;-)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

AndrewIndy#0353

**Comment by MuteTiefling** [comment]
You're sure the biome it's in didn't shift? I don't recall making any changes to that system recently, but it's restricted by biome, not dimension.

Maybe just double check the biome f3

**Comment by AndyGHG** [comment]
Standing on top of the laser drill and hitting F3....
![biome](https://user-images.githubusercontent.com/91009871/182037960-b7c62571-0f31-46c7-ae87-65d97519aae4.png)

**Comment by MuteTiefling** [comment]
ooooh, right, these were added recently and I totally goofed the blacklist/whitelist.

**Comment by AndyGHG** [comment]
hehe... not a problem, and thank you!  In the mean time, I'll just filter/void them from my processing setup.
