### ISSUE TITLE
[Expert] Constellation Boxes do not require any specific constellations

### ISSUE THREAD

**Issue by IcewaveGaming** [EnigmaticaModpacks/Enigmatica6#5128]
### Modpack Version

1.4.1

### Describe your issue.

The Bright and Dim constellation boxes needed to craft the Automated Iridescent Altar's controller do not require any specific attuned celestial crystals, despite the recipe specifying certain ones. I was able to make the dim box without Horologium by using spare crystals attuned to Aevitas, Armara, and Discidia, and putting five dim-attuned crystals into the crafting grid will return the bright box if you don't add another three.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Icewave#4601

**Comment by MuteTiefling** [comment]
Thanks! Got that fixed up for next release
