### ISSUE TITLE
Buff Arc Furnace by Adding Recipes from Lower Tier Alloying Machines

### ISSUE THREAD

**Issue by Vlamonster** [EnigmaticaModpacks/Enigmatica6#5134]
### Describe your suggestion

Add recipes that lower tiers of alloying machines, such as the alloy kiln and induction smelter have to the arc furnace.

### Why would you like this added/changed?

It is a bit awkward that some of the recipes from the kiln and induction smelter can be made in the arc furnace, but not all. And some recipes are even worse when done though the arc furnace such as crystal glass (1 ghost glass to 1 crystal glass, instead of 1 to 2). For such a comparatively difficult unlock it currently feels underwhelming as the lower tiers can do more than it.

**Comment by MuteTiefling** [comment]
The intent of the arc furnace recipes for ghost glass was to cut the Strange Sand out of the equation so you wouldn't need to set up a farm for it. 

Are there other specific examples of recipes missing from it?

**Comment by Vlamonster** [comment]
Yeah, here a couple I encountered at least.

- **Andesite Alloy**
- **Enderium Ingot**
- Cured Rubber
- **Netherite Ingot**
- Seared Brick
- **Lumium Ingot**
- **Signalum Ingot**
- Hardened Glass and its upgrades

I think the bold ones make the most sense to be craftable in the arc furnace, the other ones less so.
