### ISSUE TITLE
Melting grout through mekanism

### ISSUE THREAD

**Issue by mllightitup** [EnigmaticaModpacks/Enigmatica6#5142]
### Describe your suggestion

Suggestion: add a recipe to [energized smelter] for melting grout into seared bricks. 

### Why would you like this added/changed?

In order to avoid this recipe
![image](https://user-images.githubusercontent.com/43480503/182617353-936329ae-66ab-4461-8cff-5e9f76734945.png)

**Comment by MuteTiefling** [comment]
The Energized Smelter is just a furnace. To add it to that, we'd be adding it to every furnace, which it was specifically removed from for Expert's progression

I'm not sure I understand what this is attempting to fix.

**Comment by mllightitup** [comment]
> The Energized Smelter is just a furnace. To add it to that, we'd be adding it to every furnace, which it was specifically removed from for Expert's progression
> 
> I'm not sure I understand what this is attempting to fix.

If this recipe melts the block into a brick, what is the point of doing it only in induction smelter?
I thought that induction smelter is needed primarily to fuse resources among themselves or get a few things in the output, not for recipes 1 to 1

**Comment by mllightitup** [comment]
Or does that mean that you can't add a separate recipe just for the energized smelter because it inherits the recipes of the regular furnace?

**Comment by MuteTiefling** [comment]
Exactly that. It's all or nothing.

**Comment by mllightitup** [comment]
meh

**Comment by MuteTiefling** [comment]
Again, if I understood why you were asking this, I might be able to find a solution.

**Comment by mllightitup** [comment]
I'm trying to find a way to do it optimally and quickly or parallelize the process

**Comment by mllightitup** [comment]
I can just make a 10 induction smelters purely for this recipe but it's weird

**Comment by MuteTiefling** [comment]
I mean, if you're just looking to get a lot of bricks fast, you could run the other recipe. It cost half the energy (so is twice as fast) and the recipe would be compatible with any induction smelters you already have running in parallel for 3 input crafts:

![image](https://user-images.githubusercontent.com/9543430/182627251-afb04ddd-5152-43a0-bdf2-7dcd5e2921a2.png)

We can look into maybe adding a faster recipe for a late game machine though. Will take a look later.

**Comment by Kanzaji** [comment]
I would think to maybe add recipe with grout to Enrichment Chamber :D? This is only available when you have mekanism so a bit late

**Comment by MuteTiefling** [comment]
Yeah, was thinking there might work nicely. Could even give it a bonus
