### ISSUE TITLE
[EXPERT] Plastic Sheets - You Can Touch, You Can Play

### ISSUE THREAD

**Issue by Zuiron** [EnigmaticaModpacks/Enigmatica6#5144]
### Modpack Version

1.4.1

### Describe your issue.

Quest: Plastic Sheets - You Can Touch, You Can Play
Problem: I have 4 or more plastic sheet in my inventory, its not detected and is not complete able.

i used in-world solidifying to make them. perhaps relevant.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Zuiron#5307

**Comment by Darkere** [comment]
Got a screenshot of the quest?

**Comment by Zuiron** [comment]
![Screenshot 2022-08-04 124636](https://user-images.githubusercontent.com/5185131/182828891-98c649c8-d367-4f4f-bc70-985d3ade41f9.png)

**Comment by Zuiron** [comment]
![Screenshot 2022-08-04 124835](https://user-images.githubusercontent.com/5185131/182829203-2b1cc7b8-7634-48ae-b5e9-c1f91dbfd035.png)

and here they are in my inventory.

**Comment by CaptainAlkohol** [comment]
you just dont have the requirements to complete the quest yet. click on the quest, there should be an arrow with "dependencies", click on it and you will see what quests you are missing

**Comment by Zuiron** [comment]
![Screenshot 2022-08-04 125633](https://user-images.githubusercontent.com/5185131/182830687-b690a9fe-4485-4e51-ada1-8efa58a8748a.png)

says i need 4x plastic sheet, i have that ?
