### ISSUE TITLE
Laser Drill No Longer Makes Liquid Starlight In Normal Mode

### ISSUE THREAD

**Issue by hterez** [EnigmaticaModpacks/Enigmatica6#5145]
### Modpack Version

1.4.1

### Describe your issue.

The liquid laser drill I had set up to produce liquid starlight is no longer producing liquid starlight, and it is not listed in JEI as a liquid that the Fluid Laser Base can produce at all.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report! Silly typo on my part.
