### ISSUE TITLE
Stimpacks are uncraftable if melded potions have their effects listed in the "wrong" order

### ISSUE THREAD

**Issue by Ieldra2** [EnigmaticaModpacks/Enigmatica6#5155]
### Modpack Version

1.4.1

### Describe your issue.

The melded potions needed for the stimpacks have two effects, listed in the recipe in a specific order. Potions with the same effects, only listed in reverse order, count as different potions and do not work for making the stimpacks. It is not possible to control the order of the effect list - the order may shift in the same setup from one playing session to the next one - which means that the stimpacks may be craftable or not because of factors not under the control of the player.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Ieldra@9172

**Comment by theboo** [comment]
fixed in #5133
