### ISSUE TITLE
Occultism book quests not work properly

### ISSUE THREAD

**Issue by GorrionCojonero** [EnigmaticaModpacks/Enigmatica6#5157]
### Modpack Version

1.4.1

### Describe your issue.

Hi!

There are certain rituals of the occultism mod that do not work well, when summoning the djini in particular, they do not give you the quest as completed since the book of said djini does not appear. The rituals that I have tested so far are summon djini crusher, chop chop chop, djini to make day it nighttime, djini to clear the skies.
I have performed these rituals and only the djini appears, they do not give you the book nor does the complete quest appear.

### Have you modified the modpack?

Yes

### User Modifications

OptiFine_1.16.5_HD_U_G8

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Just as a side note as well, these quests don't expect you to get an item from the ritual. You should get credit for the book by simply holding any crafted unbound djinni book. The other part is triggered by a hidden advancement.  Having just tested both the clear skies and dusk rituals, I can confirm that the quests are triggering from them without issue.

**Comment by theboo** [comment]
The books themselves should be removed from all the summon spirit quests now... Maybe I missed one or two... only reason the books were there is because ftbq used to auto claim rewards for advancement based quests upon completion so I had to add item tasks, but that has been long since fixed

**Comment by GorrionCojonero** [comment]
Here I leave the screenshot, I hope it helps

![2022-08-08_19 24 23](https://user-images.githubusercontent.com/87278004/183480908-330be05c-8e69-493d-9e01-872f850a7914.png)
![2022-08-08_19 24 42](https://user-images.githubusercontent.com/87278004/183480922-1356525c-00ae-4f06-bd7c-00b759424561.png)
![2022-08-08_19 24 50](https://user-images.githubusercontent.com/87278004/183480944-5228223e-4cb7-40f1-9e8c-666f79a1e42b.png)
![2022-08-08_19 24 58](https://user-images.githubusercontent.com/87278004/183480958-c26d8b15-98a7-4c0e-bd07-13fbd27ba2fd.png)

**Comment by theboo** [comment]
Are you doing these quests manually? Or through some sort of automation?

**Comment by GorrionCojonero** [comment]
> Are you doing these quests manually? Or through some sort of automation?

All manually

**Comment by MuteTiefling** [comment]
Would seem your advancements are not triggering then, as all of these are based on getting hidden advancements when the ritual completes. Only things I can suggest are 
1. Restart your game and try again
2. Remove optifine and try again
3. Reinstall the pack and try again

Boo, there are two quests left that still expect the book, i'll clear those out in the PR I'm working on.

**Comment by Darkere** [comment]
Since these are advancements is there any chance they are missing prerequisites there?

**Comment by GorrionCojonero** [comment]
> Would seem your advancements are not triggering then, as all of these are based on getting hidden advancements when the ritual completes. Only things I can suggest are
> 
> 1. Restart your game and try again
> 2. Remove optifine and try again
> 3. Reinstall the pack and try again
> 
> Boo, there are two quests left that still expect the book, i'll clear those out in the PR I'm working on.

Thanks for all the attention, I will try to do what you have recommended and I will inform you of how it turns out.

**Comment by theboo** [comment]
> Since these are advancements is there any chance they are missing prerequisites there?

There shouldn't be any prereqs for the hidden ones afaik... Especially considering the transporter and sapling trader cleared just fine... I might get some time tonight to do some testing,l... Maybe something happened here in the July 6 update fixing something for us...

https://github.com/klikli-dev/occultism/issues/735

**Comment by GorrionCojonero** [comment]
Following your advice, I have removed optifine and reinstalled the pack. I've tested the rituals and I'm still having problems with the chop chop chop ritual quest, and summon djinni crusher.

**Comment by MuteTiefling** [comment]
Just those two? Will test them out soon then.

**Comment by MuteTiefling** [comment]
Yep, just ran through both of those in two fresh worlds and I'm unable to reproduce this. I'm getting the advancements and as soon as that quest becomes available, it sees it and gives credit for the quest. :-\
