### ISSUE TITLE
Additional Banners

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#5160]
### URL

https://www.curseforge.com/minecraft/mc-mods/additional-banners

### Why would you like the mod added?

I am making banners for every single building in my modern-city base and I would really appreciate if your modpack had more banner patterns.

**Comment by Gcat101** [comment]
Yeah I'm asking for selfish reasons, but a small QoL mod never hurt anybody

**Comment by NielsPilgaard** [comment]
I don't think this would see enough use to warrant being included,  sorry but no.
