### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by Caerglad** [EnigmaticaModpacks/Enigmatica6#5164]
### Modpack Version

1.4.1

### Describe your issue.

Dropping vines into Petal Apothecary from Botania as 2nd item causes it to drop 1st item on the ground while keeping it inside apothecary.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate #4653

**Comment by Kanzaji** [comment]
Wait @MuteTiefling that issue you mentioned is mine spot crash :sweat_smile:

**Comment by MuteTiefling** [comment]
Oops, lol.

**Comment by MuteTiefling** [comment]
Dupe of #4652
