### ISSUE TITLE
Bountiful Bounties give really (probably unintended) overpowered rewards for cheap prices.

### ISSUE THREAD

**Issue by Fredi355** [EnigmaticaModpacks/Enigmatica6#5165]
### Describe your suggestion

Tone down the rewards from bounties as at the moment you can get stuff like occultism dim stabilizers, botania functional flowers, mekanism alloys etc. If you have the right decree it becomes really easy to farm them aswell.
![bounties](https://user-images.githubusercontent.com/40824740/184536437-52952481-d5ff-477f-930f-4b2ebde2e616.png)
![bounties1](https://user-images.githubusercontent.com/40824740/184536439-c139adda-1a49-4f93-9d88-f137960a944f.png)
![bounties2](https://user-images.githubusercontent.com/40824740/184536440-2647f296-e3db-442a-b3fa-c53b43506588.png)
![bounties3](https://user-images.githubusercontent.com/40824740/184536442-240a1ddf-1ec5-40d3-8d5d-493e37c97750.png)

### Why would you like this added/changed?

I think this lets you skip a lot of progression for doing nothing except maybe killing a couple mobs or giving the bounty board a shield etc.

**Comment by NielsPilgaard** [comment]
Thanks for the report.

I'm fairly certain this isn't intended - It's giving epic rewards from common bounties. 
Does this look like a bug to you as well @Discomanco? :)

**Comment by Discomanco** [comment]
Indeed it would be. Looks like I didn't go properly through some of the dungeon rewards

**Comment by Jodge65** [comment]
I think you have the same problem with Machinist reward: Atomic alloy is given for less than a stack of redstone and/or coal

**Comment by GoldMadoka** [comment]
The reward pools that are overtuned mostly seem to be Dungeon Dweller, Druid, and Machinist with Dungeon Dweller being far and away the most disproportionate between bounty rarity/objective/reward.

**Comment by Discomanco** [comment]
So, the main issue here is that Bountiful has 2 systems within its quests. Weight (probability) and Worth (can be used as Rarity) - which is used for both objectives and rewards.  
System should be pretty simple, an objective is chosen from the given weight which has an assigned Worth. The rewards then matches that worth through the weights, and that should balance out. Problem is that the Worths system doesn't work, so rewards can be all over the place, but we decided to keep it as-is anyways.

**Comment by Al1sa** [comment]
Wow, I was always getting nothing but crap from these bounty boards
