### ISSUE TITLE
Nether Quartz Duplication Using Magma Crucible

### ISSUE THREAD

**Issue by Flounder-M** [EnigmaticaModpacks/Enigmatica6#5173]
### Modpack Version

1.3.0

### Describe your issue.

Magma Crucible yields 1,296 mb of molten quartz from 1 quartz block. The TiC smeltery yields the correct 576 mb. I beleive the recipe anticipates the block requiring 9 quartz. This molten quartz can be sent to a casting table for a gain of 5 quartz.

Confirmed in discord with people running current version that this exists there.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Flounder#4791

**Comment by MuteTiefling** [comment]
Ah thanks, I see where that went wrong. Will get it fixed up soon
