### ISSUE TITLE
Add Starmetal to Mekanism 5x Ore Processing

### ISSUE THREAD

**Issue by Peri-42** [EnigmaticaModpacks/Enigmatica6#5178]
### Describe your suggestion

(Playing E6E)

Pretty much what it says on the tin. You can already get 5x Stardust by using the Industrial Foregoing ore meat processing, so it doesn't really break any balance, It just makes things more consistent.

### Why would you like this added/changed?

It would add consistency between the two options for ore quintupling.

**Comment by MuteTiefling** [comment]
Starmetal has always been a bit of an odd duck by design since the ingot itself is largely useless. It's the dust that matters and there are other ways to multiply that.

**Comment by Peri-42** [comment]
Oh, I didn't mean the ingots themselves, just processing the ore into stardust (sorry, should've specified that, I forgot they had the same name for a moment). You can get 5 stardust per ore from the IF processing but not through Mekanism, and the difference seemed weird. 

Actually looking closer it seems like you can't 5x any non-metal ores (diamonds, coal, etc) with Mekanism, I'm not sure if that was an oversight or a purposeful decision for balance reasons.

Ultimately if you just don't want to mess with it, that's valid too lmao. I was just asking to see if that consistency could be added, or if I should keep my IF processing setup around instead of replacing it with Mekanism.

**Comment by Kanzaji** [comment]
Most of non-ingot materials (like you said coal for example) aren't possible to process in 5x mek ore processing on default. Most of those are processed in Enrichment Chamber.

And tbh, lack of consistency in this case is good, as it makes a reason to setup both ore processing setups, and not just focus on one :D
