### ISSUE TITLE
PNC Vacuum Trap range is much smaller than displayed

### ISSUE THREAD

**Issue by TalasAmaruil** [EnigmaticaModpacks/Enigmatica6#5180]
### Modpack Version

1.4.1

### Describe your issue.

When previewing the range of the PNC Vacuum Trap, you are shown the range being 2 blocks, or further if using Range Upgrades.

In reality, the mob has to be extremely close to the trap, it seems to be within 1 block. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Talas#2706

**Comment by MuteTiefling** [comment]
It will pull anything in that range, but yes to trap it it must be pulled all the way over to the trap itself.

It also has a hard time 'fighting' things that actively move away, especially flying mobs. Just gotta get creative with how you work with it. 

What were you trying to trap, exactly?

**Comment by TalasAmaruil** [comment]
I was trapping Endermen, and they were standing as they were spawned without AI. https://media.discordapp.net/attachments/947932229143760957/1009722672239878245/unknown.png?width=740&height=640

**Comment by MuteTiefling** [comment]
Yeah, no ai is the issue there, I'm pretty certain. The trap overrides their pathfinding and gives them a point to walk to. Without ai, they just won't go. You'll either need to switch spawners, remove no ai, or bring them over with conveyor belts.

Highly recommend doing this in another dimension too to avoid having millions of loose endermen in your base. Or at least using a vinculotus to prevent teleportation.
