### ISSUE TITLE
Netherite Crafter lost all its contents

### ISSUE THREAD

**Issue by TalasAmaruil** [EnigmaticaModpacks/Enigmatica6#5184]
### Modpack Version

E6E 1.4.1

### Describe your issue.

I have two Netherite crafters that are missing all their patterns and upgrades upon logging back in. It's on a server, and there was a restart while I was logged off. The crafters are on a chunk border, and that's all I've got for information. It's the top and bottom ones in this screenshot. https://i.imgur.com/OnclYXX.png

I've heard it's a bug with Extra Storage and that it's been "fixed" so I'm throwing another bug report in to notify the devs that it's indeed still an issue.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Talas#2706

**Comment by TalasAmaruil** [comment]
Another issue that happened, maybe simultaneously, was that the third crafter which isn't missing the patterns and upgrades had the four speed upgrades stacked together in the top upgrade slot.

**Comment by Darkere** [comment]
#4820
