### ISSUE TITLE
Nerf the PN:CR Pressure Mechanic

### ISSUE THREAD

**Issue by Knightener** [EnigmaticaModpacks/Enigmatica6#5194]
### Describe your suggestion

Considering you can exchange a single Environmental Mud Ball to an Emerald via the Ceramist using nothing but the Artifacts Villager Hat;
![image](https://user-images.githubusercontent.com/62793679/188065277-8276dd4a-a082-4da2-b32c-75a5e51027e7.png)

-some of these trades feel a bit overpowered.
![image](https://user-images.githubusercontent.com/62793679/188065734-bf2d2226-3d10-4662-938c-e08545200c59.png)
![image](https://user-images.githubusercontent.com/62793679/188065955-569dc0f9-ade6-40a6-a505-284fe9f80d5a.png)

None of these villagers were zombified then cured, I am using nothing but the Villager Hat with all of these.

This also allows you to skip the entire PCB crafting process with nothing but a few emeralds.

### Why would you like this added/changed?

The ability to skip the entire PCB chain, (and the ability to get some of these items for a few emeralds, which can easily be obtained by just trading Mud Balls at the ceramist) feels way too overpowered, considering how much effort some of these items take to create in the early-mid game.

**Comment by MuteTiefling** [comment]
While it's true this let's you skip some difficult crafts, it's also a manual process. For the most part, anyway. Some people have used some clever game mechanics to automate villagers, but these are rather more involved and creative in their design than traditional 'place a block and feed it emeralds' villager traders.

I'm personally fine with it. You either automate it the intended way, or you automate it the clever way. But in the end, you'll have automated it *either* way as manual trading for the quantities you'll need to finish the pack is just not viable.
