### ISSUE TITLE
RS Large Patterns should probably be removed

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica6#5195]
### Describe your suggestion

Remove RS Large Patterns

### Why would you like this added/changed?

The functionality has been baked into RS for a while now. Don't think we need to keep this mod.

**Comment by NielsPilgaard** [comment]
This might cause issues in existing worlds though, no?

**Comment by MuteTiefling** [comment]
If it's in use yeah. They'd lose those patterns.

Might have to wait for a breaking change. Just wanted to put up a reminder as I honestly thought we removed it before Expert was released

**Comment by Quezler** [comment]
duplicate of #4747 :3

**Comment by MuteTiefling** [comment]
lol, fair
