### ISSUE TITLE
[Expert] Teleposer lightning recipe not crafting item

### ISSUE THREAD

**Issue by GoldMadoka** [EnigmaticaModpacks/Enigmatica6#5196]
### Modpack Version

1.5.1

### Describe your issue.

Dropping the required items, either manually or with any kind of machine, and then having lightning strike the same block does not create the Teleposer items that the recipe should create. Attempted the recipe in water as well to see if the Teleposers were burning up but the recipe failed there as well. #5103 has a screenshot of the recipe and I can confirm that is what is showing in JEI on my install.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Ah, yeah that was silly on my part. I'll get that fixed up soon.
