### ISSUE TITLE
[E6E] Ore Miner Djinni Quest is misleading

### ISSUE THREAD

**Issue by Jodge65** [EnigmaticaModpacks/Enigmatica6#5197]
### Modpack Version

1.4.1

### Describe your issue.

According to the quest book, the durability of the "Ore Miner Djinni" is boosted, but it will only display when the first point of durability will be lost: 
![image](https://user-images.githubusercontent.com/13049502/188274201-219fab88-1d3a-4181-a088-4456801f35d0.png)

But when i put it in the "Mineshaft", the durability was never updated:
![image](https://user-images.githubusercontent.com/13049502/188274268-3400caef-fc5b-4505-8177-e09106fa59ba.png)

The problem may be caused by the fact that those "Ore Miner Djinni" come from a "Bounty Board" reward that give me a 21 of them (note that the number of NBT was at 2 before being put in the mineshaft, and up to 4 after).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Jodge#6152

**Comment by MuteTiefling** [comment]
Quest is wrong. They're boosted in normal, reduced in expert. We'll get that fixed up.
