### ISSUE TITLE
Resourceful Bees :: centrifuge stops working

### ISSUE THREAD

**Issue by jottafan** [EnigmaticaModpacks/Enigmatica6#5198]
### Modpack Version

1.5.1

### Describe your issue.

Centrifuge stops working (tried mechanical and powered) after trying to use honeycomb blocks. 
First i bugged up my mechanical centrifuge by mistakingly putting a block in there. Had to restart the game for the block to work again. (No offhand and empty hand. Tried replacing the centrifuge) 
So i became very aware not to bug it out again. 

Later i got my powered centrifuge and did the same thing. Hoping it could process the blocks forced me to restart my game again

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SoulfieUwU** [comment]
![2022-09-03_12 57 20](https://user-images.githubusercontent.com/104746680/188280804-24e4683a-fb6a-4c9d-98f1-27cfa17959c6.png)
I'm quite certain that is intended bc honeycomb block processing are only for multiblock centrifuges as seen on the little symbol.

**Comment by jottafan** [comment]
Maybe my english is bad, but the whole point is That the centrifuges does not work normally after i try with A block.

timeline::
try a comb in centrifuge -> it spins and process the comb
Try a block -> it wont start
Then try a comb again -> wont start
Replace centrifuge and try a comb -> wont start.
Restart game and try a comb -> it WORKS!!

**Comment by Quezler** [comment]
sounds as though the fluid buffer was full, and replacing it voided any fluid that was in there, ensure you have bottles and/or a fluid output pipe, and hold shift when looking at the block next time this issue occurs so any tank bars show at the top.
