### ISSUE TITLE
MythicBotany

### ISSUE THREAD

**Issue by FrizzLandPop** [EnigmaticaModpacks/Enigmatica6#5200]
### Describe your suggestion

I really need to know if there is anyway I can re enable the wither aconite? or need to know why it was removed because i really want to use because all other mana generation methods take forever.

### Why would you like this added/changed?

Because its not in the pack but the mod is

**Comment by MuteTiefling** [comment]
Not really a suggestion. It was disabled because it's boring and other flowers can be equally fast with a bit of effort.
