### ISSUE TITLE
[E6E] Morphing Tool doesn't choose correct tool for IF devices

### ISSUE THREAD

**Issue by crookfingerjake** [EnigmaticaModpacks/Enigmatica6#5201]
### Modpack Version

1.5.1

### Describe your issue.

Morphing Tool doesn't select the correct tool (Crescent Wrench from Thermal) for Industrial Foregoing devices.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

crookfingerjake#1723

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
It doesn't seem like the Crescent Hammer works on IF machinery to me.
