### ISSUE TITLE
Make nebu automatable

### ISSUE THREAD

**Issue by Porcy** [EnigmaticaModpacks/Enigmatica6#5202]
### Describe your suggestion

Make nebu ore available in the dimensional mineshaft and/or the IF laser miners, or other mid/late game mining options you'd deem appropriate.

### Why would you like this added/changed?

Nebu is a base resource for mid to late game. Forcing even the most endgame players to go mine it manually makes no sense in an expert pack with so many mods and options to make it automatable somehow.

**Comment by Gcat101** [comment]
Use IE excavator or PNC:R Amadron

**Comment by Porcy** [comment]
Great idea :) Was looking for that! Now, if there was a way for noobs like me to find this information without resorting to open an issue, that would be awesome. JEI has a lots of limitations atm for things like this :/ 
Not sure what can be done though...

**Comment by MuteTiefling** [comment]
The IE manual shows you what can be mined with the excavator.

The quests heavily imply there's valuable things in the PNC survey chests and even gives you one for a reward.

**Comment by Porcy** [comment]
Yeah, RTFM essentially. Kinda rude imho. I'm starting to understand why it's called "**enigmatic**a".
There's so much to read to just begin to understand what you need to do in this pack that a little less "enigmatic" wording could help.

**Comment by MuteTiefling** [comment]
I'm sorry you feel that way, but as you pointed out, JEI has it's limitations. We've made efforts to point you in the direction you need to go without smashing you over the head with the answer in game. Just the same, an enormous amount of extra documentation has been added to shore up where mod manuals are lacking or non existant. This isn't one of those cases, however, and the IE manual is one of the better ones.

**Comment by Porcy** [comment]
You could squarely tell me : "Build an IE excavator to get nebu" and the challenge would stay intact. Just by the way this pack is built. That work is amazing by the way. Frustrating at times, but I see this pack as a piece of art.
