### ISSUE TITLE
Breaking an Armor Stand holding a Sophisticated Backpack deletes the backpack

### ISSUE THREAD

**Issue by emoran0403** [EnigmaticaModpacks/Enigmatica6#5204]
### Modpack Version

Enigmatica 6, 1.4.1

### Describe your issue.

My friend on our server deleted their backpack by accidently placing it onto an armor stand, and subsequently breaking the armor stand hoping it would drop.

Placing a backpack from the Sophisticated Backpacks mod onto an armor stand, and then breaking the armor stand, does not drop the backpack as an item.  Armor items are dropped normally, but the backpack (and its contents) are deleted.

These backpacks do not show up on the back of the armor stand as expected.  The only indication an armor stand has a backpack on it is a floating backpack icon above the stand.

Armor stands also will accept multiple backpacks, I tested it with 5 backpacks.  They did not appear on the back of the stand, but there were 5 little backpack icons hovering above the stand.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

BesideMyself#3075

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Oh, could you please update to 1.5.1 and see if the issue persists?

**Comment by emoran0403** [comment]
New creative world on 1.4.1.

Everything is the same as above in a single player world.

I did notice that the backpacks can be thrown 7 blocks away from the stand when it is broken.  Its possible the backpack landed behind something and my friend just could not find it.

**Comment by emoran0403** [comment]
Back on our 1.4.1. server:

8 backpacks on the stand only increase the icons on the top, adding the 9th causes it to display a backpack on the stand itself.

Right-clicking the armor stand removes the 9th backpack, removing the visual backpack.  But right-clicking the stone base of the armor stand removes backpacks while keeping the visual backpack displayed.

Adding 8 backpacks to the armor stand, then breaking it deletes all backpacks.

Adding 9 backpacks to the armor stand, then breaking it deletes all, except for the last backpack.  The 8 backpacks were empty, the 9th retained the item I had added to it.

I added 9 backpacks to the stand, then removed 3 from the base (which retains the visual backpack on the stand).  I then broke the stand, which only returned the first backpack.

**Comment by NielsPilgaard** [comment]
Erhm... @P3pp3rF1y help please 😄

**Comment by P3pp3rF1y** [comment]
Just tested with just SB and it looks like you have some mod in E6 that modifies armor stand behavior - with just SB the only thing I can do is put backpack on armor stand back which renders the same way as it would on player's back and any additional backpack I try to click on the armorstand just swaps that one for the one on the back. And breaking the armorstand properly drops backpack and also drops it right there and not like flying 7 blocks away.

**Comment by P3pp3rF1y** [comment]
I am guessing this would be the culprit? https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands

**Comment by NielsPilgaard** [comment]
> I made a new creative world on 1.5.1.
> 
> 8 backpacks may be placed on an armor stand, each adding to the icons hovering above. Only adding the 9th backpack makes the backpack display on the armor stand. Right clicking the stand while it has backpacks will remove them in the opposite order they were added.
> 
> Breaking the stand in creative mode does not drop the stand, nor any of the backpacks that were on it.
> 
> Breaking the stand in survival mode drops the stand and backpacks. with their contents intact.

Actually this behaviour seems correct to me. As long as everything drops it's good, no?

**Comment by NielsPilgaard** [comment]
> I am guessing this would be the culprit? https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands
> 
> > **[Just a moment...](https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands)**

Ah right ^^' sorry for the ping!

**Comment by P3pp3rF1y** [comment]
> Ah right ^^' sorry for the ping!
> 

Hey, no problem at all. Even I wasn't sure if I am handling backpack on armor stand properly as that's not really one of the tests that I would do.
