### ISSUE TITLE
Compressed Creativity

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#5206]
### URL

https://www.curseforge.com/minecraft/mc-mods/compressedcreativity

### Why would you like the mod added?

Compressed creativity helps bridge PNC:R and create together.

While rotation to pressure may be op, pressure to rotation is pretty cool to have.

Oh and there’s some other features that are pretty neat (like the mod by vazkii haha get it???!!).

**Comment by MuteTiefling** [comment]
I've been keeping my eyes on this. Still on the fence about it, but I'm willing to give it a look.

**Comment by NielsPilgaard** [comment]
Not for E6, perhaps future modpacks :)
