### ISSUE TITLE
E6E 1.51 Altar of Birthing (Nature's Aura), and Runic Altar (Botania) are uncraftable

### ISSUE THREAD

**Issue by BattleNachos** [EnigmaticaModpacks/Enigmatica6#5207]
### Modpack Version

1.51

### Describe your issue.

Altar of Birthing (Nature's Aura), and Runic Altar (Botania) are uncraftable.  I've tried crafting with a full aura cache and an empty one.  Neither works.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by BattleNachos** [comment]
Also, I have not completed the relevant quests under the "Magic - Adept" section.  If that matters.

**Comment by MuteTiefling** [comment]
You will need to fill the cache with an altar. Just charging in your inventory never gets it quite full

**Comment by BattleNachos** [comment]
Ah thanks.  I had no idea.
