### ISSUE TITLE
Ender Bee Honeycomb cannot be processed by centrifuges without putting the bottles in first

### ISSUE THREAD

**Issue by changhe3** [EnigmaticaModpacks/Enigmatica6#5208]
### Modpack Version

1.4.1

### Describe your issue.

![Screenshot](https://user-images.githubusercontent.com/14080480/189540615-424fe245-2cd2-4759-bcdf-e55cc02781bd.png)

As you can see, the ender bee honeycomb simply doesn't get processed in (elite) centrifuge, but other honeycombs work normally. Using bottles doesn't fix it either.

### Have you modified the modpack?

Yes

### User Modifications

Rubidium, Squatgrow, Mob Grinding Utils

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report. Did you try taking the Ender Hoenycombs out before putting bottles in, and then placing it back?

**Comment by changhe3** [comment]
I tried and that worked. Turns out it's fine as long as I put in the bottle first... Still it doesn't work if you put in the honeycomb first.

**Comment by NielsPilgaard** [comment]
I'm afraid that's just how it works ._. slightly awkward.
