### ISSUE TITLE
Centrifugal separator Honey Bottle liquid output has extremely limited uses.

### ISSUE THREAD

**Issue by Bumblebytrox** [EnigmaticaModpacks/Enigmatica6#5211]
### Modpack Version

1.5.1

### Describe your issue.

![honey](https://user-images.githubusercontent.com/86664756/189910938-3b5c42ed-436e-4a69-9ca6-c11012e8de2e.png)
![honey2](https://user-images.githubusercontent.com/86664756/189910952-0d9e8de5-08b3-4400-8c44-170d4524f06d.png)
Maybe change it to Resourceful Bees Honey? 

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Mana Liquidizer

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

『Bumble』#7797

**Comment by Gcat101** [comment]
Yeah but the bottled version has a lot of use cases i think

**Comment by Bumblebytrox** [comment]
yea the problem is only when i separate it :/ i dont want to have to make tons and tons of bottles when i can just empty and reuse them
