### ISSUE TITLE
PNC Fluid Tanks and Crafting

### ISSUE THREAD

**Issue by Celebnasse** [EnigmaticaModpacks/Enigmatica6#5212]
### Modpack Version

1.5.1

### Describe your issue.

Similar to issue #4188, when using a small fluid tank in crafting both the Refinery Controller and Refinery Output, it did not consume the tank, just took 1 bucket of water out of the tank.  Not sure if the fix in #4188 fixed this issue as well.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Caleb#3967

**Comment by NielsPilgaard** [comment]
The fix you linked was for one item only sadly, so thanks for reporting these as well 👍

**Comment by MuteTiefling** [comment]
I recall being unable to handle these via script. KubeJS simply doesn't output the PNC tank handler properly. 

So I'll just flip these over to use a dynamic tank item instead. Bypasses the issue entirely but keeps the theme.
