### ISSUE TITLE
Chisel & Bits Lag

### ISSUE THREAD

**Issue by TheRealCodaRa** [EnigmaticaModpacks/Enigmatica6#5213]
### Modpack Version

1.16.5

### Describe your issue.

The first time I used the chisel it was fine, but when I got the bits and put it into line mode the game really get laggy.  On top of that after chiseling that stuff, every time you bring out the chisel it also lags very badly. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
We can't do anything about that I'm afraid.
