### ISSUE TITLE
[Expert] Ability to craft scanners with the appropriate ores already in the block filters

### ISSUE THREAD

**Issue by BlackStone5677** [EnigmaticaModpacks/Enigmatica6#5214]
### Describe your suggestion

Because of emendatus enigmatica's feature to have ores with an appropriate stone textures you can't really scan for some ores because the scannable mod will only highlight the ones with the same stone embedment, and since there are less than 35 different stone types ores can be coated in you can have a scanner with 7 block modules and 2 range modules that will look for a certain ore and find all different versions of it, the only small issue is that you can only scan with 3 different block modules at once, but it would still be much easier to scan for ores like this.

Recipe could be a package of 7 block modules and 2 range modules, maybe called Scanner Module Package and if you craft that alongside an ore chunk of the desired ore type(let's say silver) and a scanner you will get a scanner that scans for all different versions of silver ore with 2 additional range upgrades inside as well. note that you will not get anything extra out of this, it's just for adding all the different types of an ore type to a scanner. also would be nice if the scanner was renamed to what it is scanning for example "Silver Ore Scanner" if it is supposed to scan for silver.

### Why would you like this added/changed?

it's just kind of annoying to scan for ores early game

**Comment by MuteTiefling** [comment]
The block scanner is for specific blocks. You want the common/rare ore modules for seeking ore for manual mining. Yes, this'll show all of the ore, but each one tells you exactly what it is. You just need to look over them.

 The features you're suggesting would be something the mod itself would have to add.
