### ISSUE TITLE
Aquamarine shale rate of production is way less than 2%

### ISSUE THREAD

**Issue by Porcy** [EnigmaticaModpacks/Enigmatica6#5220]
### Modpack Version

1.5.1

### Describe your issue.

As per JEI suggestion, I created an AS sand generator, seeing that 2% of the sand would be aquamarine shale. The actual production is way less.
![2022-09-29_16 40 07](https://user-images.githubusercontent.com/8096340/193138408-de609282-d630-40ae-baf0-5935d6583f1e.png)
![2022-09-29_16 39 46](https://user-images.githubusercontent.com/8096340/193138414-60405be7-9acf-4124-83e7-84bc534781e6.png)

### Have you modified the modpack?

Yes

### User Modifications

Added PAM's suite, Vanilla Food Pantry, Distant Horizons, No Fog

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
2% chance. Not guaranteed 2 in every 100.

**Comment by Porcy** [comment]
Ok. Figured it out. 0.1% is the rate for in-world sand generation. 2% is when using containment chalice, as illustrated in JEI.
