### ISSUE TITLE
Aeternium Armor durability buff

### ISSUE THREAD

**Issue by LaNeige725** [EnigmaticaModpacks/Enigmatica6#5224]
### Describe your suggestion

Aeternium armor set from BetterEnd mod, being not "not stronger than refined obsidian armor enough" is a separate discussion than this one, 

Refined Obsidian armor is too rewarding for what it costs, yes, but my main issue is with how little durability Aeternium actually has compared to it.

Aeternium armor has 520/600/640/440 (H/C/L/B) durability which is merely *just* better than Netherite armor.
I do not understand why the leggings have more durability than the chestplate but I digress, 

whereas, Refined Obsidian Armor has 825/1200/1125/975 durability

It may be a wise move to make it so Aeternium armor be in par with Refined Obsidian, or at least be more comparable. 

### Why would you like this added/changed?

Balancing 

(for when I leave my game afk for 4 minutes just to come back to a brutish zombee apotheosis boss break all my max affix armor)

**Comment by MuteTiefling** [comment]
I recall taking a look at this the last time it came up and, unfortunately, I saw no way to buff aeternium.

Mekanism helpfully adds configs for all of its armors and tools. So adjusting that is easy. Adjusting other armors is not so simple and kubejs doesn't seem to offer the ability to change existing armor, only to set up new armor.

**Comment by MuteTiefling** [comment]
Also, as a minor aside, maybe don't afk in the open ;) that can be deadly in any pack.
