### ISSUE TITLE
Recipe conflict for crushing Shiverstone

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica6#5227]
### Modpack Version

1.5.1

### Describe your issue.

Shivestone has both `forge:stone` and `forge:cobblestone` tags, creating a recipe conflict where it can be crusher (w/Mekanism crusher) to both Cobblestone and Gravel. Screenshot: https://imgur.com/jackD1R

### Have you modified the modpack?

Yes

### User Modifications

Added "Visual Workbench" mod

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

iarspider#9139

**Comment by NielsPilgaard** [comment]
Thanks for the report! The same goes for `Depthrock` and `Tremblecrust`. We'll get that fixed
