### ISSUE TITLE
Mod interaction: PNC:R Micromissiles can proc CoFH/Ensorcellation enchantment effects when dealing damage to the user

### ISSUE THREAD

**Issue by norbby42** [EnigmaticaModpacks/Enigmatica6#5228]
### Modpack Version

1.5.1

### Describe your issue.

Micromissiles from PneumaticCraft deal friendly fire damage when they explode near the user.  If the user is wielding an enchanted tool in their mainhand, the enchantments on that tool apply to the damage deal by the Micromissiles.  This means the user can be 1-shot by their own Vorpal enchantment.

Other enchantments may yield undesirable effects in this scenario as well - I haven't tested others.  Only noticed this when I triggered my Totem of Undying while killing a Baby Piglin.

Testcase:

1. Give yourself a Netherite Sword
2. Equip the sword in your mainhand
3. Give yourself Micromissiles
4. Equip them in your offhand
5. Give yourself some armor of your choice.  The objective here is to have enough to bring the splash damage from a typical explosion down to a survivable level.
6. Stand near a wall and right click to fire the Micromissiles.
7. Confirm you receive splash damage when the Micromissile projectile explodes upon hitting the wall.
8. Repeat several times, waiting to heal up to full health between each volley
9. Enchant your Netherite Sword with Vorpal V
10. Repeat steps 6-8
11. Observe that you now have a roughly 30% chance to instantly die when hit by the Micromissiles splash damage due to a Vorpal crit (it multiplies the damage value by 5)

### Have you modified the modpack?

Yes

### User Modifications

All modifications have been clientside (added the Magnesium suite of mods).  The dedicated server is running the mod pack in Expert mode with no changes.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This is simply how enchants work in minecraft.

You can do the same by holding your sword in your main hand and a bow in your offhand. Shoot into the air till you hit yourself.

It can be a huge benefit (getting looting on bow kills) but can be a bit detrimental at times too, as you've discovered.
