### ISSUE TITLE
Pressing "preview" in singleplayer world creation forces me to restart game

### ISSUE THREAD

**Issue by Benny-Boo** [EnigmaticaModpacks/Enigmatica6#5229]
### Modpack Version

1.5.1

### Describe your issue.

When I went to crate my first singleplayer world, I pressed preview cause i was curious what it did. It told me something about it being moved and to open a link in browser, that worked fine whatever. The problem is that the "go back" button didn't function, i clicked it, nothing happened. I had to restart my game cause it was literally just those buttons

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Benny-Boo** [comment]
Hm okay after restarting the preview just doesn't show up anymore, idk what's going on there, sorry if this report is useless.

**Comment by NielsPilgaard** [comment]
Thanks for the report! I'm considering just removing the retrogen mod tbh, that would "fix" this.

**Comment by Darkere** [comment]
I believe that function requires Patreon membership now.

**Comment by NielsPilgaard** [comment]
I'm pretty sure we're on a version that removed that restriction.

**Comment by Darkere** [comment]
Ah, I see. Was not up-to-date with that. However... 
```Version 3.5.0:
- Removed: All Supporter Checks from the mod, all features that are now in the mod are free.

- Removed: Preview Feature

- Removed: Preview Overlay
```


It appears the preview feature is supposed to not exist anymore
