### ISSUE TITLE
Easier infinite oil

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica6#5231]
### Describe your suggestion

Replace "Limitless oil" reward with (Mek) creative tank of oil. Or, make the oil trophy function as one. Or just add a separate quest to exchange 10k buckets of oil for some single-block oil source.

### Why would you like this added/changed?

Create's infinite bodies of liquid tend to randomly glitch/break, requiring player to re-fill it.

**Comment by MuteTiefling** [comment]
Overfilling the Create Infinite Source generally prevents it from breaking. IE and IF both also provide ways to get infinite oil.
