### ISSUE TITLE
Dupe - Logic Circuit at Engineer's Circuit Table

### ISSUE THREAD

**Issue by Sohex** [EnigmaticaModpacks/Enigmatica6#5233]
### Modpack Version

1.5.1

### Describe your issue.

It's possible to create logic circuits without actually expending resources. Add circuit backplanes and copper wire to the engineer's circuit table, select SET and then shift left click the logic circuit. The logic circuit will be added to the inventory, but the number of circuit backplanes and copper wire will not be reduced.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate #4528
