### ISSUE TITLE
Blood Altar MK2 Quest Requirements Incorrect

### ISSUE THREAD

**Issue by Sohex** [EnigmaticaModpacks/Enigmatica6#5235]
### Modpack Version

1.5.1

### Describe your issue.

The quest Blood Altar MK2 has the requirement of 6 blank runes, however 8 are needed to actually make the tier 2 blood altar.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
You also get 4 runes for free as a reward, more than filling out the gaps
