### ISSUE TITLE
Ambient Sounds 5

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#5238]
### URL

https://www.curseforge.com/minecraft/mc-mods/ambientsounds

### Why would you like the mod added?

Adds awesome biome-specific ambient noises to the game, from birds chirping, to howling peaks. I remember an older version of the mod being here at some point, but it was silently removed somewhere. Hope to bring it back, I add it in every single pack I play that has a supported MC version. Requires [CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore)

**Comment by MuteTiefling** [comment]
#2460
