### ISSUE TITLE
The tooltip GUI is messed up

### ISSUE THREAD

**Issue by LucAsl14** [EnigmaticaModpacks/Enigmatica6#5241]
### Modpack Version

1.6.0

### Describe your issue.

Whenever I shift+hover over a tool or weapon while I have one equipped, this happens:

![2022-10-20_19 03 38](https://user-images.githubusercontent.com/94207449/197076685-917ba844-59c8-4795-b5bb-2a554a4c459f.png)

### Latest Log

https://gist.github.com/LucAsl14/fc60547d24e3e56d0272eea4d74934bc

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

—ℒ—#1368

**Comment by koh-gh** [comment]
I also have this problem.
Tooltip display position is shifted in some GUIs.

**Comment by NielsPilgaard** [comment]
Thanks for the report 👍 I've relayed it to the appropriate mod's issue tracker.

**Comment by koh-gh** [comment]
I add some screenshots.
Refined Storage and Mekanism tooptips are shifted left.
![2022-10-22_11 27 37](https://user-images.githubusercontent.com/36918206/197315789-9469b587-a0d0-4e5b-8081-e0a189577b1d.png)
![2022-10-22_11 28 10](https://user-images.githubusercontent.com/36918206/197315799-2f15b543-80c0-4bdf-a6bb-2d85ab702d0f.png)

I tested to create the environment only RS, Mek, Equipment Compare, then this could not reproduce, and Equipment Compare's tooltip also shows correctly.

**Comment by Katon15** [comment]
The GUI on Thermal Expansion doesn’t even show up when you hover over. Some mod GUI’s have the information shifted to the top left as well

**Comment by AHilyard** [comment]
Just as an update for everyone, this bug is being caused by version 3.9+ of JustEnoughCalculation.  You can find a relevant issue here: https://github.com/Towdium/JustEnoughCalculation/issues/116

**Comment by koh-gh** [comment]
Cool. I was able to reproduce this and https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5250 by adding JEC 3.9.2. (Minimal mod environment)
Changing this version to 3.8.6 will fix these issues.
