### ISSUE TITLE
Adding fuel to Compression Dynamo can cause a server-side crash

### ISSUE THREAD

**Issue by OniNezuko** [EnigmaticaModpacks/Enigmatica6#5242]
### Modpack Version

1.6.0

### Describe your issue.

When we play the game and we add PneumaticCraft's fuel to Compression Dynamo, the server side crashes, but the local game does not have a problem. This is a bit of a pain because it looks like PneumaticCraft's fuel can only be used to make plastic in addition to powering Compression Dynamo.

### Crash Report

https://gist.github.com/OniNezuko/d454c71c0fbd0d82dce23ac02bc206a9

### Latest Log

https://gist.github.com/OniNezuko/d42a9b4a8cddffdb2954ebddf6972da9

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

B C#4825

**Comment by NielsPilgaard** [comment]
Thanks for the report - Have you tried on a non-Mohist server? :)

**Comment by OniNezuko** [comment]
I ganna try Arclight later,thanks for suggestion. :)

**Comment by NielsPilgaard** [comment]
My pleasure, thanks for seeing it as help :P
