### ISSUE TITLE
[Expert]Adding fuel to Compression Dynamo can cause a server-side crash on forge server

### ISSUE THREAD

**Issue by OniNezuko** [EnigmaticaModpacks/Enigmatica6#5243]
### Modpack Version

1.6.0

### Describe your issue.

When we play the game and we add PneumaticCraft's fuel to Compression Dynamo, the server side crashes, but the local game does not have a problem.
I switch saves from Moist to Forge, I can enter world sucessfully, but Compression Dynamo will still cause a crash.
Sorry for the repeated report...

### Crash Report

https://gist.github.com/OniNezuko/af9a8c737cd3194ba5aa70511dc13215

### Latest Log

https://gist.github.com/OniNezuko/1065d884845822ccecdedae36f4c5254

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

B C#4825

**Comment by NielsPilgaard** [comment]
Ehm... `Known server brands: forge, Mohist, forge arclight` 😄 the crash report is saying you're not running a plain Forge server.

**Comment by OniNezuko** [comment]
It seems like i do the wrong job to migrate saves to forge, this is what i have done:
1. I download server pack from curseforge and run，make sure forge server download all things  and  a new  "world" is created.
2. I close the server, then delete "world" folder new created, put the old saves back.
3. Run server.

Is  there anything i can do to fix my saves?  ;(

**Comment by Darkere** [comment]
The issue is probably unrelated to mohist. Though it is surprising that this is the first time we are hearing of the issue. 

To me, it looks more like a wrong version of a mod? Though the versions in the crash log do match up.
Check if you have multiple versions of the same mod installed.

**Comment by Darkere** [comment]
Also make sure your client has the same mod versions as the server.

**Comment by OniNezuko** [comment]
The mods count on server is [347](https://i.imgur.com/5Zekpg5.png), however, when server is downloading mods, some mods just  time out. Unfortunately, the logs have been cleared by the new logs, and I don't know if the information is critical.
I am going to calculating hash values of server-side mods and client-side mods,  compare if they were same.

**Comment by OniNezuko** [comment]
Something news here: when i try at my local computer, it happened again, [you can watch the video](https://streamable.com/q3zmky)
[crash-report](https://gist.github.com/OniNezuko/92220259d3dcb010bf019a808a32b014)
[mods hash here](https://gist.github.com/OniNezuko/0f8954e172dc1f7f181a33407dc6a931)
Now I don't have a clue. D:

**Comment by glektarssza** [comment]
Seeing the same issue with Thermal's Magmatic Dynamo. Doesn't matter if it's lava, Blazing Blood, or some other fuel.

See https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5245 for more details.

**Comment by OniNezuko** [comment]
I just try to change java version、redownload on GDlauncher and so on, crash are steadily triggered.
If someone need more test, I can provide my help.
