### ISSUE TITLE
Add a crafting recipe for soul shards 

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica6#5244]
### Describe your suggestion

Add a different method of obtaining eidolon's soul shards apart from the crystallization ritual and reaper scythe.

### Why would you like this added/changed?

Every time I try to make soul shards, the game crashes. I tried both methods.

[There's an issue on eidolon's repo but it's still hasn't been resolved.](https://github.com/elucent/eidolon/issues/110)

Soul shards are an important crafting ingredient in expert and the only way to obtain it for me right now is through cheating. Having an actual recipe would fix that problem.

**Comment by King65868** [comment]
Zombies work fine, skeletons don’t

**Comment by Gcat101** [comment]
Nope, zombies don't work for me either.

**Comment by MuteTiefling** [comment]
I'm unable to reproduce this. I'd suggest you provide the missing information a bug report would need (logs, any modifcations you've made to the pack) and we'll investigate from there. 

https://streamable.com/m34gey

**Comment by Gcat101** [comment]
I've added rubidium. The issue might be that eidolon's animations somehow don't work with it??

**Comment by CaptainAlkohol** [comment]
I used Rubidium without any issues with the ritual

**Comment by Gcat101** [comment]
So the last few messages of my log:

```
[21Oct2022 19:00:59.595] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] <G_cat101> here
[21Oct2022 19:01:10.329] [Render thread/ERROR] [journeymap/]: Can't get entityTexture for TranslatableComponent{key='entity.eidolon.zombie_brute', args=[], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} (SUPPRESSED)
```

I sent the "here" message before I killed two zombies with a reaper scythe.

**Comment by MuteTiefling** [comment]
Can't reproduce with Brutes in a clean instance either. Try with a clean instance. Be sure to upload full logs.

**Comment by Gcat101** [comment]
I killed a regular zombie tho

**Comment by MuteTiefling** [comment]
Which makes your two line log snippet make even less sense.

**Comment by Aelian778** [comment]
I am experiencing the same issue, game crashes when using cristalization ritual with skeletons around. No issues with zombies though. 

Added mods: Starlight, Smoothboot, Fastsuite, Oculus and Rubidium

**Comment by MuteTiefling** [comment]
> I am experiencing the same issue, game crashes when using cristalization ritual with skeletons around. No issues with zombies though. 
> 
> Added mods: Starlight, Smoothboot, Fastsuite, Oculus and Rubidium

Try it without all those added mods.
