### ISSUE TITLE
[BUG] [Expert] Thermal Magmatic Dynamo crashes the game when given fuel for the first time

### ISSUE THREAD

**Issue by glektarssza** [EnigmaticaModpacks/Enigmatica6#5245]
### Modpack Version

v1.6.0

### Describe your issue.

Adding fuel to a Thermal Magmatic Dynamo which is not currently running causes the game to crash. Reloading the save the Magmatic Dynamo runs normally as long as it's kept provided with fuel. Upon idling again and then being given fuel once more the game will crash again.

### Crash Report

https://gist.github.com/glektarssza/7be75a7b27bdaf74aecf5f1308c8f676

### Latest Log

https://gist.github.com/glektarssza/616f5317a7515ddb86fe679a1a34cfdf

### Have you modified the modpack?

Yes

### User Modifications

Added the following mods:

* Rubidium
* [Rubidium Extras](https://github.com/dimadencep/sodium-extra-forge)
* TexTrue's Rubidium Options
* Oculus
* Road Runner
* TOP Addons
* iChunUtils
* Tabula
* Morph
* Xaero's Minimap and World Map
* Just Enough Advancements
* Just Enough Immersive Multiblocks

Removed/disabled the following mods:

* Journeymap
* JMI (Journeymap Integrations)

Changed configs for:

* Just Enough Calculations (set to client mode)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by glektarssza** [comment]
Crash does not occur without the added mods installed. I suspect Road Runner due to how it alters memory routines. I'm going to test that theory now by re-enabling everything except Road Runner.

**Comment by Darkere** [comment]
RoadRunner comes with the pack. So unlikely that is the issue.

**Comment by glektarssza** [comment]
Crash is not manifesting with the added mods re-enabled. I'm honestly not sure what's going on at this stage. I'm happy to call this "cannot reproduce" for the time being. If the issue reappears, I can reopen the issue.
