### ISSUE TITLE
Industrial Foregoing range addons cannot be inserted into Mob Crusher

### ISSUE THREAD

**Issue by kurbar** [EnigmaticaModpacks/Enigmatica6#5246]
### Modpack Version

1.6.0

### Describe your issue.

Put down a Mob Crusher and try to insert an Addon: Range (e.g. Tier 2, tested with different tiers) to the machine. The machine is not accepting the addon.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

kurbar#7900

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
