### ISSUE TITLE
Not able use extract and insert buttons in Sophisicated Backpacks

### ISSUE THREAD

**Issue by sid-marie** [EnigmaticaModpacks/Enigmatica6#5247]
### Modpack Version

1.16.5

### Describe your issue.

I am not able to use the extract and insert buttons in the sophisticated backpacks. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

sid_marie

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
I'm guessing this is intentional to prevent dupe bugs, since the shift lock button works.
