### ISSUE TITLE
Unable to access Integrated Dynamics' Storage Terminal

### ISSUE THREAD

**Issue by iammael** [EnigmaticaModpacks/Enigmatica6#5249]
### Modpack Version

1.6.0

### Describe your issue.

I have a basic ID network for some storage, with a Storage Terminal to access my stuff in chests.

When I set it up first, it was working, but after a server/client reload, the terminal is greyed out and some errors are popping on the server output (see below).

The network is still working otherwise as an Item Importer is still correctly importing in my chests.

Here's a picture of the setup.

![2022-10-23_19 29 06](https://user-images.githubusercontent.com/7931135/197407665-60f85fb8-116c-4d6a-8156-5537ae921b30.png)
![2022-10-23_19 29 01](https://user-images.githubusercontent.com/7931135/197407668-1c164dfd-adf1-4b45-955f-cc7307881e97.png)

### Latest Log

https://gist.github.com/iammael/8f2919e6fe956e4a17e5e3ed28b1e27c

### Have you modified the modpack?

Yes

### User Modifications

Only a few client side mods, mainly for shaders. But the bug is confirmed without those extra mods.

- Rubidium
- Magnesium Extras
- Oculus
- ItemZoom

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Scheigy#1178

**Comment by iammael** [comment]
The bug seems to happen only on a server, as everything is working as expected after running the world locally.

**Comment by iammael** [comment]
Sorry for the third comment, but after reloading the server a third time, the bug disappeared.

I let you decide if the issue still needs to be investigated or if you want to close it.

**Comment by NielsPilgaard** [comment]
Glad to hear it 👍 I'll close this for now then, feel free to comment again if you manage to reproduce it reliably.
