### ISSUE TITLE
Refined Storage doesn't display exact amount of items on tooltip anymore

### ISSUE THREAD

**Issue by iammael** [EnigmaticaModpacks/Enigmatica6#5250]
### Modpack Version

1.6.0

### Describe your issue.

After the last pack update (1.6.0), the RS grid doesn't display the exact amount of items stored when hovering anymore.
People on Discord playing on 1.5.1 said they are able to see it just fine.

_Obviously this is not a game-breaking bug, but I thought it could still be of interest to open an issue in case this was a non-intended change between versions, as there's no mention of it in the changelog._

Related screenshot:
![image](https://user-images.githubusercontent.com/7931135/197419763-ab930fc1-f76b-4dea-a86c-1ec46643ec03.png)

### Have you modified the modpack?

Yes

### User Modifications

Yes, just mods for shaders but other players reported the same issue.

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Scheigy#1178

**Comment by NielsPilgaard** [comment]
@Darkere do you know anything about this? :)

**Comment by Darkere** [comment]
I believe there is a config option in the client config to turn off detailed tooltips. Default is on though.

**Comment by NielsPilgaard** [comment]
That's odd. We don't actually ship that config, so it might've happened by accident?

**Comment by iammael** [comment]
Haven't mess with RS config on my end and I can see the Detailed Tooltips are indeed set to on on my client.

That's completely random, but could be related to : https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5241#issuecomment-1287594224

**Comment by NielsPilgaard** [comment]
I doubt it, but not impossible 🤔 could you paste the contents of your config here please?

**Comment by iammael** [comment]
Sure:

```
[grid]
	#The maximum amount of rows that the Grid can show when stretched
	#Range: > 3
	maxRowsStretch = 2147483647
	#Whether the Grid should display a detailed tooltip when hovering over an item or fluid
	detailedTooltip = true
	#Whether the Grid should use a large font for stack quantity display
	largeFont = false
	#Whether the Grid should prevent sorting while the shift key is held down
	preventSortingWhileShiftIsDown = true
	#Whether the Grid should remember the search query when closing and re-opening the Grid
	rememberSearchQuery = false

[crafterManager]
	#The maximum amount of rows that the Crafter Manager can show when stretched
	#Range: > 3
	maxRowsStretch = 2147483647

[cover]
	#When true all the possible covers will be added to JEI (Game restart required)
	showAllCoversInJEI = false
```

**Comment by koh-gh** [comment]
The tooltip that the screenshot shows is not from RS. Tooltips in RS show the number of items and the last modified date.
I think some mod that changes the way tooltips are displayed is messing up the display. I'm trying to see if it can be reproduced with a minimal combination of Mods, mainly the Mods updated in 1.6.0, but I can't reproduce it so far.
