### ISSUE TITLE
Adding fuel to any Thermal Expansion Dynamo causes crash

### ISSUE THREAD

**Issue by Caerglad** [EnigmaticaModpacks/Enigmatica6#5255]
### Modpack Version

1.6.0/1.6.1

### Describe your issue.

Connecting magmatic dynamo to pipe system (mekanism pipes) containing blazing blood is causing client crash.
Both placing dynamo against existing pipe, or placing dynamo beforehand and then connecting it to pipe system end in client crashing. I didn;t encounter issues with other generators from Thermal Series.

Looks similar to #5243 and #5245

### Crash Report

https://gist.github.com/Caerglad/ec3dc342cde5686a8e5e7ac1162d7a07

### Have you modified the modpack?

Yes

### User Modifications

Natures Aura (disabled plant growth at hight aura level)

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Caerglad#0001

**Comment by NielsPilgaard** [comment]
Thanks for the report. Have you added Rubidium? :)

**Comment by Caerglad** [comment]
No, I don't have any shaders

**Comment by Darkere** [comment]
Someone was able to reproduce the issue with just thermal mods. Afaik KL was planning to release a new version that might fix this. Not sure if he ever did.

**Comment by NielsPilgaard** [comment]
Oh, okay.
