### ISSUE TITLE
Magebloom plants drop seeds when right-click harvested.

### ISSUE THREAD

**Issue by Fredi355** [EnigmaticaModpacks/Enigmatica6#5256]
### Modpack Version

1.5.1

### Describe your issue.

When harvesting magebloom plants by using right-click they occasionally drop seeds.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Fredi#0906

**Comment by NielsPilgaard** [comment]
I believe this is intentional :)
