### ISSUE TITLE
Don't work right with JEI

### ISSUE THREAD

**Issue by dervernichter334** [EnigmaticaModpacks/Enigmatica6#5257]
### Modpack Version

sophisticatedbackpacks-1.19.2-3.18.29.719.jar

### Describe your issue.

Hallo,
when I open the crafting fiel in the backpack and choose a recepi in JustEnoughItems i can't click on +(plus) although JustEnough items on my server is installed and i can click on +(plus) and it works.

### Have you modified the modpack?

Yes

### User Modifications

I don't have change anything but i have add other mods 
![Bildschirmfoto 2022-11-09 um 09 44 38](https://user-images.githubusercontent.com/108345689/200782370-272c9f11-8af8-479c-bb74-fda3c0fffb23.png)

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

dervernichter334#2448

**Comment by Kanzaji** [comment]
Those mods are for 1.19.2, Enigmatica 6 is on 1
16.5 ^^"
Also with this amount of mods added. If it works fine without them, we can't do much about it.

**Comment by dervernichter334** [comment]
Oh sorry this is the wrong github sorry
