### ISSUE TITLE
Borderless Window

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#5259]
### URL

https://www.curseforge.com/minecraft/mc-mods/borderless

### Why would you like the mod added?

Borderless Window replaces the regular Fullscreen mode with their version, allowing for clicking elsewhere while the game is in fullscreen, so it doesn't interrupt the game. Mostly useful for those who have multiple monitors.

It is also available for 1.18, 1.19 versions, so could potentially be in E8 and 9 as well.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. I'd rather not add this, as adding a similar mod to E2E caused a ton of issues.

**Comment by NielsPilgaard** [comment]
Yeah no, I'm scared of introducing hard to find bugs :P no thanks.
