### ISSUE TITLE
Adding fuel to Compression Dynamo causes crash

### ISSUE THREAD

**Issue by fnndyl** [EnigmaticaModpacks/Enigmatica6#5262]
### Modpack Version

1.6.0

### Describe your issue.

Adding fuel to the compression dynamo crashes my game. Once the dynamo is running everything is fine, but the initial startup crashes no matter what fuel I try.  Playing on expert mode if that makes a difference.

### Crash Report

https://gist.github.com/fnndyl/afae140b34c4fbeb78abb1b1cb6d207f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Duplicate of #5255

**Comment by NielsPilgaard** [comment]
... I renamed the wrong issue here sorry :P
