### ISSUE TITLE
E6Expert - resourcefulbees & roadrunner crash

### ISSUE THREAD

**Issue by X-Niter** [EnigmaticaModpacks/Enigmatica6#5263]
### Modpack Version

1.6.1

### Describe your issue.

When leaving a server be it disconnecting or getting kicked, the modpack crashes all the way out to the launcher.
I have gathered a successful crash report to show the stack trace of what is happening.

Users were instructed to install a fresh 1.6.1 version of E6E, use standard java 8 with 8 - 10 gigs of ram, graphical settings were set to low.

Upon the above instructions, they joined in, then left and on leaving would crash; on joining again, I kicked them and the same thing happened.

The latest log is gathered from my client to which I tested this issue as well, and the crash log is also mine but the stack trace is identical to the ones of the other users.

Additionally, before noticing this crash, we noticed that when installing a fresh 1.6.1 client, when we joined the 1.6.1 server, we had a joining error of ""failed to synchronize registry data from server"". 
To fix that, we deleted are `common.toml` config inside of the `resourcefulbees` config folder and were able to join. 
I don't know if that helps with pointing towards the crash, but, given that the crash log mentioned the resourceful bees mod and our issue with joining the server was also related to the same mod, I figured I would be thorough and give that info.

### Crash Report

https://gist.github.com/X-Niter/31ca6ae950a19feae48112a842974856

### Latest Log

https://gist.github.com/X-Niter/6e8d2ad25ead9d01c00b27c175c9c5da

### Have you modified the modpack?

No

### User Modifications

No modifications and reproduction was successful with all users requested to test. (3 users)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

X_Niter#2563

**Comment by NielsPilgaard** [comment]
Thanks for the report. Do you perhaps still have the erroneous `common.toml` config? :)

**Comment by X-Niter** [comment]
I do have that file, yes. 
If any file corruption is potentially a concern, I am providing at least a screenshot of the file size as the file appears to be healthy.

There is also "kubejs errors" upon joining the 1.6.1 server as well. 
We did do a clean installation for the update but kept the world as we didn't want to lose it, we are currently performing a clean new E6E server/world altogether now to see if the situation remains. 

I will make sure to report back on if there is any change with a "fresh" E6E server/world start, the old world and files will still remain saved for troubleshooting purposes if we/you need them.

![image](https://user-images.githubusercontent.com/30506033/202285314-cad4e58c-6dae-4491-9cd5-d2c4233ea43e.png)

[common.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10025385/common.txt)

**Comment by NielsPilgaard** [comment]
Hm, the file matches the one shipped with the modpack. Which KubeJS Error did you get?

**Comment by X-Niter** [comment]
The error ingame that goes to the server.txt log, is [here](https://gist.github.com/X-Niter/4687b04391ec71c5d9e07401dc76fe3b)

The full kubejs/server.txt log is [here](https://gist.github.com/X-Niter/d42355e80256f04f23746f2513f679c7)

A screenshot does not do much justice due to the long text, but I can at least attempt to provide a "friendly" small view of what it looks like and the first few errors.
It seems that maybe one or two points at the resourceful bees at rainbow honey but that's just an observation.
![image](https://user-images.githubusercontent.com/30506033/202299381-66e8945e-b82c-45a0-8c27-0391330c8509.png)

**Comment by X-Niter** [comment]
I would like to come back to report the status of running a full new server of version 1.6.2 was successful and showed that this current dilemma no longer exists. 

That being said, 1.6.2 is a Release and not a beta, so best idea here is "Update solved it" unless it comes up again from someone else.
