### ISSUE TITLE
Potentially replace Journeymap

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#5266]
### Describe your suggestion

Unfortunately, Journeymap is not very good as of lately. The mod severely bogs performance, sometimes even a 40% drop in frames. For the past 8 months or so, every pack I play I disable the mod and either use it's own web map, or I use something like FTBChunks or Xaero because of this performance decrease. With, to my knowledge, no way to turn down how fast the map updates, it's not really a viable map mod anymore.

### Why would you like this added/changed?

With a close to 40% drop in frames, at least for me, can make the experience very unplayable. I believe there are much better alternatives, like FTBChunks.

**Comment by MuteTiefling** [comment]
FTB Chunks is already in the pack, and you can safely disable JourneyMap with no ill effects, even if you are playing on a server.

**Comment by FooterMan14** [comment]
The problem with that is the configs for Chunks gets reset when either the world loads, or the pack loads (I don't know witch). I've tried to see if there was a setting in the files or something to fix it, but I couldn't find it. If the configs don't change, I'd say that'd be pretty good for those who don't want Journey.

**Comment by Gcat101** [comment]
Get off my lawn

**Comment by MuteTiefling** [comment]
Start by disabling JourneyMap and JourneyMap Integrations entirely. Click the toggle in CurseForge:
![image](https://user-images.githubusercontent.com/9543430/202455773-3898bcf3-8f32-47bc-be3c-0602091abd31.png)
If you're not using CF, I think the other launchers have ways to do this. Or just delete the mod from the instance/mods folder. You will need to repeat this every update, unfortunately.

JourneyMap Integrations is responsible for disabling FTBChunks minimap. https://github.com/EnigmaticaModpacks/Enigmatica6/blob/7624718ea89993dd2549e2cf53259450beee8e5b/defaultconfigs/jmi-client.toml#L9

Open your world map and click the gear in the lower left
![image](https://user-images.githubusercontent.com/9543430/202466302-6f4a87db-335d-48cc-b151-d8905b0739f6.png)

Then change the minimap to true
![image](https://user-images.githubusercontent.com/9543430/202466421-f1cf3e49-404c-4476-ae4f-c1daa3504827.png)

Make any other settings changes you want while you're there.

Make a backup of `instance/local/ftbchunks/client-config.snbt` as this is where the config is stored. 

You'll need to replace it every time you update as we do ship this file in the pack, but it should not be modified anymore with JMI disabled.

**Comment by FooterMan14** [comment]
I just don't understand why FTBC has to be locked down so hard. I remember E6 used it for map purposes and it was just fine, then Journey came out of no where and shut it down. I feel like players should get full control over what map they want to use. It's legit just a map mod.

**Comment by NielsPilgaard** [comment]
> I just don't understand why FTBC has to be locked down so hard. I remember E6 used it for map purposes and it was just fine, then Journey came out of no where and shut it down. I feel like players should get full control over what map they want to use. It's legit just a map mod.

It seemed like the majority of users wanted JM over FTBC, so we chose JM. In order to not tank performance, we disabled the FTBC map as much as we could.
