### ISSUE TITLE
Isenium Ingot progression (expert mode)

### ISSUE THREAD

**Issue by Caerglad** [EnigmaticaModpacks/Enigmatica6#5267]
### Describe your suggestion

Add Iesnium Ingot to Sentient Harm recipe in expert mode.
Remove Isenium from early quest rewards.

### Why would you like this added/changed?

Ars Noueum's Sentient Harm is the only Sentient tool not using this material and that breakes progression from questline.
Also I've got Isenium block from quest rewards long before gaining ability to mine it.

**Comment by Caerglad** [comment]
Also, is it intened for netherite pickaxe to mine Iesnium Ore?

**Comment by MuteTiefling** [comment]
Sentient harm is meant to be your shortcut into Will.
