### ISSUE TITLE
Crafting with the infinite water bucket converts it to an ordinary one

### ISSUE THREAD

**Issue by JonasDoe** [EnigmaticaModpacks/Enigmatica6#5272]
### Modpack Version

E6E 1.6.2

### Describe your issue.

I tried to craft tiny rubber with this "MLG yolo" bucket and twines around, and I could only craft once - then it became an ordinary bucket. Maybe the receipe shouldn't work with that one (or work similar to a Mekanism tank with creosote oil and planks).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
We don't have that level of control, but you could request this on Quark's issue tracker.
