### ISSUE TITLE
[Typo] Foundry Controller TC quest

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5274]
### Modpack Version

1.6.2

### Describe your issue.

"Check it's quest" should be "its quest"

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Fixed in-dev, thanks 👍

**Comment by MuteTiefling** [comment]
Found a bunch more `it's > its` typos elsewhere that are fixed in dev now too.

**Comment by Splutty** [comment]
I didn't attempt to find them all, I just reported the ones I accidentally saw :D But I'm sure you did a grep over the whole thing!
