### ISSUE TITLE
[Typo] Quest Building - The Mighty Architect

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5276]
### Modpack Version

1.6.2

### Describe your issue.

"this this mod is for you" -> "then this mod is for you"
"Create Shematicannon" -> Schematicannon

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Fixed in-dev, thanks 👍
