### ISSUE TITLE
Refined Storage External Storage

### ISSUE THREAD

**Issue by HeavymetalXXI** [EnigmaticaModpacks/Enigmatica6#5279]
### Modpack Version

1.6.1

### Describe your issue.

While having a Refined Storage External Storage buffer to a Drawer controller, when you re-log into world it doesn't connect to RS system, you have to break the piece, and replace for items in your Drawers to show up. I made a get around for the External Storage buffer to toggle on Redstone signal and placed a wireless signal to turn it off then on again.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Heavymetal21#9910

**Comment by NielsPilgaard** [comment]
Very known issue sadly, there's nothing we can do about it :(
