### ISSUE TITLE
Bug: Green Present JEI Recipe uses wrong green dye

### ISSUE THREAD

**Issue by PeaceIsBliss** [EnigmaticaModpacks/Enigmatica6#5280]
### Modpack Version

1.6.0

### Describe your issue.

Green Present from Supplementaries (Recipe ID: supplementaries:jei_present_green) uses pitg:green_dye (Pain in the Glass) instead of minecraft:green_dye for recipe in JEI. The recipe works in crafters if you force minecraft dye; Only noticed this trying to create present with remote crafting.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Warteks#3319

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
I can't find the recipe, which leads me to believe it's defined in code - We cannot override that sadly. I can however add another recipe.
