### ISSUE TITLE
Missing Withered Bone recipe for Tinker's Construct modifier Severing

### ISSUE THREAD

**Issue by dubbat** [EnigmaticaModpacks/Enigmatica6#5281]
### Modpack Version

Enigmatica 6 Expert 1.6.2

### Describe your issue.

Not 100% sure this is a bug as I haven't found a fortress yet in the Nether, but the wither skeletons I have found (archer type) do no drop the Tinker version of wither bones and it seems like only village bounties are the only way to get them (or normal wither skeletons if they exist?)

Tinker: Necrotic Bone
Architect's Pallete: Withered Bone

The Soulfire Wand takes either (custom recipe), so I assume this recipe was just missed.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by dubbat** [comment]
Little update. Did find a Fortress yesterday. Did find regular Wither Skeletons. They did drop the Tinker wither bones.
I supposed this could be left as-is, but it would make sense to either add the recipe or add the tinker bones to the drop table of the wither skeleton archers, unless you want to lock the "beheading" modifier to finding a fortress.

**Comment by theboo** [comment]
One way around this is to use a cleaver since it comes with the severing enchant and will get tinkers bones from any wither skeleton...

But according to knightminer ages ago, it is not intended to need severing to get these bones, they should drop from any wither skeleton  but the architects pallette bones are overriding the drops... I think the fix would be to add the tinker's tag to the AP bones? This way they can be used for beheading as well

**Comment by dubbat** [comment]
Mmm. Not sure if I had a cleaver at the time I was attempting this, but I do now. The issue is the beheading default enchant with the cleaver is not high enough. I was attempting to add MORE beheading as Luckiest + default Severing (2?) was not enough. This is why I ran into the whole issue in the first place as I had not found a fortress (found it later BURIED and did not show on FTB map because it is top down) and needed better Severing.

Needing Severing to get (or more) Severing is a bit of a circular dependency. Kinda nasty. Especially when the recipes are usually interchangeable, but this one specifically is not.

**Comment by dubbat** [comment]
Looks like this is auto-closing with the recent change once it hits release. Thanks!

**Comment by juh9870** [comment]
I think TiC quest line should be updated too, to accept different kinds of wither bones
