### ISSUE TITLE
[Typo] Powah: Lens of Ender

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5282]
### Modpack Version

1.6.2

### Describe your issue.

"Just right click it on and it will"

I think there's an "an Enderman" missing there :)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Oh, yep. Will get that fixed up.
