### ISSUE TITLE
[Heat] PNC Questlines

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5294]
### Describe your suggestion

Copy/paste part of the "How can I generate heat" descriptions (especially the list of machines that generate heat) in the Vortex Tube quest into the TPP quest.

I for one never even did the Vortex Tube quest to begin with. And it's a somewhat odd place to put very useful information.

### Why would you like this added/changed?

Lots of people asking in Discord "How to heat the TPP", not "How do I make heat with a Vortex Tube".

**Comment by NielsPilgaard** [comment]
Sounds like a good change 👍

**Comment by MuteTiefling** [comment]
Considering there are several machines that need heat and an entire tree dedicated to creating and managing heat, I've just done a little restructure to point people at the existing quests as they get into the Refinery, which is a requirement for the TPP quest.
