### ISSUE TITLE
Crash: Schematicannon

### ISSUE THREAD

**Issue by ottodk1** [EnigmaticaModpacks/Enigmatica6#5295]
### Modpack Version

1.6.2

### Describe your issue.

If material checklist is input AFTER schematic, the game crashes

The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Ticking block entity
Exit code: -1

_No response_

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report. It's a known issue that we can't do anything about sadly, Create doesn't get bugfixes on 1.16.5
Schematicannon issues for reference: https://github.com/Creators-of-Create/Create/issues?q=is%3Aissue+schematicannon+crash
