### ISSUE TITLE
Useless recipe: (egg, raw pasta x8) = (raw pasta x8)

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#5297]
### Modpack Version

1.6.2

### Describe your issue.

![2022-12-29_03 21 07](https://user-images.githubusercontent.com/13237198/209868538-cd9e039b-4a1c-45f7-a6ab-4d2f18a489e6.png)

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Spotted on the official Enigmatica 6 server and a local sp world

### Discord Username
Haxton#4254

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
