### ISSUE TITLE
Typo: Enigmatica 6 Normal, Botania questline Sparks, Shear > Sheer

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica6#5298]
### Modpack Version

1.6.2

### Describe your issue.

![2022-12-29_05 39 25](https://user-images.githubusercontent.com/13237198/209869606-b1a91d10-e471-4f1b-9a79-233be1d3dbfd.png)

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Haxton#4254

**Comment by MuteTiefling** [comment]
Good catch, thanks!
