### ISSUE TITLE
Pretty Pipes not working well with potions

### ISSUE THREAD

**Issue by janarjo** [EnigmaticaModpacks/Enigmatica6#5303]
### Modpack Version

1.6.2

### Describe your issue.

I am attempting to automate enchanted golden apples using potions. My item network is based on Pretty Pipes which has been pretty successful so far however, it's unusable when it comes to potions.

Potions that I tested with: Potion of Regeneration (II), Potion of Absorption (IV), Potion of Fire Protection, Potion of Resistance.

1. Retrieval modules don't filter them properly. Seems it considers all potions equivalent and sends whatever potions it can get even when you filter for a specific type. Stack limiter does work correctly though, fortunately.

2. When requesting potions from a item/crafting terminal, it will send the correct type but 64 at a time even when you request only one. Since potions don't stack, this is not great.

Effectively, Pretty Pipes and potions don't work well at all together.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report! Would you mind posting it on Pretty Pipes' issue tracker as well?
https://github.com/Ellpeck/PrettyPipes/issues

**Comment by FalseID** [comment]
Problem 1. can be mitigated by using a Data Filter module. Seems it filters correctly then.

2. Is still relevant and inconvenient.

As requested, I posted it for Pretty Pipes https://github.com/Ellpeck/PrettyPipes/issues/175
