### ISSUE TITLE
Client crash when opening FTBQuests journal

### ISSUE THREAD

**Issue by FalseID** [EnigmaticaModpacks/Enigmatica6#5305]
### Modpack Version

1.6.2

### Describe your issue.

Client crashes immediately when opening the quests windows. Affects everyone on the server.

Everything was fine yesterday. When we started the server today then we can no longer open the quest journal without crashing the client. We have not upgraded or modified the server configuration in any way. 

Issue also seems to affect FTBChunks menu, opening it will cause some kind of mouseClicked event handler NullPointer and also crashes the game. It's a different error but it's for sure related. Let me know if you'd like a separate crash report for it.

### Crash Report

https://gist.github.com/FalseID/79e8b7901d766182e4c748ca2b18adef

### Latest Log

https://gist.github.com/FalseID/02a3587da6074ce5a20f249f088b7a03

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by FalseID** [comment]
Restarting the server seems to have fixed it for now. Not sure why it happened, there was no indication of any server issue.

**Comment by NielsPilgaard** [comment]
That's.. strange 🤔 please comment here if you manage to reproduce it.
