### ISSUE TITLE
[E6E] RFTools Advanced Porter uncraftable.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5307]
### Modpack Version

E6E 1.6.2

### Describe your issue.

Recipe for this doesn't work, might be because the normal porter was charged, but even then, that's bad.

In a vanilla Crafting Terminal (same thing happens in RS crafting terminal):

![Crafting Terminal](https://cdn.discordapp.com/attachments/947932229143760957/1061759687470620682/image.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Probably some weirdo nbt thing. Will take a look in a bit, thanks
