### ISSUE TITLE
Quest reward bug/Dimensional shard bug(Enigmatica 6 normal)

### ISSUE THREAD

**Issue by lCobaltl** [EnigmaticaModpacks/Enigmatica6#5313]
### Modpack Version

1.6.2

### Describe your issue.

The first issue is about quest rewards, You are able to complete them but when you claim a reward you don't get anything.
![image](https://user-images.githubusercontent.com/123050472/213359280-d60be642-7a24-41f7-ad0e-2171b8e3ac9c.png)
Next thing is when you mine dimensional ore you get the enigmatic version of the ore. Problem is its not the same as the RFTools dimensional ore so the enigmatic version of dimensional ore is useless doesn't craft into anything.
![image](https://user-images.githubusercontent.com/123050472/213359491-9045daf2-617b-483d-9a4e-4361a57714f8.png)

### Have you modified the modpack?

Yes

### User Modifications

![image](https://user-images.githubusercontent.com/123050472/213360042-76ec83fd-7e9a-480b-b92b-d1adaf3d8f35.png)
disabled quark automatic recipe unlock

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Cobalt#8663

**Comment by NielsPilgaard** [comment]
If most quests are like that, something is wrong with your modpack files. The other issue points towards the same. 

I recommend you reinstall the modpack without your additions, and see if that fixed the issues.

**Comment by lCobaltl** [comment]
it worked on singleplayer without the additions so im assuming thats correct ill try adding one mod at a time and seeing if it fixes the issue thank you
