### ISSUE TITLE
Step up assist wont work

### ISSUE THREAD

**Issue by totte1015** [EnigmaticaModpacks/Enigmatica6#5314]
### Modpack Version

1.16.5, 1.6.2

### Describe your issue.

Suddenly my step up assist trinklet stopped working, i also tried Astral "hiking boots" perk but not working either

### Have you modified the modpack?

Yes

### User Modifications

Shaders

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Aurani** [comment]
I'm on version 1.12.0 and my horseshoe trinket was working just fine until I learned the Hiking Boots perk from Astral Sorcery.
The perk apparently completely overrides the trinket with its own step-up that requires sprinting to trigger.

**Comment by NielsPilgaard** [comment]
That sucks, but we can't do anything about it I'm afraid.

**Comment by theboo** [comment]
There is a thingie you can make to reset your perks and not reset your points... Something shifting star something... There's 2, one resets your points as well, don't make that one
