### ISSUE TITLE
RGBee not available via beekeeper villager

### ISSUE THREAD

**Issue by AngrierPat** [EnigmaticaModpacks/Enigmatica6#5315]
### Modpack Version

1.6.2

### Describe your issue.

Most of the basic bees are available from the beekeeper villager, but the RGBee is not.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

AutumnWitch#1997

**Comment by NielsPilgaard** [comment]
Thanks for the report - This isn't something we can control, this would be for the mod's issue tracker :)
https://github.com/Team-Resourceful/ResourcefulBees/issues

**Comment by theboo** [comment]
We can control this, as we have added all overworld worldgen bees to the beekeeper trades through the enigmatica companion mod config.. I must have missed the rgbee when I set this up haha... Unfortunately I do not have the time(and am not home) to add this bee to each tier trade but it probably should be done

**Comment by theboo** [comment]
https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/config/enigmatica/beekeeper.json

Here is the config if anyone wants to add this, needs to be added to tiers 2-5

**Comment by NielsPilgaard** [comment]
Oh, woops 😅 Sure I'll do it.
