### ISSUE TITLE
Fluid duplication with Create and Thermal

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#5317]
### Modpack Version

1.6.2

### Describe your issue.

Thermal Expansion Fluid Cell auto-outputting into hose pulley leads to pulley dispensing an infinite amount of liquid, without actually consuming any from the cell.
Steps to reproduce:
1. Place fluid cell and fill it to the brim with a fluid (no upgrades needed)
![image](https://user-images.githubusercontent.com/15922601/213884763-765def77-50ec-4f41-8da1-07f35513ca37.png)
2. Place a hose pulley near it
![image](https://user-images.githubusercontent.com/15922601/213884781-34e95da4-55f5-4b7f-9223-95a9be2d44fe.png)
3. Set a side facing hose pulley to auto-output
![image](https://user-images.githubusercontent.com/15922601/213884797-dc160bdb-c334-4223-b7e3-7ef23812a0d7.png)
4. Done. You now have infinite amount of fluid. Cell will have fluid level stuck at 30500 or 31500. If it didn't work for you, then break both cell and hose pulley and try again
![image](https://user-images.githubusercontent.com/15922601/213884864-315a7ef1-cbe7-44d4-b0ec-5f43d6d610d9.png)

### Crash Report

-

### Latest Log

https://gist.github.com/juh9870/cb6117fbf9be3f159cb9e9b9d32734c8

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

juh9870#8970

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
No longer an issue in latest in-dev
