### ISSUE TITLE
add enchantments from mods to quark ancient tomes. 

### ISSUE THREAD

**Issue by Kuktar** [EnigmaticaModpacks/Enigmatica6#5321]
### Describe your suggestion

so as the modpack stands just minecraft enchantments are in the Quark config file for the ancient tomes feature. 

I am not sure if everyone else will find it as usefull as me but i just took all the modded enchants and added them to my quark config. lets me use ancient tome +1 to modded enchanted books. 

I will paste what i ended up with just in case you wanted to use it.

[tools.ancient_tomes]
		#Set to 0 to not generate in Dungeons
		"Dungeon Weight" = 20
		#Set to 0 to not generate in Stronghold Libraries
		"Library Weight" = 30
		#Set to 0 to not generate in Bastions
		"Bastion Weight" = 25
		#Set to 0 to not generate in Woodland Mansions
		"Woodland Mansion Weight" = 15
		#Set to 0 to not generate in Nether Fortresses
		"Nether Fortress Weight" = 0
		#Set to 0 to not generate in Underwater Ruins
		"Underwater Ruin Weight" = 0
		#Set to 0 to not generate in Monster Boxes
		"Monster Box Weight" = 5
		"Item Quality" = 2
		"Normal Upgrade Cost" = 10
		"Limit Break Upgrade Cost" = 30
		"Valid Enchantments" = ["minecraft:feather_falling", "minecraft:thorns", "minecraft:sharpness", "minecraft:smite", "minecraft:bane_of_arthropods", "minecraft:knockback", "minecraft:fire_aspect", "minecraft:looting", "minecraft:sweeping", "minecraft:efficiency", "minecraft:unbreaking", "minecraft:fortune", "minecraft:power", "minecraft:punch", "minecraft:luck_of_the_sea", "minecraft:lure", "minecraft:loyalty", "minecraft:riptide", "minecraft:impaling", "minecraft:piercing", "apotheosis:bane_of_illagers", "apotheosis:berserk", "apotheosis:capturing", "apotheosis:crescendo", "apotheosis:depth_miner", "apotheosis:earths_boon", "apotheosis:hell_infusion", "apotheosis:icy_thorns", "apotheosis:infusion", "apotheosis:knowledge", "apotheosis:life_mending", "apotheosis:magic_protection", "apotheosis:natures_blessing", "apotheosis:obliteration", "apotheosis:rebounding", "apotheosis:reflective", "apotheosis:scavenger", "apotheosis:sea_infusion", "apotheosis:shield_bash", "apotheosis:spearfishing", "apotheosis:splitting", "ars_nouveau:mana_boost", "ars_nouveau:mana_regen", "ars_nouveau:reactive", "cofh_core:holding", "create:capacity", "create:potato_recovery", "ensorcellation:angler", "ensorcellation:bulwark", "ensorcellation:cavalier", "ensorcellation:damage_ender", "ensorcellation:damage_illager", "ensorcellation:damage_villager", "ensorcellation:displacement", "ensorcellation:excavating", "ensorcellation:exp_boost", "ensorcellation:fire_rebuke", "ensorcellation:frost_aspect", "ensorcellation:frost_rebuke", "ensorcellation:furrowing", "ensorcellation:gourmand", "ensorcellation:hunter", "ensorcellation:instigating", "ensorcellation:leech", "ensorcellation:magic_edge", "ensorcellation:magic_protection", "ensorcellation:phalanx", "ensorcellation:pilfering", "ensorcellation:quick_draw", "ensorcellation:reach", "ensorcellation:tilling", "ensorcellation:trueshot", "ensorcellation:vitality", "ensorcellation:vorpal", "farmersdelight:backstabbing", "gunswithoutroses:bullseye", "gunswithoutroses:impact", "gunswithoutroses:preserving", "gunswithoutroses:sleight_of_hand", "mythicbotany:hammer_mobility", "pedestals:upgradearea", "pedestals:upgradecapacity", "pedestals:upgraderange", "pedestals:upgradespeed", "travel_anchors:range"]

### Why would you like this added/changed?

I cant find any reason not to make this change :P

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion! I don't see any reason not to make this change either, unless we've disabled some of the enchants you've added to the config. @MuteTiefling can you think of any reason not to add Quark Ancient Tomes for modded enchants?

**Comment by MuteTiefling** [comment]
Nah, shouldn't hurt anything. Just going to make it rarer to get books you might want.

**Comment by NielsPilgaard** [comment]
I've added many of the ones you listed, thanks 👍

**Comment by Kuktar** [comment]
heck ya thanks my dudes have a good weekend (if you get one)
