### ISSUE TITLE
Can't launch the default install of E6E Server

### ISSUE THREAD

**Issue by rueckl** [EnigmaticaModpacks/Enigmatica6#5322]
### Modpack Version

1.6.2

### Describe your issue.

Can't launch the server

### Latest Log

https://gist.github.com/rueckl/1e710ed74c655fb1a04caf5212a149d6

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
E6e needs java 8, up to 17 also works. (18 like you have does not)
