### ISSUE TITLE
E6E: Improved Blast Furnace copy/paste gadget recipe.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5323]
### Modpack Version

E6E 1.6.2

### Describe your issue.

The recipe for the Improved Blast Furnace is completely wrong. It wants 6 heater when it only needs 2, and it places them so the machine doesn't work at all. And it has a random Stone block in it.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by FooterMan14** [comment]
I was always confused about that, I wasn't sure if adding more heaters made it process faster or something, seemed a little weird.

**Comment by MuteTiefling** [comment]
It thinks it wants six because the heaters are three blocks tall. Only thing I can do about that is remove them altogether

**Comment by NielsPilgaard** [comment]
I think removing it completely would be best then, an incomplete schematic is worse than not having one imo :)

**Comment by Splutty** [comment]
I think MuteTiefling is correct, that in the copy stage it sees 2 1x3 structures that consist of "Heater", and makes that into 3 blocks of Heater. Which is incorrect. (That's also how it pastes them)
