### ISSUE TITLE
Replace White Sails in Windmill quest with any sails

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#5324]
### Describe your suggestion

![image](https://user-images.githubusercontent.com/15922601/215264126-c56e855f-1e8a-4b25-b665-f71c724b7302.png)
Change this quest to also accept Sail Frame

### Why would you like this added/changed?

Right now this quest requires White Sails in particular, which is both misleading to new players, who would think that Sail Frames are just a crafting ingredient and won't work on a windmill, as well as serving as an annoyance to the more experienced players, who have to go out of their way to craft White Sails instead of just using Sail Frames directly

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by juh9870** [comment]
Also maybe allow using just wool or any other block that can be used as a valid sail

**Comment by MuteTiefling** [comment]
The quest text already specified some of the other blocks, but now the quest will accept them too.
