### ISSUE TITLE
Make Farmer's Delight Rice sold in Market

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#5327]
### Describe your suggestion

Please make Farmer's Delight rice sold in market.

### Why would you like this added/changed?

Crushing FD rice is the only early automatable way to make Straw, but that form of rice is not sold in Market for some reason, and it's almost impossible to find it in world

**Comment by MuteTiefling** [comment]
I'll look into adding it, but I'm the meantime https://wiki.enigmatica.net/enigmatica6/gameplay/how-to.../farmers-delight-automating-straw

**Comment by MuteTiefling** [comment]
For clarity, the rice item you'd cook with is also the seed. This stuff is very commonly found in Villager chests. The wild rice growing in the world is rather rare, however.

**Comment by juh9870** [comment]
I see, thanks for info! Will go loot some villages
