### ISSUE TITLE
Sushi Go Crafting - Roller not working

### ISSUE THREAD

**Issue by Flowylege** [EnigmaticaModpacks/Enigmatica6#5334]
### Modpack Version

Forge for 1.19.2

### Describe your issue.

The roller is not working : I cannot click on anything while inside its menu (i can't change the type of sushi I wanna make, it's stuck on the first one ; i can't change the quantity of ingredients i want and i can't roll anything at all), is it normal ? can i fix it, and if yes, how ? 
![Capture d’écran (9)](https://user-images.githubusercontent.com/125924922/220201336-d1f4fca8-9386-4b5d-9a20-072b0b512f05.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. I'm afraid you've got some conflicting information, however, so we'll need to clear that up before we proceed. 

First, is this for Enigmatica 6 or Enigmatica 9? Enigmatica 9 is for Minecraft 1.19.2, while Enigmatica 6 is for 1.16.5.

Knowing the pack version is also important, as well as knowing if you've added anything to the pack. If you have, please let us know, but also re-test without those modifications to see if the issue persists. 

The pack version can be found in your launcher, for example, here's both E9 and E6E shown in the Curseforge launcher. The version is in the top right. 

![image](https://user-images.githubusercontent.com/9543430/220207662-b5f56a1d-ae4f-4b7e-b020-124d45d6ed91.png)

**Comment by MuteTiefling** [comment]
For my part, I can't reproduce the issue in either pack.

**Comment by Flowylege** [comment]
I don't have a mod called Enigmatica whatsoever, I just added SushiGoCrafting to the "mod" files in appdata, and the mods required for it to work (like titanium and patchouli i think it was) as mentionned when I launched the game. Is Enigmatica required as well ? It wasn't mentionned

**Comment by Darkere** [comment]
How did you end up here then? This is the bug tracker for the engimatica 6 modpack. Go to the bug tracker from SushiGoCrafting?

**Comment by Flowylege** [comment]
I misread, sorry
