### ISSUE TITLE
allegedly RS block dupe ft routers

### ISSUE THREAD

**Issue by AngrierPat** [EnigmaticaModpacks/Enigmatica6#5335]
### Modpack Version

1.6.2

### Describe your issue.

Andey — Today at 6:12 PM
using a router with a placer + any refined storage cable,importer, and crafters such, dupes it without placing it

for some reason they refused to report it themselves, but here you go

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Andey#5127

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Cannot reproduce. Thanks for the report anyway, but this is why I wanted the original player to post: If this is actually an issue we're missing critical information.
