### ISSUE TITLE
FTB Backups config resetting

### ISSUE THREAD

**Issue by chriellex** [EnigmaticaModpacks/Enigmatica6#5338]
### Modpack Version

1.6.2 + 1.7.1

### Describe your issue.

When I try to edit the FTB Backups config, it resets itself. This is a big issue, as the server running doesn't have enough storage to cope with 50 GB of backups. 
Not only that, but it also changes the number of backups I want and the time between backups. And lastly, the compression level

I do believe this to be an issue that started in 1.6.0. But I haven't re-tried it in all versions. (updated, BCS I hoped it'd been fixed)

### Latest Log

https://gist.github.com/chriellex/25a7c07fa2dc2a6e44c13263c6e960c8

### Have you modified the modpack?

Yes

### User Modifications

I wanted to change the backup settings. But that's it. (running it with Rcon, but I can't see that being the problem)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

chriellex#3218

**Comment by NielsPilgaard** [comment]
Thanks for the report :)

Which exact file are you trying to modify? Was the server on or off during the edit?

**Comment by chriellex** [comment]
I believe the file is called FTBbackup_comon.toml
It’s the configuration file for the FTB Backup mod (it’s just within the standard config folder)

I have tried editing it before starting the server. And while the server is online. Resets in both occasions. Both on 1.6.2 and 1.7.1

**Comment by NielsPilgaard** [comment]
Could the value you provided have been invalid? What did you change, to what?

**Comment by chriellex** [comment]
I Don't belive so
[https://gist.github.com/chriellex/909c7ccea3e2ccf385218ebbcbacbbbd](url)
i've uploaded the exact file I've been trying to use

**Comment by chriellex** [comment]
Well, the backups tend to be about 1 gb

**Comment by chriellex** [comment]
Well, that did work. Thanks very much!
