### ISSUE TITLE
Port some of the end-game goals from e6e to e6 ?

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica6#5340]
### Describe your suggestion

Port some of the endgame recipes, items, machines related to the final goal of e6e to e6, especially the Tree of Life

### Why would you like this added/changed?

-I really like those custom items, recipes and machines of the e6e end-game goal, but e6e itself is a little bit too hardcore for me. 
-So I tried e6, but the lack of final goal made me confused about what to do next. I think porting those goals to e6 can help solve the confusion. 
-And, to be honest, the Tree of Life is really cool, I really want to see it in e6 (and actually, every modpacks in Enigmatica series)

**Comment by NielsPilgaard** [comment]
I'd like this too, but the amount of work it would require to integrate well would be hundreds of hours. We simply don't have the time for it :(
