### ISSUE TITLE
Storage Drawers Fixes

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#5343]
### URL

https://www.curseforge.com/minecraft/mc-mods/storage-drawers-fixes

### Why would you like the mod added?

My mod to fix various issues related to Drawers interacting with modded pipes.

One downside is that drawers now may be slightly less performant when you have A TON of them, but in my testing I haven't noticed a difference when attaching 4096 drawers to a controller to RS system (via storage bus) and importing ~1000 items per tick into RS

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. Which concrete issues does your mod fix?
