### ISSUE TITLE
Create Schematicannon cannot build Advanced Assembly Table

### ISSUE THREAD

**Issue by weningea** [EnigmaticaModpacks/Enigmatica6#5346]
### Modpack Version

1.7.1

### Describe your issue.

The Create Schematicannon cannot build the Advanced Assembly Table due to the fact that the assembly table schematic requires the Immersive Engineering steel block, which doesn't exist in the modpack since it's been consolidated into the Emendatus Enigmatica steel block. I suppose the more general issue might be that the schematics themselves only seem to accept blocks with a specific tag, but I hadn't checked any other structures to see if there were additional conflicts (might be worth double-checking).

Unless there's something I'm missing, that is; I checked for any settings, but it looks like the only way to work around the issue is to edit the schematic file or skip the blocks and place them by hand.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
You can get IE steel blocks from a stone cutter.
