### ISSUE TITLE
Enigmatic Tree of Life Controller recipe should use crystalline leaves as well

### ISSUE THREAD

**Issue by dizzystem** [EnigmaticaModpacks/Enigmatica6#5349]
### Describe your suggestion

Since the Enigmatic Tree of Life building uses crystalline leaves now instead of normal leaves, this should be changed in the recipe for the Controller too.

### Why would you like this added/changed?

It would make sense and also be cooler.

**Comment by MuteTiefling** [comment]
Good thinking. We'll get that fixed
