### ISSUE TITLE
Tomato sauce recipe conflict in Create mixer

### ISSUE THREAD

**Issue by dizzystem** [EnigmaticaModpacks/Enigmatica6#5350]
### Modpack Version

1.7.1

### Describe your issue.

The recipe for making tomato sauce in the Create mixer with basin conflicts with the shapeless crafting recipe for tomato soup, since both of them use two tomatoes and a bowl. One of those should probably be changed.

### Have you modified the modpack?

Yes

### User Modifications

Added Magnesium, Magnesium Extras, Sulfuric.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Tetrikitty#2647

**Comment by MuteTiefling** [comment]
New Recipes
Sauce
![image](https://user-images.githubusercontent.com/9543430/224465866-a32549b5-4f68-4b43-b7dc-e693e3bc724c.png)

Soup
![image](https://user-images.githubusercontent.com/9543430/224465876-8eca56d1-4748-4022-b6ca-3e7b2084fa48.png)
