### ISSUE TITLE
Macaw's Doors mod: Breaking Garage Doors causes server crash

### ISSUE THREAD

**Issue by justn6** [EnigmaticaModpacks/Enigmatica6#5355]
### Modpack Version

1.7.1

### Describe your issue.

On placing then breaking a garage door block, server crashes:

https://pastebin.com/17eFSSU6

After searching the Enigmatica Discord i can see others have been having the same issue with no fix. However, 8 hours ago the Macaw's Doors mod got an update that should fix this crash:

https://www.curseforge.com/minecraft/mc-mods/macaws-doors/files/4435414

I am testing this now

### Crash Report

https://gist.github.com/justn6/0af91cc4d6544108089fad88b09fd37d

### Have you modified the modpack?

Yes

### User Modifications

Mods: Oculus, Rubidium
Texture Packs: DokuCraft Lite, Custom Font, Custom UI

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Rhaal#0742

**Comment by justn6** [comment]
Confirmed no longer crashing when updating to mcw-doors-1.0.8b-forge-mc1.16.5.jar

Recommend server pack also update

**Comment by NielsPilgaard** [comment]
Thanks for the report and fix ❤️
