### ISSUE TITLE
Cannot change direction of Vessel Corner Guide Rail

### ISSUE THREAD

**Issue by PimTournaye** [EnigmaticaModpacks/Enigmatica6#5368]
### Modpack Version

1.8.0

### Describe your issue.

Shift+right-click should allow you to change the direction of the Little Logistics guide rails. However, I can't get this to work.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Wafflemancer#9748

**Comment by MuteTiefling** [comment]
Make sure you're not flying and have nothing in your offhand. Both of those can mess with right-click interactions.

For my part, I'm unable to reproduce the issue. Shift + Right-Click is correctly toggling the block between the two expected orientations. 

https://streamable.com/ziqtj0

**Comment by PimTournaye** [comment]
Was indeed not testing with an empty off-hand. Thanks!
