### ISSUE TITLE
Duplication / voiding glitch with Modular Routers

### ISSUE THREAD

**Issue by dizzystem** [EnigmaticaModpacks/Enigmatica6#5369]
### Modpack Version

1.8.0

### Describe your issue.

Routers can sometimes pull from or push to inventories that aren't there any more, duplicating or voiding items.

Example 1 (duplication):
Place two routers. Put some items in Router 2. Set Router 1 to pull from Router 2, then quickly cardboard box Router 2. Router 1 will continue pulling the stack of items from the cardboard box. After it's done, you can unbox Router 2 and the items will still be in there.

![image](https://user-images.githubusercontent.com/25002736/227775169-6cf31b9e-bd01-42b2-b5d3-0c02b082b179.png)

Example 2 (duplication):
Place a router and an RFTools crafter. Put some items in the output slot of the crafter, and set the router to pull from it. Then, break the crafter. The router will continue pulling the stack of items from thin air.

![image](https://user-images.githubusercontent.com/25002736/227775275-8f55ab11-6516-4b10-aa69-fc06ab469d90.png)

Example 3 (voiding):
Place two routers. Put some items in Router 1 and set it to send the items to Router 2. Break Router 2. Router 1 will continue sending the stack of items into thin air.

![image](https://user-images.githubusercontent.com/25002736/227775331-7b9e933c-ac2b-4415-bcf0-5c5feb942f96.png)

### Have you modified the modpack?

Yes

### User Modifications

Added Magnesium, Magnesium Extras, Sulfuric.

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Tetrikitty#2647

**Comment by dizzystem** [comment]
Just breaking the router in Example 1 doesn't cause the glitch.
In 2 and 3, using any old inventory like drawers or an alchemy table doesn't cause the glitch. The RFTools crafter works for 2 and both the crafter or a router work for 3. There might be more machines that act like that, I'm not sure.

**Comment by NielsPilgaard** [comment]
Thanks for the report 👍 I've relayed it to the appropriate mod's issue tracker.
