### ISSUE TITLE
[BG] Copy-Paste Gadget Bug - Duplicating Advanced Pressure Tubes from Gaia Reactor Template

### ISSUE THREAD

**Issue by andrzejopalinski** [EnigmaticaModpacks/Enigmatica6#5372]
### Modpack Version

1.6.2

### Describe your issue.

Discovered by accident when measuring the space needed for Gaia Reactor build. Copy-Paste gadget is placing Advanced Pressure Tubes from thin air and they are perfectly mineable and usable after that. Probably some kind of bug related to type of entity like the one when using building gadget with Mek transporters caused crashes.
![obraz](https://user-images.githubusercontent.com/75954181/230449748-6cc0ad23-14b6-4ea9-87a2-12ac3f9ff2ee.png)
![obraz](https://user-images.githubusercontent.com/75954181/230449916-c43ffb78-14f8-430f-bc39-753a316f84ee.png)
![obraz](https://user-images.githubusercontent.com/75954181/230449960-44e843ef-0fe5-4396-bb39-cd4843b20b4d.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

R31T0#5077

**Comment by MuteTiefling** [comment]
Thanks for the report. This should be fixed for next update.
