### ISSUE TITLE
Farsight: Spyglasses

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica6#5376]
### URL

https://www.curseforge.com/minecraft/mc-mods/farsight-spyglasses

### Why would you like the mod added?

This mod adds a spyglass, which would be helpful when trying to recognize sth far away. 
It's very lightweight, only adding one item. 
Also, I think it's better than a zoomer mod, because it is more immersive, and less cheating, -ish.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. I don't really think we have a need for this tbh, so no.
