### ISSUE TITLE
Engineer's Hammer cannot change mode of redstone wire connectors

### ISSUE THREAD

**Issue by Flamebom** [EnigmaticaModpacks/Enigmatica6#5386]
### Modpack Version

1.8.0

### Describe your issue.

Engineer's hammer cant change input and output of redstone wire connectors. When rightclicking them, nothing happens. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Flamebom#8228

**Comment by MuteTiefling** [comment]
You use a screwdriver now.
