### ISSUE TITLE
Fortunizer auto ejects fluxbore even at full charge

### ISSUE THREAD

**Issue by CAlonghair** [EnigmaticaModpacks/Enigmatica6#5387]
### Modpack Version

1.7.1

### Describe your issue.

If you put a fluxbore as the pickaxe for a fortunizer, the fortunizer ejects it as if it were a tool about to break even if it is at full power. It should instead drain the power to process with it and eject it when empty, or not accept the fluxbore into the pickaxe slot

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

CAlonghair#1485

**Comment by MuteTiefling** [comment]
It wasn't built to work with power tools, jut vanilla style tools.

**Comment by CAlonghair** [comment]
Ah ok. Is this something that y'all would consider adding? If not, I'd recommend at least blacklisting the fluxbore (and any other power tools) from it.

**Comment by NielsPilgaard** [comment]
> Ah ok. Is this something that y'all would consider adding? If not, I'd recommend at least blacklisting the fluxbore (and any other power tools) from it.

I'll have a look into what we can do :)

**Comment by NielsPilgaard** [comment]
I'm afraid we can't blacklist things.
