### ISSUE TITLE
More Minecarts and Rails mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica6#5389]
### URL

https://www.curseforge.com/minecraft/mc-mods/more-minecarts

### Why would you like the mod added?

E6 has some train mods, but those are criminally underutilized. Most rail mods we have only provide some extra rail types, but when you try to build any kind of automation with rails, you quickly realize that in the end our rail situation is not very different from vanilla. We have no sane way to route minecart trains, and what carts can do is severely limited, to the point where I haven't seen anyone use any minecart systems in Enigmatica discord. I suggest adding this mod to provide some more options for minecart automation via:
- **Color Detector Rails and signal minecarts:** this allows for actual minecart routing without using insane chest minecart filtering setups, while still being complicated enough to be interesting. This is my main point why I want this mod
- **Cart chunk loader:** Allows long-distance item travels via minecarts without having to chunk load whole path
- **Carts with fluid/energy storage:** self-explanatory

This mod also provides extra rail types, some of which can duplicate functionality of existing rail types, so it might be worth to add conversion recipes between those rails (and maybe do the same for existing rail mods? Iirc we have like 2 crossing rails already)

**Comment by NielsPilgaard** [comment]
I think this is too big a mod to add at this point, sorry.
