### ISSUE TITLE
suggest to change default config of integratedterminal's `craftingPlannerEnableMultithreading` to false

### ISSUE THREAD

**Issue by Frefreak** [EnigmaticaModpacks/Enigmatica6#5392]
### Describe your suggestion

In a E6E server of version 1.8.0, I experienced similar things happened [here](https://github.com/CyclopsMC/IntegratedDynamics/issues/1120) that causes the server to crash.

After changing `craftingPlannerEnableMultithreading` to false my auto crafting works without crash.

### Why would you like this added/changed?

change default config `craftingPlannerEnableMultithreading`  to `false` (integratedterminals-common.toml)

**Comment by NielsPilgaard** [comment]
Thanks for the report, very easy to act upon 👌 we'll change `craftingPlannerEnableMultithreading` to `false`
