### ISSUE TITLE
hose pulley infinite fluid list problem

### ISSUE THREAD

**Issue by Kooskoos1234** [EnigmaticaModpacks/Enigmatica6#5393]
### Modpack Version

Any - I was using 1.6.2

### Describe your issue.

Latex, along with all other fluids from industrial foregoing, when placed inworld, turns into a different type of itself, which is blacklisted by the hose pulley, even though it's supposed to be enabled
several fluids, like milk and thermal expansion's fluids, that are supposed to be hose pulley infinite-able, are not place-able at all

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kooskoos#1234

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Looks like a lot of this was just me forgetting to update the description. I've removed the IF and Thermal fluids too now due to their issues.
