### ISSUE TITLE
entitys, mobs, chests and not full blocks are invisible

### ISSUE THREAD

**Issue by theZiifamily** [EnigmaticaModpacks/Enigmatica6#5398]
### Modpack Version

1.16.5

### Describe your issue.

game works aside from all mobs and chests dont show, i can still hear, hit and interact with chests but mobs i cant touch and they still hit me back and i want to play the game without everything being gone

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Zii#2428

**Comment by theZiifamily** [comment]
huhh?

**Comment by NielsPilgaard** [comment]
Because I believe this particular issue would be better investigated on Discord :) 

If that is not the case, please provide your latest.log, and the version of the modpack. 

The modpack is indeed on Minecraft 1.16.5, but the modpack itself has a version too.
