### ISSUE TITLE
Add Refined Crafter Proxy

### ISSUE THREAD

**Issue by StevenDoesStuffs** [EnigmaticaModpacks/Enigmatica6#5400]
### URL

https://www.curseforge.com/minecraft/mc-mods/refined-crafter-proxy

### Why would you like the mod added?

Disclaimer: I am the author of this mod.

This mod makes it easier to distribute the same recipes over multiple machines by adding a "crafter proxy" which mirrors another crafter's patterns. RS will then automatically load balance the recipes across all the machines without forcing the player to create multiple of the same pattern for multiple crafters. It's a very small mod purely for QOL, and its only dependency is RS. 

I've been playing with this in my E6E world for a week or so now and have fixed all the bugs I could find in that time, and everything seems to be working now.

**Comment by NielsPilgaard** [comment]
Ooh, nice mod idea! I vote yes 😄

**Comment by StevenDoesStuffs** [comment]
Ahhh shoot I forgot that kotlinforforge is also a dependency, but y'all already have that.

**Comment by MuteTiefling** [comment]
No issue here. Just curious what the power draw is and if it is configurable.

**Comment by Darkere** [comment]
Appears to be 4x the regular crafter powerdraw. Which in our case... would be an issue.

**Comment by NielsPilgaard** [comment]
Is 4x energy cost worth it in our case?

**Comment by StevenDoesStuffs** [comment]
Ah yeah that was more of a placeholder value. I can make it configurable.

**Comment by theboo** [comment]
My only other question would be does it work with the upgraded crafters we have in e6e? Cuz upgrading for energy efficiency in e6e is a big deal lol

**Comment by StevenDoesStuffs** [comment]
Yeah I was really struggling to figure out how do deal with the extrastorage crafters. 

On one hand, I'm thinking I could just make it so that the proxy takes the properties (speed + energy draw) of whatever crafter you craft it with (meaning you could craft it with any of the upgraded crafters as well), but that's kinda difficult.

I'd have to either pull in extrastorage as a dependency or try to generically wrap a crafter node and turn it into a proxy (which might not even be possible, since I'm not sure forge would let me go from an item to a RS node that easily). 

The other idea is to store properties as part of the NBT tag, meaning they could be customized as a part of the crafting recipe, and then modpack creators like y'all could create the recipes for the upgraded crafters on your side. 

I'm thinking of going for the second one, since it's much easier on my end. Thoughts?

**Comment by MuteTiefling** [comment]
4x is a lot, especially if it only works with rs crafters and not the advanced ones.

If it's configurable that's one thing. But not supporting the extra crafters we have does make these less appealing.

**Comment by StevenDoesStuffs** [comment]
I'm currently testing the new config implementation. What do y'all think the energy usage should be for the crafter proxies?
