### ISSUE TITLE
It seems that `ci.yml` needs update

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica6#5404]
### Modpack Version

not related to modpack

### Describe your issue.

KubeJS recently changed their branch naming, `eol/1.16` is now called `1605` . But the name used in ci.yml is still eol/1.16 . 
<img width="259" alt="image" src="https://github.com/EnigmaticaModpacks/Enigmatica6/assets/47418975/06a7534d-33b4-4110-8b4f-4b30c415b7e5">
So, when a CI is triggered, it will fail when running "compile (KubeJS)" , saying `Remote branch eol/1.16 not found in upstream origin` . 

I try swaping `eol/1.16` with `1605`, the compile job succeded, but there is no workflow file found, so CI will fail again, but at the next job. 
[Before](https://github.com/ZZZank/Enigmatica6Enlightened/actions/runs/5346967303)
[After](https://github.com/ZZZank/Enigmatica6Enlightened/actions/runs/5357497442) 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Fixed, thanks a lot :)
