### ISSUE TITLE
Can't see dimlet recipe in RFTools Dimensions

### ISSUE THREAD

**Issue by ShawnDobie** [EnigmaticaModpacks/Enigmatica6#5414]
### Modpack Version

1.20-11.0.0

### Describe your issue.

I just get red squares on the grid, and I don't know what that red stuff is on the right. 

![image](https://github.com/EnigmaticaModpacks/Enigmatica6/assets/147892958/b0077971-0f30-46bc-b17e-f8ca9c0050df)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
RFTools Dimension was removed from E6 a very long time ago.
