### ISSUE TITLE
The server won't install, because it requires serverstarter-2.4.0.jar which doesn't exist

### ISSUE THREAD

**Issue by Rubickevich** [EnigmaticaModpacks/Enigmatica6#5415]
### Modpack Version

1.8.0

### Describe your issue.

Upon launch, the bat file returns: 
Error: Unable to access jarfile serverstarter-2.4.0.jar
Then it halts forever. It appears that this file is required to install the server, but it just isn't in the zip file. I suppose it was supposed to be installed by the bat file itself, as I dug inside it and got a [direct link](https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.4.0/serverstarter-2.4.0.jar), which worked. After installing serverstarter manually the whole pack downloaded successfully - so it does work as a quick solution.

Just thought it's better to let you know, while also giving the quick fix for anybody who goggles it. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
We'll look into it, thanks 👍
