### ISSUE TITLE
The Mighty Architect

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5417]
### Describe your suggestion

Put somewhere in the quest description how you're actually supposed to invoke this.

There is nothing anywhere that tells you how to start, and most/all of the online videos assume you have a default keybind for it.

So something like "You need to check or set the Start Composing keybind under The Mighty Architect in Controls." would be helpful.

### Why would you like this added/changed?

Because if at any point you unbound all "G" keybinds, it's stupidly hard to figure out what on earth you're supposed to do.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion. That'll be added next update!
