### ISSUE TITLE
Error when logging in to my server

### ISSUE THREAD

**Issue by Lazerok911** [EnigmaticaModpacks/Enigmatica6#5453]
### Modpack Version

ForgeOptiFine 1.16.5

### Describe your issue.

Faced with a problem: a friend is trying to connect to me in the world, but he gets an error: "Failed to synchronize registry data with server, connection was closed" What to do?

### Have you modified the modpack?

Yes

### User Modifications

Draconic Evolution
Solar Flux Reborn
Corail Tombstone
Space-Bosstools
JourneyMap
Ice and Fire
Divine RPG

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

.lazerok

**Comment by Lazerok911** [comment]
![1](https://github.com/EnigmaticaModpacks/Enigmatica6/assets/167432306/9e1ee81d-04f9-44b1-8c66-b5aeb3c0cdc1)
I wrote to your discord, but there has been no response for 24 hours, or did I write somewhere wrong?
https://youtu.be/CzrdK6oRfqk - a video with an error.
PS: A friend has the same mods as me, the same error occurs when using mods from the original build.

**Comment by MuteTiefling** [comment]
Discord support is handled by volunteers and it may take time for people to respond. 

That said, you've added a lot to the pack here and we do not support such modifications. If you want help reading the logs, please be sure they're posted in Discord (not a video, the actual logs) and be patient until someone finds time to assist.
