### ISSUE TITLE
Potion of Spell Damage becomes Calming Potion when adding glowstone.

### ISSUE THREAD

**Issue by jrball101** [EnigmaticaModpacks/Enigmatica6#5455]
### Modpack Version

1.9.0

### Describe your issue.

When trying to brew spell damage II potions, they instead become calming potions when adding glowstone dust.

### Have you modified the modpack?

Yes

### User Modifications

I removed the Journey map mod and changed the BYG config to keep it from adding biomes to the Nether and End.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jrball101

**Comment by MuteTiefling** [comment]
Duplicate: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4539
