### ISSUE TITLE
Vanilla lack of mods spawning

### ISSUE THREAD

**Issue by Derekm122** [EnigmaticaModpacks/Enigmatica6#5456]
### Modpack Version

Version 25.5 I think 

### Describe your issue.

I installed the mod Better Minecraft and it contains lots of different mods , including Alex’s mods and when I play it everything if good expect there is no cows/pigs and 1 or 2 sheep there and there , what can I do to make more spawn in or have it normally spawn how it should and would be , I’ve only added a few mods that has to do with weapons and graphics and don’t know how to change any configs or whatever , the only way I tried to resolve this so far was installing limitmob spawn mod and then typed /mobspawnlimit remove and nothing changed 

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Derekm122** [comment]
What is that , I don’t get it

**Comment by Derekm122** [comment]
on curse forge it says the better mc is v25.5

**Comment by Kanzaji** [comment]
Issue Tracker is a place to report issues with projects.
 This one is for Enigmatica modpacks (in this case,  E6 and E6E). The link above is one for BetterMC 🙃

Also, answering your comment on #2537, the lines you reposted there are from Environmental mod config in `configs` folder of your instance. You need to set those values from `true` to `false` to possibly fix the issue (not sure if that's the issue in BetterMC however. Something else might be the culprit)

**Comment by Derekm122** [comment]
after pressing on  config lots of files pop up , once that happens i open what it tells me on a browser , in this case operagx and it doesn't even let me change it at all.

**Comment by Derekm122** [comment]
and how do i write my issue on the link you sent me , i press new file and i dont think that is the right one to press in order to add my issue

**Comment by Kanzaji** [comment]
> after pressing on  config lots of files pop up , once that happens i open what it tells me on a browser , in this case operagx and it doesn't even let me change it at all.

Browser can only display files >.> You need to open them in a text editor, like simply notepad or VSCode

And on the BetterMC github, you need to go to the repository with the name of the modpack you downloaded (they have a few of them) and then go to the issues tab. There, you can create a new issue, like here 😀

**Comment by Derekm122** [comment]
how to i go to the resoository , im sorry i dont mean to be a bother on everything its just ive never been good at this type of stuff

**Comment by Kanzaji** [comment]
I completely didn't realize yesterday that BetterMC has a single issue tracker for all modpacks, my bad!

So when you go to that link above, just go to the issues tab and click a new issue button, and describe the problem you have with animals 🙂
