### ISSUE TITLE
Mod issue 

### ISSUE THREAD

**Issue by awesome2cherry** [EnigmaticaModpacks/Enigmatica6#5467]
### Modpack Version

1.16.5

### Describe your issue.

When ever I load into a world 5 minutes into the session my game crashes with a error regarding TerraForged with Exit Code: -1

### Crash Report

<script src="https://gist.github.com/awesome2cherry/5f279d81f5cbf740cde91b18dd8e5342.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

**[Mods]**
Just Enough Items (JEI)
Jade
JourneyMap
Mouse Tweaks
Tree Harvester
Dynamic Surroundings 
Distant Horizons: A Level of Detail mod
Collective
Biomes O'Plenty
AppleSkin
**[Resource packs]**
Dramatic Skys
Fresh Animations
Fresh Animations Extensions
Motchen's Better Leaves
Shiny Ores
Unity
**[Shaders]**
Sildur's Vibrant shaders

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

awesome2cherry#6128

**Comment by awesome2cherry** [comment]
Hey, it happened in a pack I have compiled myself. there were no
compatibility issues/ warnings. However, it would crash when I move from
the spawn location and start rendering the surroundings.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by HeatherComputer** [comment]
I love the little avast stuff. It's a bad av btw, and a waste of money.



This github is for enigmatica 6 though, and people won't be able to help much with your custom pack.
