### ISSUE TITLE
RS vanishing items

### ISSUE THREAD

**Issue by SpaceWyvern** [EnigmaticaModpacks/Enigmatica6#774]
**Modpack version**
0.3.4

**Issue**
I input items in the wireless RS grid's crafting part, close it and when I open it the items I put it vanish and come back to the previous state without putting them in the system

This is a video showing the bug:
https://streamable.com/nvs8x5

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

@Darkere is this a known bug?

**Comment by Darkere** [comment]
Nope. Although I was the last one that touched that code.... so probably my fault.

**Comment by NillerMedDild** [comment]
Will this bug report suffice or would you like it relayed to the RS issue tracker?

**Comment by Darkere** [comment]
No need. I have a few minutes to investigate :)

**Comment by Kanzaji** [comment]
I'm checking old issues atm just because I'm bored, and this one should be closed I think 😄
